var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(q,ba,Y){q!=Array.prototype&&q!=Object.prototype&&(q[ba]=Y.value)};$jscomp.getGlobal=function(q){return"undefined"!=typeof window&&window===q?q:"undefined"!=typeof global&&null!=global?global:q};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var q=0;return function(ba){return $jscomp.SYMBOL_PREFIX+(ba||"")+q++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var q=$jscomp.global.Symbol.iterator;q||(q=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[q]&&$jscomp.defineProperty(Array.prototype,q,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.arrayIterator=function(q){var ba=0;return $jscomp.iteratorPrototype(function(){return ba<q.length?{done:!1,value:q[ba++]}:{done:!0}})};$jscomp.iteratorPrototype=function(q){$jscomp.initSymbolIterator();q={next:q};q[$jscomp.global.Symbol.iterator]=function(){return this};return q};
$jscomp.iteratorFromArray=function(q,ba){$jscomp.initSymbolIterator();q instanceof String&&(q+="");var Y=0,O={next:function(){if(Y<q.length){var xb=Y++;return{value:ba(xb,q[xb]),done:!1}}O.next=function(){return{done:!0,value:void 0}};return O.next()}};O[Symbol.iterator]=function(){return O};return O};
$jscomp.polyfill=function(q,ba,Y,O){if(ba){Y=$jscomp.global;q=q.split(".");for(O=0;O<q.length-1;O++){var xb=q[O];xb in Y||(Y[xb]={});Y=Y[xb]}q=q[q.length-1];O=Y[q];ba=ba(O);ba!=O&&null!=ba&&$jscomp.defineProperty(Y,q,{configurable:!0,writable:!0,value:ba})}};
$jscomp.polyfill("Array.prototype.fill",function(q){return q?q:function(q,Y,O){var ba=this.length||0;0>Y&&(Y=Math.max(0,ba+Y));if(null==O||O>ba)O=ba;O=Number(O);0>O&&(O=Math.max(0,ba+O));for(Y=Number(Y||0);Y<O;Y++)this[Y]=q;return this}},"es6","es3");
function PEvs(q,ba,Y,O,xb,dg,We){var ua,hc,Ta,vd,Xe,wd,Ja,ic,ea,he,Ka,Kb=0,zc=0,$c,La=!1,jc=!1,yb=0,Ua=0,Lb=0,Mb=0,xd,yd,Ac=function(k){Ja=k.target;for(ea=ic=0;Ja;)ic+=Ja.offsetLeft-Ja.scrollLeft,ea+=Ja.offsetTop-Ja.scrollTop,Ja=Ja.offsetParent;Kb=(La?xd:k.pageX)-ic-document.body.scrollLeft;zc=(La?yd:k.pageY)-ea-document.body.scrollTop};this.getX=function(){return Kb};this.getY=function(){return zc};var H=function(k){k.preventDefault();k.stopImmediatePropagation?k.stopImmediatePropagation():k.stopPropagation()},
zd=function(k){Ac(k);$c=Kb;wa=zc;V=!0;null!=W&&(vd=(new Date).getTime());null!=va&&va(k)},J=function(k){V&&(Ac(k),V=!1,null!=zb&&zb(k),null!=W&&(Xe=(new Date).getTime(),wd=Xe-vd,300>wd&&W(k)))},fb=function(k){Ac(k);3>Math.abs(Kb-$c)&&3>Math.abs(zc-wa)||(wa=$c=-9999,V?null!=Ma&&Ma(k):null!=eb&&eb(k),null!=Ad&&ie())};this.touchDown=function(k){Ta=!0;if(1<k.targetTouches.length)return La=!0,Ka&&(Ua=-1,H(k)),!1;ua=k.changedTouches;hc=ua[0];zd(hc)};this.touchUp=function(k){0==k.targetTouches.length&&(La=
Ta=!1);H(k);if(La||jc)return La||(jc=!1),!1;ua=k.changedTouches;hc=ua[0];J(hc)};this.touchMove=function(k){Ta=!0;H(k);if(La)return Ka&&(ua=k.targetTouches,xd=(ua[0].pageX+ua[1].pageX)/2,yd=(ua[0].pageY+ua[1].pageY)/2,jc=!0,Lb=ua[0].pageX-ua[1].pageX,Mb=ua[0].pageY-ua[1].pageY,yb=Lb*Lb+Mb*Mb,Ka&&0<Ua&&30<Math.abs(yb-Ua)&&Ka(0<yb-Ua?1:-1),Ua=yb),!1;ua=k.changedTouches;hc=ua[0];fb(hc)};this.pointUp=function(k){H(k);for(var q=0;q<ra.length;q++)if(ra[q].pointerId==k.pointerId){ra.splice(q,1);break}0==
ra.length&&(Ta=La=!1);if(La||jc)return La||(jc=!1),!1;J(k);return!1};this.pointDown=function(k){H(k);ra.push(k);Ua=-1;Ta=!0;1<ra.length?La=!0:zd(k);return!1};this.pointMove=function(k){H(k);for(var q=0;q<ra.length;q++)ra[q].pointerId==k.pointerId&&(ra[q]=k);if(La||!jc){if(La)return xd=(ra[0].pageX+ra[1].pageX)/2,yd=(ra[0].pageY+ra[1].pageY)/2,Ka&&(jc=!0,Lb=ra[0].pageX-ra[1].pageX,Mb=ra[0].pageY-ra[1].pageY,yb=Lb*Lb+Mb*Mb,Ka&&0<Ua&&30<Math.abs(yb-Ua)&&Ka(0<yb-Ua?1:-1),Ua=yb),!1;fb(k);return!1}};this.mouseDown=
function(k){Ta||(H(k),zd(k))};this.clearDown=function(){V=!1};this.mouseUp=function(k){Ta||(H(k),J(k))};this.useWheel=function(k){q.addEventListener("wheel",this.mouseWheel,!0);Ka=k};this.mouseWheel=function(k){Ac(k);var q=Math.max(-1,Math.min(1,-k.deltaY||-k.detail));H(k);Ka&&Ka(q)};this.mouseClick=function(k){H(k);V=!1};this.mouseMove=function(k){Ta||(H(k),fb(k))};this.mouseDragged=function(k){Ta||(H(k),Ac(k),null!=Ma&&Ma(k),null!=Ad&&ie())};var ie=function(){clearTimeout(he);he=setTimeout(function(){Ad()},
600)};var wa=$c=zc=Kb=0;var va=ba;var zb=Y;var eb=O;var Ma=xb;var W=dg;var Ad=We;var V=Ta=!1;var ra=[];q.addEventListener("mousedown",this.mouseDown,!1);q.addEventListener("mouseup",this.mouseUp,!1);q.addEventListener("mousemove",this.mouseMove,!1);q.addEventListener("click",this.mouseClick,!1);q.addEventListener("touchstart",this.touchDown,!1);q.addEventListener("touchend",this.touchUp,!1);q.addEventListener("touchmove",this.touchMove,!1);q.addEventListener("touchleave",this.touchUp,!1);q.addEventListener("touchcancel",
this.touchUp,!1);q.addEventListener("contextmenu",function(k){k.preventDefault()},!1);q.style["touch-action"]="none";q.addEventListener("mouseout",function(k){V||(zc=Kb=-1,null!=eb&&eb(k));V=!1})};var HAniS=new function(){function q(b){var a,d;ad=!0;if(b instanceof Array)for(e={},a=0;a<b.length;a++){if(!(2>b[a].length)){var c=b[a].trim();if(0!=c.indexOf("#")){var h=c.indexOf("=");if(!(1>h)){var f=c.substr(0,h).trim().toLowerCase();e[f]=c.substr(h+1).trim()}}}}else e=b;je=!1;a=e.debug;null!=a&&("true"==a?(Ye=window.open("","HAniSDebugInfo","scrollbars=yes,width=400,height=200"),je=!0,fa("HAniS Version 4.25")):je=!1);gb=!0;a=e.set_className;null!=a&&E(a,"f")&&(gb=!1);fa("Is type of param an array = "+
(b instanceof Array));a=e.divalign;null!=a&&(Bd=a.trim(),y.align=Bd);a=e.prevent_shortcuts;null!=a&&E(a,"t")&&(ke=!0);a=e.initial_message;null!=a&&(b=e.initial_message_style,null==b&&(b="background-color:red;top:10px;left:10px;height:100px;width:200px"),b="z-index:99;position:absolute;"+b,kc=n("div"),kc.setAttribute("style",b),kc.innerHTML=a,kc.addEventListener("click",function(){kc.style.visibility="hidden"},!1),kc.style.visibility="visible",Va.appendChild(kc),b=e.initial_message_timeout,null!=b&&
("auto"==b?Ze=!0:(Ze=!1,b=parseInt(e.initial_message_timeout,10),2>b&&(b=2),setTimeout(function(){kc.style.visibility="hidden"},1E3*b))));a=e.coordinates;null!=a&&xb(a);c="green";h="white";f="12px Arial";var m=null,l=d=10,g=10;$e=2;eg="Lat = ";fg=" Lon = ";a=e.coordinates_display_style;null!=a&&(b=a.split(","),c=b[0].trim(),h=b[1].trim(),f=b[2].trim(),3<b.length&&(eg=b[3],fg=b[4],$e=parseInt(b[5],10),6<b.length&&(m=b[6].trim(),d=parseInt(b[7],10),l=parseInt(b[8],10),g=parseInt(b[9],10))));gg=new eb(c,
h,f,m,d,l,g);le=Bc=null;null!=e.map_scale&&(me=lc=!0,b=e.map_scale.split(","),Bc=parseFloat(b[0]),le=1<b.length?parseFloat(b[1]):Bc);hg=" ";a=e.distance_unit;null!=a&&(hg=a.trim());a=e.divcan_style;null!=a&&a.trim();af="default";a=e.distance_cursor;null!=a&&(af=a.trim());ne="default";a=e.location_cursor;null!=a&&(ne=a.trim());oe="default";a=e.probe_cursor;null!=a&&(oe=a.trim());bf="default";a=e.mark_cursor;null!=a&&(bf=a.trim());a=e.imagecan_style;null!=a&&(b=a.trim()+";position:absolute;top:0;left:0;",
mb.setAttribute("style",b+"z-index:1;"),mc.setAttribute("style",b+"z-index:6;"));c="blue";h="white";f="12px Arial";m=null;g=l=d=10;ig=1;jg="white";a=e.distance_display_style;null!=a&&(b=a.split(","),c=b[0].trim(),h=b[1].trim(),jg=5<=b.length?b[4].trim():h,f=b[2].trim(),ig=parseInt(b[3],10),5<b.length&&(m=b[5].trim(),d=parseInt(b[6],10),l=parseInt(b[7],10),g=parseInt(b[8],10)));Kh=new eb(c,h,f,m,d,l,g);c="black";h="white";f="12px Arial";m=null;g=l=d=10;a=e.probe_display_style;null!=a&&(b=a.split(","),
c=b[0].trim(),h=b[1].trim(),f=b[2].trim(),3<b.length&&(m=b[3].trim(),d=parseInt(b[4],10),l=parseInt(b[5],10),g=parseInt(b[6],10)));Lh=new eb(c,h,f,m,d,l,g);kg="Undefined";lg=!1;Cd=0;a=e.probe_undefined;null!=a&&(b=a.split(","),kg=b[0].trim(),1<b.length&&(Cd=parseInt(b[1],10)+1),2<b.length&&(lg=!0));cf=!1;e.probe_base_image&&(cf=!0);a=e.active_probe;null!=a&&(Nb=!0);a=e.pause;null!=a&&(mg=parseInt(a,10));a=e.auto_refresh;null!=a&&(df=6E4*parseInt(a,10),Cc=setInterval("HAniS.reloadFOF();",df),Dd=!0);
Ed=!1;a=e.enable_smoothing;null!=a&&E(a,"t")&&(Ed=!0);pe=!0;a=e.check_image_size;null!=a&&E(a,"f")&&(pe=!1);ng=!1;a=e.sprites;if(null!=a){b=a.split(",");ef=new Image;ff=[];gf=[];Ob=[];Pb=[];if("row"==b[1].trim().toLowerCase())for(l=h=c=0,a=2;a<b.length;)for("row"==b[a].trim().toLowerCase()&&(c=0,h+=l,l=0,a+=1),d=parseInt(b[a],10),a+=1,f=parseInt(b[a],10),a+=1,m=parseInt(b[a],10),m>l&&(l=m),a+=1,g=0;g<d;g++)ff.push(c),gf.push(h),Ob.push(f),Pb.push(m),c+=f;else for(h=!1,a=1;a<b.length;)ff.push(parseInt(b[a],
10)),a+=1,gf.push(parseInt(b[a],10)),a+=1,a>=b.length?(c=0,h=!0):c=parseInt(b[a],10),0>c?(h=!0,Ob.push(Math.abs(c)),a+=1,c=parseInt(b[a++],10),Pb.push(Math.abs(c))):h?(Ob.push(Ob[Ob.length-1]),Pb.push(Pb[Pb.length-1])):(Ob.push(parseInt(b[a],10)),a+=1,Pb.push(parseInt(b[a],10)),a+=1);ef.onload=function(){ng=!0};ef.src=b[0]}a=e.overlay_labels;null!=a&&(Qb=a.split(","));hf=null;a=e.auto_enhance_background;null!=a&&(hf=parseInt(a,10)-1);Dc=null;a=e.auto_enhance;if(null!=a)for(c=e.overlay_probe_table,
b=a.split(","),Dc=Array(b.length),a=0;a<b.length;a++)"x"==b[a].trim().toLowerCase()?Dc[a]=-1:Dc[a]=parseInt(b[a].trim(),10)-1,null==c&&(nc[a]=Dc[a]);Ec=!1;nb=-1;a=e.overlay_enhance;null!=a&&(Ec=!0,nb=parseInt(a,10)-1);oc=null;bd=!0;a=e.overlay_allow_hoverzones;if(null!=a)for(b=a.split(","),oc=Array(b.length),a=0;a<b.length;a++)if(oc[a]=!0,E(b[a],"n")||E(b[a],"f"))oc[a]=!1;R=X=null;jf=og=!1;a=e.window_size;null!=a&&(b=a.split(","),"div"==b[0]?jf=!0:(R=parseInt(b[0],10),X=parseInt(b[1],10)),og=!0);
Fd=[];a=e.use_for_all_frames;if(null!=a)for(b=a.split(","),a=0;a<b.length;a+=2)Fd[parseInt(b[a],10)]=parseInt(b[a+1],10)-1;Gd=-1;a=e.skip_missing;null!=a&&(Gd=parseInt(a,10));pg="#00000000";a=e.skip_missing_color;null!=a&&(pg=a);qe=null;a=e.overlay_spacer;if(null!=a)for(b=a.split(","),qe=Array(b.length),a=0;a<b.length;a++)qe[a]=parseInt(b[a],10);a=e.overlay_probe_table;if(null!=a)for(b=a.split(","),a=0;a<b.length;a++)"x"==b[a].trim().toLowerCase()?nc[a]=-1:nc[a]=parseInt(b[a],10)-1;kf=[];a=e.overlay_ontop;
if(null!=a)for(b=a.split(","),a=0;a<b.length;a++)kf[parseInt(b[a],10)-1]=!0;Fc=null;a=e.overlay_order;null==a&&(a=e.overlay_zorder);if(null!=a)for(b=a.split(","),Fc=Array(b.length),a=0;a<b.length;a++)Fc[parseInt(b[a],10)-1]=a;Rb=null;a=e.overlay_links;if(null!=a)for(b=a.split(","),Rb=Array(b.length),a=0;a<b.length;a++)Rb[a]=parseInt(b[a],10);qg=[];L=null;a=e.overlay_slice;if(null!=a)for(b=a.split(","),a=0;a<b.length;a++)qg[parseInt(b[a],10)-1]=!0;rg=!0;a=e.slice_smoothing;E(a,"f")&&(rg=!1);cd=null;
a=e.overlay_clear;if(null!=a)for(b=a.split(","),cd=Array(b.length),a=0;a<b.length;a++)cd[a]=b[a].trim().toLowerCase();sg=!1;a=e.transparency;null!=a&&(b=a.split(","),1==b.length?tg=ug=vg=parseInt(b[0],10):(tg=parseInt(b[0],10),ug=parseInt(b[1],10),vg=parseInt(b[2],10)),sg=!0);lf=!1;a=e.transparency_list;if(null!=a){b=a.split(",");wg=[];for(a=0;a<b.length;a++)wg[parseInt(b[a].trim(),10)-1]=!0;lf=!0}re=null;a=e.overlay_transparent_amount;if(null!=a)for(b=a.split(","),re=Array(b.length),a=0;a<b.length;a++)re[a]=
parseFloat(b[a])/100;Gc=null;a=e.overlay_zoom;if(null!=Qb&&null!=a)for(b=a.split(","),Gc=Array(b.length),a=0;a<b.length;a++)if(Gc[a]=1,E(b[a],"n")||E(b[a],"f"))Gc[a]=0;else if(E(b[a],"d")||E(b[a],"h"))Gc[a]=-1;ob=null;xg=[];a=e.overlay_preserve_list;if(null!=Qb&&null!=a)for(b=a.split(","),ob=Array(b.length),a=0;a<b.length;a++){ob[a]=!0;if(E(b[a],"n")||E(b[a],"f"))ob[a]=!1;if(E(b[a],"a")||E(b[a],"A"))xg[a]=!0}Z=null;if(null!=Qb&&null!=ob)for(b=e.overlay_preserve.replace(/&/g,",&,").split(","),c=e.overlay_preserve_position,
null!=c&&(c=c.split(",")),h=0,Z=Array(ob.length),a=f=0;a<ob.length;a++)if(ob[a]){Z[a]=[];m=0;do{Z[a][m]=[];for(d=0;4>d;d++)Z[a][m][d]=parseInt(b[f].trim(),10),f+=1;Z[a][m][2]=Z[a][m][2]-Z[a][m][0]+1;Z[a][m][3]=Z[a][m][3]-Z[a][m][1]+1;null!=c?(Z[a][m][4]=parseInt(c[h],10),Z[a][m][5]=parseInt(c[h+1],10),h+=2):(Z[a][m][4]=Z[a][m][0],Z[a][m][5]=Z[a][m][1]);f<b.length&&"&"==b[f].trim()?(f+=1,m+=1,d=!0):d=!1}while(d)}se=0;yg=" ";pc="white";Hd="transparent";Id="14pt arial";zg=!1;a=e.times_label_style;null!=
a&&(b=a.split(","),pc=b[0].trim(),1<b.length&&(se=Math.floor(60*parseFloat(b[1]))),1<b.length&&(se="?"==b[1].trim()||"auto"==b[1].trim().toLowerCase()?-Math.floor((new Date).getTimezoneOffset()):Math.floor(60*parseFloat(b[1]))),2<b.length&&(yg=b[2].trim()),3<b.length&&(Hd=b[3].trim()),4<b.length&&(Id=b[4].trim()),5<b.length&&-1!=b[5].trim().indexOf("t")&&(zg=!0));0==pc.indexOf("0x")&&(pc="#"+pc.substring(2));0==Hd.indexOf("0x")&&(Hd="#"+Hd.substring(2));dd=parseInt(Id,10);Mh=new eb("black","white",
Id,"black",20,5,5);Ag=!1;a=e.to_from_lock;null!=a&&(Ag=E(a,"t")?!0:!1);a="black";d="white";l="14px arial";c=null;m=f=h=10;Bg=Cg=" ";mf=ed=null;a=e.dirspd_display_style;null!=a&&(b=a.split(","),a=b[0].trim(),d=b[1].trim(),l=b[2].trim(),Bg=b[3],Cg=b[4],5<b.length&&(c=b[5].trim(),h=parseInt(b[6],10),f=parseInt(b[7],10),m=parseInt(b[8],10)),mf=new eb(a,d,l,c,h,f,m));c="black";h="white";f="14px arial";m=null;g=l=d=10;a=e.tipbox_display_style;null!=a&&(b=a.split(","),c=b[0].trim(),h=b[1].trim(),f=b[2].trim(),
3<b.length&&(m=b[3].trim(),d=parseInt(b[4],10),l=parseInt(b[5],10),g=parseInt(b[6],10)));Dg=new eb(c,h,f,m,d,l,g);fd=null;ca=e.image_base;null!=ca?fd=ca=ca.trim():ca=null!=e.image_only_base?e.image_only_base.trim():null;Eg=ca;a=e.overlay_base;null!=a&&(Sb=a.trim());te=!0;a=e.zip_only;null!=a&&E(a,"f")&&(te=!1);Hc=!1;a=e.zip_filename;null!=a&&(Hc=!0,nf=a.trim());ad=!0;a=e.filenames;null==a&&(a=e.background_filenames);null!=a&&Nh(a);a=e.basename;null!=a&&(c=e.base_starting_number,h=0,f=1,null!=c&&(b=
c.split(","),h=parseInt(b[0],10),1<b.length&&(f=parseInt(b[1],10))),v=e.num_frames,null==v&&(v=e.num_images),v=parseInt(v,10),Oh(a,h,f));of=!0;b=e.zip_static;null!=b&&(E(b,"f")||E(b,"n"))&&(of=!1);pf=!0;b=e.background_static;null!=b&&(E(b,"f")||E(b,"n"))&&(pf=!1);a=e.overlay_filenames;null!=a&&Ph(a);Ca=null;a=e.image_preserve;if(null!=a)for(b=a.split(","),Ca=[],a=0;a<b.length;a++)Ca[a]=parseInt(b[a].trim(),10),1<a%4&&(Ca[a]=Ca[a]-Ca[a-2]+1);Fg=!0;a=e.keep_zoom;null!=a&&E(a,"f")&&(Fg=!1);Jd=Gg=0;Hg=
!1;a=e.hide_bottom;null!=a&&(b=a.split(","),Gg=parseInt(b[0].trim(),10),1<b.length&&E(b[1],"t")&&(Hg=!0));Kd=Ig=0;Jg=!1;a=e.hide_top;null!=a&&(b=a.split(","),Ig=parseInt(b[0].trim(),10),1<b.length&&E(b[1],"t")&&(Jg=!0));Ld=Kg=0;Lg=!1;a=e.hide_left;null!=a&&(b=a.split(","),Kg=parseInt(b[0].trim(),10),1<b.length&&E(b[1],"t")&&(Lg=!0));Md=Mg=0;Ng=!1;a=e.hide_right;null!=a&&(b=a.split(","),Mg=parseInt(b[0].trim(),10),1<b.length&&E(b[1],"t")&&(Ng=!0));Og=!1;a=e.hide_background;null!=a&&E(a,"t")&&(Og=!0);
Pg="<div>";Qg=300;Rg=500;a=e.popup_style;null!=a&&(Pg='<div style="'+a+'">');a=e.popup_window_size;null!=a&&(b=a.split(","),Rg=b[0],Qg=b[1]);Sg=!1;a=e.wheel_frames;null!=a&&(Sg=!0,ka.useWheel(HAniS.wheel));Tg=xa=!1;a=e.active_zoom;null!=a&&E(a,"t")&&(null==ya&&(xa=!0),ka.useWheel(HAniS.wheel));qf=!1;a=e.cycle_zoom;null!=a&&E(a,"t")&&(qf=!0);a=e.initial_zoom;null!=a&&(b=a.split(","),qc="auto"!=b[0].toLowerCase()?parseFloat(b[0]):"auto",1<b.length?(Nd=parseInt(b[1],10),Ug=parseInt(b[2],10)):Nd=-1,Vg=
!0);gd=1;hd=!1;la=null;a=e.zoom_scale;if(null!=a)if(b=a.split(","),1===b.length)E(a,"hi_res")?(hd=!0,gd=0):gd=parseFloat(a);else{la=Array(b.length);for(a=0;a<b.length;a++)la[a]=parseFloat(b[a]);hd=!0}Ic=9999999;a=e.maximum_zoom;null!=a&&(Ic=parseFloat(a));ue=!0;a=e.use_progress_bar;null!=a&&E(a,"f")&&(ue=!1);a=e.dwell;null!=a&&(b=a.split(","),hb=parseInt(b[0].trim(),10),1<b.length&&(Tb=parseInt(b[1].trim(),10),10>Tb&&(Tb=10),Jc=parseInt(b[2].trim(),10),rf=parseInt(b[3].trim(),10)));a=e.rate;null!=
a&&(b=a.split(","),hb=Math.round(1E4/parseFloat(b[0].trim())),1<b.length&&(Tb=Math.round(1E4/parseFloat(b[2].trim())),10>Tb&&(Tb=10),Jc=Math.round(1E4/parseFloat(b[1].trim()))));a=e.frame_times_template;null!=a&&(b=a.split(","));pb=null;a=e.times;if(null!=a){b=a.split(",");pb=Array(b.length);for(a=0;a<b.length;a++)pb[a]=parseInt(b[a].trim(),10);ua(pb)}a=e.extrap_times_filename;if(null!=a){pb=[];var k=new XMLHttpRequest;k.open("get",a,!0);k.onload=function(){for(var a=k.responseText.split("\n"),b=
0;b<a.length;b++){var c=a[b].split(" ");if(3==c.length){c[2].trim();var d=parseInt(c[0],10)-1;pb[d]=100*parseInt(c[2].substring(0,2),10)+parseInt(c[2].substring(3,5),10)+parseInt(c[2].substring(6,8),10)/30}}ua(pb)};k.send()}Od=null;a=e.extrap_times_template;null!=a&&(Od=RegExp(a));Wg=["Click on target's initial position","Click on target's final position","Move pointer around or click here to select target"];Xg=10;a=e.extrap_prompts_position;null!=a&&E(a,"bot")&&(Xg=9999);a=e.extrap_prompts;null!=
a&&(Wg=a.split(","));ve=["Click on first point to mark","Save points","Remove last point"];a=e.mark_prompts;null!=a&&(ve=a.split(","));we=!0;a=e.mark_close;null!=a&&E(a,"f")&&(we=!1);sf="12pt Arial";Yg="white";a=e.mark_prompts_style;null!=a&&(b=a.split(","),sf=b[0].trim(),1<b.length&&(Yg=b[1].trim()));Zg=e.controls;fa("controls = "+e.controls);fa("bottom_controls = "+e.bottom_controls);Kc=xe=Ub=Vb=qb=rb=Ab=null;null!=Zg&&he(Zg,!0);$g=e.bottom_controls;null!=$g&&he($g,!1);Lc=!1;a=e.probe_table;null!=
a&&O(a);b=e.enhance_filename;null==b&&(b=e.enhance_table);if(null!=b){fa("Reading enhancement table...");Lc=!1;k=new XMLHttpRequest;sb=[];Mc=[];ye=[];Nc=[];Wb=[];var ah,Da,t;Wa=[];Xa=[];Ya=[];Pd=[];w=-1;bh=!0;var q=!1,p,x,B,tf,u,r,D,uf,A,H,z,F,I;k.onload=function(){for(var a=this.responseText.split("\n"),b=0;b<a.length;b++)if(!(2>a[b].length)){var c=a[b].replace(/\s+/g," ").trim(),d=c.indexOf("#");if(0!=d)if(0<d&&(c=c.substring(0,d)),d=c.split(","),0==d[0].indexOf("*"))w++,sb[w]=Array(256),Nc[w]=
Array(256),Mc[w]=Array(256),Wb[w]=Array(256),Wa[w]=Array(256),Xa[w]=Array(256),Ya[w]=Array(256),Pd[w]=Array(256),sb[w]=Array(256),ye[w]=1<d.length?d[1].trim():"None",ah=" ",Da="Value =",t=1,c=n("option"),c.innerHTML=d[0].substring(1),c.value=w,null!=za&&za.add(c);else{var h=c.indexOf("value");0>h&&(h=c.indexOf("probe"));q=!1;H=z=0;0<h&&(d=c.substring(h+1),c=c.substring(0,h),h=d.indexOf("="),d=d.substring(h+1),d=d.split(","),1==d.length?(Da=d[0].trim(),t=-1,q=!1):(H=parseFloat(d[0].trim()),z=parseFloat(d[1].trim()),
2<d.length&&(t=parseInt(d[2],10)),3<d.length&&(ah=Qh(d[3].trim())),4<d.length&&(Da=d[4].trim()),q=!0));c=c.split(" ");p=parseInt(c[0].trim(),10);x=parseInt(c[1].trim(),10);B=x-p;tf=parseFloat(c[2].trim());u=parseFloat(c[3].trim());r=parseFloat(c[4].trim());D=parseFloat(c[5].trim());uf=parseFloat(c[6].trim());A=parseFloat(c[7].trim());F=I=255;9<c.length&&(F=parseFloat(c[8].trim()),I=parseFloat(c[9].trim()));for(c=p;c<=x;c++)0===B?(Wa[w][p]=tf,Xa[w][p]=r,Ya[w][p]=uf,Pd[w][p]=F):(Wa[w][c]=Math.round(tf+
(u-tf)*(c-p)/B),Xa[w][c]=Math.round(r+(D-r)*(c-p)/B),Ya[w][c]=Math.round(uf+(A-uf)*(c-p)/B),Pd[w][c]=Math.round(F+(I-F)*(c-p)/B)),Nc[w][c]=Da,Mc[w][c]=ah,Wb[w][c]=t,q&&(sb[w][c]=H+(z-H)*(c-p)/B)}}-1!=nb&&C[nb].checked&&(za.disabled=!1);Lc=!0;ba()};k.open("get",b,!0);k.send()}else ba()}function ba(){var b=e.sprite_filenames;if(null!=b){var a=b.split(",");vf=0;ia=[];b=e.sprite_images_offset;Oc=-1;null!=b&&(Oc=parseInt(b,10)-1);for(b=0;b<a.length;b++){ia[b]=new Image;ia[b].gotit=!1;ia[b].inx=b;ia[b].fromfile=
!0;var d="/";0<a[b].indexOf("?")&&(d="?");ia[b].zoomme=0<a[b].indexOf(d+"zoom");ia[b].anim=0<a[b].indexOf(d+"animate");d=a[b].indexOf(d);0<d&&(a[b]=a[b].substring(0,d));ia[b].onload=function(){ia[this.inx].gotit=!0;vf++;vf==a.length&&Y()};ia[b].src=a[b].trim()}}else Y()}function Y(){for(var b=Object.keys(e),a=0;a<b.length;a++)E(b[a],"hotspot")&&Kb("hotspot="+e[b[a]]);ad?HAniS.getFOF():(rc=!0,Ja())}function O(b){var a=new XMLHttpRequest;sb=[];ye=[];Mc=[];var d=" ";Nc=[];var c="Value=";Wb=[];var h=
1;Pc=[];wf=[];Wa=[];Xa=[];Ya=[];var e,m=-1;w=-1;var l=0;a.onload=function(){for(var a=this.responseText.split("\n"),b=0;b<a.length;b++)if(!(2>a[b].length)){var f=a[b].replace(/\s+/g," ").trim().split(","),g=f[0].split(" ");if(0==g[0].indexOf("*"))w++,sb[w]=[],Nc[w]=[],Mc[w]=[],Wb[w]=[],Wa[w]=[],Xa[w]=[],Ya[w]=[],wf[w]=[],Pc[w]=[],m=-1,ye[w]=1<f.length?f[1].trim():"None",l=1;else if(0!=l){m++;var t=Array(3);sb[w][m]=parseFloat(g[0]);Wa[w][m]=parseInt(g[1].trim(),10);Xa[w][m]=parseInt(g[2].trim(),10);
Ya[w][m]=parseInt(g[3].trim(),10);0!=m&&(t[0]=Wa[w][m]-Wa[w][m-1],t[1]=Xa[w][m]-Xa[w][m-1],t[2]=Ya[w][m]-Ya[w][m-1],e=0,Math.abs(t[1])>Math.abs(t[e])&&(e=1),Math.abs(t[2])>Math.abs(t[e])&&(e=2),wf[w][m-1]=e,Pc[w][m-1]=t,0==Pc[w][m-1][e]&&(Pc[w][m-1][e]=1));1<f.length&&(0==f[1].trim().indexOf('"')?(h=-1,f=f[1].trim(),c=f.substr(1,f.length-2),d=""):(h=parseInt(f[1],10),2<f.length&&(d=Qh(f[2].trim())),3<f.length&&(c=f[3].trim())));Nc[w][m]=c;Wb[w][m]=h;Mc[w][m]=d}}Lc=!0};a.open("get",b,!0);a.send()}
function xb(b){b=b.split(",");var a=b[0].trim();"PS"===a?(Xb=new ii,Xb.init(b)):"CE"==a?(Xb=new ji,Xb.init(b)):"LCC"==a?(Xb=new ki,Xb.init(b)):(Xb=null,xf=parseFloat(b[0]),ch=parseFloat(b[1]),Rh=parseFloat(b[2]),Sh=parseFloat(b[3]))}function dg(b){var a=new XMLHttpRequest;a.onload=function(){q(this.responseText.split("\n"))};a.open("get",b+"?"+Math.round(1E5*Math.random()),!0);a.send()}function We(b){var a;if(null!=cd){for(a=0;a<cd.length;a++)-1!=cd[a].indexOf(b)&&(C[a].checked=!1);for(a=0;a<cd.length;a++)Ka(a)}}
function ua(b){yf=Array(b.length);for(var a=0;a<b.length;a++){var d=60*Math.floor(b[a]/100)+Math.floor(b[a])%100;0===a&&(Yb=d);var c=d-Yb;0>c&&(c=d+1440-Yb);yf[a]=c;fa("times s="+d+"  min="+yf[a])}Yb+=se;1440<=Yb&&(Yb-=1440);0>Yb&&(Yb+=1440);fa("Starting minute = "+Yb)}function hc(b,a){if(0!=b)for(var d=0;d<b;d++)0==C[Ea[d].overlay].isGhost&&(C[Ea[d].overlay].parentNode.style.visibility=a)}function Ta(){0!=tb?hc(tb,"visible"):0!=dh&&hc(dh,"hidden");rc=!0;Ja()}function vd(b,a){id||(mb.height=a,mb.width=
b,mc.height=a,mc.width=b,Qd.height=a,Qd.width=b,ze.height=a,ze.width=b,Rd=ze.getContext("2d"),R=b,X=a,Ae=R/2-100,Be=X/2-10,u=1*ma/R,r=1*ha/X,eh&&(eh=!1,null!=fh&&fh()),Va.style.height=X+"px",Va.style.width=R+"px",sc.style.height=X+"px",sc.style.width=R+"px",jd.style.height=X+"px",jd.style.width=R+"px",ie(v,!1))}function Xe(){for(var b=0,a={},d=0;d<v;a={ii:a.ii},d++){a.ii=d;var c=null==ca?sa[d]:sa[d].substring(sa[d].lastIndexOf("/")+1);(c=gh.file(c))?c.async("arraybuffer").then(function(a){return function(c){c=
new Blob([c]);tc[a.ii]=URL.createObjectURL(c);b++;b>=v&&wd()}}(a),function(a){return function(){tc[a.ii]=null;b++;b>=v&&wd()}}(a)):(tc[a.ii]=null,b++,b>=v&&wd())}}function wd(){var b=0;if(0==aa)ic();else for(var a=0;a<v;a++){uc[a]=[];for(var d={},c=0;c<aa;d={ii:d.ii,jj:d.jj},c++){d.ii=a;d.jj=c;var h=null==Sb&&null==ca?da[a][c]:da[a][c].substring(da[a][c].lastIndexOf("/")+1);(h=gh.file(h))?h.async("arraybuffer").then(function(a){return function(c){c=new Blob([c]);uc[a.ii][a.jj]=URL.createObjectURL(c);
b++;b>=v*aa&&ic()}}(d),function(a){return function(){uc[a.ii][a.jj]=null;b++;b>=v*aa&&ic()}}(d)):(uc[a][c]=null,b++,b>=v*aa&&ic())}}}function Ja(){if(Hc){var b=new XMLHttpRequest,a=null==fd?nf:fd+nf;of||(a=a+"?"+Math.round(1E5*Math.random()));b.open("GET",a,!0);b.responseType="arraybuffer";tc=[];uc=[];b.addEventListener("progress",function(a){a.lengthComputable&&ra("Loading ZIP file",a.total,a.loaded)});b.onload=function(a){(new JSZip).loadAsync(this.response).then(function(a){gh=a;Xe()},function(){fa("Unable to read ZIP file: "+
nf)})};b.send()}else ic()}function ic(){var b,a,d;void 0!=Ce&&Ce(!1);var c="?"+Math.round(1E4*Math.random()),h=[];h[0]=vc;for(b=1;b<v;b++)h[b]=b<=vc?b-1:b;Fa=Array(v);Bb=Ga=0;hh=ue;zf&&(ib.max=v);id&&(kd||Ec)&&(Zb=[],Na=[],Qc=[],Af=[],De=[]);null!=za&&(za.selectedIndex=0);for(var e=0;e<v;e++){b=h[e];id&&(kd||Ec)&&(Zb[b]=n("canvas"),Na[b]=n("canvas"));Fa[b]=new Image;Fa[b].gotit=!1;Fa[b].frameNum=b;Fa[b].onerror=function(){Ga++};Fa[b].onload=function(){id&&(ha=this.height,ma=this.width,Za=ha,$a=ma,
id=!1,og?jf?HAniS.setWindowSize(y.offsetWidth,y.offsetHeight):vd(R,X):vd(ma,ha),Vg&&("auto"==qc&&(qc=(u+r)/2,Nd=-1),Za/=qc,$a/=qc,0>Nd&&(Nd=ma/2,Ug=ha/2),N=Math.round(Nd-ma/2/qc),P=Math.round(Ug-ha/2/qc),z=F=qc,1!=qc&&(xa=!1,HAniS.toggleZooming())));Hc&&null!=tc[this.frameNum]&&URL.revokeObjectURL(tc[this.frameNum]);if(0<Ee&&!ld){Bf.height=ha;Bf.width=ma;Sd=Bf.getContext("2d");Sd.clearRect(0,0,R,X);for(var b=0;b<Oa.length;b++){for(var e=Oa[b].ctx.getImageData(0,0,Oa[b].width,Oa[b].height).data,m=
Sd.getImageData(Oa[b].xmin,Oa[b].ymin,Oa[b].width,Oa[b].height),f=3;f<e.length;f+=4)0!=e[f]&&(m.data[f]=b+1);Sd.putImageData(m,Oa[b].xmin,Oa[b].ymin)}xa||(jb=!0);z==Fe&&(jb=!0);ld=!0}if(rc){rc=!1;I=mb.getContext("2d");I.imageSmoothingEnabled=Ed;I.fillStyle="blue";I.font="bold 20px Arial";g=mc.getContext("2d");g.imageSmoothingEnabled=Ed;Pa=Array(v);ie(v,!0);Ge&&!Qa?wa(va(vc)):wa(va(x));if(0<aa)for(K=Array(v),f=0;f<v;f++)for(d=h[f],K[d]=Array(aa),a=0;a<aa;a++)K[d][a]=new Image,K[d][a].gotit=!1,K[d][a].frameNum=
d,K[d][a].overlayNum=a,K[d][a].onerror=function(){Ga++},K[d][a].onload=function(){this.gotit=!0;var a=this.frameNum;Ga++;k();!pe||this.height==ha&&this.width==ma?this.overlayNum==Gd-1&&(Pa[this.frameNum]=0):(this.gotit=!1,fa("Bad image size:"+this.src));if(Ec&&this.gotit&&this.overlayNum==nb)Zb[a].height=this.height,Zb[a].width=this.width,Td=Zb[a].getContext("2d"),Td.drawImage(this,0,0),Af[a]=Td.getImageData(0,0,this.width,this.height).data,Na[a].height=this.height,Na[a].width=this.width,Qc[a]=Na[a].getContext("2d"),
Qc[a].drawImage(this,0,0),De[a]=Qc[a].getImageData(0,0,this.width,this.height),K[a][this.overlayNum]=null,K[a][this.overlayNum]=Na[a],K[a][this.overlayNum].gotit=!0;else if(this.gotit&&C[this.overlayNum].hotspotIndex){var b=n("canvas");b.height=this.height;b.width=this.width;var c=b.getContext("2d");c.drawImage(this,0,0);var d=c.getImageData(0,0,this.width,this.height).data,h=d.length;var e=this.overlayNum;var f;for(f=0;f<h;f+=4)if(0!=d[f]){0==kb&&(lb=[]);var m=d[f];var l=Math.floor(f/4/b.width);
c=Math.floor(f/4%b.width);lb[kb]=new yb(c,l,"spritefn",m,"pan",null,null,e,a,null);kb++}}else if(this.gotit&&sg&&(!lf||lf&&wg[this.overlayNum])){b=n("canvas");b.height=this.height;b.width=this.width;c=b.getContext("2d");c.drawImage(this,0,0);l=c.getImageData(0,0,this.width,this.height);d=l.data;h=d.length;for(f=0;f<h;f+=4)d[f]===tg&&d[f+1]===ug&&d[f+2]===vg&&(d[f+3]=0);c.putImageData(l,0,0);K[a][this.overlayNum]=null;K[a][this.overlayNum]=b;K[a][this.overlayNum].gotit=!0}this.gotit&&kf[this.overlayNum]?
(Cf.clearRect(0,0,R,X),Cf.drawImage(K[a][this.overlayNum],0,0,R,X)):this.gotit&&qg[this.overlayNum]&&null!=L&&(b=n("canvas"),b.height=ha,b.width=ma,8>L.length&&(L[4]=0,L[5]=0,L[6]=ma,L[7]=ha),c=b.getContext("2d"),c.imageSmoothingEnabled=rg,c.drawImage(this,L[0],L[1],L[2],L[3],L[4],L[5],L[6],L[7]),K[a][this.overlayNum]=null,K[a][this.overlayNum]=b,K[a][this.overlayNum].gotit=!0,null!=ob&&ob[this.overlayNum]&&(K[a][this.overlayNum].origImage=this));Hc&&null!=uc[a][this.overlayNum]&&URL.revokeObjectURL(uc[a][this.overlayNum])},
b=da[d][a],void 0!=Fd[a+1]&&(b=Fd[a+1],b>=v&&(b=v-1),b=da[b][a]),void 0==Ud||Ud[a]||(b+=c),K[d][a].src=b,K[d][a].src=Hc&&(te||uc[d][a])?uc[d][a]:b,Bb++;if(null!=Rc)for($b=[],a=0;a<Rc.length;a++)$b[a]=new Image,$b[a].gotit=!1,$b[a].onerror=function(a){Ga++},$b[a].onload=function(a){a.currentTarget.gotit=!0;Ga++;k()},$b[a].src=Rc[a],Bb++;if(null!=Ha&&0<Ha.length)for(ta=[],a=0;a<Ha.length;a++)if(void 0!=Ha[a])for(ta[a]=[],d=0;d<Ha[a].length;d++)for(ta[a][d]=[],f=0;f<v;f++)Th(Ha[a][d],"/")?(b=da[f][a].lastIndexOf("/"),
b=da[f][a].substring(0,b+1)+Ha[a][d]+da[f][a].substring(b+1),ta[a][d][f]=new Image,ta[a][d][f].gotit=!1,ta[a][d][f].onerror=function(a){Ga++;k()},ta[a][d][f].onload=function(a){a.currentTarget.gotit=!0;Ga++;k()},ta[a][d][f].src=b,Bb++):0===f?(ta[a][d][0]=new Image,ta[a][d][0].gotit=!1,ta[a][d][0].onerror=function(a){Ga++;k()},ta[a][d][0].onload=function(a){a.currentTarget.gotit=!0;Ga++;k()},ta[a][d][0].src=Ha[a][d],Bb++):ta[a][d][f]=ta[a][d][0]}!pe&&0!=this.height&&0!=this.width||this.height==ha&&
this.width==ma?(this.gotit=!0,0==Gd&&(Pa[this.frameNum]=0)):(this.gotit=!1,fa("Image has invalid size:"+this.src));kd&&this.gotit&&(f=this.frameNum,Zb[f].height=this.height,Zb[f].width=this.width,Td=Zb[f].getContext("2d"),Td.drawImage(this,0,0),Af[f]=Td.getImageData(0,0,this.width,this.height).data,Na[f].height=this.height,Na[f].width=this.width,Qc[f]=Na[f].getContext("2d"),Qc[f].drawImage(this,0,0),De[f]=Qc[f].getImageData(0,0,this.width,this.height),Fa[f]=null,Fa[f]=Na[f],Fa[f].gotit=!0);Ga++;k();
Fg||HAniS.resetZoom();Sc=!0;Uh||(Uh=!0,Aa=!1,Vh());H(Qa)};var m=sa[b];void 0!=Fd[0]&&(m=Fd[0],m>=v&&(m=v-1),m=sa[m]);pf||(m+=c);Fa[b].src=Hc&&(te||tc[b])?tc[b]:m;Bb++}Tc=Cb=!1;W()}function ea(b,a,d,c,h,f){b.label_on=d;b.label_off=c;gb&&(b.className=f);d=null;c=e[a+"_labels"];null==c&&(c=e[a+"_label"]);null!=c&&(c=c.split(","),b.label_on=c[0].trim(),1<c.length&&(b.label_off=c[1].trim()),2<c.length&&(d="width:"+c[2].trim()+"px;"));null!=h&&(b.title=h);b.innerHTML=b.label_on;h=a=c=e[a+"_style"];null!=
c&&(c=c.split("&"),1<c.length&&(a=c[0],h=c[1]));b.style_on=(null!=d?d:"")+wc+a;b.style_off=(null!=d?d:"")+wc+h;null!=b.style_on&&1<b.style_on.length?b.setAttribute("style",b.style_on):(b.style_on=null,b.style_off=null)}function he(b,a){wc=e.buttons_style;null==wc&&(wc="");var d=null,c=null;d=a?e.controls_tooltip:e.bottom_controls_tooltip;var h=b.split(",");if(null!=d){var f=d.split(",");f.length!=h.length&&(fa("!!! Number of tooltips must equal number of controls!"),f=d=null)}for(b=0;b<h.length;b++){var m=
null!=d?f[b]:null;var l=h[b].trim();c=l.indexOf("/");if(0===c||0===b){0===c&&(l=l.substring(1));D=n("div");D.align=Bd;var g=e.controls_style;null!=g?D.setAttribute("style",g):D.setAttribute("style","position:relative;padding:2px;width:100%;");a?(y.insertBefore(D,Va),Df=D):(g=e.bottom_controls_style,null!=g&&D.setAttribute("style",g),y.appendChild(D),Ef=D)}"enhance"==l.trim()&&(za=n("select"),c=e.enhance_style,null!=c&&za.setAttribute("style",c),null!=m&&(za.title=m),c=n("option"),c.innerHTML="Pick Enhancement",
c.value=-1,za.add(c),za.addEventListener("change",HAniS.doEnhance,!1),kd=!Ec,za.disabled=kd?!1:!0,D.appendChild(za));"startstop"==l&&(Ab=n("button"),ea(Ab,"startstop","Start","Stop",m,"startstop start"),Ab.addEventListener("click",HAniS.toggleIsLooping,!1),D.appendChild(Ab));"looprock"==l&&(Vd=n("button"),ea(Vd,"looprock","Rock","Loop",m,"looprock rock"),Ff=1,Vd.addEventListener("click",HAniS.toggleLoopRock,!1),D.appendChild(Vd));"extrap"==l&&(ac=n("button"),ea(ac,"extrap","Enable Extrap","Disable Extrap",
m,"extrap"),ac.addEventListener("click",HAniS.toggleExtrap,!1),D.appendChild(ac));E(l,"location")&&(md=n("button"),ea(md,"location","Show Loc","Hide Loc",m,"location"),0<l.indexOf("/on")?(J(md,!1,"location off"),nd=!0,Ba.push(y.style.cursor),y.style.cursor=ne):(nd=!1,y.style.cursor=Ba.pop()),md.addEventListener("click",function(){(nd=!nd)?(J(md,!1,"location off"),Ba.push(y.style.cursor),y.style.cursor=ne):(J(md,!0,"location on"),y.style.cursor=Ba.pop());W()},!1),D.appendChild(md));"distance"==l&&
(bc=n("button"),ea(bc,"distance","Show dist","Hide dist",m,"distance"),lc=me=!1,bc.addEventListener("click",function(){(lc=!lc)?(J(bc,!1,"distance off"),Ba.push(y.style.cursor),y.style.cursor=af):(J(bc,!0,"distance on"),y.style.cursor=Ba.pop())},!1),D.appendChild(bc));E(l,"probe")&&(od=n("button"),ea(od,"probe","Show probe","Hide probe",m,"probe"),0<l.indexOf("/on")?(J(od,!1,"probe off"),Nb=!0,Ba.push(y.style.cursor),y.style.cursor=oe):(Nb=!1,y.style.cursor=Ba.pop()),od.addEventListener("click",function(){(Nb=
!Nb)?(J(od,!1,"probe off"),Ba.push(y.style.cursor),y.style.cursor=oe):(J(od,!0,"probe on"),y.style.cursor=Ba.pop())},!1),D.appendChild(od));"mark"==l&&(Uc=n("button"),ea(Uc,"mark","Mark","Stop Mark",m,"mark"),Wd=!0,Uc.addEventListener("click",function(){ub=!ub;na=[];ub?(pd=0,J(Uc,!1,"mark off"),null!=ya&&(ya.disabled=!0),Ba.push(y.style.cursor),y.style.cursor=bf):(J(Uc,!0,"mark on"),null!=ya&&(ya.disabled=!1),pd=-1,y.style.cursor=Ba.pop());W()},!1),Wh=new eb("black","white",sf,"black",20,5,5),ih=
new eb("black","white",sf,"black",20,5,5),D.appendChild(Uc));"refresh"==l&&(xe=n("button"),ea(xe,"refresh","Refresh",null,m,"refresh"),xe.addEventListener("click",HAniS.reloadFOF,!1),D.appendChild(xe));"restore"==l&&(Gf=n("button"),ea(Gf,"restore","Restore",null,m,"restore"),Gf.addEventListener("click",function(a){for(a=0;a<C.length;a++)C[a].checked=C[a].restorableState;for(a=0;a<C.length;a++)Ka(a)},!1),D.appendChild(Gf));"setframe"==l&&(ib=n("input"),gb&&(ib.className="setframe"),ib.type="range",
ib.min=1,ib.max=100,ib.value=1,He="Frame #*",null!=m&&(ib.title=m),g=e.setframe_label,null!=g&&(He=g),Xd=n("span"),Xd.innerHTML=He.replace("*",1),c="display:block;vertical-align:middle;"+e.setframe_style,ib.setAttribute("style",c),c=n("span"),c.setAttribute("style","display:inline-block;vertical-align:top;"),Xd.setAttribute("style","display:block;vertical-align:middle;"+e.setframe_label_style),c.appendChild(Xd),c.appendChild(ib),D.appendChild(c),ib.addEventListener("input",function(a){H(!1);a=parseInt(ib.value,
10)-1;0<=Pa[a]&&(wa(a),Xd.innerHTML=He.replace("*",x+1));V()},!1),zf=!0);"framelabel"==l&&(Ia=n("button"),gb&&(Ia.className="framelabel"),Ia.innerHTML="",null!=m&&(Ia.title=m),ab=null,g=e.frame_labels,null!=g&&(ab=g.split(","),Ia.innerHTML=ab[0]),c=wc+e.framelabel_style,null!=c&&Ia.setAttribute("style",c),c=e.framelabel_position,null!=c&&(c=c.split(","),Ia.style.position="absolute",Ia.style.left=y.offsetLeft+parseInt(c[0],10)+"px",Ia.style.top=y.offsetTop+parseInt(c[1],10)+"px"),D.appendChild(Ia));
if("autorefresh"==l||"autorefresh/off"==l)null!=Cc&&clearInterval(Cc),Kc=n("button"),ea(Kc,"autorefresh","Disable Auto Refresh","Enable Auto Refresh",m,"autorefresh"),Kc.addEventListener("click",HAniS.toggleAutoRefresh,!1),Dd=!1,D.appendChild(Kc),"autorefresh"==l?HAniS.toggleAutoRefresh():J(Kc,!1,"autotoggle off");"backward"==l&&(qb=n("button"),ea(qb,"backward","<","<",m,"step back"),qb.addEventListener("click",function(){H(!1);zb(-1);V()},!1),D.appendChild(qb));"forward"==l&&(rb=n("button"),ea(rb,
"forward",">",">",m,"step forward"),rb.addEventListener("click",function(){H(!1);zb(1);V()},!1),D.appendChild(rb));if("step"==l){c=e.step_labels;var k=null!=c?c.split(","):["<",">"];qb=n("button");gb&&(qb.className="step back");qb.innerHTML=k[0];qb.addEventListener("click",function(){H(!1);zb(-1);V()},!1);c=wc+e.step_style;null!=c&&qb.setAttribute("style",c);null!=m&&(qb.title=m);D.appendChild(qb);rb=n("button");gb&&(rb.className="step forward");rb.innerHTML=k[1];rb.addEventListener("click",function(){H(!1);
zb(1);V()},!1);null!=c&&rb.setAttribute("style",c);null!=m&&(rb.title=m);D.appendChild(rb)}"first"==l&&(Db=n("button"),ea(Db,"first","|<","|<",m,"firstlast first"),Db.addEventListener("click",function(){H(!1);wa(va(0));V()},!1),D.appendChild(Db));"last"==l&&(Eb=n("button"),ea(Eb,"last",">|",">|",m,"firstlast last"),Eb.addEventListener("click",function(){H(!1);wa(va(v-1));V()},!1),D.appendChild(Eb));"firstlast"==l&&(c=e.firstlast_labels,k=null!=c?c.split(","):["<<",">>"],Db=n("button"),gb&&(Db.className=
"firstlast"),Db.innerHTML=k[0],Db.addEventListener("click",function(){H(!1);wa(va(0));V()},!1),c=wc+e.firstlast_style,null!=c&&Db.setAttribute("style",c),null!=m&&(Db.title=m),D.appendChild(Db),Eb=n("button"),gb&&(Eb.className="firstlast"),Eb.innerHTML=k[1],Eb.addEventListener("click",function(){H(!1);wa(va(v-1));V()},!1),null!=c&&Eb.setAttribute("style",c),null!=m&&(Eb.title=m),D.appendChild(Eb));"setspeed"==l?(Fb=n("input"),gb&&(Fb.className="setspeed"),Fb.type="range",Fb.min=Tb,Fb.max=Jc,Fb.value=
Jc-hb,null!=m&&(Fb.title=m),c="vertical-align:middle;"+e.setspeed_style,Fb.setAttribute("style",c),Fb.addEventListener("input",function(a){hb=Jc-parseInt(Fb.value,10)+30;H(!0);V()},!1),D.appendChild(Fb)):"speed"==l&&(c=e.speed_labels,k=null!=c?c.split(","):["-","+"],Ub=n("button"),gb&&(Ub.className="speed slower"),Ub.innerHTML=k[0],Ub.addEventListener("click",function(){hb+=rf;Vb.disabled=!1;hb>Jc&&(hb=Jc,Ub.disabled=!0)},!1),c=wc+e.speed_style,null!=c&&Ub.setAttribute("style",c),null!=m&&(Ub.title=
m),D.appendChild(Ub),Vb=n("button"),gb&&(Vb.className="speed faster"),Vb.innerHTML=k[1],Vb.addEventListener("click",function(){hb-=rf;Ub.disabled=!1;hb<Tb&&(hb=Tb,Vb.disabled=!0)},!1),null!=c&&Vb.setAttribute("style",c),null!=m&&(Vb.title=m),D.appendChild(Vb));"zoom"==l&&(ya=n("button"),ea(ya,"zoom","Zoom","Un-zoom",m,"zoom off"),ya.addEventListener("click",HAniS.toggleZooming,!1),D.appendChild(ya),xa=!1);if("annotate"==l){Yd=n("button");ea(Yd,"annotate","Annotate","Finished",m,"annotate");ja=n("div");
ja.setAttribute("style","position:absolute;box-sizing:content-box;height:120px;width:180px;top:20px;left:20px;z-index:15;visibility:hidden;background-color:lightgray;border-width:6px;border-style:solid;border-color:magenta;border-radius:25px;padding:10px;font:normal normal normal 16px Arial;color:black;");ja.title="Drag this box around.  Select attributes, then go onto the image and click & drag";Vc=Wc=20;Ie=Gb=!1;jh=3;kh=11;Xc=Zd=0;p=[];ja.style["touch-action"]="none";var q=function(a){Wc=a.clientX-
Xc;Vc=a.clientY-Zd;ja.style.top=Vc+"px";ja.style.left=Wc+"px"};ja.addEventListener("mousedown",function(a){if(0!=a.clientX||0!=a.clientY)Ie=!0,Xc=a.clientX-Wc,Zd=a.clientY-Vc},!1);ja.addEventListener("mouseup",function(a){Ie=!1},!1);ja.addEventListener("mouseout",function(a){Ie&&q(a)},!1);ja.addEventListener("mousemove",function(a){Ie&&q(a)},!1);window.PointerEvent?(ja.addEventListener("pointerdown",function(a){"mouse"!=a.pointerType&&(Xc=a.clientX-Wc,Zd=a.clientY-Vc)},!1),ja.addEventListener("pointermove",
function(a){"mouse"!=a.pointerType&&(0==Xc&&(Xc=a.clientX,Zd=a.clientY),q(a))},!1)):ja.addEventListener("touchmove",function(a){a=a.changedTouches[0];0==Xc&&(Xc=a.clientX,Zd=a.clientY);q(a)},!1);Yd.addEventListener("click",function(){if(Gb=!Gb){p=[];Wc=y.offsetLeft;Vc=y.offsetTop;var a=e.annotate_position;null!=a&&(a=a.split(","),Wc+=parseInt(a[0],10),Vc+=parseInt(a[1],10));ja.style.top=Vc+"px";ja.style.left=Wc+"px";ja.style.visibility="visible";J(Yd,!1,"annotate off");Xh=xa;xa=!1;null!=ya&&(ya.disabled=
!0)}else ja.style.visibility="hidden",J(Yd,!0,"annotate on"),xa=Xh,null!=ya&&(ya.disabled=!1);W()},!0);$d=lh("Color Black White Red Green Blue Yellow Orange Cyan Magenta".split(" "),"black black white red green blue yellow orange cyan magenta".split(" "),function(a){});xc=lh("Width 1 2 3 4 5 6 7 8 10 12 14 16 18 20 24 28 32 36 38".split(" "),[1,1,2,3,4,5,6,7,8,10,12,14,16,18,20,24,28,32,36,38],function(a){6==ae.selectedIndex?kh=xc.selectedIndex:jh=xc.selectedIndex});xc.title="Select width or font size";
ae=lh("Type Arrow Circle Box Polygon Draw Text".split(" "),[-1,0,1,2,3,4,5],function(a){6==ae.selectedIndex?(Hb.focus(),Hb.select(),xc.selectedIndex=kh):xc.selectedIndex=jh;0==$d.selectedIndex&&($d.selectedIndex=2)});c=n("button");c.style.width="70px";c.style.margin="5px";c.innerHTML="Erase";c.title="Erase last item";c.addEventListener("click",function(){0<p.length&&(p.pop(),W())},!1);Hb=n("input");Hb.type="text";Hb.style.width="150px";Hb.style.margin="5px";Hb.title="Enter your text here, then click where you want it";
Hb.value="Text input";k=e.annotate_defaults;null!=k&&(k=k.split(","),ae.selectedIndex=parseInt(k[0],10),1<k.length&&($d.selectedIndex=parseInt(k[1],10)),2<k.length&&(xc.selectedIndex=parseInt(k[2],10)),3<k.length&&(Hb.value=k[3].trim()));k=n("div");k.innerHTML="Annotation Tools";var Da=n("div");Da.appendChild(ae);Da.appendChild($d);var t=n("div");t.appendChild(xc);t.appendChild(c);c=n("div");c.appendChild(Hb);ja.appendChild(k);ja.appendChild(Da);ja.appendChild(t);ja.appendChild(c);D.appendChild(Yd);
y.appendChild(ja)}"saveall"==l&&(Hf=n("button"),ea(Hf,"saveall","SaveAll","SaveAll",m,"saveall"),mh=e.saveall_prompt,cc=e.saveall_filename,c=e.saveall_list,nh=null==c?["0"]:c.split(","),Hf.addEventListener("click",function(){for(var a=0;a<nh.length;a++)for(var b=parseInt(nh[a],10),c=0;c<sa.length;c++){0===c&&null!=mh&&(cc=window.prompt(mh,cc),null!=cc&&1>cc.length&&(cc=null));var d=null==cc?"":-1!=cc.indexOf("#")?cc.replace("#",c.toString()):cc+c;var h=document.createElement("a");h.href=0==b?sa[c]:
da[c][b-1];h.download=d;d=new MouseEvent("click");h.dispatchEvent(d)}},!1),D.appendChild(Hf));if("capture"==l){If=n("button");ea(If,"capture","Capture","Capture",m,"capture");var w=e.capture_prompt;Jf=e.capture_filename;null==Jf&&(Jf="haimage.png");If.addEventListener("click",function(){var a=Jf;if(null!=w&&(a=window.prompt(w,a),null==a))return;var b=n("canvas");b.height=mb.height;b.width=mb.width;var c=b.getContext("2d");Wd=!1;W();c.drawImage(mb,0,0);c.drawImage(mc,0,0);Wd=!0;b.toBlob(function(b){var c=
URL.createObjectURL(b),d=document.createElement("a");d.href=c;d.download=a;c=new MouseEvent("click");d.dispatchEvent(c);setTimeout(function(){URL.revokeObjectURL(b)},3E4)})},!1);D.appendChild(If)}"show"==l&&(Kf=n("button"),ea(Kf,"show","Show","Show",m,"show"),Lf=e.show_prompt,Yh=e.show_image_file,null==Lf&&(Lf="Right-click to save or copy the image<br> <font size='-1'>(to save in some browsers, you may need to first 'Open in New Tab')</font> <p>"),Kf.addEventListener("click",function(){if(Yh)window.open(sa[x]);
else{var a=mb.toDataURL("image/png;base64;");var b=window.open();b.document.write(Lf+"<img src="+a+"></img>")}},!1),D.appendChild(Kf));"toggle"==l&&(Pa=[],c=e.toggle_size,null!=c?(c=c.split(","),qd=parseInt(c[0],10),Je=parseInt(c[1],10),Ke=parseInt(c[2],10)):(Je=qd=10,Ke=3),oh="red",ph="blue",qh="orange",rh=!1,E(e.toggle_layout_width,"t")&&(rh=!0),c=e.toggle_colors,null!=c&&(c=c.split(","),ph=c[0].trim(),oh=c[1].trim(),qh=c[2].trim()),vb=n("div"),vb.setAttribute("style","position:relative;border:0px;margin:0px;padding:0px;-webkit-user-select:none; -moz-user-select:none; -ms-user-select:none; user-select:none; -webkit-tap-heightlight-color:transparent;"),
vb.style.backgroundColor=D.style.backgroundColor,vb.align=Bd,sh=new PEvs(vb,null,null,null,null,HAniS.togclick,null),Yc=n("canvas"),Yc.height=2*Je,Mf=Yc.getContext("2d"),vb.appendChild(Yc),a?y.insertBefore(vb,Va):y.appendChild(vb),c=e.toggle_onoff,Le=null,null!=c&&(Le=c.split(",")),Nf=!0,null!=m&&(vb.title=m));if("overlay"==l){C=[];l=e.overlay_tooltip;m=null;null!=l&&(m=l.split(","));l=e.overlay_radio;c=null;null!=l&&(c=l.split(","));Da=e.overlay_labels_color;k=null;null!=Da&&(k=Da.split(","));Ud=
[];t=e.overlay_caching;Da=null;null==t&&(t=e.overlay_static);null!=t&&(Da=t.split(","));var B=!0;null!=e.overlay_nonewdiv&&(B=!1);for(t=0;t<Qb.length;t++){var r=Qb[t].trim();if(0==t||0==r.indexOf("/"))0==r.indexOf("/")&&(r=r.substr(1)),B?(Ib=n("div"),th++,Ib.align="center",a?y.insertBefore(Ib,Va):y.appendChild(Ib)):(Ib=n("span"),D.appendChild(Ib)),g=e.overlay_labels_style,null!=g&&Ib.setAttribute("style",g);var u=!1;g=r.length;0<r.indexOf("/on")&&r.indexOf("/on")==g-3&&(u=!0,r=r.substr(0,g-3));var A=
!1;0<r.indexOf("/always")&&r.indexOf("/always")==g-7&&(A=u=!0);var F=!1;0<r.indexOf("/hidden")&&(F=!0);var z=!1;0<r.indexOf("/hotspots")&&(z=!0,r=r.substr(0,r.indexOf("/")));null!=Da?E(Da[t],"y")||E(Da[t],"t")?Ud[t]=!0:Ud[t]=!1:Ud[t]=!0;C[t]=n("input");C[t].type="checkbox";C[t].value=r;C[t].id=r;C[t].showMe=!(A&F)&!z;var I="vertical-align:middle;";g=e.checkbox_style;null!=g&&(I+=g);C[t].setAttribute("style",I);C[t].checked=u;C[t].restorableState=u;C[t].name=0;C[t].hotspotIndex=z;null!=za&&t==nb&&
C[t].checked&&(za.disabled=!1);null!=oc&&!oc[t]&&u&&(bd=!1);C[t].addEventListener("click",HAniS.overClick,!1);null!=l&&(g=c[t].indexOf("/"),-1!=g&&(C[t].name=c[t].substr(g+1).trim()),E(c[t],"t")&&(C[t].type="radio",-1==g&&(C[t].name="all")));C[t].isGhost=!0;A||F||(null!=m&&(C[t].title=m[t]),g=n("label"),g.htmlFor=r,null!=m&&(g.title=m[t]),g.innerHTML=r,g.name=C[t].name,r="vertical-align:middle;",null!=k&&(r=r+"color:"+k[t]+";"),g.setAttribute("style",r),r=n("span"),A="10",null!=qe&&(A=10+qe[t]),r.setAttribute("style",
"margin-left:"+A+"px;"),r.appendChild(C[t]),r.appendChild(g),Ib.appendChild(r),C[t].isGhost=!1)}if(null==Rb)for(Rb=Array(Qb.length),t=0;t<Qb.length;t++)Rb[t]=0;else for(t=0;t<Qb.length;t++)Ka(t)}}Qa=!0;Ge=null;g=e.start_looping;null!=g&&(c=g.split(","),E(c[0],"f")&&(Qa=!1),1<c.length&&(vc=parseInt(c[1],10)-1,isNaN(vc)&&(vc=0),x=vc),2<c.length&&(E(c[2],"t")&&(Ge=!0),E(c[2],"f")&&(Ge=!1)));H(Qa)}function Ka(b){var a;if(0>Rb[b]){var d=!1;for(a=0;a<Qb.length;a++)Rb[a]!=-Rb[b]||d||(d=C[a].checked);C[b].checked=
d}}function Kb(b){0==kb&&(lb=[]);b=b.substr(b.indexOf("=")+1).trim().split(",");var a=b[4].trim(),d=b[4].indexOf("/"),c=b[4].indexOf("?"),h=-1,f=-1;-1!=d&&(h=parseInt(b[4].substring(d+1),10)-1,a=a.substring(0,d));-1!=c&&(f=parseInt(b[4].substring(c+1),10)-1,c<d||-1==d)&&(a=a.substring(0,c));lb[kb]=new yb(parseInt(b[0].trim(),10),parseInt(b[1].trim(),10),b[2].trim(),b[3].trim(),a.toLowerCase(),b[5].trim().toLowerCase(),b[6].trim(),h,f,8==b.length?b[7].trim():null);kb+=1}function zc(b){0==Ee&&(Oa=[],
oa=null);var a=b.substr(b.indexOf("=")+1).trim().split("(");b=a[0].split(",");var d=b[0].trim();0==d.indexOf("0x")&&(d="#"+d.substring(2));Oa[Ee]=new La(d,b[1].trim(),b[2].trim(),b[3].trim(),a[1].trim());Ee+=1}function $c(b){0==tb&&(Ea=[]);b=b.substr(b.indexOf("=")+1).trim().split(",");Ea[tb]=new jc(parseInt(b[0],10)-1,parseInt(b[1],16),b[2].trim(),b[3].trim(),5==b.length?b[4].trim():"Click for details");tb+=1}function La(b,a,d,c,h){this.color=b;this.alpha=1;7<this.color.length&&(this.alpha=parseInt(this.color.substring(7),
16)/255,this.color=this.color.substring(0,7),.1>this.alpha&&(this.alpha=.1));this.action=a;this.value=d;this.tip=c;this.poly=h;b=h.split(",");this.xy=[];this.ymin=this.xmin=9999;for(a=this.ymax=this.xmax=0;a<b.length;a++)this.xy[a]=parseInt(b[a].trim(),10),0==a%2?(this.xy[a]<this.xmin&&(this.xmin=this.xy[a]),this.xy[a]>this.xmax&&(this.xmax=this.xy[a])):(this.xy[a]<this.ymin&&(this.ymin=this.xy[a]),this.xy[a]>this.ymax&&(this.ymax=this.xy[a]));this.height=this.ymax-this.ymin+1;this.width=this.xmax-
this.xmin+1;this.can=n("canvas");this.can.height=this.height;this.can.width=this.width;this.ctx=this.can.getContext("2d");this.ctx.imageSmoothingEnabled=!1;this.ctx.fillStyle=this.color;this.ctx.globalAlpha=this.alpha;this.ctx.beginPath();this.ctx.moveTo(this.xy[0]-this.xmin,this.xy[1]-this.ymin);for(a=2;a<this.xy.length;a+=2)this.ctx.lineTo(this.xy[a]-this.xmin,this.xy[a+1]-this.ymin);this.ctx.closePath();this.ctx.fill()}function jc(b,a,d,c,h){this.overlay=b;this.color=a;this.action=d;this.value=
c;this.tip=h}function yb(b,a,d,c,h,f,e,g,k,q){this.x0=b;this.y0=a;this.icon=null;this.isIcon=!1;if("icon"==d)this.icon=new Image,this.icon.hotspot=this,Of=!0,this.icon.onload=function(a){this.gotit=!0;this.hotspot.x1=this.hotspot.x0+this.width;this.hotspot.y1=this.hotspot.y0+this.height;this.hotspot.width=this.width;this.hotspot.height=this.height;this.hotspot.w2=this.width/2;this.hotspot.h2=this.height/2;this.hotspot.isIcon=!0;this.hotspot.origX=0;this.hotspot.origY=0},this.y1=this.x1=-1,this.zoomme=
this.fromfile=this.anim=!1,this.icon.gotit=!1,this.icon.src=c.trim();else if("sprite"==d||"spritefn"===d){this.x0=b;this.y0=a;this.inx=parseInt(c,10)-1;be=!1;ng?null!=ia&&(-1!=Oc?this.inx>=Oc&&this.inx<=Oc+ia.length&&(be=!0):"spritefn"===d&&(be=!0)):be=!0;if(be){-1!=Oc&&(this.inx-=Oc);if(this.inx>=ia.length)return null;this.x1=ia[this.inx].width+b;this.y1=ia[this.inx].height+a;this.width=ia[this.inx].width;this.height=ia[this.inx].height;this.w2=this.width/2;this.h2=this.height/2;this.origY=this.origX=
0;this.icon=ia[this.inx].cloneNode();this.anim=ia[this.inx].anim;this.fromfile=ia[this.inx].fromfile;this.zoomme=ia[this.inx].zoomme;this.anim&&(this.icon.setAttribute("style","position:absolute;top:0px;left:0px;visibility:hidden;"),sc.appendChild(this.icon))}else this.x1=Ob[this.inx]+b,this.y1=Pb[this.inx]+a,this.width=Ob[this.inx],this.height=Pb[this.inx],this.w2=Ob[this.inx]/2,this.h2=Pb[this.inx]/2,this.origX=ff[this.inx],this.origY=gf[this.inx],this.icon=ef,this.zoomme=this.fromfile=this.anim=
!1;Of=this.isIcon=!0;this.icon.gotit=!0}else this.width=parseInt(d,10),this.height=parseInt(c,10),this.x1=this.width+b,this.y1=this.height+a,this.w2=this.width/2,this.h2=this.height/2;this.pan=h;this.isPan=!1;"pan"===this.pan&&(this.isPan=!0);this.action=f;this.value=e;this.overlay=g;this.frame=k;this.tip=q}function Ua(){if(rd&&!hd){S=-1;for(var b=0;b<la.length;b++)z>=la[b]&&(S=b)}}function Lb(){null!=Xb?bb=Xb.toLatLon(pa,qa):null!=xf?(bb[0]=xf+(Rh-xf)*qa/ha,bb[1]=ch+(Sh-ch)*pa/ma):(bb[0]=Math.round(pa),
bb[1]=Math.round(qa))}function Mb(b,a){"popup"==b.action?(null!=Pf&&Pf.close(),Pf=window.open("","HAniSPopup","scrollbars=yes,width="+Rg+",height="+Qg),Pf.document.write(Pg+b.value+"</div>")):"link"==b.action?(b=b.value,Lb(),b=b.replace("%LATITUDE%",bb[0].toFixed(4)),b=b.replace("%LONGITUDE%",bb[1].toFixed(4)),b=b.replace("%FRAMENUMBER%",x+1),window.open(b,"_blank","")):"fof"==b.action&&(ca=Eg,HAniS.resetZoom(),HAniS.newFOF(b.value,!0),We(a))}function xd(){var b=Lg?Ld/z:0;N+b<Ld&&(N=Ld-b);b=Ng?Md/
z:0;N+$a-b>ma-Md&&(N=ma-$a+b-Md);b=Jg?Kd/F:0;P+b<Kd&&(P=Kd-b);b=Hg?Jd/F:0;P+Za-b>ha-Jd&&(P=ha-Za-Jd+b);P=Math.round(P);N=Math.round(N)}function yd(b){var a=!1;b?hd?(S--,0>S?a=!0:(z=la[S],F=la[S])):(z-=.1*gd/u,F-=.1*gd/r):hd?(S++,S>=la.length?(S--,qf&&(a=!0)):(z=la[S],F=la[S])):(!qf||z!==Ic&&F!==Ic||(a=!0),z+=.1*gd/u,F+=.1*gd/r,z>Ic&&(z=Ic),F>Ic&&(F=Ic));a||z<=Fe||F<=Me?(z=Fe,F=Me,S=-1,pa=A,qa=B,P=N=0,Za=ha,$a=ma,Ld=Md=Kd=Jd=0,ld&&(jb=!0)):(Jd=Gg,Kd=Ig,Md=Mg,Ld=Kg,N=pa-A/z,P=qa-B/F,Za=Math.floor(ha/
F),$a=Math.floor(ma/z),xd(),ld&&(jb=!1));Ua()}function Ac(){Ne=0;Jb=Array(2);wb=Array(2);sd=Array(2);Ra=0;ed=null;wa(va(0))}function H(b){Aa=!b;HAniS.toggleIsLooping()}function zd(b,a,d,c,h,f){Rd.clearRect(0,0,R,X);Rd.imageSmoothingEnabled=Ed;I.imageSmoothingEnabled=Ed;Rd.drawImage(b,a,d,c,h,0,0,R,X);uh=Rd.getImageData(0,0,R,X);Zc=uh.data;Qf=Wa[f];Rf=Xa[f];Sf=Ya[f];Tf=Pd[f];Zh=4*R*X;for(dc=0;dc<Zh;dc+=4)cb=Zc[dc],cb===Zc[dc+1]&&cb===Zc[dc+2]&&(Zc[dc]=Qf[cb],Zc[dc+1]=Rf[cb],Zc[dc+2]=Sf[cb],Zc[dc+3]=
Tf[cb]);Rd.putImageData(uh,0,0);I.drawImage(ze,0,0,R,X)}function J(b,a,d){null!=b&&(a?(null!=b.style_on&&b.setAttribute("style",b.style_on),b.innerHTML=b.label_on):(null!=b.style_off&&b.setAttribute("style",b.style_off),b.innerHTML=b.label_off),gb&&(b.className=d))}function fb(b,a){if(!(b>=v)&&(-2==Pa[b]&&(a=-2),Pa[b]=a,zf&&1==a&&(ib.value=b+1,Xd.innerHTML=He.replace("*",b+1)),Nf)){b=vh+b*(qd+Ke);var d=qh;0==a?d=ph:-1==a?d=oh:-2==a&&(d=pg);Mf.fillStyle=d;Mf.fillRect(b,Je/2,qd,Je)}}function ie(b,a){Nf&&
(Yc.width=rh?parseInt(y.style.width,10):R,Mf.clearRect(0,0,Yc.width,Yc.height),vh=Yc.width/2-b*(qd+Ke)/2);for(var d=0;d<b;d++)a?-1!=Gd?fb(d,-2):null!=Le&&"n"==Le[d].toLowerCase().trim()?fb(d,-1):fb(d,0):fb(d,Pa[d])}function wa(b){fb(x,0);x=b;fb(x,1);null!=Ia&&null!=ab&&null!=ab[x]&&(Ia.innerHTML=ab[x]);void 0!=Oe&&Oe(x)}function va(b){b>=v&&(b=v-1);if(0<=Pa[b])return b;var a=-1,d=b;0==d&&(a=1);for(var c=0;c<v-1;c++)if(d+=a,0<=Pa[d])return d;return b}function zb(b){fb(x,0);var a=b;do 0<a?(a=va(v-1),
x+=1,x>a&&(ce&&Aa?(x=a,b=-b):x=va(0))):(a=va(0),--x,x<a&&(ce&&Aa?(x=a,b=-b):x=va(v-1))),a=b;while(0>Pa[x]);void 0!=Oe&&Oe(x);Ff=a;fb(x,1);null!=Ia&&null!=ab&&null!=ab[x]&&(Ia.innerHTML=ab[x])}function eb(b,a,d,c,h,f,e){this.bg=b;null!=b&&0==this.bg.indexOf("0x")&&(this.bg="#"+this.bg.substring(2));this.fg=a;null!=a&&0==this.fg.indexOf("0x")&&(this.fg="#"+this.fg.substring(2));this.font=d;this.fontHeight=Math.round(1.1*parseInt(d,10));this.scolor=c;null!=c&&0==this.scolor.indexOf("0x")&&(this.scolor=
"#"+this.scolor.substring(2));this.sblur=h;this.sxoff=f;this.syoff=e}function Ma(b,a,d,c,h){g.globalAlpha=1;g.font=b.font;var f=b.fontHeight;d=d-f-6;var e=g.measureText(c).width;1==h&&(a-=e);0==h&&(a-=e/2);5>a&&(a=5);5>d&&(d=5);d+f+3>X&&(d=X-f-6);a+3+e>R&&(a=R-e-6);g.save();g.beginPath();g.fillStyle=b.bg;null!=b.scolor&&(g.shadowColor=b.scolor,g.shadowBlur=b.sblur,g.shadowOffsetX=b.sxoff,g.shadowOffsetY=b.syoff);Pe=a-3;Uf=d;wh=e+6;Vf=f+6;g.fillRect(Pe,Uf,wh,Vf);g.closePath();g.restore();g.textBaseline=
"bottom";g.fillStyle=b.fg;g.fillText(c,a,d+f+3)}function W(){g.clearRect(0,0,R,X);Wf=!1;if(db){g.beginPath();g.lineWidth=2;g.strokeStyle="white";var b=Ra;1<b&&(b=2);for(var a=0;a<b;a++)1<Ra&&(g.moveTo(Jb[0]/u,wb[0]/r),g.lineTo(Jb[1]/u,wb[1]/r)),g.moveTo(Jb[a]/u-15,wb[a]/r),g.lineTo(Jb[a]/u+15,wb[a]/r),g.moveTo(Jb[a]/u,wb[a]/r-15),g.lineTo(Jb[a]/u,wb[a]/r+15);g.closePath();g.stroke();if(3==Ra){var d=T,c=M;g.moveTo(d,c);g.fillStyle=pc;g.fillRect(d-2,c-2,5,5);b=td;a=Math.round(d+Qe/u*de*(td-sd[1]));
for(var h=Math.round(c+ee/r*de*(td-sd[1])),f=0;300>f;f++){g.beginPath();g.lineWidth=1;g.strokeStyle=pc;g.moveTo(d,c);g.lineTo(a,h);g.stroke();g.beginPath();g.lineWidth=3;g.rect(a-2,h-2,5,5);g.stroke();if(3>a||a+3>R||3>h||h+3>X)break;c=Yb+b;c=100*Math.floor(c/60)+c%60;c%=2400;zg?(d="AM",1200<=c?(1300<=c&&(c-=1200),d="PM"):100>c&&(c+=1200),d=Math.floor(c/100)+":"+Math.floor(Math.floor(c%100)/10)+Math.floor(c%10)+" "+d):(d=c+" ",1E3>c&&(d="0"+c),100>c&&(d="00"+c),10>c&&(d="000"+c));c=0;Math.abs(Xf)<
dd+5&&(c=45*.0174533);var e=h;0>xh*Xf&&0==c&&(e=h+dd);g.font=Id;d=d+" "+yg;var l=g.measureText(d).width;g.fillStyle=Hd;0===c?(g.fillRect(a+2,e-dd-2+c,l+4,dd+3),g.fillStyle=pc,g.textBaseline="bottom",g.fillText(d,a+5,e)):(g.save(),g.translate(a+5,h),g.rotate(c),g.fillRect(2,-2,l+4,dd+3),g.fillStyle=pc,g.textBaseline="bottom",g.fillText(d,5,dd),g.restore());d=a;c=h;a=Math.round(d+de*xh);h=Math.round(c+de*Xf);b+=U}}null!=ed&&Ma(mf,$h,ai,ed,0);Wd&&(Ma(Mh,9999,Xg,Wg[Ne],0),yh=Pe,zh=Uf,Ah=Uf+Vf)}if(ub){Wd&&
(0==pd?Ma(ih,9999,10,ve[0],0):(Ma(Wh,10,10,ve[1],0),bi=Pe+wh,Ma(ih,9999,10,ve[2],0)),ci=Pe,di=Vf);g.beginPath();g.lineWidth=2;g.strokeStyle=Yg;for(b=0;b<na.length;b+=2)0==b?g.moveTo(na[b]/u,na[b+1]/r):g.lineTo(na[b]/u,na[b+1]/r);we&4<na.length&&g.lineTo(na[0]/u,na[1]/r);g.stroke();for(b=0;b<na.length;b+=2)g.beginPath(),g.rect(na[b]/u-2,na[b+1]/r-2,5,5),g.stroke()}if(Gb)for(b=0;b<p.length;b++){a=p[b].type;g.beginPath();g.strokeStyle=p[b].color;g.lineWidth=p[b].width;if("0"==a)a=Math.atan2(p[b].xe-
p[b].x,p[b].ye-p[b].y),h=p[b].x+p[b].width*Math.sin(a),f=p[b].y+p[b].width*Math.cos(a),g.beginPath(),g.moveTo(h,f),g.lineTo(p[b].xe,p[b].ye),d=12+p[b].width/5,g.moveTo(h+d*Math.sin(a-.523599),f+d*Math.cos(a-.523599)),g.lineTo(h,f),g.lineTo(h+d*Math.sin(a+.523599),f+d*Math.cos(a+.523599));else if("1"==a)g.arc(p[b].x,p[b].y,p[b].size,0,2*Math.PI);else if("2"==a)g.rect(p[b].x-p[b].size,p[b].y-p[b].size,2*p[b].size,2*p[b].size);else if("3"==a){g.moveTo(p[b].xp[0],p[b].yp[0]);for(h=1;h<p[b].xp.length;h++)g.lineTo(p[b].xp[h],
p[b].yp[h]);g.lineTo(p[b].xp[0],p[b].yp[0])}else if("4"==a)for(g.moveTo(p[b].xp[0],p[b].yp[0]),h=1;h<p[b].xp.length;h++)g.lineTo(p[b].xp[h],p[b].yp[h]);else"5"==a&&(g.fillStyle=p[b].color,g.font=p[b].width+"pt arial",a=g.measureText(p[b].text).width,g.fillText(p[b].text,p[b].x-a/2,p[b].y+p[b].width/2));g.stroke()}Tc&&(b=Bc*(Re-fe)/z,a=le*(Se-ge)/F,b=" "+Math.sqrt(b*b+a*a).toFixed(ig)+" "+hg+" ",Ma(Kh,fe/u,ge/r,b,-1),g.beginPath(),g.strokeStyle=jg,g.lineWidth=3,g.moveTo(Re/u,Se/r),g.lineTo(fe/u,ge/
r),g.stroke(),g.closePath());Cb&&Ma(Dg,Bh,Ch,Dh,-1);if(Nb||nd)if(T=ka.getX(),A=T*u,M=ka.getY(),B=M*r,0<=A&&0<=B){pa=N+A/z;qa=P+B/F;if(nd){Lb();ei=eg+bb[0].toFixed($e)+"  "+fg+bb[1].toFixed($e);b=M;if(Tc||Cb)b=M+gg.fontHeight+6;Ma(gg,T+10,b,ei,-1)}if(Nb&&Lc&&Sc)if(pa=Math.round(pa),qa=Math.round(qa),cf)Sa.clearRect(0,0,1,1),Sa.drawImage(Fa[x],pa,qa,1,1,0,0,1,1),Q=Sa.getImageData(0,0,1,1).data,G=0,Ad(!1);else for(b=0;b<aa;b++)if(a=aa-b-1,K[x][a].gotit&&C[a].checked&&(a==nb||null!=nc[a]&&0<=nc[a])){Sa.clearRect(0,
0,1,1);a==nb?Sa.drawImage(Zb[x],pa,qa,1,1,0,0,1,1):Sa.drawImage(K[x][a],pa,qa,1,1,0,0,1,1);Q=Sa.getImageData(0,0,1,1).data;G=nc[a];null!=G&&Ad(a==nb||bh);break}}!jb||db||lc||Nb||null==oa||(g.drawImage(oa.can,0,0,oa.width,oa.height,oa.xmin/u,oa.ymin/r,oa.width/u,oa.height/r),Ma(Dg,(oa.xmin+oa.xmax)/2/u,(oa.ymin+oa.ymax)/2/r,oa.tip,0),Wf=!0)}function Ad(b){Te=999;ec=kg;var a=sb[G].length-1;if(0==Q[3])ec=ye[G];else{if(lg)fc=Q[0];else if(b)Yf=0,fc=Q[0],Te=0;else for(var d=0;d<a;d++)gc[0]=Q[0]-Wa[G][d],
0>gc[0]*(Wa[G][d+1]-Q[0]-1)||(gc[1]=Q[1]-Xa[G][d],0>gc[1]*(Xa[G][d+1]-Q[1]-1)||(gc[2]=Q[2]-Ya[G][d],0>gc[2]*(Ya[G][d+1]-Q[2]-1)||(ud=wf[G][d],Zf=gc[ud]/Pc[G][d][ud],Eh=Math.abs(gc[Fh[ud]]-Zf*Pc[G][d][Fh[ud]])+Math.abs(gc[Gh[ud]]-Zf*Pc[G][d][Gh[ud]]),Eh<Te&&(fc=d,Te=Eh,Yf=Zf))));if(999>Te)ec=Nc[G][fc],-1!=Wb[G][fc]&&(Hh=sb[G][fc],0!=Yf&&(Hh+=Yf*(sb[G][fc+1]-sb[G][fc])),ec=ec+" "+Hh.toFixed(Wb[G][fc])+" "+Mc[G][fc]);else if(b||0<Cd){var c=-1;if(b)c=Q[0];else for(d=0;d<a;d++)if(Math.abs(Q[0]-Wa[G][d])<
Cd&&Math.abs(Q[1]-Xa[G][d])<Cd&&Math.abs(Q[2]-Ya[G][d])<Cd){c=d;break}-1!=c&&(ec=Nc[G][c],-1!=Wb[G][c]&&(ec=ec+" "+sb[G][c].toFixed(Wb[G][c])+" "+Mc[G][c]))}}"hide"!=ec&&Ma(Lh,T-10,M,ec,1)}function V(){if(Sc)try{I.clearRect(0,0,R,X);I.globalAlpha=1;if(!Og)if(rd&&null!=$b&&0<=S&&$b[S].gotit)I.drawImage($b[S],N*la[S],P*la[S],$a*la[S],Za*la[S],0,0,R,X);else if(Fa[x].gotit&&(null!=hf?zd(Fa[x],N,P,$a,Za,hf):I.drawImage(Fa[x],N,P,$a,Za,0,0,R,X)),null!=Ca&&(I.globalAlpha=1,Fa[x].gotit))for(var b=0;b<Ca.length;b+=
4)I.drawImage(Fa[x],Ca[b],Ca[b+1],Ca[b+2],Ca[b+3],Ca[b]/u,Ca[b+1]/r,Ca[b+2]/u,Ca[b+3]/r);if(0<aa){for(b=0;b<aa;b++){var a=null!=Fc?Fc[b]:b;!kf[a]&&C[a].checked&&C[a].showMe&&(null!=re&&(I.globalAlpha=re[a]),rd&&0<=S&&null!=ta&&void 0!=ta[a]&&ta[a][S][x].gotit?I.drawImage(ta[a][S][x],N*la[S],P*la[S],$a*la[S],Za*la[S],0,0,R,X):K[x][a].gotit&&(null==Gc||1===Gc[a]?null!=Dc&&0<=Dc[a]?zd(K[x][a],N,P,$a,Za,Dc[a]):I.drawImage(K[x][a],N,P,$a,Za,0,0,R,X):0===Gc[a]&&I.drawImage(K[x][a],0,0,ma,ha,0,0,R,X)))}if(null!=
ob)for(I.globalAlpha=1,b=0;b<aa;b++)if(a=null!=Fc?Fc[b]:b,K[x][a].gotit&&(xg[a]||C[a].checked)&&ob[a])for(var d=0;d<Z[a].length;d++)I.drawImage(null!=K[x][a].origImage?K[x][a].origImage:K[x][a],Z[a][d][0],Z[a][d][1],Z[a][d][2],Z[a][d][3],Z[a][d][4]/u,Z[a][d][5]/r,Z[a][d][2]/u,Z[a][d][3]/r);Nb&&W()}hh&&k();if(Of)for(I.globalAlpha=1,a=0;a<kb;a++)if(null!=lb[a]){var c=lb[a];null!=c.icon&&(c.icon.style.visibility="hidden");if((-1==c.frame||c.frame==x)&&null!=c.icon&&c.icon.gotit&&(-1==c.overlay||-1!=
c.overlay&&C[c.overlay].checked)){if(c.isPan){c.zoomme&&(c.icon.style.width=Math.round(c.width*z)+"px",c.icon.style.height=Math.round(c.height*F)+"px",c.w2=Math.round(c.width*z/2),c.h2=Math.round(c.height*F/2));var h=Math.round(((c.x0-N)*z-c.w2)/u);var e=Math.round(((c.y0-P)*F-c.h2)/r);if(c.anim){if(0>=h+c.icon.width||h>=ma||0>=e+c.icon.height||e>=ha)continue;c.icon.style.top=e+"px";c.icon.style.left=h+"px"}else I.drawImage(c.icon,c.origX,c.origY,c.width,c.height,h,e,c.width/u,c.height/r)}else I.drawImage(c.icon,
c.origX,c.origY,c.width,c.height,c.x0/u,c.y0/r,c.width/u,c.height/r);c.icon.style.visibility="visible"}}}catch(m){fa("Error:"+m)}}function ra(b,a,d){!ue||d>=a||(I.save(),I.fillStyle="blue",I.strokeStyle="white",I.lineWidth=3,I.strokeRect(Ae,Be,200,18),I.fillRect(Ae,Be,d/a*200,18),a=I.measureText(b).width,I.fillStyle="orange",I.font="14px arial",I.fillText(b,Ae+100-a/2,Be+14),I.restore())}function k(){ue&&Bb>Ga?ra("Loading Images",Bb,Ga):(hh=!1,Ze&&(kc.style.visibility="hidden"));Ga>=Bb&&!Aa&&wa(va(x));
void 0!=Ce&&Ga>=Bb&&Ce(!0)}function fa(b){if(je&&Ye&&!Ye.closed)try{Ye.document.write(b+"<br>")}catch(a){}}function Vh(){Aa&&zb(Ff);fi=x==va(v-1)?mg+hb:hb;V();setTimeout(function(){li(Vh)},fi)}function Ue(b){for(;-180>b;)b+=360;for(;180<b;)b-=360;return b}function ji(){var b,a,d,c,h,e,g,l,k=Math.PI/180;this.init=function(c){for(var d=[],f=1;f<c.length;f++)d[f]=parseFloat(c[f]);a=d[1];b=d[4]/d[5];h=d[6];e=d[7];c=this.toXY(d[2],d[3]);h=c[0];e=c[1]};this.toXY=function(f,g){d=b*Ue(g-a)*k-h;c=-b*f*k-e;
return[d,c]};this.toLatLon=function(c,d){g=-(d+e)/b/k;l=Ue((c+h)/b/k+a);return[g,l]}}function ii(){var b,a,d,c,h,e,g,l,k,q,r,p,t,n,v,x,w,y,B,A,u,C,E,F,D,z,H,I,K,J,L,G=Math.PI/180;this.init=function(c){for(var d=[],e=1;e<c.length;e++)d[e]=parseFloat(c[e]);b=d[1];a=d[2];A=0==d[8]?!1:!0;u=d[6];C=u*u;E=C*C;F=E*C;D=E*E;g=d[5]/d[7];L=d[7];A?(l=Math.cos(G*b),k=Math.sin(G*b)):(l=Math.cos(-b*G),k=Math.sin(-b*G));w=l/Math.sqrt(1-C*k*k);B=(1-u*k)/(1+u*k);x=A?Math.tan(Math.PI/4-b*G/2)/Math.pow(B,u/2):Math.tan(Math.PI/
4- -b*G/2)/Math.pow(B,u/2);n=d[9];v=d[10];c=this.toXY(d[3],d[4]);n=c[0];v=c[1]};this.toXY=function(f,l){A?(h=G*f,e=G*(l-a)):(h=G*-f,e=G*(a-l));B=(1-u*Math.sin(h))/(1+u*Math.sin(h));y=Math.tan(Math.PI/4-h/2)/Math.pow(B,u/2);z=90!=b&&-90!=b?g*w*y/x:2*g*L*y/Math.sqrt(Math.pow(1+u,1+u)*Math.pow(1-u,1-u));d=z*Math.sin(e);c=z*Math.cos(e);A||(d=-d,c=-c);q=d-n;r=c-v;return[q,r]};this.toLatLon=function(e,f){d=e+n;c=f+v;z=Math.sqrt(d*d+c*c);y=90==b||-90==b?z*Math.sqrt(Math.pow(1+u,1+u)*Math.pow(1-u,1-u))/(2*
g*L):z*x/(g*w);H=Math.PI/2-2*Math.atan(y);I=Math.sin(2*H);K=Math.sin(4*H);J=Math.sin(6*H);h=H+I*C/2+5*I*E/24+I*F/12+13*I*D/360+7*K*E/48+29*K*F/240+811*K*D/11520+7*J*F/120+81*J*D/1120+4279*Math.sin(8*H)*D/161280;A?(p=h/G,t=Math.atan2(d,c)/G+a):(p=-h/G,t=-Math.atan2(-d,-c)/G+a);return[p,Ue(t)]}}function ki(){var b,a,d,c,e,f,g,l,k,q,r,n,t,p,v,u,x,w,y,B,A,C,E,z,D,F,H,I,G,K,J,L,O,N,P,M=Math.PI/180;this.init=function(c){for(var e=[],h=1;h<c.length;h++)e[h]=parseFloat(c[h]);b=e[1];a=e[2];d=e[3];z=e[7];D=
z*z;F=D*D;H=F*D;I=F*F;l=e[6]/e[8];k=Math.cos(M*b);q=Math.cos(M*a);n=Math.sin(b*M);r=Math.sin(a*M);A=k/Math.sqrt(1-D*n*n);C=q/Math.sqrt(1-D*r*r);y=Math.sqrt((1-n)/(1+n)*Math.pow((1+z*n)/(1-z*n),z));B=Math.sqrt((1-r)/(1+r)*Math.pow((1+z*r)/(1-z*r),z));J=(Math.log(A)-Math.log(C))/(Math.log(y)-Math.log(B));L=A/(J*Math.pow(y,J));N=l*L*Math.pow(y,J);x=e[9];w=e[10];c=this.toXY(e[4],e[5]);x=c[0];w=c[1]};this.toXY=function(a,b){f=M*a;g=M*Ue(b-d);P=Math.sin(f);E=Math.sqrt((1-P)/(1+P)*Math.pow((1+z*P)/(1-z*
P),z));K=l*L*Math.pow(E,J);O=J*g;c=K*Math.sin(O);e=N+K*Math.cos(O);t=c-x;p=e-w;return[t,p]};this.toLatLon=function(a,b){c=a+x;e=b+w;K=Math.abs(J)/J*Math.sqrt(c*c+(N-e)*(N-e));E=Math.pow(K/(l*L),1/J);G=Math.PI/2-2*Math.atan(E);O=0>J?Math.atan(-c/(e-N)):Math.atan(c/(N-e));g=O/J;f=G+(D/2+5/24*F+H/12+13/360*I)*Math.sin(2*G)+(7/48*F+29/240*H+811/11520*I)*Math.sin(6*G)+(7/120*H+81/1120*I)*Math.sin(6*G)+4279/161280*I*Math.sin(8*G);v=f/M;u=Ue(d-g/M);return[v,u]}}var og,X,R,ha,ma,u,r,Zg,$g,Db,Eb,kc,Ze,ka,
je,Pf,Ye,wc,$f,jf=!1,y,D,Df,Ef,Va,sc,jd,mb,I,Sa,mc,g,Qd,Cf,Hc,nf,te,gh,of,tc,v,sa,Sg,aa,kf,Qb,Fc,da,uc,Rb,fd,ca,Eg,Fa,K,C,re,Ud,Cb,Dh,Bh,Ch,cd,Fd,qg,L,rg,ag,Ih,T,M,A,B,pa,qa,$a,Za,N,P,Wd,gb,vc,Uh,Aa,Qa,Ge,x,Oe,Ff,ce,rc,id=!0,pe,bg,ke,e,hb,Tb,Jc,Ce,rf,mg,fi,Ed,za,kd,Ec,nb,Na,Zb,Qc,Td,Af,De,hf,ze,Rd,uh,Zc,cb,Qf,Rf,Sf,Tf,Zh,dc,Dc,Pa,qd,Je,Ke,rh,vb,vh,sh,oh,ph,qh,Gd,pg,lb,kb,Of,pf,vf,ia,Oc,be,dh,tb,Ea,Q,cg,Oa,Ee,jb,ld,Bf,Sd,oa,Wf,oc,bd,la,S,$b,Rc,ta,Ha,rd,ab,Ia,yc,Nf,Le,Yc,Mf,Sc,ad,Ab,rb,qb,Fb,Vb,Ub,
qe,Uc,ub,pd,ve,sf,we,Yg,na,Wh,ih,ci,bi,di,ac,db,Ra,Jb,wb,sd,yh,Wg,zh,Ah,Xg,Mh,pb,de,Qe,ee,Jh,Od,yf,xh,Xf,td,U,Ne,Yb,se,yg,pc,Hd,Id,dd,zg,Ag,Yh,Kf,Lf,If,Jf,Yd,p,Hf,mh,cc,nh,ja,Gb,Xc,Zd,Wc,Vc,Ie,Xh,ae,$d,xc,Hb,jh,kh,ya,Fg,gd,z,F,Fe,Me,Vg,qc,Nd,Ug,Tg,xa,Ic,hd,Ve,qf,sg=!1,tg,ug,vg,lf,wg,Vd,ib,He,Xd,zf,bc,lc,Re,Se,ig,me,Pe,Uf,wh,Vf,eh=!0,fh,fe,ge,Kh,jg,bf,Ba,af,ne,Tc,Bc,le,hg,Dg,md,nd,$e,eg,fg,gg,Xb,bb,ei,xf,ch,Rh,Sh,Ca,Ib,th,Gc,ob,Z,xg,Gf,xe,Kc,Pg,Rg,Qg,nc,Nb,od,oe,Lc,Mc,Nc,Wb,ud,Te,Lh,kg,Cd,lg,cf,mf,
Bg,Cg,ed,$h,ai,fc,Yf,Zf,Fh,Gh,gc,G,Eh,ec,Hh,sb,w,Pc,bh,Wa,Xa,Ya,Pd,wf,ye,gi,Dd,df,Cc,ue,ef,ff,gf,Ob,Pb,ng,hh,Ae,Be,Ga,Bb,Jd,Og,Gg,Kd,Ig,Ld,Kg,Hg,Jg,Ng,Lg,Md,Mg,Bd,Sb,mi="N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW N".split(" "),li=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||function(b){setTimeout(b,10)},n=function(b){return document.createElement(b)},E=function(b,a){if(null!=b)return 0==b.trim().toLowerCase().indexOf(a)},
Th=function(b,a){if(null!=b)return b=b.trim(),b.lastIndexOf(a)===b.length-1},Qh=function(b){void 0==$f&&($f=n("textarea"));$f.innerHTML=b;return $f.value},lh=function(b,a,d){var c=n("select");c.style.width="70px";c.style.margin="5px";for(var e=0;e<b.length;e++){var f=n("option");f.innerHTML=b[e];f.value=a[e];c.add(f)}c.addEventListener("change",d,!1);return c},Ph=function(b){b=b.split(",");da=Array(v);for(var a=0;a<b.length;a++){var d=b[a].split("&");aa=b.length;for(var c=0;c<v;c++)0===a&&(da[c]=
Array(aa)),da[c][a]=d[1==d.length?0:c].trim(),null!=Sb?da[c][a]=(Sb+da[c][a]).trim():null!=ca&&(da[c][a]=(ca+da[c][a]).trim())}ad=!1},Nh=function(b){b=b.split(",");v=b.length;sa=Array(v);for(var a=0;a<v;a++)sa[a]=null!=ca?ca+b[a].trim():b[a].trim();ad=!1;v>aa&&(aa=0)},Oh=function(b,a,d){var c=b;null!=ca&&(c=ca+b);sa=Array(v);for(var h=0;h<v;h++){b=h*d+a;if(0<=c.indexOf("*"))sa[h]=c.replace("*",b);else if(0<=c.indexOf("?")){for(var f=c;0<=f.lastIndexOf("?");){var g=f.lastIndexOf("?");f=f.substring(0,
g)+b%10+f.substring(g+1);b=Math.floor(b/10)}sa[h]=f}else sa[h]=c+h;fa("image filename = "+sa[h])}b=e.reverse_order;null!=b&&E(b,"t")&&sa.reverse();ad=!1;v>aa&&(aa=0)};HTMLCanvasElement.prototype.toBlob||Object.defineProperty(HTMLCanvasElement.prototype,"toBlob",{value:function(b,a,d){d=window.atob(this.toDataURL(a,d).split(",")[1]);for(var c=d.length,e=new Uint8Array(c),f=0;f<c;f++)e[f]=d.charCodeAt(f);b(new Blob([e],{type:a||"image/png"}))}});this.setup=function(b,a,d){void 0==a&&(a="MORdivcan");
fh=d;y=document.getElementById(a);Bd="center";y.align=Bd;Va=n("div");Va.setAttribute("style","position:relative;border:0px;margin:0px;padding:0px;-webkit-user-select:none; -moz-user-select:none; -ms-user-select:none; user-select:none; -webkit-tap-heightlight-color:transparent;");mb=n("canvas");mb.setAttribute("style","position:absolute;top:0;left:0;z-index:1;");I=mb.getContext("2d");mc=n("canvas");mc.setAttribute("style","position:absolute;top:0;left:0;z-index:6;");g=mc.getContext("2d");g.imageSmoothingEnabled=
!1;Qd=n("canvas");Qd.setAttribute("style","position:absolute;top:0;left:0;z-index:10;");Cf=Qd.getContext("2d");Cf.imageSmoothingEnabled=!1;sc=n("div");sc.setAttribute("style","position:absolute;top:0;left:0;z-index:5;overflow:hidden;border-width:0px;padding:0px;margin:0px;");jd=n("div");jd.setAttribute("style","position:absolute;top:0;left:0;z-index:10;overflow:hidden;border-width:0px;padding:0px;margin:0px;");jd.appendChild(Qd);ze=n("canvas");Va.appendChild(jd);Va.appendChild(mb);Va.appendChild(mc);
Va.appendChild(sc);y.appendChild(Va);ka=new PEvs(Va,HAniS.down,HAniS.up,HAniS.move,HAniS.drag,null,HAniS.canTip);y.setAttribute("tabindex",0);y.addEventListener("keyup",function(a){Gb||ke||(bg=!1,a.preventDefault(),a.stopPropagation())},!1);y.addEventListener("keypress",function(a){Gb||ke||(a.preventDefault(),a.stopPropagation())},!1);y.addEventListener("keydown",function(a){Gb||ke||(a.preventDefault(),a.stopPropagation(),bg=a.ctrlKey?!0:!1,37==a.keyCode?(H(!1),zb(-1),V()):39==a.keyCode?(H(!1),zb(1),
V()):32==a.keyCode?HAniS.toggleIsLooping():82==a.keyCode&&a.altKey&&HAniS.resetZoom())},!1);jd.addEventListener("mouseenter",function(a){y.focus()},!1);y.style.outlineWidth="0px";y.style.outline="none";y.focus();vc=x=0;ce=!1;Ff=1;Qa=Aa=!0;kb=aa=v=0;pe=!0;Fc=null;rc=!0;hb=500;Tb=100;Jc=2E3;rf=30;mg=0;df=6E4;Cc=null;Hc=Dd=!1;te=!0;tc=[];la=Eg=fd=Sb=ca=null;rd=!1;S=-1;hd=!1;Me=Fe=F=z=1;Ve=!1;P=N=Za=$a=qa=pa=B=A=M=T=0;Vg=!1;id=eh=!0;Nf=Ze=jf=!1;Gd=-1;Pa=[];tb=0;Of=!1;ia=null;Oc=-1;vf=0;be=!1;Ia=null;
Be=Ae=Ga=Bb=0;bh=!1;G=0;Cb=of=pf=Sc=!1;Re=Se=fe=ge=0;Tc=lc=!1;Ba=[];Ba.push("default");Ba.push("default");af="default";nd=!1;ne="default";Xb=null;bb=[0,0];jb=zf=me=!1;bd=!0;oa=oc=null;ub=Wf=!1;we=!0;bf="default";Wd=!0;na=[];Nb=cf=!1;oe="default";Lc=!1;Fh=[1,0,0];Gh=[2,2,1];gc=[];nc=[];Ec=kd=db=!1;se=Ne=0;Ib=Ef=Df=D=vb=null;th=0;Gb=ke=bg=!1;a=n("canvas");a.height=1;a.width=1;Sa=a.getContext("2d");Sa.imageSmoothingEnabled=!1;Bf=n("canvas");je=!1;"string"===typeof b?0>b.indexOf("\n")?dg(b):q(b.split("\n")):
q(b)};this.newBasenames=function(b,a,d,c){Sc=!1;Qa=Aa;H(!1);v=c;Oh(b,a,d);rc=!0;Ja()};this.newFilenames=function(b){Sc=!1;Qa=Aa;H(!1);Nh(b);rc=!0;Ja()};this.newOverlayFilenames=function(b){Sc=!1;Qa=Aa;H(!1);Ph(b);rc=!0;Ja()};this.newProbeTable=function(b){Lc=!1;O(b.trim())};this.reloadFOF=function(){fa("reload FoF = "+Cc);We("r");ad?hi(gi,!1):(Qa=null==Ge?!0:Aa,rc=!0,Ja())};this.getFOF=function(){var b=e.file_of_filenames.trim();HAniS.newFOF(null!=fd?fd+b:b,!0)};this.newFOF=function(b,a){HAniS.resetZoom();
hi(b,a)};var hi=function(b,a){var d,c,e,f,g=new XMLHttpRequest,l,k,q,r,n,t,p,u=null,x=!1;dh=tb;Sc=!1;Qa=Aa;H(!1);a&&wa(vc);tb=v=0;sa=[];L=Oa=null;Ih=[];for(ag=null;sc.hasChildNodes();)sc.removeChild(sc.lastChild);Ee=0;rd=jb=ld=!1;ta=Rc=$b=null;Ha=[];yc=-1;da=[];var w=!1;if(null==pb||null!=Od)pb=[];fa("new FOF="+b);db&&(null!=ac&&(J(ac,!0,"extrap on"),y.style.cursor="default",H(Qa),Ra=-1),db=!1,W());ub&&(null!=Uc&&(J(Uc,!0,"mark on"),y.style.cursor="default",H(Qa),pd=-1),ub=!1,W());g.onload=function(){var a=
this.responseText.split("\n");for(d=0;d<a.length;d++)if(!(2>a[d].length)&&(l=a[d].trim(),fa("FOF: "+l),0!=l.indexOf("#")))if(0==l.indexOf("frame_labels"))n=l.split("="),ab=n[1].split(",");else if(0==l.indexOf("redirect"))for(n=l.split("="),p=n[1].split(","),ag=p[0].trim(),c=1;c<p.length;c++){var b=parseInt(p[c],10)-1;Ih[b]=!0}else if(0==l.indexOf("slice")){n=l.split("=");p=n[1].split(",");L=[];for(c=0;c<p.length;c++)L[c]=parseInt(p[c],10);L[2]=L[2]-L[0]+1;L[3]=L[3]-L[1]+1;4<L.length&&(L[6]=L[6]-L[4]+
1,L[7]=L[7]-L[5]+1)}else if(0==l.indexOf("fof_extension"))n=l.split("="),u=n[1].trim();else if(0==l.indexOf("probe_table"))n=l.split("="),Lc=!1,O(n[1].trim());else if(0==l.indexOf("image_base"))n=l.split("="),ca=n[1].trim();else if(0==l.indexOf("overlay_base"))n=l.split("="),Sb=n[1].trim();else if(0==l.indexOf("high_res_basemap")){n=l.split("=");p=n[1].split(",");Rc=[];for(c=0;c<p.length;c++)Rc[c]=p[c].trim(),null!=ca&&(Rc[c]=ca+Rc[c]);rd=!0}else if(0==l.indexOf("high_res_overlay"))for(n=l.split("="),
t=n[1].split("&"),e=0;e<t.length;e++){p=t[e].split(",");yc=parseInt(p[0].trim(),10)-1;Ha[yc]=[];for(c=1;c<p.length;c++)Ha[yc][c-1]=p[c].trim(),Th(Ha[yc][c-1],"/")||(null!=Sb?Ha[yc][c-1]=Sb+Ha[yc][c-1]:null!=ca&&(Ha[yc][c-1]=ca+Ha[yc][c-1]));rd=!0}else if(0==l.indexOf("high_res_zoom")){n=l.split("=");p=n[1].split(",");la=[];for(c=0;c<p.length;c++)la[c]=parseFloat(p[c].trim());Ua()}else if(0==l.indexOf("hoverzone"))zc(l);else if(0==l.indexOf("hotzone"))$c(l);else if(0==l.indexOf("hotspot"))x||(lb=null,
kb=0,x=!0),Kb(l);else if(0==l.indexOf("toggle_onoff"))n=l.split("="),Le=n[1].split(",");else if(0==l.indexOf("coordinates"))n=l.split("="),xb(n[1]);else if(0==l.indexOf("map_scale"))n=l.split("="),p=n[1].split(","),Bc=parseFloat(p[0]),le=1<p.length?parseFloat(p[1]):Bc;else if(0==l.indexOf("times")){n=l.split("=");p=n[1].split(",");for(d=0;d<p.length;d++)pb[d]=parseInt(p[d].trim(),10);w=!0}else{null!=Od&&(b=l.match(Od),null!=b&&2==b.length?(pb.push(parseInt(b[1],10)),fa("+ + + Extrap time = "+b[1]),
w=!0):fa("+ + + Cannot parse times using "+Od+" from line: "+l));e=l.indexOf(" ");0>e&&(e=l.length);sa[v]=l.substring(0,e).trim();null!=ca&&(sa[v]=ca+sa[v]);l=l.substring(e+1);b=l.indexOf('"');0<=b&&(null==ab&&(ab=[]),e=l.substring(b+1),b=e.indexOf('"'),0<=b&&(ab[v]=e.substring(0,b),0==v&&(Ia.innerHTML=ab[0])));da[v]=[];b=l.indexOf("overlay");if(0<=b)for(k=l.substring(b),b=k.indexOf("="),0>b&&fa("Cannot find a = sign in "+k),q=k.substring(b+1),k=q.trim(),q=k.split(","),aa=q.length,fa("numOverlays set to "+
aa),f=0;f<q.length;f++)da[v][f]=q[f].trim(),null!=ag&&Ih[f]?da[v][f]=(ag+da[v][f]).trim():null!=Sb?da[v][f]=(Sb+da[v][f]).trim():null!=ca&&(da[v][f]=(ca+da[v][f]).trim());v+=1}w&&ua(pb);null!=u?(a=new XMLHttpRequest,a.onload=function(){var a=this.responseText.split("\n");for(d=0;d<a.length;d++)2>a[d].length||(r=a[d].trim(),fa("ext_FOF: "+r),0!=r.indexOf("#")&&(0==r.indexOf("hotzone")?$c(r):0==r.indexOf("hotspot")&&Kb(r)));Ta()},a.onerror=function(){Ta()},a.open("get",u+"?"+Math.round(1E5*Math.random()),
!0),a.send()):Ta()};gi=b;g.open("get",b+"?"+Math.round(1E5*Math.random()),!0);g.send()};this.setWindowSize=function(b,a){if(null!=y){y.style.height=a+"px";y.style.width=b+"px";y.style.padding="0px";a=a-(null!=Df?Df.offsetHeight:0)-(null!=Ef?Ef.offsetHeight:0)-(null!=vb?vb.offsetHeight:0)-th*(null!=Ib?Ib.offsetHeight:0);a>ha&&(a=ha);var d=a*ma/ha;d>b&&(d=b,a=b*ha/ma);a=Math.floor(a);d=Math.floor(d);id||(vd(d,a),W())}};this.drag=function(b){ub||(T=ka.getX(),M=ka.getY(),Gb?(b=p.length-1,p[b].xe=T,p[b].ye=
M,p[b].xp.push(T),p[b].yp.push(M),p[b].size=Math.round(Math.sqrt(Math.pow(T-p[b].x,2)+Math.pow(M-p[b].y,2)))):(A=T*u,B=M*r,Tc=Cb=!1,lc&&(!me||me&&b.shiftKey)?(fe=A,ge=B,Tc=!0):(xa&&F!=Me?(N=pa-A/z,P=qa-B/F,xd(),pa=Math.round(N+A/z),qa=Math.round(P+B/F)):ub||db||!jb||(oa=null,bd&&0<=A&&0<=B&&(Q=Sd.getImageData(A,B,1,1).data,0!=Q[3]&&(oa=Oa[Q[3]-1]))),Ve=!0,V())),W())};this.resetZoom=function(){z=Fe;F=Me;S=-1;null!=ya&&(J(ya,!0,"zoom on"),xa=!1);pa=A;qa=B;P=N=0;Za=ha;$a=ma;Ua();V();ld&&(jb=!0)};this.canTip=
function(){var b;Cb=!1;T=ka.getX();A=T*u;M=ka.getY();B=M*r;if(!((ub||db)&&B<Ah&&B>zh&&A>yh)){pa=Math.round(N+A/z);qa=Math.round(P+B/F);if(0!=tb)for(b=0;b<tb;b++)if(Ea[b].overlay>=aa)fa(" Error...hotzone overlay # "+Ea[b].overlay+" > number of overlays = "+aa);else if(C[Ea[b].overlay].checked&&(Sa.clearRect(0,0,1,1),Sa.drawImage(K[x][Ea[b].overlay],pa,qa,1,1,0,0,1,1),Q=Sa.getImageData(0,0,1,1).data,cg=(Q[0]<<16)+(Q[1]<<8)+Q[2],cg==Ea[b].color)){Cb=!0;Bh=T;Ch=M;Dh=Ea[b].tip;break}if(0!=kb)for(b=kb-
1;0<=b;b--)if(null!=lb[b]){var a=lb[b];if(-1==a.frame||a.frame==x)if(-1==a.overlay||C[a.overlay].checked){var d=!1;if(a.isPan)if(a.isIcon){var c=(a.x0-N)*z-a.w2;var e=(a.y0-P)*F-a.h2;A>c&&A<c+a.width&&B>e&&B<e+a.height&&(d=!0)}else c=(a.x0-N)*z,e=(a.y0-P)*F,A>c&&A<c+a.width*z&&B>e&&B<e+a.height*F&&(d=!0);else A>a.x0&&A<a.x1&&B>a.y0&&B<a.y1&&(d=!0);if(d&&null!=a.tip){Cb=!0;Bh=T;Ch=M;Dh=lb[b].tip;break}}}W()}};this.move=function(){if(!db&&jb&&(oa=null,bd)){var b=ka.getX()*u,a=ka.getY()*r;0<=b&&0<=a&&
(Q=Sd.getImageData(b,a,1,1).data,0!=Q[3]&&(oa=Oa[Q[3]-1]))}db&&2<=Ra&&(T=ka.getX(),A=T*u,M=ka.getY(),B=M*r);W()};this.down=function(){Cb&&(Cb=!1,W());T=ka.getX();A=T*u;M=ka.getY();B=M*r;Re=A;Se=B;fe=Re;ge=Se;pa=Math.round(N+A/z);qa=Math.round(P+B/F);Ve=!1;if(Gb){var b={};b.x=T;b.y=M;b.xe=T;b.ye=M;b.xp=[T];b.yp=[M];b.type=ae.value;b.color=$d.value;b.width=xc.value;b.text=Hb.value;b.size=0;p.push(b)}};this.up=function(b){Cb=!1;if(!Gb){if(db||ub){T=ka.getX();A=T*u;M=ka.getY();B=M*r;if(ub){pd=1;if(0<
pd&&B/r<di){if(A/u>ci){na.pop();na.pop();0==na.length&&(pd=0);W();return}if(A/u<bi){W();b=window.open("","Mark Points");b.document.write("<div>Marked Points<br>");for(var a=[],d=0;d<na.length;d+=2)pa=N+na[d]/z,qa=P+na[d+1]/F,Lb(),b.document.write(bb[0].toFixed(4)+","+bb[1].toFixed(4)+"<br>"),0==d&&(a[0]=bb[0],a[1]=bb[1]);we&&b.document.write(a[0].toFixed(4)+","+a[1].toFixed(4)+"<br>");return}}na.push(A);na.push(B);W();return}if(3>Ra)if(Jb[Ra]=A,wb[Ra]=B,sd[Ra]=yf[x],0==Ra)Ra=1,wa(va(v-1)),Ne=1,ed=
null;else{Jh=sd[1]-sd[0];Qe=(Jb[1]-Jb[0])/Jh;ee=(wb[1]-wb[0])/Jh;if(null!=mf&&null!=Bc){d=Qe*Bc;var c=ee*le;a=Math.round(60*Math.sqrt(d*d+c*c));d=Math.atan2(d,-c)/.0174533;0>d&&(d+=360);ed=Bg+mi[Math.round(d/22.5)]+" at "+a+" "+Cg;$h=Jb[0];ai=0<ee?wb[0]-15:wb[0]+30}a=parseInt(Id,10);U=Math.round(Math.abs(4*(a+4)/Qe));td=Math.round(Math.abs(2*(a+4)/ee));td<U&&(U=td);120<U?U=120*Math.floor(U/120)+60:90<U?U=120:60<U?U=90:30<U?U=60:15<U?U=30:10<U?U=15:5<U?U=10:2<U?U=5:0==U&&(U=1);td=sd[1]/U*U+U;de=1;
Ag&&(de=-1);xh=Qe*U;Xf=ee*U;wa(va(v-1));Ra=3;Ne=2}else if(B/r<Ah&&B/r>zh&&A/u>yh&&3==Ra){Ac();W();return}W()}if(Tc)Tc=!1,W();else if(null!=bc&&xa&&(lc=!1,J(bc,!0,"distance on")),Ve)Ve=!1;else if(b.altKey)HAniS.resetZoom();else if(jb&&null!=oa&&Wf)Mb(oa,"z");else{T=ka.getX();A=T*u;M=ka.getY();B=M*r;if(0!=tb)for(a=0;a<tb;a++)if(Ea[a].overlay>=aa)fa(" Error...hotzone overlay # "+Ea[a].overlay+" > number of overlays = "+aa);else if(C[Ea[a].overlay].checked&&(Sa.clearRect(0,0,1,1),Sa.drawImage(K[x][Ea[a].overlay],
Math.floor(pa),Math.floor(qa),1,1,0,0,1,1),Q=Sa.getImageData(0,0,1,1).data,cg=(Q[0]<<16)+(Q[1]<<8)+Q[2],cg==Ea[a].color)){Mb(Ea[a],"z");return}if(0!=kb)for(a=kb-1;0<=a;a--)if(null!=lb[a]){var e=lb[a];if(!(-1!=e.frame&&e.frame!=x||e.fromfile||-1!=e.overlay&&!C[e.overlay].checked)){var f=!1;e.isPan?e.isIcon?(d=(e.x0-N)*z-e.w2,c=(e.y0-P)*F-e.h2,A>d&&A<d+e.width&&B>c&&B<c+e.height&&(f=!0)):(d=(e.x0-N)*z,c=(e.y0-P)*F,A>d&&A<d+e.width*z&&B>c&&B<c+e.height*F&&(f=!0)):A>e.x0&&A<e.x1&&B>e.y0&&B<e.y1&&(f=!0);
if(f){Mb(lb[a],"s");return}}}xa&&(jb=!1,yd(b.ctrlKey||bg||b.which&&3==b.which||b.button&&2==b.button));V();W()}}};this.wheel=function(b){Sg?zb(b):xa&&(T=ka.getX(),A=T*u,M=ka.getY(),B=M*r,pa=Math.round(N+A/z),qa=Math.round(P+B/F),yd(-1==b))};this.toggleAutoRefresh=function(){Dd?(J(Kc,!1,"autorefresh off"),null!=Cc&&clearInterval(Cc),Dd=!1):(J(Kc,!0,"autorefresh on"),Cc=setInterval("HAniS.reloadFOF();",df),Dd=!0)};this.toggleLoopRock=function(){ce?(J(Vd,!0,"looprock rock"),ce=!1):(J(Vd,!1,"looprock loop"),
ce=!0)};this.toggleExtrap=function(){db?(null!=ac&&(J(ac,!0,"extrap on"),y.style.cursor=Ba.pop(),null!=Ab&&(Ab.disabled=!1),H(Qa),xa=Tg,Ra=-1),db=!1,W()):(null!=ac&&(db=!0,ed=null,Ba.push(y.style.cursor),y.style.cursor="crosshair",J(ac,!1,"extrap off"),Qa=Aa,null!=Ab&&(Ab.disabled=!0),Aa=!1,Tg=xa,xa=!1,HAniS.resetZoom(),Ac(),W()),V())};this.doEnhance=function(b){if(kd||Ec){var a=Na[0].height,d=Na[0].width;b=parseInt(za.value,10);0<=b?(Qf=Wa[b],Rf=Xa[b],Sf=Ya[b],Tf=Pd[b],nc[nb]=b):nc[nb]=null;var c=
a*d*4;for(d=0;d<Zb.length;d++)if(Na[d].gotit){Na[d].gotit=!1;var e=De[d].data;var f=Af[d];if(0>b)for(a=0;a<c;a+=4)e[a]=f[a],e[a+1]=f[a+1],e[a+2]=f[a+2],e[a+3]=f[a+3];else for(a=0;a<c;a+=4)cb=f[a],cb===f[a+1]&&cb===f[a+2]&&(e[a]=Qf[cb],e[a+1]=Rf[cb],e[a+2]=Sf[cb],e[a+3]=Tf[cb]);Qc[d].putImageData(De[d],0,0);Na[d].gotit=!0}}};this.overClick=function(b){var a;if(b.target.checked)for(a=0;a<C.length;a++)b.target!=C[a]&&0!=b.target.name&&b.target.name==C[a].name&&(C[a].checked=!1);bd=!0;for(a=0;a<Rb.length;a++)b.target!=
C[a]&&Ka(a),null!=oc&&!oc[a]&&C[a].checked&&(bd=!1),null!=za&&a===nb&&(za.disabled=!C[a].checked);V()};this.toggleIsLooping=function(){Aa?(Aa=!1,J(Ab,!0,"startstop start")):(Aa=!0,J(Ab,!1,"startstop stop"))};this.toggleZooming=function(){xa?(HAniS.resetZoom(),J(ya,!0,"zoom on")):(J(ya,!1,"zoom off"),xa=!0,null!=bc&&(lc=!1,J(bc,!0,"distance on")),ld&&(jb=!0),db&&HAniS.toggleExtrap())};this.togclick=function(b){var a=sh.getX();sh.getY();for(var d=vh,c=0;c<Pa.length;c++){if(a>d&&a<d+qd){if(b.shiftKey){0<=
Pa[c]&&(H(!1),wa(c));break}b=0;0<=Pa[c]&&(b=-1);fb(c,b);break}d=d+qd+Ke}};this.doneLoading=function(b){Ce=b};this.frameChanged=function(b){Oe=b};this.getFrame=function(){return x};this.showFrame=function(b){wa(va(b))}};
