var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(q,ca,Z){q!=Array.prototype&&q!=Object.prototype&&(q[ca]=Z.value)};$jscomp.getGlobal=function(q){return"undefined"!=typeof window&&window===q?q:"undefined"!=typeof global&&null!=global?global:q};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var q=0;return function(ca){return $jscomp.SYMBOL_PREFIX+(ca||"")+q++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var q=$jscomp.global.Symbol.iterator;q||(q=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[q]&&$jscomp.defineProperty(Array.prototype,q,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.arrayIterator=function(q){var ca=0;return $jscomp.iteratorPrototype(function(){return ca<q.length?{done:!1,value:q[ca++]}:{done:!0}})};$jscomp.iteratorPrototype=function(q){$jscomp.initSymbolIterator();q={next:q};q[$jscomp.global.Symbol.iterator]=function(){return this};return q};
$jscomp.iteratorFromArray=function(q,ca){$jscomp.initSymbolIterator();q instanceof String&&(q+="");var Z=0,O={next:function(){if(Z<q.length){var yb=Z++;return{value:ca(yb,q[yb]),done:!1}}O.next=function(){return{done:!0,value:void 0}};return O.next()}};O[Symbol.iterator]=function(){return O};return O};
$jscomp.polyfill=function(q,ca,Z,O){if(ca){Z=$jscomp.global;q=q.split(".");for(O=0;O<q.length-1;O++){var yb=q[O];yb in Z||(Z[yb]={});Z=Z[yb]}q=q[q.length-1];O=Z[q];ca=ca(O);ca!=O&&null!=ca&&$jscomp.defineProperty(Z,q,{configurable:!0,writable:!0,value:ca})}};
$jscomp.polyfill("Array.prototype.fill",function(q){return q?q:function(q,Z,O){var ca=this.length||0;0>Z&&(Z=Math.max(0,ca+Z));if(null==O||O>ca)O=ca;O=Number(O);0>O&&(O=Math.max(0,ca+O));for(Z=Number(Z||0);Z<O;Z++)this[Z]=q;return this}},"es6","es3");
function PEvs(q,ca,Z,O,yb,eg,Xe){var va,ic,Ua,wd,Ye,xd,Ka,jc,fa,ie,La,Lb=0,Ac=0,ad,Ma=!1,kc=!1,zb=0,Va=0,Mb=0,Nb=0,yd,zd,Bc=function(k){Ka=k.target;for(fa=jc=0;Ka;)jc+=Ka.offsetLeft-Ka.scrollLeft,fa+=Ka.offsetTop-Ka.scrollTop,Ka=Ka.offsetParent;Lb=(Ma?yd:k.pageX)-jc-document.body.scrollLeft;Ac=(Ma?zd:k.pageY)-fa-document.body.scrollTop};this.getX=function(){return Lb};this.getY=function(){return Ac};var H=function(k){k.preventDefault();k.stopImmediatePropagation?k.stopImmediatePropagation():k.stopPropagation()},
Ad=function(k){Bc(k);ad=Lb;xa=Ac;W=!0;null!=X&&(wd=(new Date).getTime());null!=wa&&wa(k)},J=function(k){W&&(Bc(k),W=!1,null!=Ab&&Ab(k),null!=X&&(Ye=(new Date).getTime(),xd=Ye-wd,300>xd&&X(k)))},gb=function(k){Bc(k);3>Math.abs(Lb-ad)&&3>Math.abs(Ac-xa)||(xa=ad=-9999,W?null!=Na&&Na(k):null!=fb&&fb(k),null!=Bd&&je())};this.touchDown=function(k){Ua=!0;if(1<k.targetTouches.length)return Ma=!0,La&&(Va=-1,H(k)),!1;va=k.changedTouches;ic=va[0];Ad(ic)};this.touchUp=function(k){0==k.targetTouches.length&&(Ma=
Ua=!1);H(k);if(Ma||kc)return Ma||(kc=!1),!1;va=k.changedTouches;ic=va[0];J(ic)};this.touchMove=function(k){Ua=!0;H(k);if(Ma)return La&&(va=k.targetTouches,yd=(va[0].pageX+va[1].pageX)/2,zd=(va[0].pageY+va[1].pageY)/2,kc=!0,Mb=va[0].pageX-va[1].pageX,Nb=va[0].pageY-va[1].pageY,zb=Mb*Mb+Nb*Nb,La&&0<Va&&30<Math.abs(zb-Va)&&La(0<zb-Va?1:-1),Va=zb),!1;va=k.changedTouches;ic=va[0];gb(ic)};this.pointUp=function(k){H(k);for(var q=0;q<sa.length;q++)if(sa[q].pointerId==k.pointerId){sa.splice(q,1);break}0==
sa.length&&(Ua=Ma=!1);if(Ma||kc)return Ma||(kc=!1),!1;J(k);return!1};this.pointDown=function(k){H(k);sa.push(k);Va=-1;Ua=!0;1<sa.length?Ma=!0:Ad(k);return!1};this.pointMove=function(k){H(k);for(var q=0;q<sa.length;q++)sa[q].pointerId==k.pointerId&&(sa[q]=k);if(Ma||!kc){if(Ma)return yd=(sa[0].pageX+sa[1].pageX)/2,zd=(sa[0].pageY+sa[1].pageY)/2,La&&(kc=!0,Mb=sa[0].pageX-sa[1].pageX,Nb=sa[0].pageY-sa[1].pageY,zb=Mb*Mb+Nb*Nb,La&&0<Va&&30<Math.abs(zb-Va)&&La(0<zb-Va?1:-1),Va=zb),!1;gb(k);return!1}};this.mouseDown=
function(k){Ua||(H(k),Ad(k))};this.clearDown=function(){W=!1};this.mouseUp=function(k){Ua||(H(k),J(k))};this.useWheel=function(k){q.addEventListener("wheel",this.mouseWheel,!0);La=k};this.mouseWheel=function(k){Bc(k);var q=Math.max(-1,Math.min(1,-k.deltaY||-k.detail));H(k);La&&La(q)};this.mouseClick=function(k){H(k);W=!1};this.mouseMove=function(k){Ua||(H(k),gb(k))};this.mouseDragged=function(k){Ua||(H(k),Bc(k),null!=Na&&Na(k),null!=Bd&&je())};var je=function(){clearTimeout(ie);ie=setTimeout(function(){Bd()},
600)};var xa=ad=Ac=Lb=0;var wa=ca;var Ab=Z;var fb=O;var Na=yb;var X=eg;var Bd=Xe;var W=Ua=!1;var sa=[];q.addEventListener("mousedown",this.mouseDown,!1);q.addEventListener("mouseup",this.mouseUp,!1);q.addEventListener("mousemove",this.mouseMove,!1);q.addEventListener("click",this.mouseClick,!1);q.addEventListener("touchstart",this.touchDown,!1);q.addEventListener("touchend",this.touchUp,!1);q.addEventListener("touchmove",this.touchMove,!1);q.addEventListener("touchleave",this.touchUp,!1);q.addEventListener("touchcancel",
this.touchUp,!1);q.addEventListener("contextmenu",function(k){k.preventDefault()},!1);q.style["touch-action"]="none";q.addEventListener("mouseout",function(k){W||(Ac=Lb=-1,null!=fb&&fb(k));W=!1})};var HAniSF=function(){function q(b){var a,d;bd=!0;if(b instanceof Array)for(e={},a=0;a<b.length;a++){if(!(2>b[a].length)){var c=b[a].trim();if(0!=c.indexOf("#")){var h=c.indexOf("=");if(!(1>h)){var f=c.substr(0,h).trim().toLowerCase();e[f]=c.substr(h+1).trim()}}}}else e=b;ke=!1;a=e.debug;null!=a&&("true"==a?(Ze=window.open("","HAniSDebugInfo","scrollbars=yes,width=400,height=200"),ke=!0,ha("HAniS Version 4.25")):ke=!1);hb=!0;a=e.set_className;null!=a&&E(a,"f")&&(hb=!1);ha("Is type of param an array = "+
(b instanceof Array));a=e.divalign;null!=a&&(Cd=a.trim(),y.align=Cd);a=e.prevent_shortcuts;null!=a&&E(a,"t")&&(le=!0);a=e.initial_message;null!=a&&(b=e.initial_message_style,null==b&&(b="background-color:red;top:10px;left:10px;height:100px;width:200px"),b="z-index:99;position:absolute;"+b,lc=n("div"),lc.setAttribute("style",b),lc.innerHTML=a,lc.addEventListener("click",function(){lc.style.visibility="hidden"},!1),lc.style.visibility="visible",Wa.appendChild(lc),b=e.initial_message_timeout,null!=b&&
("auto"==b?$e=!0:($e=!1,b=parseInt(e.initial_message_timeout,10),2>b&&(b=2),setTimeout(function(){lc.style.visibility="hidden"},1E3*b))));a=e.coordinates;null!=a&&yb(a);c="green";h="white";f="12px Arial";var m=null,l=d=10,g=10;af=2;fg="Lat = ";gg=" Lon = ";a=e.coordinates_display_style;null!=a&&(b=a.split(","),c=b[0].trim(),h=b[1].trim(),f=b[2].trim(),3<b.length&&(fg=b[3],gg=b[4],af=parseInt(b[5],10),6<b.length&&(m=b[6].trim(),d=parseInt(b[7],10),l=parseInt(b[8],10),g=parseInt(b[9],10))));hg=new fb(c,
h,f,m,d,l,g);me=Cc=null;null!=e.map_scale&&(ne=mc=!0,b=e.map_scale.split(","),Cc=parseFloat(b[0]),me=1<b.length?parseFloat(b[1]):Cc);ig=" ";a=e.distance_unit;null!=a&&(ig=a.trim());a=e.divcan_style;null!=a&&a.trim();bf="default";a=e.distance_cursor;null!=a&&(bf=a.trim());oe="default";a=e.location_cursor;null!=a&&(oe=a.trim());pe="default";a=e.probe_cursor;null!=a&&(pe=a.trim());cf="default";a=e.mark_cursor;null!=a&&(cf=a.trim());a=e.imagecan_style;null!=a&&(b=a.trim()+";position:absolute;top:0;left:0;",
nb.setAttribute("style",b+"z-index:1;"),nc.setAttribute("style",b+"z-index:6;"));c="blue";h="white";f="12px Arial";m=null;g=l=d=10;jg=1;kg="white";a=e.distance_display_style;null!=a&&(b=a.split(","),c=b[0].trim(),h=b[1].trim(),kg=5<=b.length?b[4].trim():h,f=b[2].trim(),jg=parseInt(b[3],10),5<b.length&&(m=b[5].trim(),d=parseInt(b[6],10),l=parseInt(b[7],10),g=parseInt(b[8],10)));Lh=new fb(c,h,f,m,d,l,g);c="black";h="white";f="12px Arial";m=null;g=l=d=10;a=e.probe_display_style;null!=a&&(b=a.split(","),
c=b[0].trim(),h=b[1].trim(),f=b[2].trim(),3<b.length&&(m=b[3].trim(),d=parseInt(b[4],10),l=parseInt(b[5],10),g=parseInt(b[6],10)));Mh=new fb(c,h,f,m,d,l,g);lg="Undefined";mg=!1;Dd=0;a=e.probe_undefined;null!=a&&(b=a.split(","),lg=b[0].trim(),1<b.length&&(Dd=parseInt(b[1],10)+1),2<b.length&&(mg=!0));df=!1;e.probe_base_image&&(df=!0);a=e.active_probe;null!=a&&(Ob=!0);a=e.pause;null!=a&&(ng=parseInt(a,10));a=e.auto_refresh;null!=a&&(ef=6E4*parseInt(a,10),Dc=setInterval("HAniS.reloadFOF();",ef),Ed=!0);
Fd=!1;a=e.enable_smoothing;null!=a&&E(a,"t")&&(Fd=!0);qe=!0;a=e.check_image_size;null!=a&&E(a,"f")&&(qe=!1);og=!1;a=e.sprites;if(null!=a){b=a.split(",");ff=new Image;gf=[];hf=[];Pb=[];Qb=[];if("row"==b[1].trim().toLowerCase())for(l=h=c=0,a=2;a<b.length;)for("row"==b[a].trim().toLowerCase()&&(c=0,h+=l,l=0,a+=1),d=parseInt(b[a],10),a+=1,f=parseInt(b[a],10),a+=1,m=parseInt(b[a],10),m>l&&(l=m),a+=1,g=0;g<d;g++)gf.push(c),hf.push(h),Pb.push(f),Qb.push(m),c+=f;else for(h=!1,a=1;a<b.length;)gf.push(parseInt(b[a],
10)),a+=1,hf.push(parseInt(b[a],10)),a+=1,a>=b.length?(c=0,h=!0):c=parseInt(b[a],10),0>c?(h=!0,Pb.push(Math.abs(c)),a+=1,c=parseInt(b[a++],10),Qb.push(Math.abs(c))):h?(Pb.push(Pb[Pb.length-1]),Qb.push(Qb[Qb.length-1])):(Pb.push(parseInt(b[a],10)),a+=1,Qb.push(parseInt(b[a],10)),a+=1);ff.onload=function(){og=!0};ff.src=b[0]}a=e.overlay_labels;null!=a&&(Rb=a.split(","));jf=null;a=e.auto_enhance_background;null!=a&&(jf=parseInt(a,10)-1);Ec=null;a=e.auto_enhance;if(null!=a)for(c=e.overlay_probe_table,
b=a.split(","),Ec=Array(b.length),a=0;a<b.length;a++)"x"==b[a].trim().toLowerCase()?Ec[a]=-1:Ec[a]=parseInt(b[a].trim(),10)-1,null==c&&(oc[a]=Ec[a]);Fc=!1;ob=-1;a=e.overlay_enhance;null!=a&&(Fc=!0,ob=parseInt(a,10)-1);pc=null;cd=!0;a=e.overlay_allow_hoverzones;if(null!=a)for(b=a.split(","),pc=Array(b.length),a=0;a<b.length;a++)if(pc[a]=!0,E(b[a],"n")||E(b[a],"f"))pc[a]=!1;S=Y=null;kf=pg=!1;a=e.window_size;null!=a&&(b=a.split(","),"div"==b[0]?kf=!0:(S=parseInt(b[0],10),Y=parseInt(b[1],10)),pg=!0);
Gd=[];a=e.use_for_all_frames;if(null!=a)for(b=a.split(","),a=0;a<b.length;a+=2)Gd[parseInt(b[a],10)]=parseInt(b[a+1],10)-1;Hd=-1;a=e.skip_missing;null!=a&&(Hd=parseInt(a,10));qg="#00000000";a=e.skip_missing_color;null!=a&&(qg=a);re=null;a=e.overlay_spacer;if(null!=a)for(b=a.split(","),re=Array(b.length),a=0;a<b.length;a++)re[a]=parseInt(b[a],10);a=e.overlay_probe_table;if(null!=a)for(b=a.split(","),a=0;a<b.length;a++)"x"==b[a].trim().toLowerCase()?oc[a]=-1:oc[a]=parseInt(b[a],10)-1;lf=[];a=e.overlay_ontop;
if(null!=a)for(b=a.split(","),a=0;a<b.length;a++)lf[parseInt(b[a],10)-1]=!0;Gc=null;a=e.overlay_order;null==a&&(a=e.overlay_zorder);if(null!=a)for(b=a.split(","),Gc=Array(b.length),a=0;a<b.length;a++)Gc[parseInt(b[a],10)-1]=a;Sb=null;a=e.overlay_links;if(null!=a)for(b=a.split(","),Sb=Array(b.length),a=0;a<b.length;a++)Sb[a]=parseInt(b[a],10);rg=[];I=null;a=e.overlay_slice;if(null!=a)for(b=a.split(","),a=0;a<b.length;a++)rg[parseInt(b[a],10)-1]=!0;sg=!0;a=e.slice_smoothing;E(a,"f")&&(sg=!1);dd=null;
a=e.overlay_clear;if(null!=a)for(b=a.split(","),dd=Array(b.length),a=0;a<b.length;a++)dd[a]=b[a].trim().toLowerCase();tg=!1;a=e.transparency;null!=a&&(b=a.split(","),1==b.length?ug=vg=wg=parseInt(b[0],10):(ug=parseInt(b[0],10),vg=parseInt(b[1],10),wg=parseInt(b[2],10)),tg=!0);mf=!1;a=e.transparency_list;if(null!=a){b=a.split(",");xg=[];for(a=0;a<b.length;a++)xg[parseInt(b[a].trim(),10)-1]=!0;mf=!0}se=null;a=e.overlay_transparent_amount;if(null!=a)for(b=a.split(","),se=Array(b.length),a=0;a<b.length;a++)se[a]=
parseFloat(b[a])/100;Hc=null;a=e.overlay_zoom;if(null!=Rb&&null!=a)for(b=a.split(","),Hc=Array(b.length),a=0;a<b.length;a++)if(Hc[a]=1,E(b[a],"n")||E(b[a],"f"))Hc[a]=0;else if(E(b[a],"d")||E(b[a],"h"))Hc[a]=-1;pb=null;yg=[];a=e.overlay_preserve_list;if(null!=Rb&&null!=a)for(b=a.split(","),pb=Array(b.length),a=0;a<b.length;a++){pb[a]=!0;if(E(b[a],"n")||E(b[a],"f"))pb[a]=!1;if(E(b[a],"a")||E(b[a],"A"))yg[a]=!0}aa=null;if(null!=Rb&&null!=pb)for(b=e.overlay_preserve.replace(/&/g,",&,").split(","),c=e.overlay_preserve_position,
null!=c&&(c=c.split(",")),h=0,aa=Array(pb.length),a=f=0;a<pb.length;a++)if(pb[a]){aa[a]=[];m=0;do{aa[a][m]=[];for(d=0;4>d;d++)aa[a][m][d]=parseInt(b[f].trim(),10),f+=1;aa[a][m][2]=aa[a][m][2]-aa[a][m][0]+1;aa[a][m][3]=aa[a][m][3]-aa[a][m][1]+1;null!=c?(aa[a][m][4]=parseInt(c[h],10),aa[a][m][5]=parseInt(c[h+1],10),h+=2):(aa[a][m][4]=aa[a][m][0],aa[a][m][5]=aa[a][m][1]);f<b.length&&"&"==b[f].trim()?(f+=1,m+=1,d=!0):d=!1}while(d)}te=0;zg=" ";qc="white";Id="transparent";Jd="14pt arial";Ag=!1;a=e.times_label_style;
null!=a&&(b=a.split(","),qc=b[0].trim(),1<b.length&&(te=Math.floor(60*parseFloat(b[1]))),1<b.length&&(te="?"==b[1].trim()||"auto"==b[1].trim().toLowerCase()?-Math.floor((new Date).getTimezoneOffset()):Math.floor(60*parseFloat(b[1]))),2<b.length&&(zg=b[2].trim()),3<b.length&&(Id=b[3].trim()),4<b.length&&(Jd=b[4].trim()),5<b.length&&-1!=b[5].trim().indexOf("t")&&(Ag=!0));0==qc.indexOf("0x")&&(qc="#"+qc.substring(2));0==Id.indexOf("0x")&&(Id="#"+Id.substring(2));ed=parseInt(Jd,10);Nh=new fb("black",
"white",Jd,"black",20,5,5);Bg=!1;a=e.to_from_lock;null!=a&&(Bg=E(a,"t")?!0:!1);a="black";d="white";l="14px arial";c=null;m=f=h=10;Cg=Dg=" ";nf=fd=null;a=e.dirspd_display_style;null!=a&&(b=a.split(","),a=b[0].trim(),d=b[1].trim(),l=b[2].trim(),Cg=b[3],Dg=b[4],5<b.length&&(c=b[5].trim(),h=parseInt(b[6],10),f=parseInt(b[7],10),m=parseInt(b[8],10)),nf=new fb(a,d,l,c,h,f,m));c="black";h="white";f="14px arial";m=null;g=l=d=10;a=e.tipbox_display_style;null!=a&&(b=a.split(","),c=b[0].trim(),h=b[1].trim(),
f=b[2].trim(),3<b.length&&(m=b[3].trim(),d=parseInt(b[4],10),l=parseInt(b[5],10),g=parseInt(b[6],10)));Eg=new fb(c,h,f,m,d,l,g);gd=null;da=e.image_base;null!=da?gd=da=da.trim():da=null!=e.image_only_base?e.image_only_base.trim():null;Fg=da;a=e.overlay_base;null!=a&&(Tb=a.trim());ue=!0;a=e.zip_only;null!=a&&E(a,"f")&&(ue=!1);Ic=!1;a=e.zip_filename;null!=a&&(Ic=!0,of=a.trim());bd=!0;a=e.filenames;null==a&&(a=e.background_filenames);null!=a&&Oh(a);a=e.basename;null!=a&&(c=e.base_starting_number,h=0,
f=1,null!=c&&(b=c.split(","),h=parseInt(b[0],10),1<b.length&&(f=parseInt(b[1],10))),v=e.num_frames,null==v&&(v=e.num_images),v=parseInt(v,10),Ph(a,h,f));pf=!0;b=e.zip_static;null!=b&&(E(b,"f")||E(b,"n"))&&(pf=!1);qf=!0;b=e.background_static;null!=b&&(E(b,"f")||E(b,"n"))&&(qf=!1);a=e.overlay_filenames;null!=a&&Qh(a);Da=null;a=e.image_preserve;if(null!=a)for(b=a.split(","),Da=[],a=0;a<b.length;a++)Da[a]=parseInt(b[a].trim(),10),1<a%4&&(Da[a]=Da[a]-Da[a-2]+1);Gg=!0;a=e.keep_zoom;null!=a&&E(a,"f")&&(Gg=
!1);Kd=Hg=0;Ig=!1;a=e.hide_bottom;null!=a&&(b=a.split(","),Hg=parseInt(b[0].trim(),10),1<b.length&&E(b[1],"t")&&(Ig=!0));Ld=Jg=0;Kg=!1;a=e.hide_top;null!=a&&(b=a.split(","),Jg=parseInt(b[0].trim(),10),1<b.length&&E(b[1],"t")&&(Kg=!0));Md=Lg=0;Mg=!1;a=e.hide_left;null!=a&&(b=a.split(","),Lg=parseInt(b[0].trim(),10),1<b.length&&E(b[1],"t")&&(Mg=!0));Nd=Ng=0;Og=!1;a=e.hide_right;null!=a&&(b=a.split(","),Ng=parseInt(b[0].trim(),10),1<b.length&&E(b[1],"t")&&(Og=!0));Pg=!1;a=e.hide_background;null!=a&&
E(a,"t")&&(Pg=!0);Qg="<div>";Rg=300;Sg=500;a=e.popup_style;null!=a&&(Qg='<div style="'+a+'">');a=e.popup_window_size;null!=a&&(b=a.split(","),Sg=b[0],Rg=b[1]);Tg=!1;a=e.wheel_frames;null!=a&&(Tg=!0,la.useWheel(L.wheel));Ug=ya=!1;a=e.active_zoom;null!=a&&E(a,"t")&&(null==za&&(ya=!0),la.useWheel(L.wheel));rf=!1;a=e.cycle_zoom;null!=a&&E(a,"t")&&(rf=!0);a=e.initial_zoom;null!=a&&(b=a.split(","),rc="auto"!=b[0].toLowerCase()?parseFloat(b[0]):"auto",1<b.length?(Od=parseInt(b[1],10),Vg=parseInt(b[2],10)):
Od=-1,Wg=!0);hd=1;id=!1;ma=null;a=e.zoom_scale;if(null!=a)if(b=a.split(","),1===b.length)E(a,"hi_res")?(id=!0,hd=0):hd=parseFloat(a);else{ma=Array(b.length);for(a=0;a<b.length;a++)ma[a]=parseFloat(b[a]);id=!0}Jc=9999999;a=e.maximum_zoom;null!=a&&(Jc=parseFloat(a));ve=!0;a=e.use_progress_bar;null!=a&&E(a,"f")&&(ve=!1);a=e.dwell;null!=a&&(b=a.split(","),ib=parseInt(b[0].trim(),10),1<b.length&&(Ub=parseInt(b[1].trim(),10),10>Ub&&(Ub=10),Kc=parseInt(b[2].trim(),10),sf=parseInt(b[3].trim(),10)));a=e.rate;
null!=a&&(b=a.split(","),ib=Math.round(1E4/parseFloat(b[0].trim())),1<b.length&&(Ub=Math.round(1E4/parseFloat(b[2].trim())),10>Ub&&(Ub=10),Kc=Math.round(1E4/parseFloat(b[1].trim()))));a=e.frame_times_template;null!=a&&(b=a.split(","));qb=null;a=e.times;if(null!=a){b=a.split(",");qb=Array(b.length);for(a=0;a<b.length;a++)qb[a]=parseInt(b[a].trim(),10);va(qb)}a=e.extrap_times_filename;if(null!=a){qb=[];var k=new XMLHttpRequest;k.open("get",a,!0);k.onload=function(){for(var a=k.responseText.split("\n"),
b=0;b<a.length;b++){var c=a[b].split(" ");if(3==c.length){c[2].trim();var d=parseInt(c[0],10)-1;qb[d]=100*parseInt(c[2].substring(0,2),10)+parseInt(c[2].substring(3,5),10)+parseInt(c[2].substring(6,8),10)/30}}va(qb)};k.send()}Pd=null;a=e.extrap_times_template;null!=a&&(Pd=RegExp(a));Xg=["Click on target's initial position","Click on target's final position","Move pointer around or click here to select target"];Yg=10;a=e.extrap_prompts_position;null!=a&&E(a,"bot")&&(Yg=9999);a=e.extrap_prompts;null!=
a&&(Xg=a.split(","));we=["Click on first point to mark","Save points","Remove last point"];a=e.mark_prompts;null!=a&&(we=a.split(","));xe=!0;a=e.mark_close;null!=a&&E(a,"f")&&(xe=!1);tf="12pt Arial";Zg="white";a=e.mark_prompts_style;null!=a&&(b=a.split(","),tf=b[0].trim(),1<b.length&&(Zg=b[1].trim()));$g=e.controls;ha("controls = "+e.controls);ha("bottom_controls = "+e.bottom_controls);Lc=ye=Vb=Wb=rb=sb=Bb=null;null!=$g&&ie($g,!0);ah=e.bottom_controls;null!=ah&&ie(ah,!1);Mc=!1;a=e.probe_table;null!=
a&&O(a);b=e.enhance_filename;null==b&&(b=e.enhance_table);if(null!=b){ha("Reading enhancement table...");Mc=!1;k=new XMLHttpRequest;tb=[];Nc=[];ze=[];Oc=[];Xb=[];var bh,Ea,t;Xa=[];Ya=[];Za=[];Qd=[];w=-1;ch=!0;var q=!1,p,x,B,uf,u,r,D,vf,A,H,z,F,G;k.onload=function(){for(var a=this.responseText.split("\n"),b=0;b<a.length;b++)if(!(2>a[b].length)){var c=a[b].replace(/\s+/g," ").trim(),d=c.indexOf("#");if(0!=d)if(0<d&&(c=c.substring(0,d)),d=c.split(","),0==d[0].indexOf("*"))w++,tb[w]=Array(256),Oc[w]=
Array(256),Nc[w]=Array(256),Xb[w]=Array(256),Xa[w]=Array(256),Ya[w]=Array(256),Za[w]=Array(256),Qd[w]=Array(256),tb[w]=Array(256),ze[w]=1<d.length?d[1].trim():"None",bh=" ",Ea="Value =",t=1,c=n("option"),c.innerHTML=d[0].substring(1),c.value=w,null!=Aa&&Aa.add(c);else{var h=c.indexOf("value");0>h&&(h=c.indexOf("probe"));q=!1;H=z=0;0<h&&(d=c.substring(h+1),c=c.substring(0,h),h=d.indexOf("="),d=d.substring(h+1),d=d.split(","),1==d.length?(Ea=d[0].trim(),t=-1,q=!1):(H=parseFloat(d[0].trim()),z=parseFloat(d[1].trim()),
2<d.length&&(t=parseInt(d[2],10)),3<d.length&&(bh=Rh(d[3].trim())),4<d.length&&(Ea=d[4].trim()),q=!0));c=c.split(" ");p=parseInt(c[0].trim(),10);x=parseInt(c[1].trim(),10);B=x-p;uf=parseFloat(c[2].trim());u=parseFloat(c[3].trim());r=parseFloat(c[4].trim());D=parseFloat(c[5].trim());vf=parseFloat(c[6].trim());A=parseFloat(c[7].trim());F=G=255;9<c.length&&(F=parseFloat(c[8].trim()),G=parseFloat(c[9].trim()));for(c=p;c<=x;c++)0===B?(Xa[w][p]=uf,Ya[w][p]=r,Za[w][p]=vf,Qd[w][p]=F):(Xa[w][c]=Math.round(uf+
(u-uf)*(c-p)/B),Ya[w][c]=Math.round(r+(D-r)*(c-p)/B),Za[w][c]=Math.round(vf+(A-vf)*(c-p)/B),Qd[w][c]=Math.round(F+(G-F)*(c-p)/B)),Oc[w][c]=Ea,Nc[w][c]=bh,Xb[w][c]=t,q&&(tb[w][c]=H+(z-H)*(c-p)/B)}}-1!=ob&&C[ob].checked&&(Aa.disabled=!1);Mc=!0;ca()};k.open("get",b,!0);k.send()}else ca()}function ca(){var b=e.sprite_filenames;if(null!=b){var a=b.split(",");wf=0;ja=[];b=e.sprite_images_offset;Pc=-1;null!=b&&(Pc=parseInt(b,10)-1);for(b=0;b<a.length;b++){ja[b]=new Image;ja[b].gotit=!1;ja[b].inx=b;ja[b].fromfile=
!0;var d="/";0<a[b].indexOf("?")&&(d="?");ja[b].zoomme=0<a[b].indexOf(d+"zoom");ja[b].anim=0<a[b].indexOf(d+"animate");d=a[b].indexOf(d);0<d&&(a[b]=a[b].substring(0,d));ja[b].onload=function(){ja[this.inx].gotit=!0;wf++;wf==a.length&&Z()};ja[b].src=a[b].trim()}}else Z()}function Z(){for(var b=Object.keys(e),a=0;a<b.length;a++)E(b[a],"hotspot")&&Lb("hotspot="+e[b[a]]);bd?L.getFOF():(sc=!0,Ka())}function O(b){var a=new XMLHttpRequest;tb=[];ze=[];Nc=[];var d=" ";Oc=[];var c="Value=";Xb=[];var h=1;Qc=
[];xf=[];Xa=[];Ya=[];Za=[];var e,m=-1;w=-1;var l=0;a.onload=function(){for(var a=this.responseText.split("\n"),b=0;b<a.length;b++)if(!(2>a[b].length)){var f=a[b].replace(/\s+/g," ").trim().split(","),g=f[0].split(" ");if(0==g[0].indexOf("*"))w++,tb[w]=[],Oc[w]=[],Nc[w]=[],Xb[w]=[],Xa[w]=[],Ya[w]=[],Za[w]=[],xf[w]=[],Qc[w]=[],m=-1,ze[w]=1<f.length?f[1].trim():"None",l=1;else if(0!=l){m++;var t=Array(3);tb[w][m]=parseFloat(g[0]);Xa[w][m]=parseInt(g[1].trim(),10);Ya[w][m]=parseInt(g[2].trim(),10);Za[w][m]=
parseInt(g[3].trim(),10);0!=m&&(t[0]=Xa[w][m]-Xa[w][m-1],t[1]=Ya[w][m]-Ya[w][m-1],t[2]=Za[w][m]-Za[w][m-1],e=0,Math.abs(t[1])>Math.abs(t[e])&&(e=1),Math.abs(t[2])>Math.abs(t[e])&&(e=2),xf[w][m-1]=e,Qc[w][m-1]=t,0==Qc[w][m-1][e]&&(Qc[w][m-1][e]=1));1<f.length&&(0==f[1].trim().indexOf('"')?(h=-1,f=f[1].trim(),c=f.substr(1,f.length-2),d=""):(h=parseInt(f[1],10),2<f.length&&(d=Rh(f[2].trim())),3<f.length&&(c=f[3].trim())));Oc[w][m]=c;Xb[w][m]=h;Nc[w][m]=d}}Mc=!0};a.open("get",b,!0);a.send()}function yb(b){b=
b.split(",");var a=b[0].trim();"PS"===a?(Yb=new ji,Yb.init(b)):"CE"==a?(Yb=new ki,Yb.init(b)):"LCC"==a?(Yb=new li,Yb.init(b)):(Yb=null,yf=parseFloat(b[0]),dh=parseFloat(b[1]),Sh=parseFloat(b[2]),Th=parseFloat(b[3]))}function eg(b){var a=new XMLHttpRequest;a.onload=function(){q(this.responseText.split("\n"))};a.open("get",b+"?"+Math.round(1E5*Math.random()),!0);a.send()}function Xe(b){var a;if(null!=dd){for(a=0;a<dd.length;a++)-1!=dd[a].indexOf(b)&&(C[a].checked=!1);for(a=0;a<dd.length;a++)La(a)}}
function va(b){zf=Array(b.length);for(var a=0;a<b.length;a++){var d=60*Math.floor(b[a]/100)+Math.floor(b[a])%100;0===a&&(Zb=d);var c=d-Zb;0>c&&(c=d+1440-Zb);zf[a]=c;ha("times s="+d+"  min="+zf[a])}Zb+=te;1440<=Zb&&(Zb-=1440);0>Zb&&(Zb+=1440);ha("Starting minute = "+Zb)}function ic(b,a){if(0!=b)for(var d=0;d<b;d++)0==C[Fa[d].overlay].isGhost&&(C[Fa[d].overlay].parentNode.style.visibility=a)}function Ua(){0!=ub?ic(ub,"visible"):0!=eh&&ic(eh,"hidden");sc=!0;Ka()}function wd(b,a){jd||(nb.height=a,nb.width=
b,nc.height=a,nc.width=b,Rd.height=a,Rd.width=b,Ae.height=a,Ae.width=b,Sd=Ae.getContext("2d"),S=b,Y=a,Be=S/2-100,Ce=Y/2-10,u=1*na/S,r=1*ia/Y,fh&&(fh=!1,null!=gh&&gh()),Wa.style.height=Y+"px",Wa.style.width=S+"px",tc.style.height=Y+"px",tc.style.width=S+"px",kd.style.height=Y+"px",kd.style.width=S+"px",je(v,!1))}function Ye(){for(var b=0,a={},d=0;d<v;a={ii:a.ii},d++){a.ii=d;var c=null==da?ta[d]:ta[d].substring(ta[d].lastIndexOf("/")+1);(c=hh.file(c))?c.async("arraybuffer").then(function(a){return function(c){c=
new Blob([c]);uc[a.ii]=URL.createObjectURL(c);b++;b>=v&&xd()}}(a),function(a){return function(){uc[a.ii]=null;b++;b>=v&&xd()}}(a)):(uc[a.ii]=null,b++,b>=v&&xd())}}function xd(){var b=0;if(0==ba)jc();else for(var a=0;a<v;a++){vc[a]=[];for(var d={},c=0;c<ba;d={ii:d.ii,jj:d.jj},c++){d.ii=a;d.jj=c;var h=null==Tb&&null==da?ea[a][c]:ea[a][c].substring(ea[a][c].lastIndexOf("/")+1);(h=hh.file(h))?h.async("arraybuffer").then(function(a){return function(c){c=new Blob([c]);vc[a.ii][a.jj]=URL.createObjectURL(c);
b++;b>=v*ba&&jc()}}(d),function(a){return function(){vc[a.ii][a.jj]=null;b++;b>=v*ba&&jc()}}(d)):(vc[a][c]=null,b++,b>=v*ba&&jc())}}}function Ka(){if(Ic){var b=new XMLHttpRequest,a=null==gd?of:gd+of;pf||(a=a+"?"+Math.round(1E5*Math.random()));b.open("GET",a,!0);b.responseType="arraybuffer";uc=[];vc=[];b.addEventListener("progress",function(a){a.lengthComputable&&sa("Loading ZIP file",a.total,a.loaded)});b.onload=function(a){(new JSZip).loadAsync(this.response).then(function(a){hh=a;Ye()},function(){ha("Unable to read ZIP file: "+
of)})};b.send()}else jc()}function jc(){var b,a,d;void 0!=De&&De(!1);var c="?"+Math.round(1E4*Math.random()),h=[];h[0]=wc;for(b=1;b<v;b++)h[b]=b<=wc?b-1:b;Ga=Array(v);Cb=Ha=0;ih=ve;Af&&(jb.max=v);jd&&(ld||Fc)&&($b=[],Oa=[],Rc=[],Bf=[],Ee=[]);null!=Aa&&(Aa.selectedIndex=0);for(var e=0;e<v;e++){b=h[e];jd&&(ld||Fc)&&($b[b]=n("canvas"),Oa[b]=n("canvas"));Ga[b]=new Image;Ga[b].gotit=!1;Ga[b].frameNum=b;Ga[b].onerror=function(){Ha++};Ga[b].onload=function(){jd&&(ia=this.height,na=this.width,$a=ia,ab=na,
jd=!1,pg?kf?L.setWindowSize(y.offsetWidth,y.offsetHeight):wd(S,Y):wd(na,ia),Wg&&("auto"==rc&&(rc=(u+r)/2,Od=-1),$a/=rc,ab/=rc,0>Od&&(Od=na/2,Vg=ia/2),P=Math.round(Od-na/2/rc),M=Math.round(Vg-ia/2/rc),z=F=rc,1!=rc&&(ya=!1,L.toggleZooming())));Ic&&null!=uc[this.frameNum]&&URL.revokeObjectURL(uc[this.frameNum]);if(0<Fe&&!md){Cf.height=ia;Cf.width=na;Td=Cf.getContext("2d");Td.clearRect(0,0,S,Y);for(var b=0;b<Pa.length;b++){for(var e=Pa[b].ctx.getImageData(0,0,Pa[b].width,Pa[b].height).data,m=Td.getImageData(Pa[b].xmin,
Pa[b].ymin,Pa[b].width,Pa[b].height),f=3;f<e.length;f+=4)0!=e[f]&&(m.data[f]=b+1);Td.putImageData(m,Pa[b].xmin,Pa[b].ymin)}ya||(kb=!0);z==Ge&&(kb=!0);md=!0}if(sc){sc=!1;G=nb.getContext("2d");G.imageSmoothingEnabled=Fd;G.fillStyle="blue";G.font="bold 20px Arial";g=nc.getContext("2d");g.imageSmoothingEnabled=Fd;Qa=Array(v);je(v,!0);He&&!Ra?xa(wa(wc)):xa(wa(x));if(0<ba)for(K=Array(v),f=0;f<v;f++)for(d=h[f],K[d]=Array(ba),a=0;a<ba;a++)K[d][a]=new Image,K[d][a].gotit=!1,K[d][a].frameNum=d,K[d][a].overlayNum=
a,K[d][a].onerror=function(){Ha++},K[d][a].onload=function(){this.gotit=!0;var a=this.frameNum;Ha++;k();!qe||this.height==ia&&this.width==na?this.overlayNum==Hd-1&&(Qa[this.frameNum]=0):(this.gotit=!1,ha("Bad image size:"+this.src));if(Fc&&this.gotit&&this.overlayNum==ob)$b[a].height=this.height,$b[a].width=this.width,Ud=$b[a].getContext("2d"),Ud.drawImage(this,0,0),Bf[a]=Ud.getImageData(0,0,this.width,this.height).data,Oa[a].height=this.height,Oa[a].width=this.width,Rc[a]=Oa[a].getContext("2d"),
Rc[a].drawImage(this,0,0),Ee[a]=Rc[a].getImageData(0,0,this.width,this.height),K[a][this.overlayNum]=null,K[a][this.overlayNum]=Oa[a],K[a][this.overlayNum].gotit=!0;else if(this.gotit&&C[this.overlayNum].hotspotIndex){var b=n("canvas");b.height=this.height;b.width=this.width;var c=b.getContext("2d");c.drawImage(this,0,0);var d=c.getImageData(0,0,this.width,this.height).data,h=d.length;var e=this.overlayNum;var f;for(f=0;f<h;f+=4)if(0!=d[f]){0==lb&&(mb=[]);var m=d[f];var l=Math.floor(f/4/b.width);
c=Math.floor(f/4%b.width);mb[lb]=new zb(c,l,"spritefn",m,"pan",null,null,e,a,null);lb++}}else if(this.gotit&&tg&&(!mf||mf&&xg[this.overlayNum])){b=n("canvas");b.height=this.height;b.width=this.width;c=b.getContext("2d");c.drawImage(this,0,0);l=c.getImageData(0,0,this.width,this.height);d=l.data;h=d.length;for(f=0;f<h;f+=4)d[f]===ug&&d[f+1]===vg&&d[f+2]===wg&&(d[f+3]=0);c.putImageData(l,0,0);K[a][this.overlayNum]=null;K[a][this.overlayNum]=b;K[a][this.overlayNum].gotit=!0}this.gotit&&lf[this.overlayNum]?
(Df.clearRect(0,0,S,Y),Df.drawImage(K[a][this.overlayNum],0,0,S,Y)):this.gotit&&rg[this.overlayNum]&&null!=I&&(b=n("canvas"),b.height=ia,b.width=na,8>I.length&&(I[4]=0,I[5]=0,I[6]=na,I[7]=ia),c=b.getContext("2d"),c.imageSmoothingEnabled=sg,c.drawImage(this,I[0],I[1],I[2],I[3],I[4],I[5],I[6],I[7]),K[a][this.overlayNum]=null,K[a][this.overlayNum]=b,K[a][this.overlayNum].gotit=!0,null!=pb&&pb[this.overlayNum]&&(K[a][this.overlayNum].origImage=this));Ic&&null!=vc[a][this.overlayNum]&&URL.revokeObjectURL(vc[a][this.overlayNum])},
b=ea[d][a],void 0!=Gd[a+1]&&(b=Gd[a+1],b>=v&&(b=v-1),b=ea[b][a]),void 0==Vd||Vd[a]||(b+=c),K[d][a].src=b,K[d][a].src=Ic&&(ue||vc[d][a])?vc[d][a]:b,Cb++;if(null!=Sc)for(ac=[],a=0;a<Sc.length;a++)ac[a]=new Image,ac[a].gotit=!1,ac[a].onerror=function(a){Ha++},ac[a].onload=function(a){a.currentTarget.gotit=!0;Ha++;k()},ac[a].src=Sc[a],Cb++;if(null!=Ia&&0<Ia.length)for(ua=[],a=0;a<Ia.length;a++)if(void 0!=Ia[a])for(ua[a]=[],d=0;d<Ia[a].length;d++)for(ua[a][d]=[],f=0;f<v;f++)Uh(Ia[a][d],"/")?(b=ea[f][a].lastIndexOf("/"),
b=ea[f][a].substring(0,b+1)+Ia[a][d]+ea[f][a].substring(b+1),ua[a][d][f]=new Image,ua[a][d][f].gotit=!1,ua[a][d][f].onerror=function(a){Ha++;k()},ua[a][d][f].onload=function(a){a.currentTarget.gotit=!0;Ha++;k()},ua[a][d][f].src=b,Cb++):0===f?(ua[a][d][0]=new Image,ua[a][d][0].gotit=!1,ua[a][d][0].onerror=function(a){Ha++;k()},ua[a][d][0].onload=function(a){a.currentTarget.gotit=!0;Ha++;k()},ua[a][d][0].src=Ia[a][d],Cb++):ua[a][d][f]=ua[a][d][0]}!qe&&0!=this.height&&0!=this.width||this.height==ia&&
this.width==na?(this.gotit=!0,0==Hd&&(Qa[this.frameNum]=0)):(this.gotit=!1,ha("Image has invalid size:"+this.src));ld&&this.gotit&&(f=this.frameNum,$b[f].height=this.height,$b[f].width=this.width,Ud=$b[f].getContext("2d"),Ud.drawImage(this,0,0),Bf[f]=Ud.getImageData(0,0,this.width,this.height).data,Oa[f].height=this.height,Oa[f].width=this.width,Rc[f]=Oa[f].getContext("2d"),Rc[f].drawImage(this,0,0),Ee[f]=Rc[f].getImageData(0,0,this.width,this.height),Ga[f]=null,Ga[f]=Oa[f],Ga[f].gotit=!0);Ha++;k();
Gg||L.resetZoom();Tc=!0;Vh||(Vh=!0,Ba=!1,Wh());H(Ra)};var m=ta[b];void 0!=Gd[0]&&(m=Gd[0],m>=v&&(m=v-1),m=ta[m]);qf||(m+=c);Ga[b].src=Ic&&(ue||uc[b])?uc[b]:m;Cb++}Uc=Db=!1;X()}function fa(b,a,d,c,h,f){b.label_on=d;b.label_off=c;hb&&(b.className=f);d=null;c=e[a+"_labels"];null==c&&(c=e[a+"_label"]);null!=c&&(c=c.split(","),b.label_on=c[0].trim(),1<c.length&&(b.label_off=c[1].trim()),2<c.length&&(d="width:"+c[2].trim()+"px;"));null!=h&&(b.title=h);b.innerHTML=b.label_on;h=a=c=e[a+"_style"];null!=c&&
(c=c.split("&"),1<c.length&&(a=c[0],h=c[1]));b.style_on=(null!=d?d:"")+xc+a;b.style_off=(null!=d?d:"")+xc+h;null!=b.style_on&&1<b.style_on.length?b.setAttribute("style",b.style_on):(b.style_on=null,b.style_off=null)}function ie(b,a){xc=e.buttons_style;null==xc&&(xc="");var d=null,c=null;d=a?e.controls_tooltip:e.bottom_controls_tooltip;var h=b.split(",");if(null!=d){var f=d.split(",");f.length!=h.length&&(ha("!!! Number of tooltips must equal number of controls!"),f=d=null)}for(b=0;b<h.length;b++){var m=
null!=d?f[b]:null;var l=h[b].trim();c=l.indexOf("/");if(0===c||0===b){0===c&&(l=l.substring(1));D=n("div");D.align=Cd;var g=e.controls_style;null!=g?D.setAttribute("style",g):D.setAttribute("style","position:relative;padding:2px;width:100%;");a?(y.insertBefore(D,Wa),Ef=D):(g=e.bottom_controls_style,null!=g&&D.setAttribute("style",g),y.appendChild(D),Ff=D)}"enhance"==l.trim()&&(Aa=n("select"),c=e.enhance_style,null!=c&&Aa.setAttribute("style",c),null!=m&&(Aa.title=m),c=n("option"),c.innerHTML="Pick Enhancement",
c.value=-1,Aa.add(c),Aa.addEventListener("change",L.doEnhance,!1),ld=!Fc,Aa.disabled=ld?!1:!0,D.appendChild(Aa));"startstop"==l&&(Bb=n("button"),fa(Bb,"startstop","Start","Stop",m,"startstop start"),Bb.addEventListener("click",L.toggleIsLooping,!1),D.appendChild(Bb));"looprock"==l&&(Wd=n("button"),fa(Wd,"looprock","Rock","Loop",m,"looprock rock"),Gf=1,Wd.addEventListener("click",L.toggleLoopRock,!1),D.appendChild(Wd));"extrap"==l&&(bc=n("button"),fa(bc,"extrap","Enable Extrap","Disable Extrap",m,
"extrap"),bc.addEventListener("click",L.toggleExtrap,!1),D.appendChild(bc));E(l,"location")&&(nd=n("button"),fa(nd,"location","Show Loc","Hide Loc",m,"location"),0<l.indexOf("/on")?(J(nd,!1,"location off"),od=!0,Ca.push(y.style.cursor),y.style.cursor=oe):(od=!1,y.style.cursor=Ca.pop()),nd.addEventListener("click",function(){(od=!od)?(J(nd,!1,"location off"),Ca.push(y.style.cursor),y.style.cursor=oe):(J(nd,!0,"location on"),y.style.cursor=Ca.pop());X()},!1),D.appendChild(nd));"distance"==l&&(cc=n("button"),
fa(cc,"distance","Show dist","Hide dist",m,"distance"),mc=ne=!1,cc.addEventListener("click",function(){(mc=!mc)?(J(cc,!1,"distance off"),Ca.push(y.style.cursor),y.style.cursor=bf):(J(cc,!0,"distance on"),y.style.cursor=Ca.pop())},!1),D.appendChild(cc));E(l,"probe")&&(pd=n("button"),fa(pd,"probe","Show probe","Hide probe",m,"probe"),0<l.indexOf("/on")?(J(pd,!1,"probe off"),Ob=!0,Ca.push(y.style.cursor),y.style.cursor=pe):(Ob=!1,y.style.cursor=Ca.pop()),pd.addEventListener("click",function(){(Ob=!Ob)?
(J(pd,!1,"probe off"),Ca.push(y.style.cursor),y.style.cursor=pe):(J(pd,!0,"probe on"),y.style.cursor=Ca.pop())},!1),D.appendChild(pd));"mark"==l&&(Vc=n("button"),fa(Vc,"mark","Mark","Stop Mark",m,"mark"),Xd=!0,Vc.addEventListener("click",function(){vb=!vb;oa=[];vb?(qd=0,J(Vc,!1,"mark off"),null!=za&&(za.disabled=!0),Ca.push(y.style.cursor),y.style.cursor=cf):(J(Vc,!0,"mark on"),null!=za&&(za.disabled=!1),qd=-1,y.style.cursor=Ca.pop());X()},!1),Xh=new fb("black","white",tf,"black",20,5,5),jh=new fb("black",
"white",tf,"black",20,5,5),D.appendChild(Vc));"refresh"==l&&(ye=n("button"),fa(ye,"refresh","Refresh",null,m,"refresh"),ye.addEventListener("click",L.reloadFOF,!1),D.appendChild(ye));"restore"==l&&(Hf=n("button"),fa(Hf,"restore","Restore",null,m,"restore"),Hf.addEventListener("click",function(a){for(a=0;a<C.length;a++)C[a].checked=C[a].restorableState;for(a=0;a<C.length;a++)La(a)},!1),D.appendChild(Hf));"setframe"==l&&(jb=n("input"),hb&&(jb.className="setframe"),jb.type="range",jb.min=1,jb.max=100,
jb.value=1,Ie="Frame #*",null!=m&&(jb.title=m),g=e.setframe_label,null!=g&&(Ie=g),Yd=n("span"),Yd.innerHTML=Ie.replace("*",1),c="display:block;vertical-align:middle;"+e.setframe_style,jb.setAttribute("style",c),c=n("span"),c.setAttribute("style","display:inline-block;vertical-align:top;"),Yd.setAttribute("style","display:block;vertical-align:middle;"+e.setframe_label_style),c.appendChild(Yd),c.appendChild(jb),D.appendChild(c),jb.addEventListener("input",function(a){H(!1);a=parseInt(jb.value,10)-1;
0<=Qa[a]&&(xa(a),Yd.innerHTML=Ie.replace("*",x+1));W()},!1),Af=!0);"framelabel"==l&&(Ja=n("button"),hb&&(Ja.className="framelabel"),Ja.innerHTML="",null!=m&&(Ja.title=m),bb=null,g=e.frame_labels,null!=g&&(bb=g.split(","),Ja.innerHTML=bb[0]),c=xc+e.framelabel_style,null!=c&&Ja.setAttribute("style",c),c=e.framelabel_position,null!=c&&(c=c.split(","),Ja.style.position="absolute",Ja.style.left=y.offsetLeft+parseInt(c[0],10)+"px",Ja.style.top=y.offsetTop+parseInt(c[1],10)+"px"),D.appendChild(Ja));if("autorefresh"==
l||"autorefresh/off"==l)null!=Dc&&clearInterval(Dc),Lc=n("button"),fa(Lc,"autorefresh","Disable Auto Refresh","Enable Auto Refresh",m,"autorefresh"),Lc.addEventListener("click",L.toggleAutoRefresh,!1),Ed=!1,D.appendChild(Lc),"autorefresh"==l?L.toggleAutoRefresh():J(Lc,!1,"autotoggle off");"backward"==l&&(rb=n("button"),fa(rb,"backward","<","<",m,"step back"),rb.addEventListener("click",function(){H(!1);Ab(-1);W()},!1),D.appendChild(rb));"forward"==l&&(sb=n("button"),fa(sb,"forward",">",">",m,"step forward"),
sb.addEventListener("click",function(){H(!1);Ab(1);W()},!1),D.appendChild(sb));if("step"==l){c=e.step_labels;var k=null!=c?c.split(","):["<",">"];rb=n("button");hb&&(rb.className="step back");rb.innerHTML=k[0];rb.addEventListener("click",function(){H(!1);Ab(-1);W()},!1);c=xc+e.step_style;null!=c&&rb.setAttribute("style",c);null!=m&&(rb.title=m);D.appendChild(rb);sb=n("button");hb&&(sb.className="step forward");sb.innerHTML=k[1];sb.addEventListener("click",function(){H(!1);Ab(1);W()},!1);null!=c&&
sb.setAttribute("style",c);null!=m&&(sb.title=m);D.appendChild(sb)}"first"==l&&(Eb=n("button"),fa(Eb,"first","|<","|<",m,"firstlast first"),Eb.addEventListener("click",function(){H(!1);xa(wa(0));W()},!1),D.appendChild(Eb));"last"==l&&(Fb=n("button"),fa(Fb,"last",">|",">|",m,"firstlast last"),Fb.addEventListener("click",function(){H(!1);xa(wa(v-1));W()},!1),D.appendChild(Fb));"firstlast"==l&&(c=e.firstlast_labels,k=null!=c?c.split(","):["<<",">>"],Eb=n("button"),hb&&(Eb.className="firstlast"),Eb.innerHTML=
k[0],Eb.addEventListener("click",function(){H(!1);xa(wa(0));W()},!1),c=xc+e.firstlast_style,null!=c&&Eb.setAttribute("style",c),null!=m&&(Eb.title=m),D.appendChild(Eb),Fb=n("button"),hb&&(Fb.className="firstlast"),Fb.innerHTML=k[1],Fb.addEventListener("click",function(){H(!1);xa(wa(v-1));W()},!1),null!=c&&Fb.setAttribute("style",c),null!=m&&(Fb.title=m),D.appendChild(Fb));"setspeed"==l?(Gb=n("input"),hb&&(Gb.className="setspeed"),Gb.type="range",Gb.min=Ub,Gb.max=Kc,Gb.value=Kc-ib,null!=m&&(Gb.title=
m),c="vertical-align:middle;"+e.setspeed_style,Gb.setAttribute("style",c),Gb.addEventListener("input",function(a){ib=Kc-parseInt(Gb.value,10)+30;H(!0);W()},!1),D.appendChild(Gb)):"speed"==l&&(c=e.speed_labels,k=null!=c?c.split(","):["-","+"],Vb=n("button"),hb&&(Vb.className="speed slower"),Vb.innerHTML=k[0],Vb.addEventListener("click",function(){ib+=sf;Wb.disabled=!1;ib>Kc&&(ib=Kc,Vb.disabled=!0)},!1),c=xc+e.speed_style,null!=c&&Vb.setAttribute("style",c),null!=m&&(Vb.title=m),D.appendChild(Vb),Wb=
n("button"),hb&&(Wb.className="speed faster"),Wb.innerHTML=k[1],Wb.addEventListener("click",function(){ib-=sf;Vb.disabled=!1;ib<Ub&&(ib=Ub,Wb.disabled=!0)},!1),null!=c&&Wb.setAttribute("style",c),null!=m&&(Wb.title=m),D.appendChild(Wb));"zoom"==l&&(za=n("button"),fa(za,"zoom","Zoom","Un-zoom",m,"zoom off"),za.addEventListener("click",L.toggleZooming,!1),D.appendChild(za),ya=!1);if("annotate"==l){Zd=n("button");fa(Zd,"annotate","Annotate","Finished",m,"annotate");ka=n("div");ka.setAttribute("style",
"position:absolute;box-sizing:content-box;height:120px;width:180px;top:20px;left:20px;z-index:15;visibility:hidden;background-color:lightgray;border-width:6px;border-style:solid;border-color:magenta;border-radius:25px;padding:10px;font:normal normal normal 16px Arial;color:black;");ka.title="Drag this box around.  Select attributes, then go onto the image and click & drag";Wc=Xc=20;Je=Hb=!1;kh=3;lh=11;Yc=$d=0;p=[];ka.style["touch-action"]="none";var q=function(a){Xc=a.clientX-Yc;Wc=a.clientY-$d;ka.style.top=
Wc+"px";ka.style.left=Xc+"px"};ka.addEventListener("mousedown",function(a){if(0!=a.clientX||0!=a.clientY)Je=!0,Yc=a.clientX-Xc,$d=a.clientY-Wc},!1);ka.addEventListener("mouseup",function(a){Je=!1},!1);ka.addEventListener("mouseout",function(a){Je&&q(a)},!1);ka.addEventListener("mousemove",function(a){Je&&q(a)},!1);window.PointerEvent?(ka.addEventListener("pointerdown",function(a){"mouse"!=a.pointerType&&(Yc=a.clientX-Xc,$d=a.clientY-Wc)},!1),ka.addEventListener("pointermove",function(a){"mouse"!=
a.pointerType&&(0==Yc&&(Yc=a.clientX,$d=a.clientY),q(a))},!1)):ka.addEventListener("touchmove",function(a){a=a.changedTouches[0];0==Yc&&(Yc=a.clientX,$d=a.clientY);q(a)},!1);Zd.addEventListener("click",function(){if(Hb=!Hb){p=[];Xc=y.offsetLeft;Wc=y.offsetTop;var a=e.annotate_position;null!=a&&(a=a.split(","),Xc+=parseInt(a[0],10),Wc+=parseInt(a[1],10));ka.style.top=Wc+"px";ka.style.left=Xc+"px";ka.style.visibility="visible";J(Zd,!1,"annotate off");Yh=ya;ya=!1;null!=za&&(za.disabled=!0)}else ka.style.visibility=
"hidden",J(Zd,!0,"annotate on"),ya=Yh,null!=za&&(za.disabled=!1);X()},!0);ae=mh("Color Black White Red Green Blue Yellow Orange Cyan Magenta".split(" "),"black black white red green blue yellow orange cyan magenta".split(" "),function(a){});yc=mh("Width 1 2 3 4 5 6 7 8 10 12 14 16 18 20 24 28 32 36 38".split(" "),[1,1,2,3,4,5,6,7,8,10,12,14,16,18,20,24,28,32,36,38],function(a){6==be.selectedIndex?lh=yc.selectedIndex:kh=yc.selectedIndex});yc.title="Select width or font size";be=mh("Type Arrow Circle Box Polygon Draw Text".split(" "),
[-1,0,1,2,3,4,5],function(a){6==be.selectedIndex?(Ib.focus(),Ib.select(),yc.selectedIndex=lh):yc.selectedIndex=kh;0==ae.selectedIndex&&(ae.selectedIndex=2)});c=n("button");c.style.width="70px";c.style.margin="5px";c.innerHTML="Erase";c.title="Erase last item";c.addEventListener("click",function(){0<p.length&&(p.pop(),X())},!1);Ib=n("input");Ib.type="text";Ib.style.width="150px";Ib.style.margin="5px";Ib.title="Enter your text here, then click where you want it";Ib.value="Text input";k=e.annotate_defaults;
null!=k&&(k=k.split(","),be.selectedIndex=parseInt(k[0],10),1<k.length&&(ae.selectedIndex=parseInt(k[1],10)),2<k.length&&(yc.selectedIndex=parseInt(k[2],10)),3<k.length&&(Ib.value=k[3].trim()));k=n("div");k.innerHTML="Annotation Tools";var Ea=n("div");Ea.appendChild(be);Ea.appendChild(ae);var t=n("div");t.appendChild(yc);t.appendChild(c);c=n("div");c.appendChild(Ib);ka.appendChild(k);ka.appendChild(Ea);ka.appendChild(t);ka.appendChild(c);D.appendChild(Zd);y.appendChild(ka)}"saveall"==l&&(If=n("button"),
fa(If,"saveall","SaveAll","SaveAll",m,"saveall"),nh=e.saveall_prompt,dc=e.saveall_filename,c=e.saveall_list,oh=null==c?["0"]:c.split(","),If.addEventListener("click",function(){for(var a=0;a<oh.length;a++)for(var b=parseInt(oh[a],10),c=0;c<ta.length;c++){0===c&&null!=nh&&(dc=window.prompt(nh,dc),null!=dc&&1>dc.length&&(dc=null));var d=null==dc?"":-1!=dc.indexOf("#")?dc.replace("#",c.toString()):dc+c;var h=document.createElement("a");h.href=0==b?ta[c]:ea[c][b-1];h.download=d;d=new MouseEvent("click");
h.dispatchEvent(d)}},!1),D.appendChild(If));if("capture"==l){Jf=n("button");fa(Jf,"capture","Capture","Capture",m,"capture");var w=e.capture_prompt;Kf=e.capture_filename;null==Kf&&(Kf="haimage.png");Jf.addEventListener("click",function(){var a=Kf;if(null!=w&&(a=window.prompt(w,a),null==a))return;var b=n("canvas");b.height=nb.height;b.width=nb.width;var c=b.getContext("2d");Xd=!1;X();c.drawImage(nb,0,0);c.drawImage(nc,0,0);Xd=!0;b.toBlob(function(b){var c=URL.createObjectURL(b),d=document.createElement("a");
d.href=c;d.download=a;c=new MouseEvent("click");d.dispatchEvent(c);setTimeout(function(){URL.revokeObjectURL(b)},3E4)})},!1);D.appendChild(Jf)}"show"==l&&(Lf=n("button"),fa(Lf,"show","Show","Show",m,"show"),Mf=e.show_prompt,Zh=e.show_image_file,null==Mf&&(Mf="Right-click to save or copy the image<br> <font size='-1'>(to save in some browsers, you may need to first 'Open in New Tab')</font> <p>"),Lf.addEventListener("click",function(){if(Zh)window.open(ta[x]);else{var a=nb.toDataURL("image/png;base64;");
var b=window.open();b.document.write(Mf+"<img src="+a+"></img>")}},!1),D.appendChild(Lf));"toggle"==l&&(Qa=[],c=e.toggle_size,null!=c?(c=c.split(","),rd=parseInt(c[0],10),Ke=parseInt(c[1],10),Le=parseInt(c[2],10)):(Ke=rd=10,Le=3),ph="red",qh="blue",rh="orange",sh=!1,E(e.toggle_layout_width,"t")&&(sh=!0),c=e.toggle_colors,null!=c&&(c=c.split(","),qh=c[0].trim(),ph=c[1].trim(),rh=c[2].trim()),wb=n("div"),wb.setAttribute("style","position:relative;border:0px;margin:0px;padding:0px;-webkit-user-select:none; -moz-user-select:none; -ms-user-select:none; user-select:none; -webkit-tap-heightlight-color:transparent;"),
wb.style.backgroundColor=D.style.backgroundColor,wb.align=Cd,th=new PEvs(wb,null,null,null,null,L.togclick,null),Zc=n("canvas"),Zc.height=2*Ke,Nf=Zc.getContext("2d"),wb.appendChild(Zc),a?y.insertBefore(wb,Wa):y.appendChild(wb),c=e.toggle_onoff,Me=null,null!=c&&(Me=c.split(",")),Of=!0,null!=m&&(wb.title=m));if("overlay"==l){C=[];l=e.overlay_tooltip;m=null;null!=l&&(m=l.split(","));l=e.overlay_radio;c=null;null!=l&&(c=l.split(","));Ea=e.overlay_labels_color;k=null;null!=Ea&&(k=Ea.split(","));Vd=[];
t=e.overlay_caching;Ea=null;null==t&&(t=e.overlay_static);null!=t&&(Ea=t.split(","));var B=!0;null!=e.overlay_nonewdiv&&(B=!1);for(t=0;t<Rb.length;t++){var r=Rb[t].trim();if(0==t||0==r.indexOf("/"))0==r.indexOf("/")&&(r=r.substr(1)),B?(Jb=n("div"),uh++,Jb.align="center",a?y.insertBefore(Jb,Wa):y.appendChild(Jb)):(Jb=n("span"),D.appendChild(Jb)),g=e.overlay_labels_style,null!=g&&Jb.setAttribute("style",g);var u=!1;g=r.length;0<r.indexOf("/on")&&r.indexOf("/on")==g-3&&(u=!0,r=r.substr(0,g-3));var A=
!1;0<r.indexOf("/always")&&r.indexOf("/always")==g-7&&(A=u=!0);var F=!1;0<r.indexOf("/hidden")&&(F=!0);var z=!1;0<r.indexOf("/hotspots")&&(z=!0,r=r.substr(0,r.indexOf("/")));null!=Ea?E(Ea[t],"y")||E(Ea[t],"t")?Vd[t]=!0:Vd[t]=!1:Vd[t]=!0;C[t]=n("input");C[t].type="checkbox";C[t].value=r;C[t].id=r;C[t].showMe=!(A&F)&!z;var G="vertical-align:middle;";g=e.checkbox_style;null!=g&&(G+=g);C[t].setAttribute("style",G);C[t].checked=u;C[t].restorableState=u;C[t].name=0;C[t].hotspotIndex=z;null!=Aa&&t==ob&&
C[t].checked&&(Aa.disabled=!1);null!=pc&&!pc[t]&&u&&(cd=!1);C[t].addEventListener("click",L.overClick,!1);null!=l&&(g=c[t].indexOf("/"),-1!=g&&(C[t].name=c[t].substr(g+1).trim()),E(c[t],"t")&&(C[t].type="radio",-1==g&&(C[t].name="all")));C[t].isGhost=!0;A||F||(null!=m&&(C[t].title=m[t]),g=n("label"),g.htmlFor=r,null!=m&&(g.title=m[t]),g.innerHTML=r,g.name=C[t].name,r="vertical-align:middle;",null!=k&&(r=r+"color:"+k[t]+";"),g.setAttribute("style",r),r=n("span"),A="10",null!=re&&(A=10+re[t]),r.setAttribute("style",
"margin-left:"+A+"px;"),r.appendChild(C[t]),r.appendChild(g),Jb.appendChild(r),C[t].isGhost=!1)}if(null==Sb)for(Sb=Array(Rb.length),t=0;t<Rb.length;t++)Sb[t]=0;else for(t=0;t<Rb.length;t++)La(t)}}Ra=!0;He=null;g=e.start_looping;null!=g&&(c=g.split(","),E(c[0],"f")&&(Ra=!1),1<c.length&&(wc=parseInt(c[1],10)-1,isNaN(wc)&&(wc=0),x=wc),2<c.length&&(E(c[2],"t")&&(He=!0),E(c[2],"f")&&(He=!1)));H(Ra)}function La(b){var a;if(0>Sb[b]){var d=!1;for(a=0;a<Rb.length;a++)Sb[a]!=-Sb[b]||d||(d=C[a].checked);C[b].checked=
d}}function Lb(b){0==lb&&(mb=[]);b=b.substr(b.indexOf("=")+1).trim().split(",");var a=b[4].trim(),d=b[4].indexOf("/"),c=b[4].indexOf("?"),h=-1,f=-1;-1!=d&&(h=parseInt(b[4].substring(d+1),10)-1,a=a.substring(0,d));-1!=c&&(f=parseInt(b[4].substring(c+1),10)-1,c<d||-1==d)&&(a=a.substring(0,c));mb[lb]=new zb(parseInt(b[0].trim(),10),parseInt(b[1].trim(),10),b[2].trim(),b[3].trim(),a.toLowerCase(),b[5].trim().toLowerCase(),b[6].trim(),h,f,8==b.length?b[7].trim():null);lb+=1}function Ac(b){0==Fe&&(Pa=[],
pa=null);var a=b.substr(b.indexOf("=")+1).trim().split("(");b=a[0].split(",");var d=b[0].trim();0==d.indexOf("0x")&&(d="#"+d.substring(2));Pa[Fe]=new Ma(d,b[1].trim(),b[2].trim(),b[3].trim(),a[1].trim());Fe+=1}function ad(b){0==ub&&(Fa=[]);b=b.substr(b.indexOf("=")+1).trim().split(",");Fa[ub]=new kc(parseInt(b[0],10)-1,parseInt(b[1],16),b[2].trim(),b[3].trim(),5==b.length?b[4].trim():"Click for details");ub+=1}function Ma(b,a,d,c,h){this.color=b;this.alpha=1;7<this.color.length&&(this.alpha=parseInt(this.color.substring(7),
16)/255,this.color=this.color.substring(0,7),.1>this.alpha&&(this.alpha=.1));this.action=a;this.value=d;this.tip=c;this.poly=h;b=h.split(",");this.xy=[];this.ymin=this.xmin=9999;for(a=this.ymax=this.xmax=0;a<b.length;a++)this.xy[a]=parseInt(b[a].trim(),10),0==a%2?(this.xy[a]<this.xmin&&(this.xmin=this.xy[a]),this.xy[a]>this.xmax&&(this.xmax=this.xy[a])):(this.xy[a]<this.ymin&&(this.ymin=this.xy[a]),this.xy[a]>this.ymax&&(this.ymax=this.xy[a]));this.height=this.ymax-this.ymin+1;this.width=this.xmax-
this.xmin+1;this.can=n("canvas");this.can.height=this.height;this.can.width=this.width;this.ctx=this.can.getContext("2d");this.ctx.imageSmoothingEnabled=!1;this.ctx.fillStyle=this.color;this.ctx.globalAlpha=this.alpha;this.ctx.beginPath();this.ctx.moveTo(this.xy[0]-this.xmin,this.xy[1]-this.ymin);for(a=2;a<this.xy.length;a+=2)this.ctx.lineTo(this.xy[a]-this.xmin,this.xy[a+1]-this.ymin);this.ctx.closePath();this.ctx.fill()}function kc(b,a,d,c,h){this.overlay=b;this.color=a;this.action=d;this.value=
c;this.tip=h}function zb(b,a,d,c,h,f,e,g,k,q){this.x0=b;this.y0=a;this.icon=null;this.isIcon=!1;if("icon"==d)this.icon=new Image,this.icon.hotspot=this,Pf=!0,this.icon.onload=function(a){this.gotit=!0;this.hotspot.x1=this.hotspot.x0+this.width;this.hotspot.y1=this.hotspot.y0+this.height;this.hotspot.width=this.width;this.hotspot.height=this.height;this.hotspot.w2=this.width/2;this.hotspot.h2=this.height/2;this.hotspot.isIcon=!0;this.hotspot.origX=0;this.hotspot.origY=0},this.y1=this.x1=-1,this.zoomme=
this.fromfile=this.anim=!1,this.icon.gotit=!1,this.icon.src=c.trim();else if("sprite"==d||"spritefn"===d){this.x0=b;this.y0=a;this.inx=parseInt(c,10)-1;ce=!1;og?null!=ja&&(-1!=Pc?this.inx>=Pc&&this.inx<=Pc+ja.length&&(ce=!0):"spritefn"===d&&(ce=!0)):ce=!0;if(ce){-1!=Pc&&(this.inx-=Pc);if(this.inx>=ja.length)return null;this.x1=ja[this.inx].width+b;this.y1=ja[this.inx].height+a;this.width=ja[this.inx].width;this.height=ja[this.inx].height;this.w2=this.width/2;this.h2=this.height/2;this.origY=this.origX=
0;this.icon=ja[this.inx].cloneNode();this.anim=ja[this.inx].anim;this.fromfile=ja[this.inx].fromfile;this.zoomme=ja[this.inx].zoomme;this.anim&&(this.icon.setAttribute("style","position:absolute;top:0px;left:0px;visibility:hidden;"),tc.appendChild(this.icon))}else this.x1=Pb[this.inx]+b,this.y1=Qb[this.inx]+a,this.width=Pb[this.inx],this.height=Qb[this.inx],this.w2=Pb[this.inx]/2,this.h2=Qb[this.inx]/2,this.origX=gf[this.inx],this.origY=hf[this.inx],this.icon=ff,this.zoomme=this.fromfile=this.anim=
!1;Pf=this.isIcon=!0;this.icon.gotit=!0}else this.width=parseInt(d,10),this.height=parseInt(c,10),this.x1=this.width+b,this.y1=this.height+a,this.w2=this.width/2,this.h2=this.height/2;this.pan=h;this.isPan=!1;"pan"===this.pan&&(this.isPan=!0);this.action=f;this.value=e;this.overlay=g;this.frame=k;this.tip=q}function Va(){if(sd&&!id){T=-1;for(var b=0;b<ma.length;b++)z>=ma[b]&&(T=b)}}function Mb(){null!=Yb?cb=Yb.toLatLon(qa,ra):null!=yf?(cb[0]=yf+(Sh-yf)*ra/ia,cb[1]=dh+(Th-dh)*qa/na):(cb[0]=Math.round(qa),
cb[1]=Math.round(ra))}function Nb(b,a){"popup"==b.action?(null!=Qf&&Qf.close(),Qf=window.open("","HAniSPopup","scrollbars=yes,width="+Sg+",height="+Rg),Qf.document.write(Qg+b.value+"</div>")):"link"==b.action?(b=b.value,Mb(),b=b.replace("%LATITUDE%",cb[0].toFixed(4)),b=b.replace("%LONGITUDE%",cb[1].toFixed(4)),b=b.replace("%FRAMENUMBER%",x+1),window.open(b,"_blank","")):"fof"==b.action&&(da=Fg,L.resetZoom(),L.newFOF(b.value,!0),Xe(a))}function yd(){var b=Mg?Md/z:0;P+b<Md&&(P=Md-b);b=Og?Nd/z:0;P+ab-
b>na-Nd&&(P=na-ab+b-Nd);b=Kg?Ld/F:0;M+b<Ld&&(M=Ld-b);b=Ig?Kd/F:0;M+$a-b>ia-Kd&&(M=ia-$a-Kd+b);M=Math.round(M);P=Math.round(P)}function zd(b){var a=!1;b?id?(T--,0>T?a=!0:(z=ma[T],F=ma[T])):(z-=.1*hd/u,F-=.1*hd/r):id?(T++,T>=ma.length?(T--,rf&&(a=!0)):(z=ma[T],F=ma[T])):(!rf||z!==Jc&&F!==Jc||(a=!0),z+=.1*hd/u,F+=.1*hd/r,z>Jc&&(z=Jc),F>Jc&&(F=Jc));a||z<=Ge||F<=Ne?(z=Ge,F=Ne,T=-1,qa=A,ra=B,M=P=0,$a=ia,ab=na,Md=Nd=Ld=Kd=0,md&&(kb=!0)):(Kd=Hg,Ld=Jg,Nd=Ng,Md=Lg,P=qa-A/z,M=ra-B/F,$a=Math.floor(ia/F),ab=Math.floor(na/
z),yd(),md&&(kb=!1));Va()}function Bc(){Oe=0;Kb=Array(2);xb=Array(2);td=Array(2);Sa=0;fd=null;xa(wa(0))}function H(b){Ba=!b;L.toggleIsLooping()}function Ad(b,a,d,c,h,f){Sd.clearRect(0,0,S,Y);Sd.imageSmoothingEnabled=Fd;G.imageSmoothingEnabled=Fd;Sd.drawImage(b,a,d,c,h,0,0,S,Y);vh=Sd.getImageData(0,0,S,Y);$c=vh.data;Rf=Xa[f];Sf=Ya[f];Tf=Za[f];Uf=Qd[f];$h=4*S*Y;for(ec=0;ec<$h;ec+=4)db=$c[ec],db===$c[ec+1]&&db===$c[ec+2]&&($c[ec]=Rf[db],$c[ec+1]=Sf[db],$c[ec+2]=Tf[db],$c[ec+3]=Uf[db]);Sd.putImageData(vh,
0,0);G.drawImage(Ae,0,0,S,Y)}function J(b,a,d){null!=b&&(a?(null!=b.style_on&&b.setAttribute("style",b.style_on),b.innerHTML=b.label_on):(null!=b.style_off&&b.setAttribute("style",b.style_off),b.innerHTML=b.label_off),hb&&(b.className=d))}function gb(b,a){if(!(b>=v)&&(-2==Qa[b]&&(a=-2),Qa[b]=a,Af&&1==a&&(jb.value=b+1,Yd.innerHTML=Ie.replace("*",b+1)),Of)){b=wh+b*(rd+Le);var d=rh;0==a?d=qh:-1==a?d=ph:-2==a&&(d=qg);Nf.fillStyle=d;Nf.fillRect(b,Ke/2,rd,Ke)}}function je(b,a){Of&&(Zc.width=sh?parseInt(y.style.width,
10):S,Nf.clearRect(0,0,Zc.width,Zc.height),wh=Zc.width/2-b*(rd+Le)/2);for(var d=0;d<b;d++)a?-1!=Hd?gb(d,-2):null!=Me&&"n"==Me[d].toLowerCase().trim()?gb(d,-1):gb(d,0):gb(d,Qa[d])}function xa(b){gb(x,0);x=b;gb(x,1);null!=Ja&&null!=bb&&null!=bb[x]&&(Ja.innerHTML=bb[x]);void 0!=Pe&&Pe(x)}function wa(b){b>=v&&(b=v-1);if(0<=Qa[b])return b;var a=-1,d=b;0==d&&(a=1);for(var c=0;c<v-1;c++)if(d+=a,0<=Qa[d])return d;return b}function Ab(b){gb(x,0);var a=b;do 0<a?(a=wa(v-1),x+=1,x>a&&(de&&Ba?(x=a,b=-b):x=wa(0))):
(a=wa(0),--x,x<a&&(de&&Ba?(x=a,b=-b):x=wa(v-1))),a=b;while(0>Qa[x]);void 0!=Pe&&Pe(x);Gf=a;gb(x,1);null!=Ja&&null!=bb&&null!=bb[x]&&(Ja.innerHTML=bb[x])}function fb(b,a,d,c,h,f,e){this.bg=b;null!=b&&0==this.bg.indexOf("0x")&&(this.bg="#"+this.bg.substring(2));this.fg=a;null!=a&&0==this.fg.indexOf("0x")&&(this.fg="#"+this.fg.substring(2));this.font=d;this.fontHeight=Math.round(1.1*parseInt(d,10));this.scolor=c;null!=c&&0==this.scolor.indexOf("0x")&&(this.scolor="#"+this.scolor.substring(2));this.sblur=
h;this.sxoff=f;this.syoff=e}function Na(b,a,d,c,h){g.globalAlpha=1;g.font=b.font;var f=b.fontHeight;d=d-f-6;var e=g.measureText(c).width;1==h&&(a-=e);0==h&&(a-=e/2);5>a&&(a=5);5>d&&(d=5);d+f+3>Y&&(d=Y-f-6);a+3+e>S&&(a=S-e-6);g.save();g.beginPath();g.fillStyle=b.bg;null!=b.scolor&&(g.shadowColor=b.scolor,g.shadowBlur=b.sblur,g.shadowOffsetX=b.sxoff,g.shadowOffsetY=b.syoff);Qe=a-3;Vf=d;xh=e+6;Wf=f+6;g.fillRect(Qe,Vf,xh,Wf);g.closePath();g.restore();g.textBaseline="bottom";g.fillStyle=b.fg;g.fillText(c,
a,d+f+3)}function X(){g.clearRect(0,0,S,Y);Xf=!1;if(eb){g.beginPath();g.lineWidth=2;g.strokeStyle="white";var b=Sa;1<b&&(b=2);for(var a=0;a<b;a++)1<Sa&&(g.moveTo(Kb[0]/u,xb[0]/r),g.lineTo(Kb[1]/u,xb[1]/r)),g.moveTo(Kb[a]/u-15,xb[a]/r),g.lineTo(Kb[a]/u+15,xb[a]/r),g.moveTo(Kb[a]/u,xb[a]/r-15),g.lineTo(Kb[a]/u,xb[a]/r+15);g.closePath();g.stroke();if(3==Sa){var d=U,c=Q;g.moveTo(d,c);g.fillStyle=qc;g.fillRect(d-2,c-2,5,5);b=ud;a=Math.round(d+Re/u*ee*(ud-td[1]));for(var h=Math.round(c+fe/r*ee*(ud-td[1])),
f=0;300>f;f++){g.beginPath();g.lineWidth=1;g.strokeStyle=qc;g.moveTo(d,c);g.lineTo(a,h);g.stroke();g.beginPath();g.lineWidth=3;g.rect(a-2,h-2,5,5);g.stroke();if(3>a||a+3>S||3>h||h+3>Y)break;c=Zb+b;c=100*Math.floor(c/60)+c%60;c%=2400;Ag?(d="AM",1200<=c?(1300<=c&&(c-=1200),d="PM"):100>c&&(c+=1200),d=Math.floor(c/100)+":"+Math.floor(Math.floor(c%100)/10)+Math.floor(c%10)+" "+d):(d=c+" ",1E3>c&&(d="0"+c),100>c&&(d="00"+c),10>c&&(d="000"+c));c=0;Math.abs(Yf)<ed+5&&(c=45*.0174533);var e=h;0>yh*Yf&&0==c&&
(e=h+ed);g.font=Jd;d=d+" "+zg;var l=g.measureText(d).width;g.fillStyle=Id;0===c?(g.fillRect(a+2,e-ed-2+c,l+4,ed+3),g.fillStyle=qc,g.textBaseline="bottom",g.fillText(d,a+5,e)):(g.save(),g.translate(a+5,h),g.rotate(c),g.fillRect(2,-2,l+4,ed+3),g.fillStyle=qc,g.textBaseline="bottom",g.fillText(d,5,ed),g.restore());d=a;c=h;a=Math.round(d+ee*yh);h=Math.round(c+ee*Yf);b+=V}}null!=fd&&Na(nf,ai,bi,fd,0);Xd&&(Na(Nh,9999,Yg,Xg[Oe],0),zh=Qe,Ah=Vf,Bh=Vf+Wf)}if(vb){Xd&&(0==qd?Na(jh,9999,10,we[0],0):(Na(Xh,10,
10,we[1],0),ci=Qe+xh,Na(jh,9999,10,we[2],0)),di=Qe,ei=Wf);g.beginPath();g.lineWidth=2;g.strokeStyle=Zg;for(b=0;b<oa.length;b+=2)0==b?g.moveTo(oa[b]/u,oa[b+1]/r):g.lineTo(oa[b]/u,oa[b+1]/r);xe&4<oa.length&&g.lineTo(oa[0]/u,oa[1]/r);g.stroke();for(b=0;b<oa.length;b+=2)g.beginPath(),g.rect(oa[b]/u-2,oa[b+1]/r-2,5,5),g.stroke()}if(Hb)for(b=0;b<p.length;b++){a=p[b].type;g.beginPath();g.strokeStyle=p[b].color;g.lineWidth=p[b].width;if("0"==a)a=Math.atan2(p[b].xe-p[b].x,p[b].ye-p[b].y),h=p[b].x+p[b].width*
Math.sin(a),f=p[b].y+p[b].width*Math.cos(a),g.beginPath(),g.moveTo(h,f),g.lineTo(p[b].xe,p[b].ye),d=12+p[b].width/5,g.moveTo(h+d*Math.sin(a-.523599),f+d*Math.cos(a-.523599)),g.lineTo(h,f),g.lineTo(h+d*Math.sin(a+.523599),f+d*Math.cos(a+.523599));else if("1"==a)g.arc(p[b].x,p[b].y,p[b].size,0,2*Math.PI);else if("2"==a)g.rect(p[b].x-p[b].size,p[b].y-p[b].size,2*p[b].size,2*p[b].size);else if("3"==a){g.moveTo(p[b].xp[0],p[b].yp[0]);for(h=1;h<p[b].xp.length;h++)g.lineTo(p[b].xp[h],p[b].yp[h]);g.lineTo(p[b].xp[0],
p[b].yp[0])}else if("4"==a)for(g.moveTo(p[b].xp[0],p[b].yp[0]),h=1;h<p[b].xp.length;h++)g.lineTo(p[b].xp[h],p[b].yp[h]);else"5"==a&&(g.fillStyle=p[b].color,g.font=p[b].width+"pt arial",a=g.measureText(p[b].text).width,g.fillText(p[b].text,p[b].x-a/2,p[b].y+p[b].width/2));g.stroke()}Uc&&(b=Cc*(Se-ge)/z,a=me*(Te-he)/F,b=" "+Math.sqrt(b*b+a*a).toFixed(jg)+" "+ig+" ",Na(Lh,ge/u,he/r,b,-1),g.beginPath(),g.strokeStyle=kg,g.lineWidth=3,g.moveTo(Se/u,Te/r),g.lineTo(ge/u,he/r),g.stroke(),g.closePath());Db&&
Na(Eg,Ch,Dh,Eh,-1);if(Ob||od)if(U=la.getX(),A=U*u,Q=la.getY(),B=Q*r,0<=A&&0<=B){qa=P+A/z;ra=M+B/F;if(od){Mb();fi=fg+cb[0].toFixed(af)+"  "+gg+cb[1].toFixed(af);b=Q;if(Uc||Db)b=Q+hg.fontHeight+6;Na(hg,U+10,b,fi,-1)}if(Ob&&Mc&&Tc)if(qa=Math.round(qa),ra=Math.round(ra),df)Ta.clearRect(0,0,1,1),Ta.drawImage(Ga[x],qa,ra,1,1,0,0,1,1),R=Ta.getImageData(0,0,1,1).data,N=0,Bd(!1);else for(b=0;b<ba;b++)if(a=ba-b-1,K[x][a].gotit&&C[a].checked&&(a==ob||null!=oc[a]&&0<=oc[a])){Ta.clearRect(0,0,1,1);a==ob?Ta.drawImage($b[x],
qa,ra,1,1,0,0,1,1):Ta.drawImage(K[x][a],qa,ra,1,1,0,0,1,1);R=Ta.getImageData(0,0,1,1).data;N=oc[a];null!=N&&Bd(a==ob||ch);break}}!kb||eb||mc||Ob||null==pa||(g.drawImage(pa.can,0,0,pa.width,pa.height,pa.xmin/u,pa.ymin/r,pa.width/u,pa.height/r),Na(Eg,(pa.xmin+pa.xmax)/2/u,(pa.ymin+pa.ymax)/2/r,pa.tip,0),Xf=!0)}function Bd(b){Ue=999;fc=lg;var a=tb[N].length-1;if(0==R[3])fc=ze[N];else{if(mg)gc=R[0];else if(b)Zf=0,gc=R[0],Ue=0;else for(var d=0;d<a;d++)hc[0]=R[0]-Xa[N][d],0>hc[0]*(Xa[N][d+1]-R[0]-1)||(hc[1]=
R[1]-Ya[N][d],0>hc[1]*(Ya[N][d+1]-R[1]-1)||(hc[2]=R[2]-Za[N][d],0>hc[2]*(Za[N][d+1]-R[2]-1)||(vd=xf[N][d],$f=hc[vd]/Qc[N][d][vd],Fh=Math.abs(hc[Gh[vd]]-$f*Qc[N][d][Gh[vd]])+Math.abs(hc[Hh[vd]]-$f*Qc[N][d][Hh[vd]]),Fh<Ue&&(gc=d,Ue=Fh,Zf=$f))));if(999>Ue)fc=Oc[N][gc],-1!=Xb[N][gc]&&(Ih=tb[N][gc],0!=Zf&&(Ih+=Zf*(tb[N][gc+1]-tb[N][gc])),fc=fc+" "+Ih.toFixed(Xb[N][gc])+" "+Nc[N][gc]);else if(b||0<Dd){var c=-1;if(b)c=R[0];else for(d=0;d<a;d++)if(Math.abs(R[0]-Xa[N][d])<Dd&&Math.abs(R[1]-Ya[N][d])<Dd&&Math.abs(R[2]-
Za[N][d])<Dd){c=d;break}-1!=c&&(fc=Oc[N][c],-1!=Xb[N][c]&&(fc=fc+" "+tb[N][c].toFixed(Xb[N][c])+" "+Nc[N][c]))}}"hide"!=fc&&Na(Mh,U-10,Q,fc,1)}function W(){if(Tc)try{G.clearRect(0,0,S,Y);G.globalAlpha=1;if(!Pg)if(sd&&null!=ac&&0<=T&&ac[T].gotit)G.drawImage(ac[T],P*ma[T],M*ma[T],ab*ma[T],$a*ma[T],0,0,S,Y);else if(Ga[x].gotit&&(null!=jf?Ad(Ga[x],P,M,ab,$a,jf):G.drawImage(Ga[x],P,M,ab,$a,0,0,S,Y)),null!=Da&&(G.globalAlpha=1,Ga[x].gotit))for(var b=0;b<Da.length;b+=4)G.drawImage(Ga[x],Da[b],Da[b+1],Da[b+
2],Da[b+3],Da[b]/u,Da[b+1]/r,Da[b+2]/u,Da[b+3]/r);if(0<ba){for(b=0;b<ba;b++){var a=null!=Gc?Gc[b]:b;!lf[a]&&C[a].checked&&C[a].showMe&&(null!=se&&(G.globalAlpha=se[a]),sd&&0<=T&&null!=ua&&void 0!=ua[a]&&ua[a][T][x].gotit?G.drawImage(ua[a][T][x],P*ma[T],M*ma[T],ab*ma[T],$a*ma[T],0,0,S,Y):K[x][a].gotit&&(null==Hc||1===Hc[a]?null!=Ec&&0<=Ec[a]?Ad(K[x][a],P,M,ab,$a,Ec[a]):G.drawImage(K[x][a],P,M,ab,$a,0,0,S,Y):0===Hc[a]&&G.drawImage(K[x][a],0,0,na,ia,0,0,S,Y)))}if(null!=pb)for(G.globalAlpha=1,b=0;b<ba;b++)if(a=
null!=Gc?Gc[b]:b,K[x][a].gotit&&(yg[a]||C[a].checked)&&pb[a])for(var d=0;d<aa[a].length;d++)G.drawImage(null!=K[x][a].origImage?K[x][a].origImage:K[x][a],aa[a][d][0],aa[a][d][1],aa[a][d][2],aa[a][d][3],aa[a][d][4]/u,aa[a][d][5]/r,aa[a][d][2]/u,aa[a][d][3]/r);Ob&&X()}ih&&k();if(Pf)for(G.globalAlpha=1,a=0;a<lb;a++)if(null!=mb[a]){var c=mb[a];null!=c.icon&&(c.icon.style.visibility="hidden");if((-1==c.frame||c.frame==x)&&null!=c.icon&&c.icon.gotit&&(-1==c.overlay||-1!=c.overlay&&C[c.overlay].checked)){if(c.isPan){c.zoomme&&
(c.icon.style.width=Math.round(c.width*z)+"px",c.icon.style.height=Math.round(c.height*F)+"px",c.w2=Math.round(c.width*z/2),c.h2=Math.round(c.height*F/2));var h=Math.round(((c.x0-P)*z-c.w2)/u);var e=Math.round(((c.y0-M)*F-c.h2)/r);if(c.anim){if(0>=h+c.icon.width||h>=na||0>=e+c.icon.height||e>=ia)continue;c.icon.style.top=e+"px";c.icon.style.left=h+"px"}else G.drawImage(c.icon,c.origX,c.origY,c.width,c.height,h,e,c.width/u,c.height/r)}else G.drawImage(c.icon,c.origX,c.origY,c.width,c.height,c.x0/u,
c.y0/r,c.width/u,c.height/r);c.icon.style.visibility="visible"}}}catch(m){ha("Error:"+m)}}function sa(b,a,d){!ve||d>=a||(G.save(),G.fillStyle="blue",G.strokeStyle="white",G.lineWidth=3,G.strokeRect(Be,Ce,200,18),G.fillRect(Be,Ce,d/a*200,18),a=G.measureText(b).width,G.fillStyle="orange",G.font="14px arial",G.fillText(b,Be+100-a/2,Ce+14),G.restore())}function k(){ve&&Cb>Ha?sa("Loading Images",Cb,Ha):(ih=!1,$e&&(lc.style.visibility="hidden"));Ha>=Cb&&!Ba&&xa(wa(x));void 0!=De&&Ha>=Cb&&De(!0)}function ha(b){if(ke&&
Ze&&!Ze.closed)try{Ze.document.write(b+"<br>")}catch(a){}}function Wh(){Ba&&Ab(Gf);gi=x==wa(v-1)?ng+ib:ib;W();setTimeout(function(){mi(Wh)},gi)}function Ve(b){for(;-180>b;)b+=360;for(;180<b;)b-=360;return b}function ki(){var b,a,d,c,h,e,g,l,k=Math.PI/180;this.init=function(c){for(var d=[],f=1;f<c.length;f++)d[f]=parseFloat(c[f]);a=d[1];b=d[4]/d[5];h=d[6];e=d[7];c=this.toXY(d[2],d[3]);h=c[0];e=c[1]};this.toXY=function(f,g){d=b*Ve(g-a)*k-h;c=-b*f*k-e;return[d,c]};this.toLatLon=function(c,d){g=-(d+e)/
b/k;l=Ve((c+h)/b/k+a);return[g,l]}}function ji(){var b,a,d,c,h,e,g,l,k,q,r,p,t,n,v,x,w,y,B,A,u,C,E,F,D,z,H,G,K,J,L,I=Math.PI/180;this.init=function(c){for(var d=[],e=1;e<c.length;e++)d[e]=parseFloat(c[e]);b=d[1];a=d[2];A=0==d[8]?!1:!0;u=d[6];C=u*u;E=C*C;F=E*C;D=E*E;g=d[5]/d[7];L=d[7];A?(l=Math.cos(I*b),k=Math.sin(I*b)):(l=Math.cos(-b*I),k=Math.sin(-b*I));w=l/Math.sqrt(1-C*k*k);B=(1-u*k)/(1+u*k);x=A?Math.tan(Math.PI/4-b*I/2)/Math.pow(B,u/2):Math.tan(Math.PI/4- -b*I/2)/Math.pow(B,u/2);n=d[9];v=d[10];
c=this.toXY(d[3],d[4]);n=c[0];v=c[1]};this.toXY=function(f,l){A?(h=I*f,e=I*(l-a)):(h=I*-f,e=I*(a-l));B=(1-u*Math.sin(h))/(1+u*Math.sin(h));y=Math.tan(Math.PI/4-h/2)/Math.pow(B,u/2);z=90!=b&&-90!=b?g*w*y/x:2*g*L*y/Math.sqrt(Math.pow(1+u,1+u)*Math.pow(1-u,1-u));d=z*Math.sin(e);c=z*Math.cos(e);A||(d=-d,c=-c);q=d-n;r=c-v;return[q,r]};this.toLatLon=function(e,f){d=e+n;c=f+v;z=Math.sqrt(d*d+c*c);y=90==b||-90==b?z*Math.sqrt(Math.pow(1+u,1+u)*Math.pow(1-u,1-u))/(2*g*L):z*x/(g*w);H=Math.PI/2-2*Math.atan(y);
G=Math.sin(2*H);K=Math.sin(4*H);J=Math.sin(6*H);h=H+G*C/2+5*G*E/24+G*F/12+13*G*D/360+7*K*E/48+29*K*F/240+811*K*D/11520+7*J*F/120+81*J*D/1120+4279*Math.sin(8*H)*D/161280;A?(p=h/I,t=Math.atan2(d,c)/I+a):(p=-h/I,t=-Math.atan2(-d,-c)/I+a);return[p,Ve(t)]}}function li(){var b,a,d,c,e,f,g,l,k,q,r,n,t,p,v,u,x,w,y,B,A,C,E,z,D,F,H,I,G,K,J,L,N,O,P,M=Math.PI/180;this.init=function(c){for(var e=[],h=1;h<c.length;h++)e[h]=parseFloat(c[h]);b=e[1];a=e[2];d=e[3];z=e[7];D=z*z;F=D*D;H=F*D;I=F*F;l=e[6]/e[8];k=Math.cos(M*
b);q=Math.cos(M*a);n=Math.sin(b*M);r=Math.sin(a*M);A=k/Math.sqrt(1-D*n*n);C=q/Math.sqrt(1-D*r*r);y=Math.sqrt((1-n)/(1+n)*Math.pow((1+z*n)/(1-z*n),z));B=Math.sqrt((1-r)/(1+r)*Math.pow((1+z*r)/(1-z*r),z));J=(Math.log(A)-Math.log(C))/(Math.log(y)-Math.log(B));L=A/(J*Math.pow(y,J));O=l*L*Math.pow(y,J);x=e[9];w=e[10];c=this.toXY(e[4],e[5]);x=c[0];w=c[1]};this.toXY=function(a,b){f=M*a;g=M*Ve(b-d);P=Math.sin(f);E=Math.sqrt((1-P)/(1+P)*Math.pow((1+z*P)/(1-z*P),z));K=l*L*Math.pow(E,J);N=J*g;c=K*Math.sin(N);
e=O+K*Math.cos(N);t=c-x;p=e-w;return[t,p]};this.toLatLon=function(a,b){c=a+x;e=b+w;K=Math.abs(J)/J*Math.sqrt(c*c+(O-e)*(O-e));E=Math.pow(K/(l*L),1/J);G=Math.PI/2-2*Math.atan(E);N=0>J?Math.atan(-c/(e-O)):Math.atan(c/(O-e));g=N/J;f=G+(D/2+5/24*F+H/12+13/360*I)*Math.sin(2*G)+(7/48*F+29/240*H+811/11520*I)*Math.sin(6*G)+(7/120*H+81/1120*I)*Math.sin(6*G)+4279/161280*I*Math.sin(8*G);v=f/M;u=Ve(d-g/M);return[v,u]}}var L=this,pg,Y,S,ia,na,u,r,$g,ah,Eb,Fb,lc,$e,la,ke,Qf,Ze,xc,ag,kf=!1,y,D,Ef,Ff,Wa,tc,kd,nb,
G,Ta,nc,g,Rd,Df,Ic,of,ue,hh,pf,uc,v,ta,Tg,ba,lf,Rb,Gc,ea,vc,Sb,gd,da,Fg,Ga,K,C,se,Vd,Db,Eh,Ch,Dh,dd,Gd,rg,I,sg,bg,Jh,U,Q,A,B,qa,ra,ab,$a,P,M,Xd,hb,wc,Vh,Ba,Ra,He,x,Pe,Gf,de,sc,jd=!0,qe,cg,le,e,ib,Ub,Kc,De,sf,ng,gi,Fd,Aa,ld,Fc,ob,Oa,$b,Rc,Ud,Bf,Ee,jf,Ae,Sd,vh,$c,db,Rf,Sf,Tf,Uf,$h,ec,Ec,Qa,rd,Ke,Le,sh,wb,wh,th,ph,qh,rh,Hd,qg,mb,lb,Pf,qf,wf,ja,Pc,ce,eh,ub,Fa,R,dg,Pa,Fe,kb,md,Cf,Td,pa,Xf,pc,cd,ma,T,ac,Sc,ua,Ia,sd,bb,Ja,zc,Of,Me,Zc,Nf,Tc,bd,Bb,sb,rb,Gb,Wb,Vb,re,Vc,vb,qd,we,tf,xe,Zg,oa,Xh,jh,di,ci,ei,bc,
eb,Sa,Kb,xb,td,zh,Xg,Ah,Bh,Yg,Nh,qb,ee,Re,fe,Kh,Pd,zf,yh,Yf,ud,V,Oe,Zb,te,zg,qc,Id,Jd,ed,Ag,Bg,Zh,Lf,Mf,Jf,Kf,Zd,p,If,nh,dc,oh,ka,Hb,Yc,$d,Xc,Wc,Je,Yh,be,ae,yc,Ib,kh,lh,za,Gg,hd,z,F,Ge,Ne,Wg,rc,Od,Vg,Ug,ya,Jc,id,We,rf,tg=!1,ug,vg,wg,mf,xg,Wd,jb,Ie,Yd,Af,cc,mc,Se,Te,jg,ne,Qe,Vf,xh,Wf,fh=!0,gh,ge,he,Lh,kg,cf,Ca,bf,oe,Uc,Cc,me,ig,Eg,nd,od,af,fg,gg,hg,Yb,cb,fi,yf,dh,Sh,Th,Da,Jb,uh,Hc,pb,aa,yg,Hf,ye,Lc,Qg,Sg,Rg,oc,Ob,pd,pe,Mc,Nc,Oc,Xb,vd,Ue,Mh,lg,Dd,mg,df,nf,Cg,Dg,fd,ai,bi,gc,Zf,$f,Gh,Hh,hc,N,Fh,fc,Ih,
tb,w,Qc,ch,Xa,Ya,Za,Qd,xf,ze,hi,Ed,ef,Dc,ve,ff,gf,hf,Pb,Qb,og,ih,Be,Ce,Ha,Cb,Kd,Pg,Hg,Ld,Jg,Md,Lg,Ig,Kg,Og,Mg,Nd,Ng,Cd,Tb,ni="N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW N".split(" "),mi=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||function(b){setTimeout(b,10)},n=function(b){return document.createElement(b)},E=function(b,a){if(null!=b)return 0==b.trim().toLowerCase().indexOf(a)},Uh=function(b,a){if(null!=
b)return b=b.trim(),b.lastIndexOf(a)===b.length-1},Rh=function(b){void 0==ag&&(ag=n("textarea"));ag.innerHTML=b;return ag.value},mh=function(b,a,d){var c=n("select");c.style.width="70px";c.style.margin="5px";for(var e=0;e<b.length;e++){var f=n("option");f.innerHTML=b[e];f.value=a[e];c.add(f)}c.addEventListener("change",d,!1);return c},Qh=function(b){b=b.split(",");ea=Array(v);for(var a=0;a<b.length;a++){var d=b[a].split("&");ba=b.length;for(var c=0;c<v;c++)0===a&&(ea[c]=Array(ba)),ea[c][a]=d[1==d.length?
0:c].trim(),null!=Tb?ea[c][a]=(Tb+ea[c][a]).trim():null!=da&&(ea[c][a]=(da+ea[c][a]).trim())}bd=!1},Oh=function(b){b=b.split(",");v=b.length;ta=Array(v);for(var a=0;a<v;a++)ta[a]=null!=da?da+b[a].trim():b[a].trim();bd=!1;v>ba&&(ba=0)},Ph=function(b,a,d){var c=b;null!=da&&(c=da+b);ta=Array(v);for(var h=0;h<v;h++){b=h*d+a;if(0<=c.indexOf("*"))ta[h]=c.replace("*",b);else if(0<=c.indexOf("?")){for(var f=c;0<=f.lastIndexOf("?");){var g=f.lastIndexOf("?");f=f.substring(0,g)+b%10+f.substring(g+1);b=Math.floor(b/
10)}ta[h]=f}else ta[h]=c+h;ha("image filename = "+ta[h])}b=e.reverse_order;null!=b&&E(b,"t")&&ta.reverse();bd=!1;v>ba&&(ba=0)};HTMLCanvasElement.prototype.toBlob||Object.defineProperty(HTMLCanvasElement.prototype,"toBlob",{value:function(b,a,d){d=window.atob(this.toDataURL(a,d).split(",")[1]);for(var c=d.length,e=new Uint8Array(c),f=0;f<c;f++)e[f]=d.charCodeAt(f);b(new Blob([e],{type:a||"image/png"}))}});this.setup=function(b,a,d){void 0==a&&(a="MORdivcan");gh=d;y=document.getElementById(a);Cd="center";
y.align=Cd;Wa=n("div");Wa.setAttribute("style","position:relative;border:0px;margin:0px;padding:0px;-webkit-user-select:none; -moz-user-select:none; -ms-user-select:none; user-select:none; -webkit-tap-heightlight-color:transparent;");nb=n("canvas");nb.setAttribute("style","position:absolute;top:0;left:0;z-index:1;");G=nb.getContext("2d");nc=n("canvas");nc.setAttribute("style","position:absolute;top:0;left:0;z-index:6;");g=nc.getContext("2d");g.imageSmoothingEnabled=!1;Rd=n("canvas");Rd.setAttribute("style",
"position:absolute;top:0;left:0;z-index:10;");Df=Rd.getContext("2d");Df.imageSmoothingEnabled=!1;tc=n("div");tc.setAttribute("style","position:absolute;top:0;left:0;z-index:5;overflow:hidden;border-width:0px;padding:0px;margin:0px;");kd=n("div");kd.setAttribute("style","position:absolute;top:0;left:0;z-index:10;overflow:hidden;border-width:0px;padding:0px;margin:0px;");kd.appendChild(Rd);Ae=n("canvas");Wa.appendChild(kd);Wa.appendChild(nb);Wa.appendChild(nc);Wa.appendChild(tc);y.appendChild(Wa);la=
new PEvs(Wa,L.down,L.up,L.move,L.drag,null,L.canTip);y.setAttribute("tabindex",0);y.addEventListener("keyup",function(a){Hb||le||(cg=!1,a.preventDefault(),a.stopPropagation())},!1);y.addEventListener("keypress",function(a){Hb||le||(a.preventDefault(),a.stopPropagation())},!1);y.addEventListener("keydown",function(a){Hb||le||(a.preventDefault(),a.stopPropagation(),cg=a.ctrlKey?!0:!1,37==a.keyCode?(H(!1),Ab(-1),W()):39==a.keyCode?(H(!1),Ab(1),W()):32==a.keyCode?L.toggleIsLooping():82==a.keyCode&&a.altKey&&
L.resetZoom())},!1);kd.addEventListener("mouseenter",function(a){y.focus()},!1);y.style.outlineWidth="0px";y.style.outline="none";y.focus();wc=x=0;de=!1;Gf=1;Ra=Ba=!0;lb=ba=v=0;qe=!0;Gc=null;sc=!0;ib=500;Ub=100;Kc=2E3;sf=30;ng=0;ef=6E4;Dc=null;Ic=Ed=!1;ue=!0;uc=[];ma=Fg=gd=Tb=da=null;sd=!1;T=-1;id=!1;Ne=Ge=F=z=1;We=!1;M=P=$a=ab=ra=qa=B=A=Q=U=0;Wg=!1;jd=fh=!0;Of=$e=kf=!1;Hd=-1;Qa=[];ub=0;Pf=!1;ja=null;Pc=-1;wf=0;ce=!1;Ja=null;Ce=Be=Ha=Cb=0;ch=!1;N=0;Db=pf=qf=Tc=!1;Se=Te=ge=he=0;Uc=mc=!1;Ca=[];Ca.push("default");
Ca.push("default");bf="default";od=!1;oe="default";Yb=null;cb=[0,0];kb=Af=ne=!1;cd=!0;pa=pc=null;vb=Xf=!1;xe=!0;cf="default";Xd=!0;oa=[];Ob=df=!1;pe="default";Mc=!1;Gh=[1,0,0];Hh=[2,2,1];hc=[];oc=[];Fc=ld=eb=!1;te=Oe=0;Jb=Ff=Ef=D=wb=null;uh=0;Hb=le=cg=!1;a=n("canvas");a.height=1;a.width=1;Ta=a.getContext("2d");Ta.imageSmoothingEnabled=!1;Cf=n("canvas");ke=!1;"string"===typeof b?0>b.indexOf("\n")?eg(b):q(b.split("\n")):q(b)};this.newBasenames=function(b,a,d,c){Tc=!1;Ra=Ba;H(!1);v=c;Ph(b,a,d);sc=!0;
Ka()};this.newFilenames=function(b){Tc=!1;Ra=Ba;H(!1);Oh(b);sc=!0;Ka()};this.newOverlayFilenames=function(b){Tc=!1;Ra=Ba;H(!1);Qh(b);sc=!0;Ka()};this.newProbeTable=function(b){Mc=!1;O(b.trim())};this.reloadFOF=function(){ha("reload FoF = "+Dc);Xe("r");bd?ii(hi,!1):(Ra=null==He?!0:Ba,sc=!0,Ka())};this.getFOF=function(){var b=e.file_of_filenames.trim();L.newFOF(null!=gd?gd+b:b,!0)};this.newFOF=function(b,a){L.resetZoom();ii(b,a)};var ii=function(b,a){var d,c,e,f,g=new XMLHttpRequest,l,k,q,r,n,t,p,u=
null,x=!1;eh=ub;Tc=!1;Ra=Ba;H(!1);a&&xa(wc);ub=v=0;ta=[];I=Pa=null;Jh=[];for(bg=null;tc.hasChildNodes();)tc.removeChild(tc.lastChild);Fe=0;sd=kb=md=!1;ua=Sc=ac=null;Ia=[];zc=-1;ea=[];var w=!1;if(null==qb||null!=Pd)qb=[];ha("new FOF="+b);eb&&(null!=bc&&(J(bc,!0,"extrap on"),y.style.cursor="default",H(Ra),Sa=-1),eb=!1,X());vb&&(null!=Vc&&(J(Vc,!0,"mark on"),y.style.cursor="default",H(Ra),qd=-1),vb=!1,X());g.onload=function(){var a=this.responseText.split("\n");for(d=0;d<a.length;d++)if(!(2>a[d].length)&&
(l=a[d].trim(),ha("FOF: "+l),0!=l.indexOf("#")))if(0==l.indexOf("frame_labels"))n=l.split("="),bb=n[1].split(",");else if(0==l.indexOf("redirect"))for(n=l.split("="),p=n[1].split(","),bg=p[0].trim(),c=1;c<p.length;c++){var b=parseInt(p[c],10)-1;Jh[b]=!0}else if(0==l.indexOf("slice")){n=l.split("=");p=n[1].split(",");I=[];for(c=0;c<p.length;c++)I[c]=parseInt(p[c],10);I[2]=I[2]-I[0]+1;I[3]=I[3]-I[1]+1;4<I.length&&(I[6]=I[6]-I[4]+1,I[7]=I[7]-I[5]+1)}else if(0==l.indexOf("fof_extension"))n=l.split("="),
u=n[1].trim();else if(0==l.indexOf("probe_table"))n=l.split("="),Mc=!1,O(n[1].trim());else if(0==l.indexOf("image_base"))n=l.split("="),da=n[1].trim();else if(0==l.indexOf("overlay_base"))n=l.split("="),Tb=n[1].trim();else if(0==l.indexOf("high_res_basemap")){n=l.split("=");p=n[1].split(",");Sc=[];for(c=0;c<p.length;c++)Sc[c]=p[c].trim(),null!=da&&(Sc[c]=da+Sc[c]);sd=!0}else if(0==l.indexOf("high_res_overlay"))for(n=l.split("="),t=n[1].split("&"),e=0;e<t.length;e++){p=t[e].split(",");zc=parseInt(p[0].trim(),
10)-1;Ia[zc]=[];for(c=1;c<p.length;c++)Ia[zc][c-1]=p[c].trim(),Uh(Ia[zc][c-1],"/")||(null!=Tb?Ia[zc][c-1]=Tb+Ia[zc][c-1]:null!=da&&(Ia[zc][c-1]=da+Ia[zc][c-1]));sd=!0}else if(0==l.indexOf("high_res_zoom")){n=l.split("=");p=n[1].split(",");ma=[];for(c=0;c<p.length;c++)ma[c]=parseFloat(p[c].trim());Va()}else if(0==l.indexOf("hoverzone"))Ac(l);else if(0==l.indexOf("hotzone"))ad(l);else if(0==l.indexOf("hotspot"))x||(mb=null,lb=0,x=!0),Lb(l);else if(0==l.indexOf("toggle_onoff"))n=l.split("="),Me=n[1].split(",");
else if(0==l.indexOf("coordinates"))n=l.split("="),yb(n[1]);else if(0==l.indexOf("map_scale"))n=l.split("="),p=n[1].split(","),Cc=parseFloat(p[0]),me=1<p.length?parseFloat(p[1]):Cc;else if(0==l.indexOf("times")){n=l.split("=");p=n[1].split(",");for(d=0;d<p.length;d++)qb[d]=parseInt(p[d].trim(),10);w=!0}else{null!=Pd&&(b=l.match(Pd),null!=b&&2==b.length?(qb.push(parseInt(b[1],10)),ha("+ + + Extrap time = "+b[1]),w=!0):ha("+ + + Cannot parse times using "+Pd+" from line: "+l));e=l.indexOf(" ");0>e&&
(e=l.length);ta[v]=l.substring(0,e).trim();null!=da&&(ta[v]=da+ta[v]);l=l.substring(e+1);b=l.indexOf('"');0<=b&&(null==bb&&(bb=[]),e=l.substring(b+1),b=e.indexOf('"'),0<=b&&(bb[v]=e.substring(0,b),0==v&&(Ja.innerHTML=bb[0])));ea[v]=[];b=l.indexOf("overlay");if(0<=b)for(k=l.substring(b),b=k.indexOf("="),0>b&&ha("Cannot find a = sign in "+k),q=k.substring(b+1),k=q.trim(),q=k.split(","),ba=q.length,ha("numOverlays set to "+ba),f=0;f<q.length;f++)ea[v][f]=q[f].trim(),null!=bg&&Jh[f]?ea[v][f]=(bg+ea[v][f]).trim():
null!=Tb?ea[v][f]=(Tb+ea[v][f]).trim():null!=da&&(ea[v][f]=(da+ea[v][f]).trim());v+=1}w&&va(qb);null!=u?(a=new XMLHttpRequest,a.onload=function(){var a=this.responseText.split("\n");for(d=0;d<a.length;d++)2>a[d].length||(r=a[d].trim(),ha("ext_FOF: "+r),0!=r.indexOf("#")&&(0==r.indexOf("hotzone")?ad(r):0==r.indexOf("hotspot")&&Lb(r)));Ua()},a.onerror=function(){Ua()},a.open("get",u+"?"+Math.round(1E5*Math.random()),!0),a.send()):Ua()};hi=b;g.open("get",b+"?"+Math.round(1E5*Math.random()),!0);g.send()};
this.setWindowSize=function(b,a){if(null!=y){y.style.height=a+"px";y.style.width=b+"px";y.style.padding="0px";a=a-(null!=Ef?Ef.offsetHeight:0)-(null!=Ff?Ff.offsetHeight:0)-(null!=wb?wb.offsetHeight:0)-uh*(null!=Jb?Jb.offsetHeight:0);a>ia&&(a=ia);var d=a*na/ia;d>b&&(d=b,a=b*ia/na);a=Math.floor(a);d=Math.floor(d);jd||(wd(d,a),X())}};this.drag=function(b){vb||(U=la.getX(),Q=la.getY(),Hb?(b=p.length-1,p[b].xe=U,p[b].ye=Q,p[b].xp.push(U),p[b].yp.push(Q),p[b].size=Math.round(Math.sqrt(Math.pow(U-p[b].x,
2)+Math.pow(Q-p[b].y,2)))):(A=U*u,B=Q*r,Uc=Db=!1,mc&&(!ne||ne&&b.shiftKey)?(ge=A,he=B,Uc=!0):(ya&&F!=Ne?(P=qa-A/z,M=ra-B/F,yd(),qa=Math.round(P+A/z),ra=Math.round(M+B/F)):vb||eb||!kb||(pa=null,cd&&0<=A&&0<=B&&(R=Td.getImageData(A,B,1,1).data,0!=R[3]&&(pa=Pa[R[3]-1]))),We=!0,W())),X())};this.resetZoom=function(){z=Ge;F=Ne;T=-1;null!=za&&(J(za,!0,"zoom on"),ya=!1);qa=A;ra=B;M=P=0;$a=ia;ab=na;Va();W();md&&(kb=!0)};this.canTip=function(){var b;Db=!1;U=la.getX();A=U*u;Q=la.getY();B=Q*r;if(!((vb||eb)&&
B<Bh&&B>Ah&&A>zh)){qa=Math.round(P+A/z);ra=Math.round(M+B/F);if(0!=ub)for(b=0;b<ub;b++)if(Fa[b].overlay>=ba)ha(" Error...hotzone overlay # "+Fa[b].overlay+" > number of overlays = "+ba);else if(C[Fa[b].overlay].checked&&(Ta.clearRect(0,0,1,1),Ta.drawImage(K[x][Fa[b].overlay],qa,ra,1,1,0,0,1,1),R=Ta.getImageData(0,0,1,1).data,dg=(R[0]<<16)+(R[1]<<8)+R[2],dg==Fa[b].color)){Db=!0;Ch=U;Dh=Q;Eh=Fa[b].tip;break}if(0!=lb)for(b=lb-1;0<=b;b--)if(null!=mb[b]){var a=mb[b];if(-1==a.frame||a.frame==x)if(-1==a.overlay||
C[a.overlay].checked){var d=!1;if(a.isPan)if(a.isIcon){var c=(a.x0-P)*z-a.w2;var e=(a.y0-M)*F-a.h2;A>c&&A<c+a.width&&B>e&&B<e+a.height&&(d=!0)}else c=(a.x0-P)*z,e=(a.y0-M)*F,A>c&&A<c+a.width*z&&B>e&&B<e+a.height*F&&(d=!0);else A>a.x0&&A<a.x1&&B>a.y0&&B<a.y1&&(d=!0);if(d&&null!=a.tip){Db=!0;Ch=U;Dh=Q;Eh=mb[b].tip;break}}}X()}};this.move=function(){if(!eb&&kb&&(pa=null,cd)){var b=la.getX()*u,a=la.getY()*r;0<=b&&0<=a&&(R=Td.getImageData(b,a,1,1).data,0!=R[3]&&(pa=Pa[R[3]-1]))}eb&&2<=Sa&&(U=la.getX(),
A=U*u,Q=la.getY(),B=Q*r);X()};this.down=function(){Db&&(Db=!1,X());U=la.getX();A=U*u;Q=la.getY();B=Q*r;Se=A;Te=B;ge=Se;he=Te;qa=Math.round(P+A/z);ra=Math.round(M+B/F);We=!1;if(Hb){var b={};b.x=U;b.y=Q;b.xe=U;b.ye=Q;b.xp=[U];b.yp=[Q];b.type=be.value;b.color=ae.value;b.width=yc.value;b.text=Ib.value;b.size=0;p.push(b)}};this.up=function(b){Db=!1;if(!Hb){if(eb||vb){U=la.getX();A=U*u;Q=la.getY();B=Q*r;if(vb){qd=1;if(0<qd&&B/r<ei){if(A/u>di){oa.pop();oa.pop();0==oa.length&&(qd=0);X();return}if(A/u<ci){X();
b=window.open("","Mark Points");b.document.write("<div>Marked Points<br>");for(var a=[],d=0;d<oa.length;d+=2)qa=P+oa[d]/z,ra=M+oa[d+1]/F,Mb(),b.document.write(cb[0].toFixed(4)+","+cb[1].toFixed(4)+"<br>"),0==d&&(a[0]=cb[0],a[1]=cb[1]);xe&&b.document.write(a[0].toFixed(4)+","+a[1].toFixed(4)+"<br>");return}}oa.push(A);oa.push(B);X();return}if(3>Sa)if(Kb[Sa]=A,xb[Sa]=B,td[Sa]=zf[x],0==Sa)Sa=1,xa(wa(v-1)),Oe=1,fd=null;else{Kh=td[1]-td[0];Re=(Kb[1]-Kb[0])/Kh;fe=(xb[1]-xb[0])/Kh;if(null!=nf&&null!=Cc){d=
Re*Cc;var c=fe*me;a=Math.round(60*Math.sqrt(d*d+c*c));d=Math.atan2(d,-c)/.0174533;0>d&&(d+=360);fd=Cg+ni[Math.round(d/22.5)]+" at "+a+" "+Dg;ai=Kb[0];bi=0<fe?xb[0]-15:xb[0]+30}a=parseInt(Jd,10);V=Math.round(Math.abs(4*(a+4)/Re));ud=Math.round(Math.abs(2*(a+4)/fe));ud<V&&(V=ud);120<V?V=120*Math.floor(V/120)+60:90<V?V=120:60<V?V=90:30<V?V=60:15<V?V=30:10<V?V=15:5<V?V=10:2<V?V=5:0==V&&(V=1);ud=td[1]/V*V+V;ee=1;Bg&&(ee=-1);yh=Re*V;Yf=fe*V;xa(wa(v-1));Sa=3;Oe=2}else if(B/r<Bh&&B/r>Ah&&A/u>zh&&3==Sa){Bc();
X();return}X()}if(Uc)Uc=!1,X();else if(null!=cc&&ya&&(mc=!1,J(cc,!0,"distance on")),We)We=!1;else if(b.altKey)L.resetZoom();else if(kb&&null!=pa&&Xf)Nb(pa,"z");else{U=la.getX();A=U*u;Q=la.getY();B=Q*r;if(0!=ub)for(a=0;a<ub;a++)if(Fa[a].overlay>=ba)ha(" Error...hotzone overlay # "+Fa[a].overlay+" > number of overlays = "+ba);else if(C[Fa[a].overlay].checked&&(Ta.clearRect(0,0,1,1),Ta.drawImage(K[x][Fa[a].overlay],Math.floor(qa),Math.floor(ra),1,1,0,0,1,1),R=Ta.getImageData(0,0,1,1).data,dg=(R[0]<<
16)+(R[1]<<8)+R[2],dg==Fa[a].color)){Nb(Fa[a],"z");return}if(0!=lb)for(a=lb-1;0<=a;a--)if(null!=mb[a]){var e=mb[a];if(!(-1!=e.frame&&e.frame!=x||e.fromfile||-1!=e.overlay&&!C[e.overlay].checked)){var f=!1;e.isPan?e.isIcon?(d=(e.x0-P)*z-e.w2,c=(e.y0-M)*F-e.h2,A>d&&A<d+e.width&&B>c&&B<c+e.height&&(f=!0)):(d=(e.x0-P)*z,c=(e.y0-M)*F,A>d&&A<d+e.width*z&&B>c&&B<c+e.height*F&&(f=!0)):A>e.x0&&A<e.x1&&B>e.y0&&B<e.y1&&(f=!0);if(f){Nb(mb[a],"s");return}}}ya&&(kb=!1,zd(b.ctrlKey||cg||b.which&&3==b.which||b.button&&
2==b.button));W();X()}}};this.wheel=function(b){Tg?Ab(b):ya&&(U=la.getX(),A=U*u,Q=la.getY(),B=Q*r,qa=Math.round(P+A/z),ra=Math.round(M+B/F),zd(-1==b))};this.toggleAutoRefresh=function(){Ed?(J(Lc,!1,"autorefresh off"),null!=Dc&&clearInterval(Dc),Ed=!1):(J(Lc,!0,"autorefresh on"),Dc=setInterval("HAniS.reloadFOF();",ef),Ed=!0)};this.toggleLoopRock=function(){de?(J(Wd,!0,"looprock rock"),de=!1):(J(Wd,!1,"looprock loop"),de=!0)};this.toggleExtrap=function(){eb?(null!=bc&&(J(bc,!0,"extrap on"),y.style.cursor=
Ca.pop(),null!=Bb&&(Bb.disabled=!1),H(Ra),ya=Ug,Sa=-1),eb=!1,X()):(null!=bc&&(eb=!0,fd=null,Ca.push(y.style.cursor),y.style.cursor="crosshair",J(bc,!1,"extrap off"),Ra=Ba,null!=Bb&&(Bb.disabled=!0),Ba=!1,Ug=ya,ya=!1,L.resetZoom(),Bc(),X()),W())};this.doEnhance=function(b){if(ld||Fc){var a=Oa[0].height,d=Oa[0].width;b=parseInt(Aa.value,10);0<=b?(Rf=Xa[b],Sf=Ya[b],Tf=Za[b],Uf=Qd[b],oc[ob]=b):oc[ob]=null;var c=a*d*4;for(d=0;d<$b.length;d++)if(Oa[d].gotit){Oa[d].gotit=!1;var e=Ee[d].data;var f=Bf[d];
if(0>b)for(a=0;a<c;a+=4)e[a]=f[a],e[a+1]=f[a+1],e[a+2]=f[a+2],e[a+3]=f[a+3];else for(a=0;a<c;a+=4)db=f[a],db===f[a+1]&&db===f[a+2]&&(e[a]=Rf[db],e[a+1]=Sf[db],e[a+2]=Tf[db],e[a+3]=Uf[db]);Rc[d].putImageData(Ee[d],0,0);Oa[d].gotit=!0}}};this.overClick=function(b){var a;if(b.target.checked)for(a=0;a<C.length;a++)b.target!=C[a]&&0!=b.target.name&&b.target.name==C[a].name&&(C[a].checked=!1);cd=!0;for(a=0;a<Sb.length;a++)b.target!=C[a]&&La(a),null!=pc&&!pc[a]&&C[a].checked&&(cd=!1),null!=Aa&&a===ob&&(Aa.disabled=
!C[a].checked);W()};this.toggleIsLooping=function(){Ba?(Ba=!1,J(Bb,!0,"startstop start")):(Ba=!0,J(Bb,!1,"startstop stop"))};this.toggleZooming=function(){ya?(L.resetZoom(),J(za,!0,"zoom on")):(J(za,!1,"zoom off"),ya=!0,null!=cc&&(mc=!1,J(cc,!0,"distance on")),md&&(kb=!0),eb&&L.toggleExtrap())};this.togclick=function(b){var a=th.getX();th.getY();for(var d=wh,c=0;c<Qa.length;c++){if(a>d&&a<d+rd){if(b.shiftKey){0<=Qa[c]&&(H(!1),xa(c));break}b=0;0<=Qa[c]&&(b=-1);gb(c,b);break}d=d+rd+Le}};this.doneLoading=
function(b){De=b};this.frameChanged=function(b){Pe=b};this.getFrame=function(){return x};this.showFrame=function(b){xa(wa(b))}};
