:wq
#!wing
#!version=4.0
##################################################################
# Wing IDE project file                                          #
##################################################################
#!wing
#!version=4.0
##################################################################
# Wing IDE project file : User-specific branch                   #
##################################################################
[user attributes]
cache.last-mime-type = {loc('unknown:<untitled> #8'): 'text/x-diff',
                        loc('unknown:<untitled> #6'): 'text/x-diff',
                        loc('unknown:<untitled> #10'): 'text/x-diff',
                        loc('unknown:<untitled> #7'): 'text/x-diff',
                        loc('unknown:<untitled> #9'): 'text/x-diff'}
console.id-seed = 51
console.toolbox = [{'autosave': False,
                    'ctype': ('loc',
                              u'/w21/prj/tc/20110413_tcgen2/p.tcgen2.py'),
                    'env': ('project',
                            []),
                    'id': 'cmd-1',
                    'io_encoding': None,
                    'key_binding': None,
                    'line_mode': True,
                    'pseudo_tty': False,
                    'pypath': ('project',
                               ''),
                    'raise_panel': True,
                    'rundir': ('project',
                               ''),
                    'title': None}]
debug.err-values = {None: {},
                    loc('../prc/lib/python/tc2.py'): {}}
debug.recent-run-args = {loc('../prc/lib/python/tcbase.py'): ['-S e -s'],
                         loc('../prc/tcdat/localvdstat2.py'): ['ecmwf,tmtrkN'\
        ',jtwc -S 09w.12 -T edet -l3 -p ls -R'],
                         loc('../prc/tcdat/w2.tc.dss.md2.anl.py'): ['-S e -s'],
                         loc('../prc/tcdat/w2.tc.dss.vdeck.anl.py'): ['ecmwf'\
        ',tmtrkN,jtwc -S 09w.12 -T edet -l3 -p ls -R'],
                         loc('../prc/tcdiag/w2.tc.lsdiag.py'): ['cur12-12 rt'\
        'fim9 -P',
        'cur12-12 rtfim9 -Pl',
        '2012072206 gfs2 -o -l'],
                         loc('tc/20110413_tcgen2/p.tcgen2.py'): ['cur12 ecm2'\
        ' -b lant -l -t 60',
        '2013076 gfs2 -S 09w.12 -o -l',
        '2012072206 gfs2 -S 09w.12 -o -l',
        '2013061000 gfs2 -l',
        '2013060812 all -P -T',
        'cur12 gfs2 -b lant -l']}
debug.run-args = {loc('../prc/lib/python/tcbase.py'): '-S e -s',
                  loc('../prc/tcdat/localvdstat2.py'): 'ecmwf,tmtrkN,jtwc -S'\
        ' 09w.12 -T edet -l3 -p ls -R',
                  loc('../prc/tcdat/w2.tc.dss.md2.anl.py'): '-S e -s',
                  loc('../prc/tcdat/w2.tc.dss.vdeck.anl.py'): 'ecmwf,tmtrkN,'\
        'jtwc -S 09w.12 -T edet -l3 -p ls -R',
                  loc('../prc/tcdiag/w2.tc.lsdiag.py'): 'cur12-12 rtfim9 -P',
                  loc('tc/20110413_tcgen2/p.tcgen2.py'): 'cur12 ecm2 -b lant'\
        ' -l -t 60'}
gui.named-bookmarks = {0: (u'/w21/prj/tc/20110413_tcgen2/p.tcgen2.py',
                           {'attrib-starts': [('InvHash',
        27),
        ('InvHash.parseHash',
         140)],
                            'first-line': 128,
                            'folded-linenos': [],
                            'sel-line': 140,
                            'sel-line-start': 2994,
                            'selection_end': 3076,
                            'selection_start': 3060})}
guimgr.overall-gui-state = {'windowing-policy': 'combined-window',
                            'windows': [{'name': '0uEhdBheFZPvfQOtZJVUwqxvlx'\
        'XIDOrB',
        'size-state': '',
        'type': 'dock',
        'view': {'area': 'tall',
                 'constraint': None,
                 'current_pages': [0,
                                   1],
                 'full-screen': False,
                 'notebook_display': 'normal',
                 'notebook_percent': 0.24843260188087779,
                 'override_title': None,
                 'pagelist': [('debug-stack',
                               'tall',
                               1,
                               {'codeline-mode': 'below'}),
                              ('indent',
                               'tall',
                               2,
                               {}),
                              ('project',
                               'tall',
                               0,
                               {'tree-state': {'file-sort-method': 'by name',
        'list-files-first': False,
        'tree-states': {'deep': {'column-widths': [1.0],
                                 'expanded-nodes': [(0,),
        (0,
         0),
        (0,
         1),
        (1,),
        (2,)],
                                 'selected-nodes': [(0,
        1,
        0)],
                                 'top-node': (0,)},
                        'flat': {'column-widths': [1.0],
                                 'expanded-nodes': [(0,)],
                                 'selected-nodes': [(0,)],
                                 'top-node': (0,)}},
        'tree-style': 'deep'}}),
                              ('pylintpanel#02EFWRQK9X24',
                               'tall',
                               0,
                               {}),
                              ('refactoring',
                               'tall',
                               0,
                               {}),
                              ('snippets',
                               'tall',
                               0,
                               {'tree-states': {'__all__': [],
        u'c': [['decl',
                'code',
                '']],
        u'django': [['a',
                     'content',
                     '']],
        u'html': [['a',
                   'content',
                   '']],
        u'py': [['class',
                 'all',
                 '']]}}),
                              ('source-assistant',
                               'tall',
                               2,
                               {'docstring-during-complete': False,
                                'wrap-lines': True}),
                              ('browser',
                               'tall',
                               0,
                               {'all_tree_states': {u'By Module': {'column-w'\
        'idths': [1.0],
        'expanded-nodes': [],
        'selected-nodes': [],
        'top-node': None}},
                                'browse_mode': u'By Module',
                                'follow-selection': False,
                                'sort_mode': 'Alphabetically',
                                'visibility_options': {u'Derived Classes': False,
        u'Imported': False,
        u'Modules': True}}),
                              ('uses',
                               'tall',
                               0,
                               {})],
                 'primary_view_state': {'area': 'wide',
        'constraint': None,
        'current_pages': [2,
                          0],
        'notebook_display': 'normal',
        'notebook_percent': 0.1464723926380368,
        'override_title': None,
        'pagelist': [('bookmarks',
                      'wide',
                      1,
                      {}),
                     ('debug-breakpoints',
                      'wide',
                      0,
                      {'tree-state': []}),
                     ('debug-io',
                      'wide',
                      1,
                      {'attrib-starts': [],
                       'first-line': 0,
                       'folded-linenos': [],
                       'sel-line': 0,
                       'sel-line-start': 0,
                       'selection_end': 0,
                       'selection_start': 0}),
                     ('debug-probe',
                      'wide',
                      2,
                      {'attrib-starts': [],
                       'first-line': 0,
                       'folded-linenos': [],
                       'history': {},
                       'sel-line': 0,
                       'sel-line-start': 0,
                       'selection_end': 0,
                       'selection_start': 0}),
                     ('debug-exceptions',
                      'wide',
                      0,
                      {}),
                     ('messages',
                      'wide',
                      2,
                      {'current-domain': 0}),
                     ('debug-modules',
                      'wide',
                      1,
                      {}),
                     ('os-command',
                      'wide',
                      1,
                      {'last-percent': 0.80000000000000004,
                       'toolbox-percent': 1.0,
                       'toolbox-tree-sel': 'cmd-1'}),
                     ('python-shell',
                      'wide',
                      2,
                      {}),
                     ('interactive-search',
                      'wide',
                      0,
                      {'fScope': {'fFileSetName': u'All Source Files',
                                  'fLocation': None,
                                  'fRecursive': True,
                                  'fType': 'project-files'},
                       'fSearchSpec': {'fEndPos': None,
                                       'fIncludeLinenos': True,
                                       'fInterpretBackslashes': False,
                                       'fMatchCase': False,
                                       'fOmitBinary': True,
                                       'fRegexFlags': 46,
                                       'fReplaceText': u'i',
                                       'fReverse': False,
                                       'fSearchText': u'ii',
                                       'fStartPos': 0,
                                       'fStyle': 'text',
                                       'fWholeWords': False,
                                       'fWrap': True},
                       'fUIOptions': {'fAutoBackground': True,
                                      'fFilePrefix': 'short-file',
                                      'fFindAfterReplace': True,
                                      'fInSelection': False,
                                      'fIncremental': True,
                                      'fReplaceOnDisk': False,
                                      'fShowFirstMatch': False,
                                      'fShowLineno': True,
                                      'fShowReplaceWidgets': True},
                       'replace-entry-expanded': False,
                       'search-entry-expanded': False}),
                     ('batch-search',
                      'wide',
                      0,
                      {'fScope': {'fFileSetName': u'All Source Files',
                                  'fLocation': None,
                                  'fRecursive': True,
                                  'fType': 'current-file'},
                       'fSearchSpec': {'fEndPos': None,
                                       'fIncludeLinenos': True,
                                       'fInterpretBackslashes': False,
                                       'fMatchCase': False,
                                       'fOmitBinary': True,
                                       'fRegexFlags': 46,
                                       'fReplaceText': u'domain',
                                       'fReverse': False,
                                       'fSearchText': u'smooth(',
                                       'fStartPos': 0,
                                       'fStyle': 'text',
                                       'fWholeWords': False,
                                       'fWrap': True},
                       'fUIOptions': {'fAutoBackground': True,
                                      'fFilePrefix': 'short-file',
                                      'fFindAfterReplace': True,
                                      'fInSelection': False,
                                      'fIncremental': True,
                                      'fReplaceOnDisk': False,
                                      'fShowFirstMatch': False,
                                      'fShowLineno': True,
                                      'fShowReplaceWidgets': False},
                       'replace-entry-expanded': False,
                       'search-entry-expanded': False}),
                     ('debug-data',
                      'wide',
                      0,
                      {}),
                     ('versioncontrol.svn',
                      'wide',
                      0,
                      {}),
                     ('testing',
                      'wide',
                      0,
                      {'added-files': [],
                       'filter': '',
                       'recent-filters': None,
                       'sort-order': 'alpha'}),
                     ('debug-watch',
                      'wide',
                      1,
                      {'node-states': [],
                       'tree-state': {'column-widths': [0.40126715945089758,
        0.59873284054910247],
                                      'expanded-nodes': [],
                                      'selected-nodes': [],
                                      'top-node': (0,)}})],
        'primary_view_state': {'editor_states': ('horizontal',
        0.5,
        {'bookmarks': ([[loc('../../../../../w21/prc/tcgen/w2.tc.tcgen2.py'),
                         {'attrib-starts': [],
                          'first-line': 2846,
                          'folded-linenos': [],
                          'sel-line': 2885,
                          'sel-line-start': 78899,
                          'selection_end': 78912,
                          'selection_start': 78907},
                         1376693598.1598589]],
                       0),
         'current-loc': None,
         'editor-states': {},
         'has-focus': False,
         'locked': False},
        {'bookmarks': ([(loc('../../../../../data/amb/projects/hfip/tcgen/js/tcGenJQuery.js'),
                         {'attrib-starts': [],
                          'first-line': 251,
                          'folded-linenos': [],
                          'sel-line': 288,
                          'sel-line-start': 10575,
                          'selection_end': 10576,
                          'selection_start': 10576},
                         1376689750.8697541),
                        (loc('../../../../../data/amb/projects/hfip/tcgen/inv.tcgen.js'),
                         {'attrib-starts': [],
                          'first-line': 216,
                          'folded-linenos': [],
                          'sel-line': 229,
                          'sel-line-start': 18314,
                          'selection_end': 18464,
                          'selection_start': 18464},
                         1376689769.4012949),
                        [loc('../../../../../data/amb/projects/hfip/tcgen/js/tcGenJQuery.js'),
                         {'attrib-starts': [],
                          'first-line': 251,
                          'folded-linenos': [],
                          'sel-line': 288,
                          'sel-line-start': 10575,
                          'selection_end': 10576,
                          'selection_start': 10576},
                         1376689796.460921],
                        [loc('../../prc/flddat/w2.fld.wget.mirror.cmc.gdps.py'),
                         {'attrib-starts': [],
                          'first-line': 0,
                          'folded-linenos': [],
                          'sel-line': 0,
                          'sel-line-start': 0,
                          'selection_end': 0,
                          'selection_start': 0},
                         1376692180.0957191],
                        [loc('../../../../../w21/prc/tcgen/w2.tc.tcgen2.py'),
                         {'attrib-starts': [],
                          'first-line': 2846,
                          'folded-linenos': [],
                          'sel-line': 2885,
                          'sel-line-start': 78899,
                          'selection_end': 78912,
                          'selection_start': 78907},
                         1376693598.101299]],
                       4),
         'current-loc': None,
         'editor-states': {},
         'has-focus': False,
         'locked': False}),
                               'open_files': []},
        'saved_notebook_display': None,
        'split_percents': {0: 0.53588266107909899},
        'splits': 2,
        'tab_location': 'top',
        'user_data': {}},
                 'saved_notebook_display': None,
                 'split_percents': {0: 0.5},
                 'splits': 2,
                 'tab_location': 'left',
                 'user_data': {}},
        'window-alloc': (-4,
                         -4,
                         1280,
                         800)}]}
guimgr.recent-documents = [loc('../../../../../data/amb/projects/hfip/tcgen/js/tcGenJQuery.js'),
                           loc('../../../../../w21/prc/tcgen/w2.tc.tcgen2.py')]
guimgr.visual-state = {loc('../../../../../data/amb/projects/hfip/tcgen/inv.tcgen.txt'): {''\
        'attrib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 0,
        'selection_start': 0},
                       loc('../../../../../data/amb/projects/hfip/tcgen/js/tcGenJQuery.js'): {''\
        'attrib-starts': [],
        'first-line': 156,
        'folded-linenos': [],
        'sel-line': 216,
        'sel-line-start': 8133,
        'selection_end': 8150,
        'selection_start': 8150},
                       loc('../../../../../data/amb/projects/hfip/tcgen/tcGenInv.js'): {''\
        'attrib-starts': [],
        'first-line': 96,
        'folded-linenos': [],
        'sel-line': 82,
        'sel-line-start': 3635,
        'selection_end': 3650,
        'selection_start': 3650},
                       loc('../../../../../data/rapb/projects/wxmap2/prwInv.js'): {''\
        'attrib-starts': [],
        'first-line': 71,
        'folded-linenos': [],
        'sel-line': 92,
        'sel-line-start': 4845,
        'selection_end': 4926,
        'selection_start': 4926},
                       loc('../../Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/UserDict.py'): {''\
        'attrib-starts': [('UserDict',
                           2),
                          ('UserDict.__getitem__',
                           17)],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 22,
        'sel-line-start': 781,
        'selection_end': 781,
        'selection_start': 781},
                       loc('../../Volumes/dat1/w21/prc/flddat/l2.py'): {'att'\
        'rib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 47,
        'sel-line-start': 782,
        'selection_end': 796,
        'selection_start': 787},
                       loc('../../Volumes/dat1/w21/prc/lib/python/FM.py'): {''\
        'attrib-starts': [('FimRun',
                           2053),
                          ('FimRun.DoGrib',
                           3046)],
        'first-line': 3030,
        'folded-linenos': [],
        'sel-line': 3046,
        'sel-line-start': 92456,
        'selection_end': 92471,
        'selection_start': 92464},
                       loc('../../Volumes/dat1/w21/prc/lib/python/HFIP.py'): {''\
        'attrib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 7,
        'sel-line-start': 111,
        'selection_end': 125,
        'selection_start': 116},
                       loc('../../Volumes/dat1/w21/prc/lib/python/TCdiag.py'): {''\
        'attrib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 5,
        'sel-line-start': 49,
        'selection_end': 63,
        'selection_start': 54},
                       loc('../../Volumes/dat1/w21/prc/lib/python/jet/FM.py'): {''\
        'attrib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 7,
        'sel-line-start': 90,
        'selection_end': 90,
        'selection_start': 90},
                       loc('../../prc/flddat/w2.du.py'): {'attrib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 0,
        'selection_start': 0},
                       loc('../../prc/flddat/w2.fld.tigge.ecmwf.py'): {'attr'\
        'ib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 0,
        'selection_start': 0},
                       loc('../../prc/lib/python/ATCF.py'): {'attrib-starts': [(''\
        'EaidProperties',
        841)],
        'first-line': 696,
        'folded-linenos': [],
        'sel-line': 841,
        'sel-line-start': 35107,
        'selection_end': 35127,
        'selection_start': 35113},
                       loc('../../prc/lib/python/atcf.py'): {'attrib-starts': [(''\
        'IsTrackModelAlias',
        993)],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 993,
        'sel-line-start': 45328,
        'selection_end': 45349,
        'selection_start': 45332},
                       loc('../../prc/lib/python/ecmwf.py'): {'attrib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 0,
        'selection_start': 0},
                       loc('../../prc/lib/python/tcbase.py'): {'attrib-start'\
        's': [('aceTC',
               444)],
        'first-line': 0,
        'folded-linenos': [91,
                           106,
                           121,
                           136,
                           158,
                           163,
                           177,
                           192,
                           206,
                           219,
                           232,
                           245,
                           258,
                           271,
                           284,
                           297,
                           310,
                           327,
                           336,
                           345,
                           354,
                           363,
                           372,
                           381,
                           389,
                           422,
                           426,
                           429,
                           433,
                           437,
                           444,
                           445,
                           447,
                           452,
                           461,
                           473,
                           483,
                           489,
                           495,
                           505,
                           513,
                           515,
                           524,
                           525,
                           529,
                           532,
                           535,
                           541,
                           542,
                           555,
                           559,
                           560,
                           562,
                           566,
                           567,
                           569,
                           572,
                           581,
                           586,
                           589,
                           591,
                           593,
                           595,
                           598,
                           599,
                           601,
                           603,
                           604,
                           606,
                           610,
                           614,
                           616,
                           621,
                           627,
                           633,
                           642,
                           645,
                           652,
                           655,
                           663,
                           667,
                           669,
                           671,
                           677,
                           679,
                           689,
                           692,
                           697,
                           699,
                           709,
                           712,
                           719,
                           726,
                           728,
                           730,
                           734,
                           738,
                           741,
                           744,
                           748,
                           750,
                           753,
                           758,
                           766,
                           773,
                           775,
                           777,
                           781,
                           785,
                           788,
                           791,
                           795,
                           797,
                           800,
                           803,
                           806,
                           807,
                           810,
                           814,
                           821,
                           847,
                           868,
                           872,
                           874,
                           882,
                           894,
                           899,
                           902,
                           905,
                           912,
                           914,
                           915,
                           918,
                           930,
                           940,
                           945,
                           948,
                           951,
                           953,
                           955,
                           956,
                           958,
                           973,
                           981,
                           987,
                           1003,
                           1012,
                           1021,
                           1023,
                           1033,
                           1035,
                           1041,
                           1046,
                           1047,
                           1050,
                           1061,
                           1064,
                           1066,
                           1072,
                           1075,
                           1080,
                           1085,
                           1091,
                           1097,
                           1101,
                           1103,
                           1109,
                           1111,
                           1113,
                           1120,
                           1124,
                           1126,
                           1132,
                           1134,
                           1136,
                           1144,
                           1148,
                           1150,
                           1156,
                           1158,
                           1160,
                           1168,
                           1170,
                           1173,
                           1177,
                           1185,
                           1190,
                           1195,
                           1201,
                           1214,
                           1217,
                           1219,
                           1225,
                           1228,
                           1237,
                           1246,
                           1255,
                           1260,
                           1266,
                           1270,
                           1277,
                           1283,
                           1287,
                           1294,
                           1296,
                           1300,
                           1301,
                           1305,
                           1316,
                           1318,
                           1322,
                           1323,
                           1327,
                           1337,
                           1338,
                           1340,
                           1341,
                           1343,
                           1345,
                           1350,
                           1352,
                           1363,
                           1364,
                           1369,
                           1375,
                           1379,
                           1382,
                           1385,
                           1392,
                           1397,
                           1399,
                           1402,
                           1412,
                           1415,
                           1421,
                           1425,
                           1432,
                           1436,
                           1441,
                           1447,
                           1454,
                           1459,
                           1464,
                           1468,
                           1470,
                           1472,
                           1486,
                           1488,
                           1490,
                           1495,
                           1505,
                           1507,
                           1511,
                           1516,
                           1520,
                           1525,
                           1527,
                           1540,
                           1543,
                           1545,
                           1556,
                           1557,
                           1562,
                           1568,
                           1572,
                           1575,
                           1578,
                           1585,
                           1592,
                           1593,
                           1597,
                           1602,
                           1606,
                           1609,
                           1610,
                           1613,
                           1617,
                           1619,
                           1620,
                           1624,
                           1625,
                           1628,
                           1635,
                           1640,
                           1642,
                           1647,
                           1654,
                           1674,
                           1677,
                           1679,
                           1683,
                           1689,
                           1690,
                           1692,
                           1695,
                           1698,
                           1700,
                           1710,
                           1720,
                           1723,
                           1729,
                           1733,
                           1735,
                           1751,
                           1754,
                           1756,
                           1762,
                           1769,
                           1772,
                           1773,
                           1775,
                           1778,
                           1780,
                           1787,
                           1789,
                           1791,
                           1797,
                           1798,
                           1804,
                           1907,
                           1927,
                           1936,
                           1949,
                           1953,
                           1962,
                           1966,
                           1969,
                           1977,
                           1989,
                           1998,
                           2000,
                           2002,
                           2009,
                           2028,
                           2031,
                           2057,
                           2061,
                           2063,
                           2078,
                           2081,
                           2087,
                           2092,
                           2097,
                           2118,
                           2125,
                           2128,
                           2134,
                           2139,
                           2147,
                           2149,
                           2155,
                           2157,
                           2162,
                           2166,
                           2168,
                           2170,
                           2175,
                           2187,
                           2199,
                           2203,
                           2223,
                           2225,
                           2237,
                           2248,
                           2251,
                           2253,
                           2255,
                           2256,
                           2267,
                           2268,
                           2271,
                           2297,
                           2300,
                           2304,
                           2312,
                           2329,
                           2350,
                           2351,
                           2357,
                           2368,
                           2373,
                           2375,
                           2377,
                           2381,
                           2383,
                           2386,
                           2390,
                           2392,
                           2395,
                           2403,
                           2404,
                           2423,
                           2445,
                           2459,
                           2471,
                           2474,
                           2481,
                           2484,
                           2506,
                           2510,
                           2518,
                           2523,
                           2526,
                           2532,
                           2540,
                           2542,
                           2545,
                           2548,
                           2550,
                           2553,
                           2555,
                           2558,
                           2561,
                           2563,
                           2574,
                           2582,
                           2584,
                           2591,
                           2592,
                           2607,
                           2623,
                           2628,
                           2632,
                           2637,
                           2644,
                           2649,
                           2656,
                           2661,
                           2668,
                           2673,
                           2681,
                           2683,
                           2692,
                           2699,
                           2706,
                           2712,
                           2719,
                           2726,
                           2733,
                           2740,
                           2749,
                           2759,
                           2766,
                           2783,
                           2785,
                           2787,
                           2797,
                           2804,
                           2806,
                           2808,
                           2810,
                           2819,
                           2826,
                           2828,
                           2840,
                           2844,
                           2847,
                           2850,
                           2853,
                           2856,
                           2860,
                           2866,
                           2870,
                           2880,
                           2887,
                           2892,
                           2893,
                           2896,
                           2898,
                           2904,
                           2906,
                           2911,
                           2914,
                           2916,
                           2921,
                           2926,
                           2933,
                           2938,
                           2949,
                           2970,
                           2972,
                           2984,
                           2987,
                           2990,
                           2992,
                           2997,
                           2999,
                           3004,
                           3005,
                           3007,
                           3009,
                           3019,
                           3020,
                           3021,
                           3023,
                           3032,
                           3038,
                           3043,
                           3045,
                           3047,
                           3061,
                           3063,
                           3065,
                           3068,
                           3076,
                           3078,
                           3080,
                           3082,
                           3090,
                           3092,
                           3093,
                           3138,
                           3143,
                           3150,
                           3154,
                           3174,
                           3175,
                           3179,
                           3186,
                           3187,
                           3194,
                           3197,
                           3199,
                           3201,
                           3212,
                           3222,
                           3223,
                           3236,
                           3248,
                           3251,
                           3256,
                           3257,
                           3263,
                           3268,
                           3273,
                           3317,
                           3326,
                           3332,
                           3346,
                           3350,
                           3353,
                           3357,
                           3364,
                           3367,
                           3369,
                           3372,
                           3374,
                           3377,
                           3379,
                           3383,
                           3387,
                           3390,
                           3395,
                           3399,
                           3402,
                           3406,
                           3413,
                           3416,
                           3419,
                           3422,
                           3424,
                           3427,
                           3429,
                           3433,
                           3437,
                           3440,
                           3446,
                           3451,
                           3457,
                           3459,
                           3462,
                           3466,
                           3485,
                           3489,
                           3491,
                           3493,
                           3495,
                           3510,
                           3520,
                           3524,
                           3540,
                           3542,
                           3545,
                           3550,
                           3552,
                           3559,
                           3564,
                           3565,
                           3567,
                           3571,
                           3593,
                           3594,
                           3601,
                           3607,
                           3624,
                           3625,
                           3632,
                           3638,
                           3691,
                           3696,
                           3699,
                           3703,
                           3707,
                           3727,
                           3733,
                           3734,
                           3737,
                           3740,
                           3749,
                           3760,
                           3762,
                           3767,
                           3773,
                           3774,
                           3779,
                           3786,
                           3790,
                           3798,
                           3802,
                           3807,
                           3813,
                           3818,
                           3829,
                           3832,
                           3844,
                           3847,
                           3876,
                           3877,
                           3882,
                           3888,
                           3894,
                           3896,
                           3898,
                           3900,
                           3913,
                           3915,
                           3918,
                           3920,
                           3923,
                           3934,
                           3940,
                           3955,
                           3957,
                           3959,
                           3961,
                           3966,
                           3967,
                           3969,
                           3972,
                           3976,
                           3978,
                           3981,
                           3985,
                           3986,
                           3988,
                           3996,
                           4000,
                           4003,
                           4006,
                           4024,
                           4027,
                           4032,
                           4034,
                           4051,
                           4054,
                           4056,
                           4060,
                           4061,
                           4064,
                           4071,
                           4073,
                           4089,
                           4126,
                           4130,
                           4135,
                           4137,
                           4142,
                           4143,
                           4152,
                           4155,
                           4172,
                           4177,
                           4183,
                           4191,
                           4193,
                           4194,
                           4196,
                           4203,
                           4207,
                           4211,
                           4216,
                           4221,
                           4225,
                           4231,
                           4237,
                           4240,
                           4241,
                           4245,
                           4255,
                           4257,
                           4265,
                           4272,
                           4273,
                           4279,
                           4283,
                           4293,
                           4300,
                           4309,
                           4310,
                           4316,
                           4320,
                           4329,
                           4335,
                           4347,
                           4371,
                           4382,
                           4396,
                           4424,
                           4440,
                           4445,
                           4452,
                           4467,
                           4472,
                           4476,
                           4479,
                           4482,
                           4508,
                           4511,
                           4519,
                           4521,
                           4545,
                           4546,
                           4554,
                           4561,
                           4564,
                           4570,
                           4572,
                           4583,
                           4586,
                           4591,
                           4592,
                           4595,
                           4598,
                           4599,
                           4602,
                           4605,
                           4606,
                           4609,
                           4612,
                           4613,
                           4616,
                           4624,
                           4627,
                           4630,
                           4632,
                           4635,
                           4638,
                           4640,
                           4643,
                           4646,
                           4648,
                           4651,
                           4654,
                           4656,
                           4659,
                           4662,
                           4671,
                           4674,
                           4680,
                           4683,
                           4690,
                           4698,
                           4702,
                           4704,
                           4706,
                           4707,
                           4709,
                           4711,
                           4713,
                           4720,
                           4725,
                           4728,
                           4736,
                           4738,
                           4757,
                           4761,
                           4765,
                           4769,
                           4776,
                           4778,
                           4781,
                           4783,
                           4788,
                           4789,
                           4791,
                           4801,
                           4807,
                           4811,
                           4819,
                           4826,
                           4828,
                           4833,
                           4836,
                           4844,
                           4848,
                           4854,
                           4856,
                           4858,
                           4861,
                           4874,
                           4878,
                           4880,
                           4885,
                           4889,
                           4894,
                           4896,
                           4899,
                           4907,
                           4908,
                           4910,
                           4912,
                           4915,
                           4916,
                           4919,
                           4922,
                           4923,
                           4926,
                           4933,
                           4957,
                           4968,
                           4982],
        'sel-line': 446,
        'sel-line-start': 7836,
        'selection_end': 7857,
        'selection_start': 7857},
                       loc('../prc/fldanal/w2.prw.loop.py'): {'attrib-starts': [],
        'first-line': 446,
        'folded-linenos': [],
        'sel-line': 458,
        'sel-line-start': 11408,
        'selection_end': 11408,
        'selection_start': 11408},
                       loc('../prc/flddat/l2.py'): {'attrib-starts': [],
        'first-line': 155,
        'folded-linenos': [],
        'sel-line': 201,
        'sel-line-start': 4327,
        'selection_end': 4327,
        'selection_start': 4327},
                       loc('../prc/flddat/w2.fld.cpc.wget.py'): {'attrib-sta'\
        'rts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 0,
        'selection_start': 0},
                       loc('../prc/flddat/w2.fld.wget.mirror.cmc.gdps.py'): {''\
        'attrib-starts': [('makeCtl',
                           40)],
        'first-line': 1,
        'folded-linenos': [],
        'sel-line': 71,
        'sel-line-start': 2024,
        'selection_end': 2037,
        'selection_start': 2037},
                       loc('../prc/flddat/w2.fld.wget.mirror.cpc.oisst.py'): {''\
        'attrib-starts': [],
        'first-line': 16,
        'folded-linenos': [],
        'sel-line': 48,
        'sel-line-start': 951,
        'selection_end': 980,
        'selection_start': 980},
                       loc('../prc/flddat/w2.fld.wget.mirror.gfs.stbgoes.py'): {''\
        'attrib-starts': [],
        'first-line': 72,
        'folded-linenos': [],
        'sel-line': 106,
        'sel-line-start': 2779,
        'selection_end': 2817,
        'selection_start': 2779},
                       loc('../prc/lib/python/AD.py'): {'attrib-starts': [(''\
        'Adeck',
        1058),
        ('Adeck.GetAidStmids',
         1796)],
        'first-line': 1790,
        'folded-linenos': [],
        'sel-line': 1808,
        'sel-line-start': 44702,
        'selection_end': 44739,
        'selection_start': 44739},
                       loc('../prc/lib/python/ATCF.py'): {'attrib-starts': [(''\
        'AidProp',
        148),
        ('AidProp.__init__',
         608)],
        'first-line': 598,
        'folded-linenos': [],
        'sel-line': 660,
        'sel-line-start': 30875,
        'selection_end': 30896,
        'selection_start': 30896},
                       loc('../prc/lib/python/CM.py'): {'attrib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 0,
        'selection_start': 0},
                       loc('../prc/lib/python/ECtigge.py'): {'attrib-starts': [(''\
        'ECMWFDataServer',
        5),
        ('ECMWFDataServer._call',
         12)],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 29,
        'sel-line-start': 699,
        'selection_end': 723,
        'selection_start': 723},
                       loc('../prc/lib/python/FM.py'): {'attrib-starts': [(''\
        'FieldRequest',
        1837)],
        'first-line': 1834,
        'folded-linenos': [],
        'sel-line': 1839,
        'sel-line-start': 55038,
        'selection_end': 55094,
        'selection_start': 55094},
                       loc('../prc/lib/python/FM2.py'): {'attrib-starts': [],
        'first-line': 2935,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 119593,
        'selection_start': 0},
                       loc('../prc/lib/python/M.py'): {'attrib-starts': [('M'\
        'Futils',
        207),
        ('MFutils.getPathSiz',
         412)],
        'first-line': 379,
        'folded-linenos': [],
        'sel-line': 412,
        'sel-line-start': 10800,
        'selection_end': 10818,
        'selection_start': 10808},
                       loc('../prc/lib/python/M2.py'): {'attrib-starts': [(''\
        'Cgd2',
        3395),
        ('Cgd2.__init__',
         3403)],
        'first-line': 3387,
        'folded-linenos': [],
        'sel-line': 3405,
        'sel-line-start': 97548,
        'selection_end': 97572,
        'selection_start': 97572},
                       loc('../prc/lib/python/TCdiag.py'): {'attrib-starts': [(''\
        'TcDiag',
        355),
        ('TcDiag.replaceAidcards',
         1905)],
        'first-line': 1890,
        'folded-linenos': [],
        'sel-line': 1905,
        'sel-line-start': 55028,
        'selection_end': 55051,
        'selection_start': 55036},
                       loc('../prc/lib/python/TCdiag2.py'): {'attrib-starts': [(''\
        'Oisst',
        5096),
        ('Oisst.__init__',
         5104)],
        'first-line': 3508,
        'folded-linenos': [],
        'sel-line': 5151,
        'sel-line-start': 120669,
        'selection_end': 120686,
        'selection_start': 120686},
                       loc('../prc/lib/python/VD.py'): {'attrib-starts': [(''\
        'MakeVdeckS',
        789)],
        'first-line': 883,
        'folded-linenos': [],
        'sel-line': 944,
        'sel-line-start': 23529,
        'selection_end': 23553,
        'selection_start': 23553},
                       loc('../prc/lib/python/VT.py'): {'attrib-starts': [(''\
        'SumStatsPlot',
        203),
        ('SumStatsPlot.smooth',
         463)],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 490,
        'sel-line-start': 11712,
        'selection_end': 11712,
        'selection_start': 11712},
                       loc('../prc/lib/python/WxMAP2.py'): {'attrib-starts': [(''\
        'f77GridOutput',
        555),
        ('f77GridOutput.getDpaths',
         1036)],
        'first-line': 1011,
        'folded-linenos': [],
        'sel-line': 1036,
        'sel-line-start': 23359,
        'selection_end': 23376,
        'selection_start': 23367},
                       loc('../prc/lib/python/ad2.py'): {'attrib-starts': [(''\
        'AdeckSources',
        8),
        ('AdeckSources.setAdeckSource',
         43)],
        'first-line': 453,
        'folded-linenos': [],
        'sel-line': 475,
        'sel-line-start': 17799,
        'selection_end': 17839,
        'selection_start': 17839},
                       loc('../prc/lib/python/atcf.py'): {'attrib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 470,
        'sel-line-start': 33769,
        'selection_end': 33769,
        'selection_start': 33769},
                       loc('../prc/lib/python/const.py'): {'attrib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 0,
        'selection_start': 0},
                       loc('../prc/lib/python/ga2.py'): {'attrib-starts': [(''\
        'setGA',
        2620),
        ('setGA.W2GaNum',
         2785)],
        'first-line': 2728,
        'folded-linenos': [],
        'sel-line': 2788,
        'sel-line-start': 75811,
        'selection_end': 75811,
        'selection_start': 75811},
                       loc('../prc/lib/python/jet/FM.py'): {'attrib-starts': [],
        'first-line': 3713,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 119593,
        'selection_start': 0},
                       loc('../prc/lib/python/mf.py'): {'attrib-starts': [(''\
        'dtg',
        199)],
        'first-line': 196,
        'folded-linenos': [],
        'sel-line': 253,
        'sel-line-start': 5308,
        'selection_end': 5318,
        'selection_start': 5318},
                       loc('../prc/lib/python/nwp.py'): {'attrib-starts': [(''\
        'Nwp2Models',
        10),
        ('Nwp2Models.__init__',
         31)],
        'first-line': 65,
        'folded-linenos': [],
        'sel-line': 65,
        'sel-line-start': 1835,
        'selection_end': 1835,
        'selection_start': 1835},
                       loc('../prc/lib/python/tc2.py'): {'attrib-starts': [(''\
        'StormData',
        98)],
        'first-line': 49,
        'folded-linenos': [],
        'sel-line': 100,
        'sel-line-start': 2252,
        'selection_end': 2262,
        'selection_start': 2260},
                       loc('../prc/lib/python/tcbase.py'): {'attrib-starts': [(''\
        'getTyphoonCat',
        475)],
        'first-line': 483,
        'folded-linenos': [],
        'sel-line': 483,
        'sel-line-start': 8713,
        'selection_end': 8713,
        'selection_start': 8713},
                       loc('../prc/lib/python/tigge.py'): {'attrib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 0,
        'selection_start': 0},
                       loc('../prc/lib/python/tutt.py'): {'attrib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 18,
        'selection_start': 17},
                       loc('../prc/lib/python/ukmo.py'): {'attrib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 0,
        'selection_start': 0},
                       loc('../prc/lib/python/w2base.py'): {'attrib-starts': [(''\
        'W2Base',
        80),
        ('W2Base.initW2VarsAll',
         355)],
        'first-line': 858,
        'folded-linenos': [],
        'sel-line': 900,
        'sel-line-start': 30093,
        'selection_end': 30139,
        'selection_start': 30137},
                       loc('../prc/lib/python/w2colors.py'): {'attrib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 0,
        'selection_start': 0},
                       loc('../prc/lib/python/w2env.py'): {'attrib-starts': [(''\
        'W2env',
        6)],
        'first-line': 569,
        'folded-linenos': [],
        'sel-line': 577,
        'sel-line-start': 12326,
        'selection_end': 12405,
        'selection_start': 12345},
                       loc('../prc/lib/python/w2globalvars.py'): {'attrib-st'\
        'arts': [],
        'first-line': 103,
        'folded-linenos': [],
        'sel-line': 128,
        'sel-line-start': 3355,
        'selection_end': 3368,
        'selection_start': 3355},
                       loc('../prc/lib/python/w2localvars.py'): {'attrib-sta'\
        'rts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 27,
        'sel-line-start': 782,
        'selection_end': 782,
        'selection_start': 782},
                       loc('../prc/tcdat/localvdstat2.py'): {'attrib-starts': [(''\
        'lsStmStat',
        2373)],
        'first-line': 2351,
        'folded-linenos': [],
        'sel-line': 2375,
        'sel-line-start': 56436,
        'selection_end': 56459,
        'selection_start': 56450},
                       loc('../prc/tcdat/w2.tc.dss.adeck.py'): {'attrib-star'\
        'ts': [],
        'first-line': 192,
        'folded-linenos': [],
        'sel-line': 14,
        'sel-line-start': 224,
        'selection_end': 224,
        'selection_start': 224},
                       loc('../prc/tcdat/w2.tc.dss.md2.anl.py'): {'attrib-st'\
        'arts': [],
        'first-line': 292,
        'folded-linenos': [],
        'sel-line': 357,
        'sel-line-start': 8205,
        'selection_end': 8246,
        'selection_start': 8205},
                       loc('../prc/tcdat/w2.tc.dss.md2.py'): {'attrib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 0,
        'selection_start': 0},
                       loc('../prc/tcdat/w2.tc.dss.md2.trkplot.py'): {'attri'\
        'b-starts': [('MdeckCmdLine',
                      291),
                     ('MdeckCmdLine.__init__',
                      295)],
        'first-line': 281,
        'folded-linenos': [],
        'sel-line': 319,
        'sel-line-start': 8656,
        'selection_end': 8656,
        'selection_start': 8656},
                       loc('../prc/tcdat/w2.tc.dss.vdeck.anl-ts.py'): {'attr'\
        'ib-starts': [('getStats',
                       398)],
        'first-line': 616,
        'folded-linenos': [],
        'sel-line': 491,
        'sel-line-start': 11471,
        'selection_end': 11471,
        'selection_start': 11471},
                       loc('../prc/tcdat/w2.tc.dss.vdeck.anl.py'): {'attrib-'\
        'starts': [('getStats',
                    351)],
        'first-line': 571,
        'folded-linenos': [],
        'sel-line': 582,
        'sel-line-start': 16023,
        'selection_end': 16032,
        'selection_start': 16032},
                       loc('../prc/tcdat/w2.tc.dss.vdeck.py'): {'attrib-star'\
        'ts': [('VdeckCmdLine',
                11),
               ('VdeckCmdLine.__init__',
                13)],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 13,
        'sel-line-start': 250,
        'selection_end': 287,
        'selection_start': 287},
                       loc('../prc/tcdat/w2.tc.posit.py'): {'attrib-starts': [],
        'first-line': 210,
        'folded-linenos': [],
        'sel-line': 243,
        'sel-line-start': 4333,
        'selection_end': 4333,
        'selection_start': 4333},
                       loc('../prc/tcdiag/w2.tc.lsdiag.py'): {'attrib-starts': [],
        'first-line': 706,
        'folded-linenos': [],
        'sel-line': 711,
        'sel-line-start': 22360,
        'selection_end': 22388,
        'selection_start': 22388},
                       loc('../prc/tctrk/w2.tc.tmtrkN.py'): {'attrib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 165,
        'sel-line-start': 4142,
        'selection_end': 4143,
        'selection_start': 4143},
                       loc('../src/tcnavytrk/ngtrk.f'): {'attrib-starts': [],
        'first-line': 196,
        'folded-linenos': [],
        'sel-line': 203,
        'sel-line-start': 6736,
        'selection_end': 6746,
        'selection_start': 6746},
                       loc('tc/20110413_tcgen2/p.tcgen2.py'): {'attrib-start'\
        's': [('Tcgen',
               591),
              ('Tcgen.setTCgenProps',
               714)],
        'first-line': 939,
        'folded-linenos': [],
        'sel-line': 947,
        'sel-line-start': 25471,
        'selection_end': 25504,
        'selection_start': 25504},
                       loc('tcGenJQuery.js'): {'attrib-starts': [],
        'first-line': 448,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 28955,
        'selection_start': 0},
                       loc('untitled-1.js'): {'attrib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 0,
        'selection_start': 0},
                       loc('../../../../../w21/prc/lib/python/tc2.py'): {'at'\
        'trib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 0,
        'selection_start': 0},
                       loc('../../../../../w21/prc/lib/python/tcbase.py'): {''\
        'attrib-starts': [('makeTcgenJsInventory',
                           6612)],
        'first-line': 6606,
        'folded-linenos': [],
        'sel-line': 6651,
        'sel-line-start': 151599,
        'selection_end': 151611,
        'selection_start': 151611},
                       loc('../../../../../w21/prc/tcdat/w2.tc.dss.vdeck.anl.py'): {''\
        'attrib-starts': [],
        'first-line': 1300,
        'folded-linenos': [],
        'sel-line': 1335,
        'sel-line-start': 39510,
        'selection_end': 39540,
        'selection_start': 39535},
                       loc('../../../../../w21/prc/tcgen/w2.tc.tcgen2.py'): {''\
        'attrib-starts': [],
        'first-line': 2846,
        'folded-linenos': [],
        'sel-line': 2885,
        'sel-line-start': 78899,
        'selection_end': 78912,
        'selection_start': 78907},
                       loc('../../../../../w3/rapb/hfip/tcgen/js/tcGenJQuery.js'): {''\
        'attrib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 0,
        'selection_start': 0},
                       loc('../../../../../w3/rapb/lopez/20130521_js_jquery_dev/js'): {''\
        'attrib-starts': [],
        'first-line': 0,
        'folded-linenos': [],
        'sel-line': 0,
        'sel-line-start': 0,
        'selection_end': 0,
        'selection_start': 0},
                       loc('../../../../../w3/rapb/lopez/20130521_js_jquery_dev/js/tcGenJQuery.js'): {''\
        'attrib-starts': [],
        'first-line': 64,
        'folded-linenos': [],
        'sel-line': 72,
        'sel-line-start': 2828,
        'selection_end': 2918,
        'selection_start': 2918},
                       loc('../../../../../w3/rapb/lopez/js/tcGenJQuery.js'): {''\
        'attrib-starts': [],
        'first-line': 395,
        'folded-linenos': [],
        'sel-line': 398,
        'sel-line-start': 14995,
        'selection_end': 15536,
        'selection_start': 14995},
                       loc('../../../../../w3/rapb/wxmap2/js/prwLoopJQuery.js'): {''\
        'attrib-starts': [],
        'first-line': 193,
        'folded-linenos': [],
        'sel-line': 243,
        'sel-line-start': 6919,
        'selection_end': 6936,
        'selection_start': 6923}}
proj.build-cmd = {None: ('default',
                         None),
                  loc('../prc/lib/python/M2.py'): ('project',
        'cmd-1'),
                  loc('../prc/lib/python/tc2.py'): ('project',
        None),
                  loc('../prc/lib/python/tcbase.py'): ('project',
        'cmd-1'),
                  loc('../prc/tcdat/localvdstat2.py'): ('project',
        'cmd-1'),
                  loc('../prc/tcdat/w2.tc.dss.md2.anl.py'): ('project',
        'cmd-1'),
                  loc('../prc/tcdat/w2.tc.dss.vdeck.anl.py'): ('project',
        'cmd-1'),
                  loc('../prc/tcdiag/w2.tc.lsdiag.py'): ('project',
        'cmd-1'),
                  loc('tc/20110413_tcgen2/p.tcgen2.py'): ('project',
        'cmd-1')}
proj.env-vars = {None: ('default',
                        ['']),
                 loc('../prc/lib/python/M2.py'): ('project',
        ['']),
                 loc('../prc/lib/python/tc2.py'): ('project',
        ['']),
                 loc('../prc/lib/python/tcbase.py'): ('project',
        ['']),
                 loc('../prc/tcdat/localvdstat2.py'): ('project',
        ['']),
                 loc('../prc/tcdat/w2.tc.dss.md2.anl.py'): ('project',
        ['']),
                 loc('../prc/tcdat/w2.tc.dss.vdeck.anl.py'): ('project',
        ['']),
                 loc('../prc/tcdiag/w2.tc.lsdiag.py'): ('project',
        [''])}
proj.pypath = {None: ('default',
                      '/w21/app/python/bin:')}
search.replace-history = [u'i',
                          u'fcbasinn',
                          u'vdtg',
                          u'aTC',
                          u'wget.cmc.gdps',
                          u'domain',
                          u'Domains',
                          u'DDD']
search.search-history = [u'smooth(',
                         u'ii',
                         u'iii',
                         u'basin',
                         u'no adeck cards',
                         u'smooth',
                         u'dtgs',
                         u"'MFC'",
                         u'nTCs',
                         u'dtgopt',
                         u'no adeck struct',
                         u'btcs',
                         u'gentau',
                         u'self.vdtg',
                         u'self.gentau',
                         u'dtype',
                         u'mTC',
                         u'mtc',
                         u'dorsync',
                         u'wget.cpc.oisst']
search.search-scope-history = [loc('../prc'),
                               loc('../../Volumes/dat1/w21/prj/tc/20110413_tcgen2/nFCGNs'),
                               loc('../../Volumes/dat1/w21/prj/tc/20110413_tcgen2/nFCGN'),
                               loc('../../Volumes/dat1/w21/prj/tc/20110413_tcgen2/n'),
                               loc('../../Volumes/dat1/w21/prj/tc/20110413_tcgen2/nCurrent File'),
                               loc('../../Volumes/dat1/w21/prj/tc/20110413_tcgen2/nFCGNsCurrent File'),
                               loc('../../Volumes/dat1/w21/prj/tc/20110413_tcgen2/nFCGNCurrent File'),
                               loc('../../Volumes/dat1/w21/prj/tc/20110413_tcgen2/bCurrent File'),
                               loc('../../Volumes/dat1/w21/prj/tc/20110413_tcgen2/Current Filepar'),
                               loc('../../Volumes/dat1/w21/prj/tc/20110413_tcgen2/parsehash'),
                               loc('../../Volumes/dat1/w21/prj/tc/20110413_tcgen2/par'),
                               loc('../prc/tc'),
                               loc('../prc/tc*')]
[project attributes]
proj.directory-list = [{'dirloc': loc('../../../../../w21/prc/lib/python'),
                        'excludes': (),
                        'filter': 'Python Files',
                        'include_hidden': False,
                        'recursive': False,
                        'watch_for_changes': True}]
proj.file-list = [loc('../../../../../data/amb/projects/hfip/tcgen/css/wxmain2.css'),
                  loc('../../../../../data/amb/projects/hfip/tcgen/inv.tcgen.js'),
                  loc('../../../../../data/amb/projects/hfip/tcgen/inv.tcgen.txt'),
                  loc('../../../../../data/amb/projects/hfip/tcgen/js/dropdown.js'),
                  loc('../../../../../data/amb/projects/hfip/tcgen/js/tcGenJQuery.js'),
                  loc('../../../../../data/amb/projects/hfip/tcgen/tcgen.htm'),
                  loc('../../../../../data/amb/projects/hfip/tcgen/tcgen.php'),
                  loc('../../../../../data/amb/projects/hfip/tcgen/tcGenInv.js'),
                  loc('../../../../../data/rapb/projects/wxmap2/prwInv.js'),
                  loc('../../../../../w3/rapb/wxmap2/js/prwLoopJQuery.js')]
proj.file-type = 'normal'
