
      real              blat( 200 )

      real              blng( 200 )

      real              hlat( 1201 )

      real              hlng( 1201 )

      integer           numpos

      integer           idif

      common /bestc/    blat ,
     &                  blng ,
     &                  hlat ,
     &                  hlng ,
     &                  numpos ,
     &                  idif

