c
c  SCCS IDENTIFICATION: 
c
c     name          description
c   ----------   --------------------------------------------
c   iwndmx       initial maximum wind (kts)
c   mwndmx       model cyclone maximum wind (kts)
c   icyc         i-grid point of initial cyclone location
c   jcyc         j-grid point of initial cyclone location
c
      integer  iwndmx, mwndmx, icyc, jcyc
c
      common/i_cyclone/ iwndmx,mwndmx,icyc,jcyc
