
      real              flat( kmax )

      real              flng( kmax )

      integer           maxv( kmax )

      real              error( jmax , kmax )

      integer           ktauarr ( kmax )

      integer           kdel

      common /fcstc/    flat ,
     &                  flng ,
     &                  maxv ,
     &                  error ,
     &                  kdel,
     &                  ktauarr

