/* File: jclipmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Thu Nov  3 18:05:16 2016
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <stdarg.h>
#include "Python.h"
#include "fortranobject.h"
#include <string.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *jclip_error;
static PyObject *jclip_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
  if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
    PyErr_SetString(PyExc_MemoryError, "out of memory");\
    goto capi_fail;\
  } else {\
    (str)[len] = '\0';\
  }

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = jclip_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
  double d=0.0;
  if (double_from_pyobj(&d,obj,errmess)) {
    *v = (float)d;
    return 1;
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = jclip_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
  if (obj == Py_None) {
    if (*len == -1)
      *len = strlen(inistr); /* Will this cause problems? */
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,inistr,*len+1);
    return 1;
  }
  if (PyArray_Check(obj)) {
    if ((arr = (PyArrayObject *)obj) == NULL)
      goto capi_fail;
    if (!ISCONTIGUOUS(arr)) {
      PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
      goto capi_fail;
    }
    if (*len == -1)
      *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
    return 1;
  }
  if (PyString_Check(obj)) {
    tmp = obj;
    Py_INCREF(tmp);
  }
#if PY_VERSION_HEX >= 0x03000000
  else if (PyUnicode_Check(obj)) {
    tmp = PyUnicode_AsASCIIString(obj);
  }
  else {
    PyObject *tmp2;
    tmp2 = PyObject_Str(obj);
    if (tmp2) {
      tmp = PyUnicode_AsASCIIString(tmp2);
      Py_DECREF(tmp2);
    }
    else {
      tmp = NULL;
    }
  }
#else
  else {
    tmp = PyObject_Str(obj);
  }
#endif
  if (tmp == NULL) goto capi_fail;
  if (*len == -1)
    *len = PyString_GET_SIZE(tmp);
  STRINGMALLOC(*str,*len);
  STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
  Py_DECREF(tmp);
  return 1;
capi_fail:
  Py_XDECREF(tmp);
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = jclip_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(wpclpr,WPCLPR)(int*,float*,float*,float*,float*,float*,float*,float*);
extern void F_WRAPPEDFUNC(f1,F1)(float*,float*);
extern void F_WRAPPEDFUNC(f2,F2)(float*,int*);
extern void F_FUNC(psetup,PSETUP)(float*,float*,float*,float*,float*,float*,float*,float*,float*);
extern void F_FUNC(nmi2ll,NMI2LL)(float*,float*,float*,float*);
extern void F_WRAPPEDFUNC(newcyc,NEWCYC)(int*,int*,int*);
extern void F_FUNC(sthgpr,STHGPR)(float*,float*,float*,float*,float*,float*);
extern void F_FUNC(ll2xyh,LL2XYH)(float*,float*,float*,float*);
extern void F_FUNC(xy2llh,XY2LLH)(float*,float*,float*,float*);
extern void F_FUNC(db2ll,DB2LL)(float*,float*,float*,float*,float*,float*);
extern void F_FUNC(ll2db,LL2DB)(float*,float*,float*,float*,float*,float*);
extern void F_FUNC(seiclp,SEICLP)(int*,float*,float*,float*,float*,float*,float*,float*);
extern void F_FUNC(swpclp,SWPCLP)(int*,float*,float*,float*,float*,float*,float*,float*);
extern void F_FUNC(setup,SETUP)(float*,float*,float*,float*,float*,float*,float*,float*,float*);
extern void F_FUNC(yx2ll,YX2LL)(float*,float*,float*,float*);
extern void F_FUNC(uprcas,UPRCAS)(string,string,string,size_t,size_t,size_t);
extern void F_FUNC(fixprd,FIXPRD)(int*,int*,int*,int*,int*,float*,float*,float*,float*,float*,float*,float*);
extern void F_FUNC(cldxdy,CLDXDY)(int*,float*,float*,float*);
extern void F_FUNC(oclip,OCLIP)(int*,int*,float*,float*,float*,float*,float*,float*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** wpclpr ***********************************/
static char doc_f2py_rout_jclip_wpclpr[] = "\
wpclpr(idatim,alat00,alon00,alat12,alon12,alat24,alon24,wind)\n\nWrapper for ``wpclpr``.\
\n\nParameters\n----------\n"
"idatim : input int\n"
"alat00 : input float\n"
"alon00 : input float\n"
"alat12 : input float\n"
"alon12 : input float\n"
"alat24 : input float\n"
"alon24 : input float\n"
"wind : input float";
/* extern void F_FUNC(wpclpr,WPCLPR)(int*,float*,float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_jclip_wpclpr(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int idatim = 0;
  PyObject *idatim_capi = Py_None;
  float alat00 = 0;
  PyObject *alat00_capi = Py_None;
  float alon00 = 0;
  PyObject *alon00_capi = Py_None;
  float alat12 = 0;
  PyObject *alat12_capi = Py_None;
  float alon12 = 0;
  PyObject *alon12_capi = Py_None;
  float alat24 = 0;
  PyObject *alat24_capi = Py_None;
  float alon24 = 0;
  PyObject *alon24_capi = Py_None;
  float wind = 0;
  PyObject *wind_capi = Py_None;
  static char *capi_kwlist[] = {"idatim","alat00","alon00","alat12","alon12","alat24","alon24","wind",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO:jclip.wpclpr",\
    capi_kwlist,&idatim_capi,&alat00_capi,&alon00_capi,&alat12_capi,&alon12_capi,&alat24_capi,&alon24_capi,&wind_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable alat12 */
    f2py_success = float_from_pyobj(&alat12,alat12_capi,"jclip.wpclpr() 4th argument (alat12) can't be converted to float");
  if (f2py_success) {
  /* Processing variable alon24 */
    f2py_success = float_from_pyobj(&alon24,alon24_capi,"jclip.wpclpr() 7th argument (alon24) can't be converted to float");
  if (f2py_success) {
  /* Processing variable alon00 */
    f2py_success = float_from_pyobj(&alon00,alon00_capi,"jclip.wpclpr() 3rd argument (alon00) can't be converted to float");
  if (f2py_success) {
  /* Processing variable alon12 */
    f2py_success = float_from_pyobj(&alon12,alon12_capi,"jclip.wpclpr() 5th argument (alon12) can't be converted to float");
  if (f2py_success) {
  /* Processing variable idatim */
    f2py_success = int_from_pyobj(&idatim,idatim_capi,"jclip.wpclpr() 1st argument (idatim) can't be converted to int");
  if (f2py_success) {
  /* Processing variable alat24 */
    f2py_success = float_from_pyobj(&alat24,alat24_capi,"jclip.wpclpr() 6th argument (alat24) can't be converted to float");
  if (f2py_success) {
  /* Processing variable alat00 */
    f2py_success = float_from_pyobj(&alat00,alat00_capi,"jclip.wpclpr() 2nd argument (alat00) can't be converted to float");
  if (f2py_success) {
  /* Processing variable wind */
    f2py_success = float_from_pyobj(&wind,wind_capi,"jclip.wpclpr() 8th argument (wind) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&idatim,&alat00,&alon00,&alat12,&alon12,&alat24,&alon24,&wind);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of wind*/
  /* End of cleaning variable wind */
  } /*if (f2py_success) of alat00*/
  /* End of cleaning variable alat00 */
  } /*if (f2py_success) of alat24*/
  /* End of cleaning variable alat24 */
  } /*if (f2py_success) of idatim*/
  /* End of cleaning variable idatim */
  } /*if (f2py_success) of alon12*/
  /* End of cleaning variable alon12 */
  } /*if (f2py_success) of alon00*/
  /* End of cleaning variable alon00 */
  } /*if (f2py_success) of alon24*/
  /* End of cleaning variable alon24 */
  } /*if (f2py_success) of alat12*/
  /* End of cleaning variable alat12 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of wpclpr *******************************/

/************************************* f1 *************************************/
static char doc_f2py_rout_jclip_f1[] = "\
f1 = f1(alon)\n\nWrapper for ``f1``.\
\n\nParameters\n----------\n"
"alon : input float\n"
"\nReturns\n-------\n"
"f1 : float";
/* extern void F_WRAPPEDFUNC(f1,F1)(float*,float*); */
static PyObject *f2py_rout_jclip_f1(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float f1 = 0;
  float alon = 0;
  PyObject *alon_capi = Py_None;
  static char *capi_kwlist[] = {"alon",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:jclip.f1",\
    capi_kwlist,&alon_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable f1 */
  /* Processing variable alon */
    f2py_success = float_from_pyobj(&alon,alon_capi,"jclip.f1() 1st argument (alon) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&f1,&alon);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("f",f1);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of alon*/
  /* End of cleaning variable alon */
  /* End of cleaning variable f1 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/********************************* end of f1 *********************************/

/************************************* f2 *************************************/
static char doc_f2py_rout_jclip_f2[] = "\
f2 = f2(idatim)\n\nWrapper for ``f2``.\
\n\nParameters\n----------\n"
"idatim : input int\n"
"\nReturns\n-------\n"
"f2 : float";
/* extern void F_WRAPPEDFUNC(f2,F2)(float*,int*); */
static PyObject *f2py_rout_jclip_f2(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float f2 = 0;
  int idatim = 0;
  PyObject *idatim_capi = Py_None;
  static char *capi_kwlist[] = {"idatim",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:jclip.f2",\
    capi_kwlist,&idatim_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable idatim */
    f2py_success = int_from_pyobj(&idatim,idatim_capi,"jclip.f2() 1st argument (idatim) can't be converted to int");
  if (f2py_success) {
  /* Processing variable f2 */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&f2,&idatim);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("f",f2);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2 */
  } /*if (f2py_success) of idatim*/
  /* End of cleaning variable idatim */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/********************************* end of f2 *********************************/

/*********************************** psetup ***********************************/
static char doc_f2py_rout_jclip_psetup[] = "\
psetup(p1,p2,p3,p4,p5,p6,p7,p8,p)\n\nWrapper for ``psetup``.\
\n\nParameters\n----------\n"
"p1 : input float\n"
"p2 : input float\n"
"p3 : input float\n"
"p4 : input float\n"
"p5 : input float\n"
"p6 : input float\n"
"p7 : input float\n"
"p8 : input float\n"
"p : input rank-1 array('f') with bounds (166)";
/* extern void F_FUNC(psetup,PSETUP)(float*,float*,float*,float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_jclip_psetup(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float p1 = 0;
  PyObject *p1_capi = Py_None;
  float p2 = 0;
  PyObject *p2_capi = Py_None;
  float p3 = 0;
  PyObject *p3_capi = Py_None;
  float p4 = 0;
  PyObject *p4_capi = Py_None;
  float p5 = 0;
  PyObject *p5_capi = Py_None;
  float p6 = 0;
  PyObject *p6_capi = Py_None;
  float p7 = 0;
  PyObject *p7_capi = Py_None;
  float p8 = 0;
  PyObject *p8_capi = Py_None;
  float *p = NULL;
  npy_intp p_Dims[1] = {-1};
  const int p_Rank = 1;
  PyArrayObject *capi_p_tmp = NULL;
  int capi_p_intent = 0;
  PyObject *p_capi = Py_None;
  static char *capi_kwlist[] = {"p1","p2","p3","p4","p5","p6","p7","p8","p",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO:jclip.psetup",\
    capi_kwlist,&p1_capi,&p2_capi,&p3_capi,&p4_capi,&p5_capi,&p6_capi,&p7_capi,&p8_capi,&p_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable p2 */
    f2py_success = float_from_pyobj(&p2,p2_capi,"jclip.psetup() 2nd argument (p2) can't be converted to float");
  if (f2py_success) {
  /* Processing variable p3 */
    f2py_success = float_from_pyobj(&p3,p3_capi,"jclip.psetup() 3rd argument (p3) can't be converted to float");
  if (f2py_success) {
  /* Processing variable p1 */
    f2py_success = float_from_pyobj(&p1,p1_capi,"jclip.psetup() 1st argument (p1) can't be converted to float");
  if (f2py_success) {
  /* Processing variable p6 */
    f2py_success = float_from_pyobj(&p6,p6_capi,"jclip.psetup() 6th argument (p6) can't be converted to float");
  if (f2py_success) {
  /* Processing variable p7 */
    f2py_success = float_from_pyobj(&p7,p7_capi,"jclip.psetup() 7th argument (p7) can't be converted to float");
  if (f2py_success) {
  /* Processing variable p4 */
    f2py_success = float_from_pyobj(&p4,p4_capi,"jclip.psetup() 4th argument (p4) can't be converted to float");
  if (f2py_success) {
  /* Processing variable p5 */
    f2py_success = float_from_pyobj(&p5,p5_capi,"jclip.psetup() 5th argument (p5) can't be converted to float");
  if (f2py_success) {
  /* Processing variable p8 */
    f2py_success = float_from_pyobj(&p8,p8_capi,"jclip.psetup() 8th argument (p8) can't be converted to float");
  if (f2py_success) {
  /* Processing variable p */
  p_Dims[0]=166;
  capi_p_intent |= F2PY_INTENT_IN;
  capi_p_tmp = array_from_pyobj(NPY_FLOAT,p_Dims,p_Rank,capi_p_intent,p_capi);
  if (capi_p_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(jclip_error,"failed in converting 9th argument `p' of jclip.psetup to C/Fortran array" );
  } else {
    p = (float *)(PyArray_DATA(capi_p_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&p1,&p2,&p3,&p4,&p5,&p6,&p7,&p8,p);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_p_tmp!=p_capi) {
    Py_XDECREF(capi_p_tmp); }
  }  /*if (capi_p_tmp == NULL) ... else of p*/
  /* End of cleaning variable p */
  } /*if (f2py_success) of p8*/
  /* End of cleaning variable p8 */
  } /*if (f2py_success) of p5*/
  /* End of cleaning variable p5 */
  } /*if (f2py_success) of p4*/
  /* End of cleaning variable p4 */
  } /*if (f2py_success) of p7*/
  /* End of cleaning variable p7 */
  } /*if (f2py_success) of p6*/
  /* End of cleaning variable p6 */
  } /*if (f2py_success) of p1*/
  /* End of cleaning variable p1 */
  } /*if (f2py_success) of p3*/
  /* End of cleaning variable p3 */
  } /*if (f2py_success) of p2*/
  /* End of cleaning variable p2 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of psetup *******************************/

/*********************************** nmi2ll ***********************************/
static char doc_f2py_rout_jclip_nmi2ll[] = "\
nmi2ll(alat0,alon0,cnmis,cfcst)\n\nWrapper for ``nmi2ll``.\
\n\nParameters\n----------\n"
"alat0 : input float\n"
"alon0 : input float\n"
"cnmis : input rank-1 array('f') with bounds (12)\n"
"cfcst : input rank-1 array('f') with bounds (12)";
/* extern void F_FUNC(nmi2ll,NMI2LL)(float*,float*,float*,float*); */
static PyObject *f2py_rout_jclip_nmi2ll(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float alat0 = 0;
  PyObject *alat0_capi = Py_None;
  float alon0 = 0;
  PyObject *alon0_capi = Py_None;
  float *cnmis = NULL;
  npy_intp cnmis_Dims[1] = {-1};
  const int cnmis_Rank = 1;
  PyArrayObject *capi_cnmis_tmp = NULL;
  int capi_cnmis_intent = 0;
  PyObject *cnmis_capi = Py_None;
  float *cfcst = NULL;
  npy_intp cfcst_Dims[1] = {-1};
  const int cfcst_Rank = 1;
  PyArrayObject *capi_cfcst_tmp = NULL;
  int capi_cfcst_intent = 0;
  PyObject *cfcst_capi = Py_None;
  static char *capi_kwlist[] = {"alat0","alon0","cnmis","cfcst",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:jclip.nmi2ll",\
    capi_kwlist,&alat0_capi,&alon0_capi,&cnmis_capi,&cfcst_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable alon0 */
    f2py_success = float_from_pyobj(&alon0,alon0_capi,"jclip.nmi2ll() 2nd argument (alon0) can't be converted to float");
  if (f2py_success) {
  /* Processing variable cfcst */
  cfcst_Dims[0]=12;
  capi_cfcst_intent |= F2PY_INTENT_IN;
  capi_cfcst_tmp = array_from_pyobj(NPY_FLOAT,cfcst_Dims,cfcst_Rank,capi_cfcst_intent,cfcst_capi);
  if (capi_cfcst_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(jclip_error,"failed in converting 4th argument `cfcst' of jclip.nmi2ll to C/Fortran array" );
  } else {
    cfcst = (float *)(PyArray_DATA(capi_cfcst_tmp));

  /* Processing variable alat0 */
    f2py_success = float_from_pyobj(&alat0,alat0_capi,"jclip.nmi2ll() 1st argument (alat0) can't be converted to float");
  if (f2py_success) {
  /* Processing variable cnmis */
  cnmis_Dims[0]=12;
  capi_cnmis_intent |= F2PY_INTENT_IN;
  capi_cnmis_tmp = array_from_pyobj(NPY_FLOAT,cnmis_Dims,cnmis_Rank,capi_cnmis_intent,cnmis_capi);
  if (capi_cnmis_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(jclip_error,"failed in converting 3rd argument `cnmis' of jclip.nmi2ll to C/Fortran array" );
  } else {
    cnmis = (float *)(PyArray_DATA(capi_cnmis_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&alat0,&alon0,cnmis,cfcst);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_cnmis_tmp!=cnmis_capi) {
    Py_XDECREF(capi_cnmis_tmp); }
  }  /*if (capi_cnmis_tmp == NULL) ... else of cnmis*/
  /* End of cleaning variable cnmis */
  } /*if (f2py_success) of alat0*/
  /* End of cleaning variable alat0 */
  if((PyObject *)capi_cfcst_tmp!=cfcst_capi) {
    Py_XDECREF(capi_cfcst_tmp); }
  }  /*if (capi_cfcst_tmp == NULL) ... else of cfcst*/
  /* End of cleaning variable cfcst */
  } /*if (f2py_success) of alon0*/
  /* End of cleaning variable alon0 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of nmi2ll *******************************/

/*********************************** newcyc ***********************************/
static char doc_f2py_rout_jclip_newcyc[] = "\
newcyc = newcyc(nowcyc,n)\n\nWrapper for ``newcyc``.\
\n\nParameters\n----------\n"
"nowcyc : input int\n"
"n : input int\n"
"\nReturns\n-------\n"
"newcyc : int";
/* extern void F_WRAPPEDFUNC(newcyc,NEWCYC)(int*,int*,int*); */
static PyObject *f2py_rout_jclip_newcyc(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int newcyc = 0;
  int nowcyc = 0;
  PyObject *nowcyc_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  static char *capi_kwlist[] = {"nowcyc","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:jclip.newcyc",\
    capi_kwlist,&nowcyc_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable n */
    f2py_success = int_from_pyobj(&n,n_capi,"jclip.newcyc() 2nd argument (n) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nowcyc */
    f2py_success = int_from_pyobj(&nowcyc,nowcyc_capi,"jclip.newcyc() 1st argument (nowcyc) can't be converted to int");
  if (f2py_success) {
  /* Processing variable newcyc */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&newcyc,&nowcyc,&n);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",newcyc);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable newcyc */
  } /*if (f2py_success) of nowcyc*/
  /* End of cleaning variable nowcyc */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of newcyc *******************************/

/*********************************** sthgpr ***********************************/
static char doc_f2py_rout_jclip_sthgpr[] = "\
sthgpr(xlath,xlonh,bear,gridsz,xi0,yj0)\n\nWrapper for ``sthgpr``.\
\n\nParameters\n----------\n"
"xlath : input float\n"
"xlonh : input float\n"
"bear : input float\n"
"gridsz : input float\n"
"xi0 : input float\n"
"yj0 : input float";
/* extern void F_FUNC(sthgpr,STHGPR)(float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_jclip_sthgpr(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float xlath = 0;
  PyObject *xlath_capi = Py_None;
  float xlonh = 0;
  PyObject *xlonh_capi = Py_None;
  float bear = 0;
  PyObject *bear_capi = Py_None;
  float gridsz = 0;
  PyObject *gridsz_capi = Py_None;
  float xi0 = 0;
  PyObject *xi0_capi = Py_None;
  float yj0 = 0;
  PyObject *yj0_capi = Py_None;
  static char *capi_kwlist[] = {"xlath","xlonh","bear","gridsz","xi0","yj0",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO:jclip.sthgpr",\
    capi_kwlist,&xlath_capi,&xlonh_capi,&bear_capi,&gridsz_capi,&xi0_capi,&yj0_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable bear */
    f2py_success = float_from_pyobj(&bear,bear_capi,"jclip.sthgpr() 3rd argument (bear) can't be converted to float");
  if (f2py_success) {
  /* Processing variable yj0 */
    f2py_success = float_from_pyobj(&yj0,yj0_capi,"jclip.sthgpr() 6th argument (yj0) can't be converted to float");
  if (f2py_success) {
  /* Processing variable xi0 */
    f2py_success = float_from_pyobj(&xi0,xi0_capi,"jclip.sthgpr() 5th argument (xi0) can't be converted to float");
  if (f2py_success) {
  /* Processing variable xlath */
    f2py_success = float_from_pyobj(&xlath,xlath_capi,"jclip.sthgpr() 1st argument (xlath) can't be converted to float");
  if (f2py_success) {
  /* Processing variable gridsz */
    f2py_success = float_from_pyobj(&gridsz,gridsz_capi,"jclip.sthgpr() 4th argument (gridsz) can't be converted to float");
  if (f2py_success) {
  /* Processing variable xlonh */
    f2py_success = float_from_pyobj(&xlonh,xlonh_capi,"jclip.sthgpr() 2nd argument (xlonh) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&xlath,&xlonh,&bear,&gridsz,&xi0,&yj0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of xlonh*/
  /* End of cleaning variable xlonh */
  } /*if (f2py_success) of gridsz*/
  /* End of cleaning variable gridsz */
  } /*if (f2py_success) of xlath*/
  /* End of cleaning variable xlath */
  } /*if (f2py_success) of xi0*/
  /* End of cleaning variable xi0 */
  } /*if (f2py_success) of yj0*/
  /* End of cleaning variable yj0 */
  } /*if (f2py_success) of bear*/
  /* End of cleaning variable bear */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of sthgpr *******************************/

/*********************************** ll2xyh ***********************************/
static char doc_f2py_rout_jclip_ll2xyh[] = "\
ll2xyh(xlat,xlong,xi,yj)\n\nWrapper for ``ll2xyh``.\
\n\nParameters\n----------\n"
"xlat : input float\n"
"xlong : input float\n"
"xi : input float\n"
"yj : input float";
/* extern void F_FUNC(ll2xyh,LL2XYH)(float*,float*,float*,float*); */
static PyObject *f2py_rout_jclip_ll2xyh(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float xlat = 0;
  PyObject *xlat_capi = Py_None;
  float xlong = 0;
  PyObject *xlong_capi = Py_None;
  float xi = 0;
  PyObject *xi_capi = Py_None;
  float yj = 0;
  PyObject *yj_capi = Py_None;
  static char *capi_kwlist[] = {"xlat","xlong","xi","yj",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:jclip.ll2xyh",\
    capi_kwlist,&xlat_capi,&xlong_capi,&xi_capi,&yj_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable xi */
    f2py_success = float_from_pyobj(&xi,xi_capi,"jclip.ll2xyh() 3rd argument (xi) can't be converted to float");
  if (f2py_success) {
  /* Processing variable xlong */
    f2py_success = float_from_pyobj(&xlong,xlong_capi,"jclip.ll2xyh() 2nd argument (xlong) can't be converted to float");
  if (f2py_success) {
  /* Processing variable yj */
    f2py_success = float_from_pyobj(&yj,yj_capi,"jclip.ll2xyh() 4th argument (yj) can't be converted to float");
  if (f2py_success) {
  /* Processing variable xlat */
    f2py_success = float_from_pyobj(&xlat,xlat_capi,"jclip.ll2xyh() 1st argument (xlat) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&xlat,&xlong,&xi,&yj);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of xlat*/
  /* End of cleaning variable xlat */
  } /*if (f2py_success) of yj*/
  /* End of cleaning variable yj */
  } /*if (f2py_success) of xlong*/
  /* End of cleaning variable xlong */
  } /*if (f2py_success) of xi*/
  /* End of cleaning variable xi */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of ll2xyh *******************************/

/*********************************** xy2llh ***********************************/
static char doc_f2py_rout_jclip_xy2llh[] = "\
xy2llh(xi,yj,xlat,xlong)\n\nWrapper for ``xy2llh``.\
\n\nParameters\n----------\n"
"xi : input float\n"
"yj : input float\n"
"xlat : input float\n"
"xlong : input float";
/* extern void F_FUNC(xy2llh,XY2LLH)(float*,float*,float*,float*); */
static PyObject *f2py_rout_jclip_xy2llh(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float xi = 0;
  PyObject *xi_capi = Py_None;
  float yj = 0;
  PyObject *yj_capi = Py_None;
  float xlat = 0;
  PyObject *xlat_capi = Py_None;
  float xlong = 0;
  PyObject *xlong_capi = Py_None;
  static char *capi_kwlist[] = {"xi","yj","xlat","xlong",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:jclip.xy2llh",\
    capi_kwlist,&xi_capi,&yj_capi,&xlat_capi,&xlong_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable yj */
    f2py_success = float_from_pyobj(&yj,yj_capi,"jclip.xy2llh() 2nd argument (yj) can't be converted to float");
  if (f2py_success) {
  /* Processing variable xlong */
    f2py_success = float_from_pyobj(&xlong,xlong_capi,"jclip.xy2llh() 4th argument (xlong) can't be converted to float");
  if (f2py_success) {
  /* Processing variable xi */
    f2py_success = float_from_pyobj(&xi,xi_capi,"jclip.xy2llh() 1st argument (xi) can't be converted to float");
  if (f2py_success) {
  /* Processing variable xlat */
    f2py_success = float_from_pyobj(&xlat,xlat_capi,"jclip.xy2llh() 3rd argument (xlat) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&xi,&yj,&xlat,&xlong);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of xlat*/
  /* End of cleaning variable xlat */
  } /*if (f2py_success) of xi*/
  /* End of cleaning variable xi */
  } /*if (f2py_success) of xlong*/
  /* End of cleaning variable xlong */
  } /*if (f2py_success) of yj*/
  /* End of cleaning variable yj */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of xy2llh *******************************/

/*********************************** db2ll ***********************************/
static char doc_f2py_rout_jclip_db2ll[] = "\
db2ll(xlato,xlono,dist,bear,xlatt,xlont)\n\nWrapper for ``db2ll``.\
\n\nParameters\n----------\n"
"xlato : input float\n"
"xlono : input float\n"
"dist : input float\n"
"bear : input float\n"
"xlatt : input float\n"
"xlont : input float";
/* extern void F_FUNC(db2ll,DB2LL)(float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_jclip_db2ll(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float xlato = 0;
  PyObject *xlato_capi = Py_None;
  float xlono = 0;
  PyObject *xlono_capi = Py_None;
  float dist = 0;
  PyObject *dist_capi = Py_None;
  float bear = 0;
  PyObject *bear_capi = Py_None;
  float xlatt = 0;
  PyObject *xlatt_capi = Py_None;
  float xlont = 0;
  PyObject *xlont_capi = Py_None;
  static char *capi_kwlist[] = {"xlato","xlono","dist","bear","xlatt","xlont",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO:jclip.db2ll",\
    capi_kwlist,&xlato_capi,&xlono_capi,&dist_capi,&bear_capi,&xlatt_capi,&xlont_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable xlato */
    f2py_success = float_from_pyobj(&xlato,xlato_capi,"jclip.db2ll() 1st argument (xlato) can't be converted to float");
  if (f2py_success) {
  /* Processing variable xlont */
    f2py_success = float_from_pyobj(&xlont,xlont_capi,"jclip.db2ll() 6th argument (xlont) can't be converted to float");
  if (f2py_success) {
  /* Processing variable xlatt */
    f2py_success = float_from_pyobj(&xlatt,xlatt_capi,"jclip.db2ll() 5th argument (xlatt) can't be converted to float");
  if (f2py_success) {
  /* Processing variable dist */
    f2py_success = float_from_pyobj(&dist,dist_capi,"jclip.db2ll() 3rd argument (dist) can't be converted to float");
  if (f2py_success) {
  /* Processing variable bear */
    f2py_success = float_from_pyobj(&bear,bear_capi,"jclip.db2ll() 4th argument (bear) can't be converted to float");
  if (f2py_success) {
  /* Processing variable xlono */
    f2py_success = float_from_pyobj(&xlono,xlono_capi,"jclip.db2ll() 2nd argument (xlono) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&xlato,&xlono,&dist,&bear,&xlatt,&xlont);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of xlono*/
  /* End of cleaning variable xlono */
  } /*if (f2py_success) of bear*/
  /* End of cleaning variable bear */
  } /*if (f2py_success) of dist*/
  /* End of cleaning variable dist */
  } /*if (f2py_success) of xlatt*/
  /* End of cleaning variable xlatt */
  } /*if (f2py_success) of xlont*/
  /* End of cleaning variable xlont */
  } /*if (f2py_success) of xlato*/
  /* End of cleaning variable xlato */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of db2ll ********************************/

/*********************************** ll2db ***********************************/
static char doc_f2py_rout_jclip_ll2db[] = "\
ll2db(xlato,xlono,xlatt,xlont,dist,bear)\n\nWrapper for ``ll2db``.\
\n\nParameters\n----------\n"
"xlato : input float\n"
"xlono : input float\n"
"xlatt : input float\n"
"xlont : input float\n"
"dist : input float\n"
"bear : input float";
/* extern void F_FUNC(ll2db,LL2DB)(float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_jclip_ll2db(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float xlato = 0;
  PyObject *xlato_capi = Py_None;
  float xlono = 0;
  PyObject *xlono_capi = Py_None;
  float xlatt = 0;
  PyObject *xlatt_capi = Py_None;
  float xlont = 0;
  PyObject *xlont_capi = Py_None;
  float dist = 0;
  PyObject *dist_capi = Py_None;
  float bear = 0;
  PyObject *bear_capi = Py_None;
  static char *capi_kwlist[] = {"xlato","xlono","xlatt","xlont","dist","bear",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO:jclip.ll2db",\
    capi_kwlist,&xlato_capi,&xlono_capi,&xlatt_capi,&xlont_capi,&dist_capi,&bear_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable xlato */
    f2py_success = float_from_pyobj(&xlato,xlato_capi,"jclip.ll2db() 1st argument (xlato) can't be converted to float");
  if (f2py_success) {
  /* Processing variable dist */
    f2py_success = float_from_pyobj(&dist,dist_capi,"jclip.ll2db() 5th argument (dist) can't be converted to float");
  if (f2py_success) {
  /* Processing variable xlatt */
    f2py_success = float_from_pyobj(&xlatt,xlatt_capi,"jclip.ll2db() 3rd argument (xlatt) can't be converted to float");
  if (f2py_success) {
  /* Processing variable xlont */
    f2py_success = float_from_pyobj(&xlont,xlont_capi,"jclip.ll2db() 4th argument (xlont) can't be converted to float");
  if (f2py_success) {
  /* Processing variable bear */
    f2py_success = float_from_pyobj(&bear,bear_capi,"jclip.ll2db() 6th argument (bear) can't be converted to float");
  if (f2py_success) {
  /* Processing variable xlono */
    f2py_success = float_from_pyobj(&xlono,xlono_capi,"jclip.ll2db() 2nd argument (xlono) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&xlato,&xlono,&xlatt,&xlont,&dist,&bear);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of xlono*/
  /* End of cleaning variable xlono */
  } /*if (f2py_success) of bear*/
  /* End of cleaning variable bear */
  } /*if (f2py_success) of xlont*/
  /* End of cleaning variable xlont */
  } /*if (f2py_success) of xlatt*/
  /* End of cleaning variable xlatt */
  } /*if (f2py_success) of dist*/
  /* End of cleaning variable dist */
  } /*if (f2py_success) of xlato*/
  /* End of cleaning variable xlato */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of ll2db ********************************/

/*********************************** seiclp ***********************************/
static char doc_f2py_rout_jclip_seiclp[] = "\
seiclp(idatim,alat00,alon00,alat12,alon12,alat24,alon24,wind)\n\nWrapper for ``seiclp``.\
\n\nParameters\n----------\n"
"idatim : input int\n"
"alat00 : input float\n"
"alon00 : input float\n"
"alat12 : input float\n"
"alon12 : input float\n"
"alat24 : input float\n"
"alon24 : input float\n"
"wind : input float";
/* extern void F_FUNC(seiclp,SEICLP)(int*,float*,float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_jclip_seiclp(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int idatim = 0;
  PyObject *idatim_capi = Py_None;
  float alat00 = 0;
  PyObject *alat00_capi = Py_None;
  float alon00 = 0;
  PyObject *alon00_capi = Py_None;
  float alat12 = 0;
  PyObject *alat12_capi = Py_None;
  float alon12 = 0;
  PyObject *alon12_capi = Py_None;
  float alat24 = 0;
  PyObject *alat24_capi = Py_None;
  float alon24 = 0;
  PyObject *alon24_capi = Py_None;
  float wind = 0;
  PyObject *wind_capi = Py_None;
  static char *capi_kwlist[] = {"idatim","alat00","alon00","alat12","alon12","alat24","alon24","wind",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO:jclip.seiclp",\
    capi_kwlist,&idatim_capi,&alat00_capi,&alon00_capi,&alat12_capi,&alon12_capi,&alat24_capi,&alon24_capi,&wind_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable alat12 */
    f2py_success = float_from_pyobj(&alat12,alat12_capi,"jclip.seiclp() 4th argument (alat12) can't be converted to float");
  if (f2py_success) {
  /* Processing variable alon24 */
    f2py_success = float_from_pyobj(&alon24,alon24_capi,"jclip.seiclp() 7th argument (alon24) can't be converted to float");
  if (f2py_success) {
  /* Processing variable alon00 */
    f2py_success = float_from_pyobj(&alon00,alon00_capi,"jclip.seiclp() 3rd argument (alon00) can't be converted to float");
  if (f2py_success) {
  /* Processing variable alon12 */
    f2py_success = float_from_pyobj(&alon12,alon12_capi,"jclip.seiclp() 5th argument (alon12) can't be converted to float");
  if (f2py_success) {
  /* Processing variable idatim */
    f2py_success = int_from_pyobj(&idatim,idatim_capi,"jclip.seiclp() 1st argument (idatim) can't be converted to int");
  if (f2py_success) {
  /* Processing variable alat24 */
    f2py_success = float_from_pyobj(&alat24,alat24_capi,"jclip.seiclp() 6th argument (alat24) can't be converted to float");
  if (f2py_success) {
  /* Processing variable alat00 */
    f2py_success = float_from_pyobj(&alat00,alat00_capi,"jclip.seiclp() 2nd argument (alat00) can't be converted to float");
  if (f2py_success) {
  /* Processing variable wind */
    f2py_success = float_from_pyobj(&wind,wind_capi,"jclip.seiclp() 8th argument (wind) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&idatim,&alat00,&alon00,&alat12,&alon12,&alat24,&alon24,&wind);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of wind*/
  /* End of cleaning variable wind */
  } /*if (f2py_success) of alat00*/
  /* End of cleaning variable alat00 */
  } /*if (f2py_success) of alat24*/
  /* End of cleaning variable alat24 */
  } /*if (f2py_success) of idatim*/
  /* End of cleaning variable idatim */
  } /*if (f2py_success) of alon12*/
  /* End of cleaning variable alon12 */
  } /*if (f2py_success) of alon00*/
  /* End of cleaning variable alon00 */
  } /*if (f2py_success) of alon24*/
  /* End of cleaning variable alon24 */
  } /*if (f2py_success) of alat12*/
  /* End of cleaning variable alat12 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of seiclp *******************************/

/*********************************** swpclp ***********************************/
static char doc_f2py_rout_jclip_swpclp[] = "\
swpclp(idatim,alat00,alon00,alat12,alon12,alat24,alon24,wind)\n\nWrapper for ``swpclp``.\
\n\nParameters\n----------\n"
"idatim : input int\n"
"alat00 : input float\n"
"alon00 : input float\n"
"alat12 : input float\n"
"alon12 : input float\n"
"alat24 : input float\n"
"alon24 : input float\n"
"wind : input float";
/* extern void F_FUNC(swpclp,SWPCLP)(int*,float*,float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_jclip_swpclp(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int idatim = 0;
  PyObject *idatim_capi = Py_None;
  float alat00 = 0;
  PyObject *alat00_capi = Py_None;
  float alon00 = 0;
  PyObject *alon00_capi = Py_None;
  float alat12 = 0;
  PyObject *alat12_capi = Py_None;
  float alon12 = 0;
  PyObject *alon12_capi = Py_None;
  float alat24 = 0;
  PyObject *alat24_capi = Py_None;
  float alon24 = 0;
  PyObject *alon24_capi = Py_None;
  float wind = 0;
  PyObject *wind_capi = Py_None;
  static char *capi_kwlist[] = {"idatim","alat00","alon00","alat12","alon12","alat24","alon24","wind",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO:jclip.swpclp",\
    capi_kwlist,&idatim_capi,&alat00_capi,&alon00_capi,&alat12_capi,&alon12_capi,&alat24_capi,&alon24_capi,&wind_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable alat12 */
    f2py_success = float_from_pyobj(&alat12,alat12_capi,"jclip.swpclp() 4th argument (alat12) can't be converted to float");
  if (f2py_success) {
  /* Processing variable alon24 */
    f2py_success = float_from_pyobj(&alon24,alon24_capi,"jclip.swpclp() 7th argument (alon24) can't be converted to float");
  if (f2py_success) {
  /* Processing variable alon00 */
    f2py_success = float_from_pyobj(&alon00,alon00_capi,"jclip.swpclp() 3rd argument (alon00) can't be converted to float");
  if (f2py_success) {
  /* Processing variable alon12 */
    f2py_success = float_from_pyobj(&alon12,alon12_capi,"jclip.swpclp() 5th argument (alon12) can't be converted to float");
  if (f2py_success) {
  /* Processing variable idatim */
    f2py_success = int_from_pyobj(&idatim,idatim_capi,"jclip.swpclp() 1st argument (idatim) can't be converted to int");
  if (f2py_success) {
  /* Processing variable alat24 */
    f2py_success = float_from_pyobj(&alat24,alat24_capi,"jclip.swpclp() 6th argument (alat24) can't be converted to float");
  if (f2py_success) {
  /* Processing variable alat00 */
    f2py_success = float_from_pyobj(&alat00,alat00_capi,"jclip.swpclp() 2nd argument (alat00) can't be converted to float");
  if (f2py_success) {
  /* Processing variable wind */
    f2py_success = float_from_pyobj(&wind,wind_capi,"jclip.swpclp() 8th argument (wind) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&idatim,&alat00,&alon00,&alat12,&alon12,&alat24,&alon24,&wind);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of wind*/
  /* End of cleaning variable wind */
  } /*if (f2py_success) of alat00*/
  /* End of cleaning variable alat00 */
  } /*if (f2py_success) of alat24*/
  /* End of cleaning variable alat24 */
  } /*if (f2py_success) of idatim*/
  /* End of cleaning variable idatim */
  } /*if (f2py_success) of alon12*/
  /* End of cleaning variable alon12 */
  } /*if (f2py_success) of alon00*/
  /* End of cleaning variable alon00 */
  } /*if (f2py_success) of alon24*/
  /* End of cleaning variable alon24 */
  } /*if (f2py_success) of alat12*/
  /* End of cleaning variable alat12 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of swpclp *******************************/

/*********************************** setup ***********************************/
static char doc_f2py_rout_jclip_setup[] = "\
setup(p1,p2,p3,p4,p5,p6,p7,p8,p)\n\nWrapper for ``setup``.\
\n\nParameters\n----------\n"
"p1 : input float\n"
"p2 : input float\n"
"p3 : input float\n"
"p4 : input float\n"
"p5 : input float\n"
"p6 : input float\n"
"p7 : input float\n"
"p8 : input float\n"
"p : input rank-1 array('f') with bounds (166)";
/* extern void F_FUNC(setup,SETUP)(float*,float*,float*,float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_jclip_setup(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float p1 = 0;
  PyObject *p1_capi = Py_None;
  float p2 = 0;
  PyObject *p2_capi = Py_None;
  float p3 = 0;
  PyObject *p3_capi = Py_None;
  float p4 = 0;
  PyObject *p4_capi = Py_None;
  float p5 = 0;
  PyObject *p5_capi = Py_None;
  float p6 = 0;
  PyObject *p6_capi = Py_None;
  float p7 = 0;
  PyObject *p7_capi = Py_None;
  float p8 = 0;
  PyObject *p8_capi = Py_None;
  float *p = NULL;
  npy_intp p_Dims[1] = {-1};
  const int p_Rank = 1;
  PyArrayObject *capi_p_tmp = NULL;
  int capi_p_intent = 0;
  PyObject *p_capi = Py_None;
  static char *capi_kwlist[] = {"p1","p2","p3","p4","p5","p6","p7","p8","p",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO:jclip.setup",\
    capi_kwlist,&p1_capi,&p2_capi,&p3_capi,&p4_capi,&p5_capi,&p6_capi,&p7_capi,&p8_capi,&p_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable p2 */
    f2py_success = float_from_pyobj(&p2,p2_capi,"jclip.setup() 2nd argument (p2) can't be converted to float");
  if (f2py_success) {
  /* Processing variable p3 */
    f2py_success = float_from_pyobj(&p3,p3_capi,"jclip.setup() 3rd argument (p3) can't be converted to float");
  if (f2py_success) {
  /* Processing variable p1 */
    f2py_success = float_from_pyobj(&p1,p1_capi,"jclip.setup() 1st argument (p1) can't be converted to float");
  if (f2py_success) {
  /* Processing variable p6 */
    f2py_success = float_from_pyobj(&p6,p6_capi,"jclip.setup() 6th argument (p6) can't be converted to float");
  if (f2py_success) {
  /* Processing variable p7 */
    f2py_success = float_from_pyobj(&p7,p7_capi,"jclip.setup() 7th argument (p7) can't be converted to float");
  if (f2py_success) {
  /* Processing variable p4 */
    f2py_success = float_from_pyobj(&p4,p4_capi,"jclip.setup() 4th argument (p4) can't be converted to float");
  if (f2py_success) {
  /* Processing variable p5 */
    f2py_success = float_from_pyobj(&p5,p5_capi,"jclip.setup() 5th argument (p5) can't be converted to float");
  if (f2py_success) {
  /* Processing variable p8 */
    f2py_success = float_from_pyobj(&p8,p8_capi,"jclip.setup() 8th argument (p8) can't be converted to float");
  if (f2py_success) {
  /* Processing variable p */
  p_Dims[0]=166;
  capi_p_intent |= F2PY_INTENT_IN;
  capi_p_tmp = array_from_pyobj(NPY_FLOAT,p_Dims,p_Rank,capi_p_intent,p_capi);
  if (capi_p_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(jclip_error,"failed in converting 9th argument `p' of jclip.setup to C/Fortran array" );
  } else {
    p = (float *)(PyArray_DATA(capi_p_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&p1,&p2,&p3,&p4,&p5,&p6,&p7,&p8,p);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_p_tmp!=p_capi) {
    Py_XDECREF(capi_p_tmp); }
  }  /*if (capi_p_tmp == NULL) ... else of p*/
  /* End of cleaning variable p */
  } /*if (f2py_success) of p8*/
  /* End of cleaning variable p8 */
  } /*if (f2py_success) of p5*/
  /* End of cleaning variable p5 */
  } /*if (f2py_success) of p4*/
  /* End of cleaning variable p4 */
  } /*if (f2py_success) of p7*/
  /* End of cleaning variable p7 */
  } /*if (f2py_success) of p6*/
  /* End of cleaning variable p6 */
  } /*if (f2py_success) of p1*/
  /* End of cleaning variable p1 */
  } /*if (f2py_success) of p3*/
  /* End of cleaning variable p3 */
  } /*if (f2py_success) of p2*/
  /* End of cleaning variable p2 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of setup ********************************/

/*********************************** yx2ll ***********************************/
static char doc_f2py_rout_jclip_yx2ll[] = "\
yx2ll(alat0,alon0,disp,cfcst)\n\nWrapper for ``yx2ll``.\
\n\nParameters\n----------\n"
"alat0 : input float\n"
"alon0 : input float\n"
"disp : input rank-1 array('f') with bounds (12)\n"
"cfcst : input rank-1 array('f') with bounds (12)";
/* extern void F_FUNC(yx2ll,YX2LL)(float*,float*,float*,float*); */
static PyObject *f2py_rout_jclip_yx2ll(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float alat0 = 0;
  PyObject *alat0_capi = Py_None;
  float alon0 = 0;
  PyObject *alon0_capi = Py_None;
  float *disp = NULL;
  npy_intp disp_Dims[1] = {-1};
  const int disp_Rank = 1;
  PyArrayObject *capi_disp_tmp = NULL;
  int capi_disp_intent = 0;
  PyObject *disp_capi = Py_None;
  float *cfcst = NULL;
  npy_intp cfcst_Dims[1] = {-1};
  const int cfcst_Rank = 1;
  PyArrayObject *capi_cfcst_tmp = NULL;
  int capi_cfcst_intent = 0;
  PyObject *cfcst_capi = Py_None;
  static char *capi_kwlist[] = {"alat0","alon0","disp","cfcst",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:jclip.yx2ll",\
    capi_kwlist,&alat0_capi,&alon0_capi,&disp_capi,&cfcst_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable disp */
  disp_Dims[0]=12;
  capi_disp_intent |= F2PY_INTENT_IN;
  capi_disp_tmp = array_from_pyobj(NPY_FLOAT,disp_Dims,disp_Rank,capi_disp_intent,disp_capi);
  if (capi_disp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(jclip_error,"failed in converting 3rd argument `disp' of jclip.yx2ll to C/Fortran array" );
  } else {
    disp = (float *)(PyArray_DATA(capi_disp_tmp));

  /* Processing variable cfcst */
  cfcst_Dims[0]=12;
  capi_cfcst_intent |= F2PY_INTENT_IN;
  capi_cfcst_tmp = array_from_pyobj(NPY_FLOAT,cfcst_Dims,cfcst_Rank,capi_cfcst_intent,cfcst_capi);
  if (capi_cfcst_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(jclip_error,"failed in converting 4th argument `cfcst' of jclip.yx2ll to C/Fortran array" );
  } else {
    cfcst = (float *)(PyArray_DATA(capi_cfcst_tmp));

  /* Processing variable alat0 */
    f2py_success = float_from_pyobj(&alat0,alat0_capi,"jclip.yx2ll() 1st argument (alat0) can't be converted to float");
  if (f2py_success) {
  /* Processing variable alon0 */
    f2py_success = float_from_pyobj(&alon0,alon0_capi,"jclip.yx2ll() 2nd argument (alon0) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&alat0,&alon0,disp,cfcst);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of alon0*/
  /* End of cleaning variable alon0 */
  } /*if (f2py_success) of alat0*/
  /* End of cleaning variable alat0 */
  if((PyObject *)capi_cfcst_tmp!=cfcst_capi) {
    Py_XDECREF(capi_cfcst_tmp); }
  }  /*if (capi_cfcst_tmp == NULL) ... else of cfcst*/
  /* End of cleaning variable cfcst */
  if((PyObject *)capi_disp_tmp!=disp_capi) {
    Py_XDECREF(capi_disp_tmp); }
  }  /*if (capi_disp_tmp == NULL) ... else of disp*/
  /* End of cleaning variable disp */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of yx2ll ********************************/

/*********************************** uprcas ***********************************/
static char doc_f2py_rout_jclip_uprcas[] = "\
uprcas(eorw00,eorw12,eorw24)\n\nWrapper for ``uprcas``.\
\n\nParameters\n----------\n"
"eorw00 : input string(len=1)\n"
"eorw12 : input string(len=1)\n"
"eorw24 : input string(len=1)";
/* extern void F_FUNC(uprcas,UPRCAS)(string,string,string,size_t,size_t,size_t); */
static PyObject *f2py_rout_jclip_uprcas(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,string,string,size_t,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string eorw00 = NULL;
  int slen(eorw00);
  PyObject *eorw00_capi = Py_None;
  string eorw12 = NULL;
  int slen(eorw12);
  PyObject *eorw12_capi = Py_None;
  string eorw24 = NULL;
  int slen(eorw24);
  PyObject *eorw24_capi = Py_None;
  static char *capi_kwlist[] = {"eorw00","eorw12","eorw24",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:jclip.uprcas",\
    capi_kwlist,&eorw00_capi,&eorw12_capi,&eorw24_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable eorw24 */
  slen(eorw24) = 1;
  f2py_success = string_from_pyobj(&eorw24,&slen(eorw24),"",eorw24_capi,"string_from_pyobj failed in converting 3rd argument `eorw24' of jclip.uprcas to C string");
  if (f2py_success) {
  /* Processing variable eorw12 */
  slen(eorw12) = 1;
  f2py_success = string_from_pyobj(&eorw12,&slen(eorw12),"",eorw12_capi,"string_from_pyobj failed in converting 2nd argument `eorw12' of jclip.uprcas to C string");
  if (f2py_success) {
  /* Processing variable eorw00 */
  slen(eorw00) = 1;
  f2py_success = string_from_pyobj(&eorw00,&slen(eorw00),"",eorw00_capi,"string_from_pyobj failed in converting 1st argument `eorw00' of jclip.uprcas to C string");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(eorw00,eorw12,eorw24,slen(eorw00),slen(eorw12),slen(eorw24));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    STRINGFREE(eorw00);
  }  /*if (f2py_success) of eorw00*/
  /* End of cleaning variable eorw00 */
    STRINGFREE(eorw12);
  }  /*if (f2py_success) of eorw12*/
  /* End of cleaning variable eorw12 */
    STRINGFREE(eorw24);
  }  /*if (f2py_success) of eorw24*/
  /* End of cleaning variable eorw24 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of uprcas *******************************/

/*********************************** fixprd ***********************************/
static char doc_f2py_rout_jclip_fixprd[] = "\
fixprd(nsind,iyr,mon,idy,ihr,flt,fln,plt12,pln12,plt24,pln24,p)\n\nWrapper for ``fixprd``.\
\n\nParameters\n----------\n"
"nsind : input int\n"
"iyr : input int\n"
"mon : input int\n"
"idy : input int\n"
"ihr : input int\n"
"flt : input float\n"
"fln : input float\n"
"plt12 : input float\n"
"pln12 : input float\n"
"plt24 : input float\n"
"pln24 : input float\n"
"p : input rank-1 array('f') with bounds (35)";
/* extern void F_FUNC(fixprd,FIXPRD)(int*,int*,int*,int*,int*,float*,float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_jclip_fixprd(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,float*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int nsind = 0;
  PyObject *nsind_capi = Py_None;
  int iyr = 0;
  PyObject *iyr_capi = Py_None;
  int mon = 0;
  PyObject *mon_capi = Py_None;
  int idy = 0;
  PyObject *idy_capi = Py_None;
  int ihr = 0;
  PyObject *ihr_capi = Py_None;
  float flt = 0;
  PyObject *flt_capi = Py_None;
  float fln = 0;
  PyObject *fln_capi = Py_None;
  float plt12 = 0;
  PyObject *plt12_capi = Py_None;
  float pln12 = 0;
  PyObject *pln12_capi = Py_None;
  float plt24 = 0;
  PyObject *plt24_capi = Py_None;
  float pln24 = 0;
  PyObject *pln24_capi = Py_None;
  float *p = NULL;
  npy_intp p_Dims[1] = {-1};
  const int p_Rank = 1;
  PyArrayObject *capi_p_tmp = NULL;
  int capi_p_intent = 0;
  PyObject *p_capi = Py_None;
  static char *capi_kwlist[] = {"nsind","iyr","mon","idy","ihr","flt","fln","plt12","pln12","plt24","pln24","p",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOO:jclip.fixprd",\
    capi_kwlist,&nsind_capi,&iyr_capi,&mon_capi,&idy_capi,&ihr_capi,&flt_capi,&fln_capi,&plt12_capi,&pln12_capi,&plt24_capi,&pln24_capi,&p_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable plt12 */
    f2py_success = float_from_pyobj(&plt12,plt12_capi,"jclip.fixprd() 8th argument (plt12) can't be converted to float");
  if (f2py_success) {
  /* Processing variable pln24 */
    f2py_success = float_from_pyobj(&pln24,pln24_capi,"jclip.fixprd() 11st argument (pln24) can't be converted to float");
  if (f2py_success) {
  /* Processing variable idy */
    f2py_success = int_from_pyobj(&idy,idy_capi,"jclip.fixprd() 4th argument (idy) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ihr */
    f2py_success = int_from_pyobj(&ihr,ihr_capi,"jclip.fixprd() 5th argument (ihr) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pln12 */
    f2py_success = float_from_pyobj(&pln12,pln12_capi,"jclip.fixprd() 9th argument (pln12) can't be converted to float");
  if (f2py_success) {
  /* Processing variable iyr */
    f2py_success = int_from_pyobj(&iyr,iyr_capi,"jclip.fixprd() 2nd argument (iyr) can't be converted to int");
  if (f2py_success) {
  /* Processing variable flt */
    f2py_success = float_from_pyobj(&flt,flt_capi,"jclip.fixprd() 6th argument (flt) can't be converted to float");
  if (f2py_success) {
  /* Processing variable p */
  p_Dims[0]=35;
  capi_p_intent |= F2PY_INTENT_IN;
  capi_p_tmp = array_from_pyobj(NPY_FLOAT,p_Dims,p_Rank,capi_p_intent,p_capi);
  if (capi_p_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(jclip_error,"failed in converting 12nd argument `p' of jclip.fixprd to C/Fortran array" );
  } else {
    p = (float *)(PyArray_DATA(capi_p_tmp));

  /* Processing variable mon */
    f2py_success = int_from_pyobj(&mon,mon_capi,"jclip.fixprd() 3rd argument (mon) can't be converted to int");
  if (f2py_success) {
  /* Processing variable fln */
    f2py_success = float_from_pyobj(&fln,fln_capi,"jclip.fixprd() 7th argument (fln) can't be converted to float");
  if (f2py_success) {
  /* Processing variable nsind */
    f2py_success = int_from_pyobj(&nsind,nsind_capi,"jclip.fixprd() 1st argument (nsind) can't be converted to int");
  if (f2py_success) {
  /* Processing variable plt24 */
    f2py_success = float_from_pyobj(&plt24,plt24_capi,"jclip.fixprd() 10th argument (plt24) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&nsind,&iyr,&mon,&idy,&ihr,&flt,&fln,&plt12,&pln12,&plt24,&pln24,p);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of plt24*/
  /* End of cleaning variable plt24 */
  } /*if (f2py_success) of nsind*/
  /* End of cleaning variable nsind */
  } /*if (f2py_success) of fln*/
  /* End of cleaning variable fln */
  } /*if (f2py_success) of mon*/
  /* End of cleaning variable mon */
  if((PyObject *)capi_p_tmp!=p_capi) {
    Py_XDECREF(capi_p_tmp); }
  }  /*if (capi_p_tmp == NULL) ... else of p*/
  /* End of cleaning variable p */
  } /*if (f2py_success) of flt*/
  /* End of cleaning variable flt */
  } /*if (f2py_success) of iyr*/
  /* End of cleaning variable iyr */
  } /*if (f2py_success) of pln12*/
  /* End of cleaning variable pln12 */
  } /*if (f2py_success) of ihr*/
  /* End of cleaning variable ihr */
  } /*if (f2py_success) of idy*/
  /* End of cleaning variable idy */
  } /*if (f2py_success) of pln24*/
  /* End of cleaning variable pln24 */
  } /*if (f2py_success) of plt12*/
  /* End of cleaning variable plt12 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of fixprd *******************************/

/*********************************** cldxdy ***********************************/
static char doc_f2py_rout_jclip_cldxdy[] = "\
cldxdy(nsind,p,dx,dy)\n\nWrapper for ``cldxdy``.\
\n\nParameters\n----------\n"
"nsind : input int\n"
"p : input rank-1 array('f') with bounds (35)\n"
"dx : input rank-1 array('f') with bounds (6)\n"
"dy : input rank-1 array('f') with bounds (6)";
/* extern void F_FUNC(cldxdy,CLDXDY)(int*,float*,float*,float*); */
static PyObject *f2py_rout_jclip_cldxdy(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int nsind = 0;
  PyObject *nsind_capi = Py_None;
  float *p = NULL;
  npy_intp p_Dims[1] = {-1};
  const int p_Rank = 1;
  PyArrayObject *capi_p_tmp = NULL;
  int capi_p_intent = 0;
  PyObject *p_capi = Py_None;
  float *dx = NULL;
  npy_intp dx_Dims[1] = {-1};
  const int dx_Rank = 1;
  PyArrayObject *capi_dx_tmp = NULL;
  int capi_dx_intent = 0;
  PyObject *dx_capi = Py_None;
  float *dy = NULL;
  npy_intp dy_Dims[1] = {-1};
  const int dy_Rank = 1;
  PyArrayObject *capi_dy_tmp = NULL;
  int capi_dy_intent = 0;
  PyObject *dy_capi = Py_None;
  static char *capi_kwlist[] = {"nsind","p","dx","dy",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:jclip.cldxdy",\
    capi_kwlist,&nsind_capi,&p_capi,&dx_capi,&dy_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable nsind */
    f2py_success = int_from_pyobj(&nsind,nsind_capi,"jclip.cldxdy() 1st argument (nsind) can't be converted to int");
  if (f2py_success) {
  /* Processing variable p */
  p_Dims[0]=35;
  capi_p_intent |= F2PY_INTENT_IN;
  capi_p_tmp = array_from_pyobj(NPY_FLOAT,p_Dims,p_Rank,capi_p_intent,p_capi);
  if (capi_p_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(jclip_error,"failed in converting 2nd argument `p' of jclip.cldxdy to C/Fortran array" );
  } else {
    p = (float *)(PyArray_DATA(capi_p_tmp));

  /* Processing variable dx */
  dx_Dims[0]=6;
  capi_dx_intent |= F2PY_INTENT_IN;
  capi_dx_tmp = array_from_pyobj(NPY_FLOAT,dx_Dims,dx_Rank,capi_dx_intent,dx_capi);
  if (capi_dx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(jclip_error,"failed in converting 3rd argument `dx' of jclip.cldxdy to C/Fortran array" );
  } else {
    dx = (float *)(PyArray_DATA(capi_dx_tmp));

  /* Processing variable dy */
  dy_Dims[0]=6;
  capi_dy_intent |= F2PY_INTENT_IN;
  capi_dy_tmp = array_from_pyobj(NPY_FLOAT,dy_Dims,dy_Rank,capi_dy_intent,dy_capi);
  if (capi_dy_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(jclip_error,"failed in converting 4th argument `dy' of jclip.cldxdy to C/Fortran array" );
  } else {
    dy = (float *)(PyArray_DATA(capi_dy_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&nsind,p,dx,dy);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_dy_tmp!=dy_capi) {
    Py_XDECREF(capi_dy_tmp); }
  }  /*if (capi_dy_tmp == NULL) ... else of dy*/
  /* End of cleaning variable dy */
  if((PyObject *)capi_dx_tmp!=dx_capi) {
    Py_XDECREF(capi_dx_tmp); }
  }  /*if (capi_dx_tmp == NULL) ... else of dx*/
  /* End of cleaning variable dx */
  if((PyObject *)capi_p_tmp!=p_capi) {
    Py_XDECREF(capi_p_tmp); }
  }  /*if (capi_p_tmp == NULL) ... else of p*/
  /* End of cleaning variable p */
  } /*if (f2py_success) of nsind*/
  /* End of cleaning variable nsind */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of cldxdy *******************************/

/*********************************** oclip ***********************************/
static char doc_f2py_rout_jclip_oclip[] = "\
oclip(nsind,ymdh,flt,fln,plt12,pln12,plt24,pln24)\n\nWrapper for ``oclip``.\
\n\nParameters\n----------\n"
"nsind : input int\n"
"ymdh : input int\n"
"flt : input float\n"
"fln : input float\n"
"plt12 : input float\n"
"pln12 : input float\n"
"plt24 : input float\n"
"pln24 : input float";
/* extern void F_FUNC(oclip,OCLIP)(int*,int*,float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_jclip_oclip(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int nsind = 0;
  PyObject *nsind_capi = Py_None;
  int ymdh = 0;
  PyObject *ymdh_capi = Py_None;
  float flt = 0;
  PyObject *flt_capi = Py_None;
  float fln = 0;
  PyObject *fln_capi = Py_None;
  float plt12 = 0;
  PyObject *plt12_capi = Py_None;
  float pln12 = 0;
  PyObject *pln12_capi = Py_None;
  float plt24 = 0;
  PyObject *plt24_capi = Py_None;
  float pln24 = 0;
  PyObject *pln24_capi = Py_None;
  static char *capi_kwlist[] = {"nsind","ymdh","flt","fln","plt12","pln12","plt24","pln24",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO:jclip.oclip",\
    capi_kwlist,&nsind_capi,&ymdh_capi,&flt_capi,&fln_capi,&plt12_capi,&pln12_capi,&plt24_capi,&pln24_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable plt12 */
    f2py_success = float_from_pyobj(&plt12,plt12_capi,"jclip.oclip() 5th argument (plt12) can't be converted to float");
  if (f2py_success) {
  /* Processing variable pln24 */
    f2py_success = float_from_pyobj(&pln24,pln24_capi,"jclip.oclip() 8th argument (pln24) can't be converted to float");
  if (f2py_success) {
  /* Processing variable plt24 */
    f2py_success = float_from_pyobj(&plt24,plt24_capi,"jclip.oclip() 7th argument (plt24) can't be converted to float");
  if (f2py_success) {
  /* Processing variable pln12 */
    f2py_success = float_from_pyobj(&pln12,pln12_capi,"jclip.oclip() 6th argument (pln12) can't be converted to float");
  if (f2py_success) {
  /* Processing variable flt */
    f2py_success = float_from_pyobj(&flt,flt_capi,"jclip.oclip() 3rd argument (flt) can't be converted to float");
  if (f2py_success) {
  /* Processing variable ymdh */
    f2py_success = int_from_pyobj(&ymdh,ymdh_capi,"jclip.oclip() 2nd argument (ymdh) can't be converted to int");
  if (f2py_success) {
  /* Processing variable fln */
    f2py_success = float_from_pyobj(&fln,fln_capi,"jclip.oclip() 4th argument (fln) can't be converted to float");
  if (f2py_success) {
  /* Processing variable nsind */
    f2py_success = int_from_pyobj(&nsind,nsind_capi,"jclip.oclip() 1st argument (nsind) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&nsind,&ymdh,&flt,&fln,&plt12,&pln12,&plt24,&pln24);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of nsind*/
  /* End of cleaning variable nsind */
  } /*if (f2py_success) of fln*/
  /* End of cleaning variable fln */
  } /*if (f2py_success) of ymdh*/
  /* End of cleaning variable ymdh */
  } /*if (f2py_success) of flt*/
  /* End of cleaning variable flt */
  } /*if (f2py_success) of pln12*/
  /* End of cleaning variable pln12 */
  } /*if (f2py_success) of plt24*/
  /* End of cleaning variable plt24 */
  } /*if (f2py_success) of pln24*/
  /* End of cleaning variable pln24 */
  } /*if (f2py_success) of plt12*/
  /* End of cleaning variable plt12 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of oclip ********************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

static FortranDataDef f2py_wpclpfcst_def[] = {
  {"cfcst",1,{{12}},NPY_FLOAT},
  {NULL}
};
static void f2py_setup_wpclpfcst(char *cfcst) {
  int i_f2py=0;
  f2py_wpclpfcst_def[i_f2py++].data = cfcst;
}
extern void F_FUNC(f2pyinitwpclpfcst,F2PYINITWPCLPFCST)(void(*)(char*));
static void f2py_init_wpclpfcst(void) {
  F_FUNC(f2pyinitwpclpfcst,F2PYINITWPCLPFCST)(f2py_setup_wpclpfcst);
}

static FortranDataDef f2py_block1_def[] = {
  {"rcm",2,{{90,6}},NPY_FLOAT},
  {"rcz",2,{{95,6}},NPY_FLOAT},
  {"cnstm",1,{{6}},NPY_FLOAT},
  {"cnstz",1,{{6}},NPY_FLOAT},
  {NULL}
};
static void f2py_setup_block1(char *rcm,char *rcz,char *cnstm,char *cnstz) {
  int i_f2py=0;
  f2py_block1_def[i_f2py++].data = rcm;
  f2py_block1_def[i_f2py++].data = rcz;
  f2py_block1_def[i_f2py++].data = cnstm;
  f2py_block1_def[i_f2py++].data = cnstz;
}
extern void F_FUNC(f2pyinitblock1,F2PYINITBLOCK1)(void(*)(char*,char*,char*,char*));
static void f2py_init_block1(void) {
  F_FUNC(f2pyinitblock1,F2PYINITBLOCK1)(f2py_setup_block1);
}

static FortranDataDef f2py_block2_def[] = {
  {"npm",2,{{90,6}},NPY_SHORT},
  {"npz",2,{{95,6}},NPY_SHORT},
  {NULL}
};
static void f2py_setup_block2(char *npm,char *npz) {
  int i_f2py=0;
  f2py_block2_def[i_f2py++].data = npm;
  f2py_block2_def[i_f2py++].data = npz;
}
extern void F_FUNC(f2pyinitblock2,F2PYINITBLOCK2)(void(*)(char*,char*));
static void f2py_init_block2(void) {
  F_FUNC(f2pyinitblock2,F2PYINITBLOCK2)(f2py_setup_block2);
}

static FortranDataDef f2py_hgrprm_def[] = {
  {"a",2,{{3,3}},NPY_FLOAT},
  {"radpdg",0,{{-1}},NPY_FLOAT},
  {"rrthnm",0,{{-1}},NPY_FLOAT},
  {"dgridh",0,{{-1}},NPY_FLOAT},
  {"hgridx",0,{{-1}},NPY_FLOAT},
  {"hgridy",0,{{-1}},NPY_FLOAT},
  {NULL}
};
static void f2py_setup_hgrprm(char *a,char *radpdg,char *rrthnm,char *dgridh,char *hgridx,char *hgridy) {
  int i_f2py=0;
  f2py_hgrprm_def[i_f2py++].data = a;
  f2py_hgrprm_def[i_f2py++].data = radpdg;
  f2py_hgrprm_def[i_f2py++].data = rrthnm;
  f2py_hgrprm_def[i_f2py++].data = dgridh;
  f2py_hgrprm_def[i_f2py++].data = hgridx;
  f2py_hgrprm_def[i_f2py++].data = hgridy;
}
extern void F_FUNC(f2pyinithgrprm,F2PYINITHGRPRM)(void(*)(char*,char*,char*,char*,char*,char*));
static void f2py_init_hgrprm(void) {
  F_FUNC(f2pyinithgrprm,F2PYINITHGRPRM)(f2py_setup_hgrprm);
}

static FortranDataDef f2py_blockse1_def[] = {
  {"rcm",2,{{16,6}},NPY_FLOAT},
  {"rcz",2,{{14,6}},NPY_FLOAT},
  {"cnstm",1,{{6}},NPY_FLOAT},
  {"cnstz",1,{{6}},NPY_FLOAT},
  {NULL}
};
static void f2py_setup_blockse1(char *rcm,char *rcz,char *cnstm,char *cnstz) {
  int i_f2py=0;
  f2py_blockse1_def[i_f2py++].data = rcm;
  f2py_blockse1_def[i_f2py++].data = rcz;
  f2py_blockse1_def[i_f2py++].data = cnstm;
  f2py_blockse1_def[i_f2py++].data = cnstz;
}
extern void F_FUNC(f2pyinitblockse1,F2PYINITBLOCKSE1)(void(*)(char*,char*,char*,char*));
static void f2py_init_blockse1(void) {
  F_FUNC(f2pyinitblockse1,F2PYINITBLOCKSE1)(f2py_setup_blockse1);
}

static FortranDataDef f2py_blockse2_def[] = {
  {"npm",2,{{16,6}},NPY_SHORT},
  {"npz",2,{{14,6}},NPY_SHORT},
  {NULL}
};
static void f2py_setup_blockse2(char *npm,char *npz) {
  int i_f2py=0;
  f2py_blockse2_def[i_f2py++].data = npm;
  f2py_blockse2_def[i_f2py++].data = npz;
}
extern void F_FUNC(f2pyinitblockse2,F2PYINITBLOCKSE2)(void(*)(char*,char*));
static void f2py_init_blockse2(void) {
  F_FUNC(f2pyinitblockse2,F2PYINITBLOCKSE2)(f2py_setup_blockse2);
}

static FortranDataDef f2py_seiclpfcst_def[] = {
  {"cfcst",1,{{12}},NPY_FLOAT},
  {NULL}
};
static void f2py_setup_seiclpfcst(char *cfcst) {
  int i_f2py=0;
  f2py_seiclpfcst_def[i_f2py++].data = cfcst;
}
extern void F_FUNC(f2pyinitseiclpfcst,F2PYINITSEICLPFCST)(void(*)(char*));
static void f2py_init_seiclpfcst(void) {
  F_FUNC(f2pyinitseiclpfcst,F2PYINITSEICLPFCST)(f2py_setup_seiclpfcst);
}

static FortranDataDef f2py_blocksw2_def[] = {
  {"npm",2,{{31,6}},NPY_SHORT},
  {"npz",2,{{31,6}},NPY_SHORT},
  {NULL}
};
static void f2py_setup_blocksw2(char *npm,char *npz) {
  int i_f2py=0;
  f2py_blocksw2_def[i_f2py++].data = npm;
  f2py_blocksw2_def[i_f2py++].data = npz;
}
extern void F_FUNC(f2pyinitblocksw2,F2PYINITBLOCKSW2)(void(*)(char*,char*));
static void f2py_init_blocksw2(void) {
  F_FUNC(f2pyinitblocksw2,F2PYINITBLOCKSW2)(f2py_setup_blocksw2);
}

static FortranDataDef f2py_blocksw1_def[] = {
  {"rcm",2,{{31,6}},NPY_FLOAT},
  {"rcz",2,{{31,6}},NPY_FLOAT},
  {"cnstm",1,{{6}},NPY_FLOAT},
  {"cnstz",1,{{6}},NPY_FLOAT},
  {NULL}
};
static void f2py_setup_blocksw1(char *rcm,char *rcz,char *cnstm,char *cnstz) {
  int i_f2py=0;
  f2py_blocksw1_def[i_f2py++].data = rcm;
  f2py_blocksw1_def[i_f2py++].data = rcz;
  f2py_blocksw1_def[i_f2py++].data = cnstm;
  f2py_blocksw1_def[i_f2py++].data = cnstz;
}
extern void F_FUNC(f2pyinitblocksw1,F2PYINITBLOCKSW1)(void(*)(char*,char*,char*,char*));
static void f2py_init_blocksw1(void) {
  F_FUNC(f2pyinitblocksw1,F2PYINITBLOCKSW1)(f2py_setup_blocksw1);
}

static FortranDataDef f2py_swpclpfcst_def[] = {
  {"cfcst",1,{{12}},NPY_FLOAT},
  {NULL}
};
static void f2py_setup_swpclpfcst(char *cfcst) {
  int i_f2py=0;
  f2py_swpclpfcst_def[i_f2py++].data = cfcst;
}
extern void F_FUNC(f2pyinitswpclpfcst,F2PYINITSWPCLPFCST)(void(*)(char*));
static void f2py_init_swpclpfcst(void) {
  F_FUNC(f2pyinitswpclpfcst,F2PYINITSWPCLPFCST)(f2py_setup_swpclpfcst);
}

static FortranDataDef f2py_oldclpfcst_def[] = {
  {"cfcst",1,{{12}},NPY_FLOAT},
  {NULL}
};
static void f2py_setup_oldclpfcst(char *cfcst) {
  int i_f2py=0;
  f2py_oldclpfcst_def[i_f2py++].data = cfcst;
}
extern void F_FUNC(f2pyinitoldclpfcst,F2PYINITOLDCLPFCST)(void(*)(char*));
static void f2py_init_oldclpfcst(void) {
  F_FUNC(f2pyinitoldclpfcst,F2PYINITOLDCLPFCST)(f2py_setup_oldclpfcst);
}

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"wpclpr",-1,{{-1}},0,(char *)F_FUNC(wpclpr,WPCLPR),(f2py_init_func)f2py_rout_jclip_wpclpr,doc_f2py_rout_jclip_wpclpr},
  {"f1",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(f1,F1),(f2py_init_func)f2py_rout_jclip_f1,doc_f2py_rout_jclip_f1},
  {"f2",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(f2,F2),(f2py_init_func)f2py_rout_jclip_f2,doc_f2py_rout_jclip_f2},
  {"psetup",-1,{{-1}},0,(char *)F_FUNC(psetup,PSETUP),(f2py_init_func)f2py_rout_jclip_psetup,doc_f2py_rout_jclip_psetup},
  {"nmi2ll",-1,{{-1}},0,(char *)F_FUNC(nmi2ll,NMI2LL),(f2py_init_func)f2py_rout_jclip_nmi2ll,doc_f2py_rout_jclip_nmi2ll},
  {"newcyc",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(newcyc,NEWCYC),(f2py_init_func)f2py_rout_jclip_newcyc,doc_f2py_rout_jclip_newcyc},
  {"sthgpr",-1,{{-1}},0,(char *)F_FUNC(sthgpr,STHGPR),(f2py_init_func)f2py_rout_jclip_sthgpr,doc_f2py_rout_jclip_sthgpr},
  {"ll2xyh",-1,{{-1}},0,(char *)F_FUNC(ll2xyh,LL2XYH),(f2py_init_func)f2py_rout_jclip_ll2xyh,doc_f2py_rout_jclip_ll2xyh},
  {"xy2llh",-1,{{-1}},0,(char *)F_FUNC(xy2llh,XY2LLH),(f2py_init_func)f2py_rout_jclip_xy2llh,doc_f2py_rout_jclip_xy2llh},
  {"db2ll",-1,{{-1}},0,(char *)F_FUNC(db2ll,DB2LL),(f2py_init_func)f2py_rout_jclip_db2ll,doc_f2py_rout_jclip_db2ll},
  {"ll2db",-1,{{-1}},0,(char *)F_FUNC(ll2db,LL2DB),(f2py_init_func)f2py_rout_jclip_ll2db,doc_f2py_rout_jclip_ll2db},
  {"seiclp",-1,{{-1}},0,(char *)F_FUNC(seiclp,SEICLP),(f2py_init_func)f2py_rout_jclip_seiclp,doc_f2py_rout_jclip_seiclp},
  {"swpclp",-1,{{-1}},0,(char *)F_FUNC(swpclp,SWPCLP),(f2py_init_func)f2py_rout_jclip_swpclp,doc_f2py_rout_jclip_swpclp},
  {"setup",-1,{{-1}},0,(char *)F_FUNC(setup,SETUP),(f2py_init_func)f2py_rout_jclip_setup,doc_f2py_rout_jclip_setup},
  {"yx2ll",-1,{{-1}},0,(char *)F_FUNC(yx2ll,YX2LL),(f2py_init_func)f2py_rout_jclip_yx2ll,doc_f2py_rout_jclip_yx2ll},
  {"uprcas",-1,{{-1}},0,(char *)F_FUNC(uprcas,UPRCAS),(f2py_init_func)f2py_rout_jclip_uprcas,doc_f2py_rout_jclip_uprcas},
  {"fixprd",-1,{{-1}},0,(char *)F_FUNC(fixprd,FIXPRD),(f2py_init_func)f2py_rout_jclip_fixprd,doc_f2py_rout_jclip_fixprd},
  {"cldxdy",-1,{{-1}},0,(char *)F_FUNC(cldxdy,CLDXDY),(f2py_init_func)f2py_rout_jclip_cldxdy,doc_f2py_rout_jclip_cldxdy},
  {"oclip",-1,{{-1}},0,(char *)F_FUNC(oclip,OCLIP),(f2py_init_func)f2py_rout_jclip_oclip,doc_f2py_rout_jclip_oclip},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "jclip",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_jclip(void) {
#else
#define RETVAL
PyMODINIT_FUNC initjclip(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = jclip_module = PyModule_Create(&moduledef);
#else
  m = jclip_module = Py_InitModule("jclip", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module jclip (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'jclip' is auto-generated with f2py (version:2).\nFunctions:\n"
"  wpclpr(idatim,alat00,alon00,alat12,alon12,alat24,alon24,wind)\n"
"  f1 = f1(alon)\n"
"  f2 = f2(idatim)\n"
"  psetup(p1,p2,p3,p4,p5,p6,p7,p8,p)\n"
"  nmi2ll(alat0,alon0,cnmis,cfcst)\n"
"  newcyc = newcyc(nowcyc,n)\n"
"  sthgpr(xlath,xlonh,bear,gridsz,xi0,yj0)\n"
"  ll2xyh(xlat,xlong,xi,yj)\n"
"  xy2llh(xi,yj,xlat,xlong)\n"
"  db2ll(xlato,xlono,dist,bear,xlatt,xlont)\n"
"  ll2db(xlato,xlono,xlatt,xlont,dist,bear)\n"
"  seiclp(idatim,alat00,alon00,alat12,alon12,alat24,alon24,wind)\n"
"  swpclp(idatim,alat00,alon00,alat12,alon12,alat24,alon24,wind)\n"
"  setup(p1,p2,p3,p4,p5,p6,p7,p8,p)\n"
"  yx2ll(alat0,alon0,disp,cfcst)\n"
"  uprcas(eorw00,eorw12,eorw24)\n"
"  fixprd(nsind,iyr,mon,idy,ihr,flt,fln,plt12,pln12,plt24,pln24,p)\n"
"  cldxdy(nsind,p,dx,dy)\n"
"  oclip(nsind,ymdh,flt,fln,plt12,pln12,plt24,pln24)\n"
"COMMON blocks:\n""  /wpclpfcst/ cfcst(12)\n""  /block1/ rcm(90,6),rcz(95,6),cnstm(6),cnstz(6)\n""  /block2/ npm(90,6),npz(95,6)\n""  /hgrprm/ a(3,3),radpdg,rrthnm,dgridh,hgridx,hgridy\n""  /blockse1/ rcm(16,6),rcz(14,6),cnstm(6),cnstz(6)\n""  /blockse2/ npm(16,6),npz(14,6)\n""  /seiclpfcst/ cfcst(12)\n""  /blocksw2/ npm(31,6),npz(31,6)\n""  /blocksw1/ rcm(31,6),rcz(31,6),cnstm(6),cnstz(6)\n""  /swpclpfcst/ cfcst(12)\n""  /oldclpfcst/ cfcst(12)\n"".");
  PyDict_SetItemString(d, "__doc__", s);
  jclip_error = PyErr_NewException ("jclip.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));


    {
      extern float F_FUNC(f1,F1)(void);
      PyObject* o = PyDict_GetItemString(d,"f1");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(f1,F1),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("f1"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("f1"));
#endif
    }
    

    {
      extern float F_FUNC(f2,F2)(void);
      PyObject* o = PyDict_GetItemString(d,"f2");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(f2,F2),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("f2"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("f2"));
#endif
    }
    



    {
      extern int F_FUNC(newcyc,NEWCYC)(void);
      PyObject* o = PyDict_GetItemString(d,"newcyc");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(newcyc,NEWCYC),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("newcyc"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("newcyc"));
#endif
    }
    













/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

  F2PyDict_SetItemString(d, "wpclpfcst", PyFortranObject_New(f2py_wpclpfcst_def,f2py_init_wpclpfcst));
  F2PyDict_SetItemString(d, "block1", PyFortranObject_New(f2py_block1_def,f2py_init_block1));
  F2PyDict_SetItemString(d, "block2", PyFortranObject_New(f2py_block2_def,f2py_init_block2));
  F2PyDict_SetItemString(d, "hgrprm", PyFortranObject_New(f2py_hgrprm_def,f2py_init_hgrprm));
  F2PyDict_SetItemString(d, "blockse1", PyFortranObject_New(f2py_blockse1_def,f2py_init_blockse1));
  F2PyDict_SetItemString(d, "blockse2", PyFortranObject_New(f2py_blockse2_def,f2py_init_blockse2));
  F2PyDict_SetItemString(d, "seiclpfcst", PyFortranObject_New(f2py_seiclpfcst_def,f2py_init_seiclpfcst));
  F2PyDict_SetItemString(d, "blocksw2", PyFortranObject_New(f2py_blocksw2_def,f2py_init_blocksw2));
  F2PyDict_SetItemString(d, "blocksw1", PyFortranObject_New(f2py_blocksw1_def,f2py_init_blocksw1));
  F2PyDict_SetItemString(d, "swpclpfcst", PyFortranObject_New(f2py_swpclpfcst_def,f2py_init_swpclpfcst));
  F2PyDict_SetItemString(d, "oldclpfcst", PyFortranObject_New(f2py_oldclpfcst_def,f2py_init_oldclpfcst));
/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"jclip");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
