C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2.45.241_1926)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapF1 (F1f2pywrap, ALON)
      external F1
      real ALON
      real F1f2pywrap, F1
      F1f2pywrap = F1(ALON)
      end


      subroutine f2pywrapF2 (F2f2pywrap, IDATIM)
      external F2
      integer IDATIM
      real F2f2pywrap, F2
      F2f2pywrap = F2(IDATIM)
      end


      subroutine f2pywrapNEWCYC (NEWCYCf2pywrap, NOWCYC, N)
      external NEWCYC
      integer NOWCYC
      integer N
      integer NEWCYCf2pywrap, NEWCYC
      NEWCYCf2pywrap = NEWCYC(NOWCYC, N)
      end


      subroutine f2pyinitwpclpfcst(setupfunc)
      external setupfunc
      real CFCST(12)
      common /wpclpfcst/ CFCST
      call setupfunc(CFCST)
      end

      subroutine f2pyinitBLOCK1(setupfunc)
      external setupfunc
      real RCM(90,6)
      real RCZ(95,6)
      real CNSTM(6)
      real CNSTZ(6)
      common /BLOCK1/ RCM,RCZ,CNSTM,CNSTZ
      call setupfunc(RCM,RCZ,CNSTM,CNSTZ)
      end

      subroutine f2pyinitBLOCK2(setupfunc)
      external setupfunc
      integer*2 NPM(90,6)
      integer*2 NPZ(95,6)
      common /BLOCK2/ NPM,NPZ
      call setupfunc(NPM,NPZ)
      end

      subroutine f2pyinitHGRPRM(setupfunc)
      external setupfunc
      real A(3,3)
      real RADPDG
      real RRTHNM
      real DGRIDH
      real HGRIDX
      real HGRIDY
      common /HGRPRM/ A,RADPDG,RRTHNM,DGRIDH,HGRIDX,HGRIDY
      call setupfunc(A,RADPDG,RRTHNM,DGRIDH,HGRIDX,HGRIDY)
      end

      subroutine f2pyinitBLOCKSE1(setupfunc)
      external setupfunc
      real RCM(16,6)
      real RCZ(14,6)
      real CNSTM(6)
      real CNSTZ(6)
      common /BLOCKSE1/ RCM,RCZ,CNSTM,CNSTZ
      call setupfunc(RCM,RCZ,CNSTM,CNSTZ)
      end

      subroutine f2pyinitBLOCKSE2(setupfunc)
      external setupfunc
      integer*2 NPM(16,6)
      integer*2 NPZ(14,6)
      common /BLOCKSE2/ NPM,NPZ
      call setupfunc(NPM,NPZ)
      end

      subroutine f2pyinitseiclpfcst(setupfunc)
      external setupfunc
      real cfcst(12)
      common /seiclpfcst/ cfcst
      call setupfunc(cfcst)
      end

      subroutine f2pyinitBLOCKSW2(setupfunc)
      external setupfunc
      integer*2 NPM(31,6)
      integer*2 NPZ(31,6)
      common /BLOCKSW2/ NPM,NPZ
      call setupfunc(NPM,NPZ)
      end

      subroutine f2pyinitBLOCKSW1(setupfunc)
      external setupfunc
      real RCM(31,6)
      real RCZ(31,6)
      real CNSTM(6)
      real CNSTZ(6)
      common /BLOCKSW1/ RCM,RCZ,CNSTM,CNSTZ
      call setupfunc(RCM,RCZ,CNSTM,CNSTZ)
      end

      subroutine f2pyinitswpclpfcst(setupfunc)
      external setupfunc
      real cfcst(12)
      common /swpclpfcst/ cfcst
      call setupfunc(cfcst)
      end

      subroutine f2pyinitoldclpfcst(setupfunc)
      external setupfunc
      real cfcst(12)
      common /oldclpfcst/ cfcst
      call setupfunc(cfcst)
      end


