c
c  SCCS IDENTIFICATION:
c
c     name          description
c   ---------      --------------------------------------------------
c    gz1mn         minumum value of geopotential in gz1 field
c    gz1mx         maximum value of geopotential in gz1 field
c    gz2mn         minumum value of geopotential in gz2 field
c    gz2mx         maximum value of geopotential in gz2 field
c    pt1mn         minumum value of potential temperature in pt1 field
c    pt1mx         maximum value of potential temperature in pt1 field
c    pt2mn         minumum value of potential temperature in pt2 field
c    pt2mx         maximum value of potential temperature in pt2 field
c
      double precision gz1mn,gz1mx,gz2mn,gz2mx,pt1mn,pt1mx,pt2mn,pt2mx
c
      common/ztlmts/ gz1mn,gz1mx,gz2mn,gz2mx,pt1mn,pt1mx,pt2mn,pt2mx
c
