/* File: nclipmodule.c
 * This file is auto-generated with f2py (version:2.317).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Tue Apr  6 12:23:22 2004
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __CPLUSPLUS__
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include "fortranobject.h"
#include <string.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *nclip_error;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#ifdef OLDPYNUM
#error You need to intall Numeric Python version 13 or higher. Get it from http:/sourceforge.net/project/?group_id=1369
#endif

#define NUMFROMARROBJ(typenum,ctype) \
  if (PyArray_Check(obj)) arr = (PyArrayObject *)obj;\
  else arr = (PyArrayObject *)PyArray_ContiguousFromObject(obj,typenum,0,0);\
  if (arr) {\
    if (arr->descr->type_num==PyArray_OBJECT) {\
      if (ctype ## _from_pyobj(v,(arr->descr->getitem)(arr->data),"")) return 1;\
      goto capi_fail;\
    }\
    (arr->descr->cast[typenum])((void *)(arr->data),1,(void *)(v),1,1);\
    return 1;\
  }

#define STRINGCOPYN(to,from,n)\
  if ((strncpy(to,from,sizeof(char)*(n))) == NULL) {\
    PyErr_SetString(PyExc_MemoryError, "strncpy failed");\
    goto capi_fail;\
  }

#define STRINGMALLOC(str,len)\
  if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
    PyErr_SetString(PyExc_MemoryError, "out of memory");\
    goto capi_fail;\
  } (str)[len] = '\0';

#define ISCONTIGUOUS(m) ((m)->flags & CONTIGUOUS)
#define PRINTPYOBJERR(obj)\
  fprintf(stderr,"nclip.error is related to ");\
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");

#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif

#define len(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[0])
#define rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
#define index(i) capi_i ## i
#define slen(var) capi_ ## var ## _len

#define STRINGFREE(str)\
  if (!(str == NULL)) free(str);

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
/*     Here starts Travis Oliphant's contribution     */
#define INCREMENT(ret_ind, nd, max_ind) \
{ \
  int k; \
  k = (nd) - 1; \
  if (k<0) (ret_ind)[0] = (max_ind)[0]; else \
  if (++(ret_ind)[k] >= (max_ind)[k]) { \
    while (k >= 0 && ((ret_ind)[k] >= (max_ind)[k]-1)) \
      (ret_ind)[k--] = 0; \
    if (k >= 0) (ret_ind)[k]++; \
    else (ret_ind)[0] = (max_ind)[0]; \
  }  \
}
#define CALCINDEX(indx, nd_index, strides, ndim) \
{ \
  int i; \
  indx = 0; \
  for (i=0; i < (ndim); i++)  \
    indx += nd_index[i]*strides[i]; \
} 
static int copy_ND_array(PyArrayObject *in, PyArrayObject *out)
{

  /* This routine copies an N-D array in to an N-D array out where both
     can be discontiguous.  An appropriate (raw) cast is made on the data.
  */

  /* It works by using an N-1 length vector to hold the N-1 first indices 
     into the array.  This counter is looped through copying (and casting) 
     the entire last dimension at a time.
  */

  int *nd_index, indx1;
  int indx2, last_dim;
  int instep, outstep;

  if (0 == in->nd) {
    in->descr->cast[out->descr->type_num]((void *)in->data,1,(void *)out->data,1,1);
    return 0;
  }
  nd_index = (int *)calloc(in->nd-1,sizeof(int));
  last_dim = in->nd - 1;
  instep = in->strides[last_dim] / in->descr->elsize;
  outstep = out->strides[last_dim] / out->descr->elsize;
  if (NULL == nd_index ) {
     fprintf(stderr,"Could not allocate memory for index array.\n");
     return -1;
  }
  CFUNCSMESS("copy_ND_array: doing a complete copy\n");
  while(nd_index[0] != in->dimensions[0]) {
    CALCINDEX(indx1,nd_index,in->strides,in->nd-1);
    CALCINDEX(indx2,nd_index,out->strides,out->nd-1);
    /* Copy (with an appropriate cast) the last dimension of the array */
    (in->descr->cast[out->descr->type_num])((void *)(in->data+indx1),instep,(void *)(out->data+indx2),outstep,in->dimensions[last_dim]); 
    INCREMENT(nd_index,in->nd-1,in->dimensions);
  }
  free(nd_index);
  return 0;
} 
/* EOF T.O.'s contib */

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  PyObject *o = NULL;
  if (obj == Py_None) {
    if (*len == -1)
      *len = strlen(inistr); /* Will this cause problems? */
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,inistr,*len);
    return 1;
  }
  if (PyArray_Check(obj)) {
    if ((arr = (PyArrayObject *)obj) == NULL)
      goto capi_fail;
    if (!ISCONTIGUOUS(arr)) {
      fprintf(stderr,"nclip: string_from_pyobj: array object is non-contiguous.\n");
      goto capi_fail;
    }
    if (*len == -1)
      *len = (arr->descr->elsize)*PyArray_SIZE(arr);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,arr->data,*len);
    return 1;
  }
  if (PyString_Check(obj))
    o = obj;
  else
    o = PyObject_Str(obj);
  if (o == NULL) goto capi_fail;
  if (*len == -1)
    *len = PyString_GET_SIZE(o);
  STRINGMALLOC(*str,*len);
  STRINGCOPYN(*str,PyString_AS_STRING(o),*len);
  return 1;
capi_fail:
  PRINTPYOBJERR(obj);
  PyErr_SetString(nclip_error,errmess);
  return 0;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  if (PyFloat_Check(obj)) {
    *v = PyFloat_AS_DOUBLE(obj);
    return 1;
  }
  if (PyInt_Check(obj)) {
    *v = PyInt_AS_LONG(obj);
    return 1;
  }
  if (PyComplex_Check(obj)) {
    *v = PyComplex_RealAsDouble(obj);
    return 1;
  }
  if (PyLong_Check(obj)) {
    *v = PyLong_AsDouble(obj);
    return 1;
  }
  NUMFROMARROBJ(PyArray_FLOAT,float);
capi_fail:
  PRINTPYOBJERR(obj);
  PyErr_SetString(nclip_error,errmess);
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  if (PyInt_Check(obj)) {
    *v = PyInt_AS_LONG(obj);
    return 1;
  }
  if (PyLong_Check(obj)) {
    *v = PyLong_AsLong(obj);
    return 1;
  }
  if (PyFloat_Check(obj)) {
    *v = PyFloat_AS_DOUBLE(obj);
    return 1;
  }
  if (PyComplex_Check(obj)) {
    *v = PyComplex_RealAsDouble(obj);
    return 1;
  }
  NUMFROMARROBJ(PyArray_INT,int);
capi_fail:
  PRINTPYOBJERR(obj);
  PyErr_SetString(nclip_error,errmess);
  return 0;
}

static PyArrayObject *arr_from_pyobj(int type,int *dims,int rank,PyObject *obj) {
  PyArrayObject *self = NULL;
  PyArrayObject *self_cp = NULL;
  int i;
  if (obj == Py_None) {
    CFUNCSMESS("arr_from_pyobj: obj = None. Doing FromDims\n");
    self = (PyArrayObject *)PyArray_FromDims(rank,dims,type);
  } else {
    CFUNCSMESS("arr_from_pyobj: Trying ContigiousFromObject\n");
    self = (PyArrayObject *)PyArray_ContiguousFromObject(obj,type,0,0);
    if (self == NULL)
      CFUNCSMESS("arr_from_pyobj:  ContigiousFromObject unsuccesful\n");
  }
  if ((self == NULL) && PyArray_Check(obj)) { /* if could not cast safely in above */
    int loc_rank = ((PyArrayObject *)obj)->nd;
    int *loc_dims = ((PyArrayObject *)obj)->dimensions;
    CFUNCSMESS("arr_from_pyobj: isarray(obj). Doing FromDims\n");
    self = (PyArrayObject *)PyArray_FromDims(loc_rank,loc_dims,type);
  }
  if (self == NULL) {
    int i;
    fprintf(stderr,"arr_from_pyobj: PyArray_FromDims failed (rank=%d,type=%d,dims=(%d",rank,type,dims[0]);
    for(i=1;i<rank;i++) fprintf(stderr,",%d",dims[i]);
    fprintf(stderr,"))\n");
    goto capi_fail;
  }
    self_cp = self;
  if (!(rank==self->nd)) {
    int u_dim = -1, dims_s = 1, self_s = (self->nd)?PyArray_Size((PyObject *)self):1;
    CFUNCSMESS("arr_from_pyobj: Mismatch of ranks. Trying to match.\n");
    CFUNCSMESS("arr_from_pyobj:");
#ifdef DEBUGCFUNCS
    fprintf(stderr,"rank=%d,self->nd=%d,dims=(",rank,self->nd);
    for(i=0;i<rank;i++) fprintf(stderr," %d",dims[i]);
    fprintf(stderr,")\n");
#endif
    for(i=0;i<rank;i++)
      if (dims[i]<1)
        if (u_dim<0) u_dim = i;
        else dims[i] = 1;
      else dims_s *= dims[i];
    if (u_dim >= 0) {
      dims[u_dim] = self_s/dims_s;
      dims_s *= dims[u_dim];
    }
    CFUNCSMESS("arr_from_pyobj:");
#ifdef DEBUGCFUNCS
    fprintf(stderr,"rank=%d,self->nd=%d,self_s=%d,dims_s=%d,dims=(",rank,self->nd,self_s,dims_s);
    for(i=0;i<rank;i++) fprintf(stderr," %d",dims[i]);
    fprintf(stderr,")\n");
#endif
    if (self_s != dims_s) {
      fprintf(stderr,"nclip:arr_from_pyobj: expected rank-%d array but got rank-%d array with different size.\n",rank,self->nd);
    goto capi_fail;
    }
    self = (PyArrayObject *)PyArray_FromDimsAndDataAndDescr(rank, dims,self_cp->descr,self_cp->data);
    if (self == NULL)
      goto capi_fail;
    Py_INCREF(self_cp);
    self->base = (PyObject *)self_cp;
  }
  for (i=0;i<rank;i++)
    if (dims[i]>self->dimensions[i]) {
      fprintf(stderr,"nclip:arr_from_pyobj: %d-th dimension must be at least %d but got %d.\n",i+1,dims[i],self->dimensions[i]);
      goto capi_fail;
    }
  if (((PyObject *)self_cp != obj) && PyArray_Check(obj)) {
    if (copy_ND_array((PyArrayObject *)obj,self_cp)) {
      fprintf(stderr,"nclip:arr_from_pyobj: failed to copy object to rank-%d array with shape (",self_cp->nd);
      for(i=0;i<self_cp->nd;i++) fprintf(stderr,"%d,",self_cp->dimensions[i]);
      fprintf(stderr,")\n");
      PRINTPYOBJERR((PyObject *)self_cp);
      goto capi_fail;
    }
  }
  if (self != NULL)
    return self;
  CFUNCSMESS("arr_from_pyobj: self==NULL. Confused?!.\n");
capi_fail:
  PRINTPYOBJERR(obj);
  Py_XDECREF(self);
  return NULL;
}
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  if (PyFloat_Check(obj)) {
    *v = PyFloat_AS_DOUBLE(obj);
    return 1;
  }
  if (PyInt_Check(obj)) {
    *v = PyInt_AS_LONG(obj);
    return 1;
  }
  if (PyLong_Check(obj)) {
    *v = PyLong_AsDouble(obj);
    return 1;
  }
  if (PyComplex_Check(obj)) {
    *v = PyComplex_RealAsDouble(obj);
    return 1;
  }
  NUMFROMARROBJ(PyArray_DOUBLE,double);
capi_fail:
  PRINTPYOBJERR(obj);
  PyErr_SetString(nclip_error,errmess);
  return 0;
}


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** lastch ***********************************/
static char doc_nclip_lastch[] = "\
Function signature:\n\
  lastch = lastch(string_v)\n\
Required arguments:\n\
  string_v : input string(len=-1)\n\
Return objects:\n\
  lastch : int";
/* extern void F_WRAPPEDFUNC(lastch,LASTCH)(); */ /* obsolute */
static PyObject *nclip_lastch(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  int lastch;
  string string_v = NULL;
  int slen(string_v);
  PyObject *string_v_capi = Py_None;
  static char *capi_kwlist[] = {"string_v",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O|:nclip.lastch",\
    capi_kwlist,&string_v_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable lastch */
  /* Processing variable string_v */
  slen(string_v) = -1;
  if (!string_from_pyobj(&string_v,&slen(string_v),"",string_v_capi,"string_from_pyobj failed in converting 1st argument `string_v' of nclip.lastch to C string"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&lastch,string_v,slen(string_v));
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("i",lastch);
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  STRINGFREE(string_v);
  return capi_buildvalue;
}
/******************************* end of lastch *******************************/

/*********************************** xtrap ***********************************/
static char doc_nclip_xtrap[] = "\
Function signature:\n\
  xtrap(iymdh,latcur,loncur,latm12,lonm12,strmid)\n\
Required arguments:\n\
  iymdh : input int\n\
  latcur : input float\n\
  loncur : input float\n\
  latm12 : input float\n\
  lonm12 : input float\n\
  strmid : input string(len=8)";
/* extern void F_FUNC(xtrap,XTRAP)(); */ /* obsolute */
static PyObject *nclip_xtrap(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  int iymdh;
  PyObject *iymdh_capi = Py_None;
  float latcur;
  PyObject *latcur_capi = Py_None;
  float loncur;
  PyObject *loncur_capi = Py_None;
  float latm12;
  PyObject *latm12_capi = Py_None;
  float lonm12;
  PyObject *lonm12_capi = Py_None;
  string strmid = NULL;
  int slen(strmid);
  PyObject *strmid_capi = Py_None;
  static char *capi_kwlist[] = {"iymdh","latcur","loncur","latm12","lonm12","strmid",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|:nclip.xtrap",\
    capi_kwlist,&iymdh_capi,&latcur_capi,&loncur_capi,&latm12_capi,&lonm12_capi,&strmid_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable strmid */
  slen(strmid) = 8;
  if (!string_from_pyobj(&strmid,&slen(strmid),"",strmid_capi,"string_from_pyobj failed in converting 6th argument `strmid' of nclip.xtrap to C string"))
    goto capi_fail;
  /* Processing variable latcur */
  if (!float_from_pyobj(&latcur,latcur_capi,"float_from_pyobj failed in converting 2nd argument `latcur' of nclip.xtrap to C float\n"))
    goto capi_fail;
  /* Processing variable latm12 */
  if (!float_from_pyobj(&latm12,latm12_capi,"float_from_pyobj failed in converting 4th argument `latm12' of nclip.xtrap to C float\n"))
    goto capi_fail;
  /* Processing variable loncur */
  if (!float_from_pyobj(&loncur,loncur_capi,"float_from_pyobj failed in converting 3rd argument `loncur' of nclip.xtrap to C float\n"))
    goto capi_fail;
  /* Processing variable lonm12 */
  if (!float_from_pyobj(&lonm12,lonm12_capi,"float_from_pyobj failed in converting 5th argument `lonm12' of nclip.xtrap to C float\n"))
    goto capi_fail;
  /* Processing variable iymdh */
  if (!int_from_pyobj(&iymdh,iymdh_capi,"int_from_pyobj failed in converting 1st argument `iymdh' of nclip.xtrap to C int\n"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&iymdh,&latcur,&loncur,&latm12,&lonm12,strmid,slen(strmid));
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  STRINGFREE(strmid);
  return capi_buildvalue;
}
/******************************** end of xtrap ********************************/

/*********************************** rhdst ***********************************/
static char doc_nclip_rhdst[] = "\
Function signature:\n\
  rhdst(flat,flng,tlat,tlng,dir,dst)\n\
Required arguments:\n\
  flat : input float\n\
  flng : input float\n\
  tlat : input float\n\
  tlng : input float\n\
  dir : input float\n\
  dst : input float";
/* extern void F_FUNC(rhdst,RHDST)(); */ /* obsolute */
static PyObject *nclip_rhdst(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  float flat;
  PyObject *flat_capi = Py_None;
  float flng;
  PyObject *flng_capi = Py_None;
  float tlat;
  PyObject *tlat_capi = Py_None;
  float tlng;
  PyObject *tlng_capi = Py_None;
  float dir;
  PyObject *dir_capi = Py_None;
  float dst;
  PyObject *dst_capi = Py_None;
  static char *capi_kwlist[] = {"flat","flng","tlat","tlng","dir","dst",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|:nclip.rhdst",\
    capi_kwlist,&flat_capi,&flng_capi,&tlat_capi,&tlng_capi,&dir_capi,&dst_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable flng */
  if (!float_from_pyobj(&flng,flng_capi,"float_from_pyobj failed in converting 2nd argument `flng' of nclip.rhdst to C float\n"))
    goto capi_fail;
  /* Processing variable dir */
  if (!float_from_pyobj(&dir,dir_capi,"float_from_pyobj failed in converting 5th argument `dir' of nclip.rhdst to C float\n"))
    goto capi_fail;
  /* Processing variable dst */
  if (!float_from_pyobj(&dst,dst_capi,"float_from_pyobj failed in converting 6th argument `dst' of nclip.rhdst to C float\n"))
    goto capi_fail;
  /* Processing variable tlng */
  if (!float_from_pyobj(&tlng,tlng_capi,"float_from_pyobj failed in converting 4th argument `tlng' of nclip.rhdst to C float\n"))
    goto capi_fail;
  /* Processing variable tlat */
  if (!float_from_pyobj(&tlat,tlat_capi,"float_from_pyobj failed in converting 3rd argument `tlat' of nclip.rhdst to C float\n"))
    goto capi_fail;
  /* Processing variable flat */
  if (!float_from_pyobj(&flat,flat_capi,"float_from_pyobj failed in converting 1st argument `flat' of nclip.rhdst to C float\n"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&flat,&flng,&tlat,&tlng,&dir,&dst);
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  return capi_buildvalue;
}
/******************************** end of rhdst ********************************/

/*********************************** rltlg ***********************************/
static char doc_nclip_rltlg[] = "\
Function signature:\n\
  rltlg(flat,flng,tlat,tlng,dir,dst)\n\
Required arguments:\n\
  flat : input float\n\
  flng : input float\n\
  tlat : input float\n\
  tlng : input float\n\
  dir : input float\n\
  dst : input float";
/* extern void F_FUNC(rltlg,RLTLG)(); */ /* obsolute */
static PyObject *nclip_rltlg(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  float flat;
  PyObject *flat_capi = Py_None;
  float flng;
  PyObject *flng_capi = Py_None;
  float tlat;
  PyObject *tlat_capi = Py_None;
  float tlng;
  PyObject *tlng_capi = Py_None;
  float dir;
  PyObject *dir_capi = Py_None;
  float dst;
  PyObject *dst_capi = Py_None;
  static char *capi_kwlist[] = {"flat","flng","tlat","tlng","dir","dst",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|:nclip.rltlg",\
    capi_kwlist,&flat_capi,&flng_capi,&tlat_capi,&tlng_capi,&dir_capi,&dst_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable flng */
  if (!float_from_pyobj(&flng,flng_capi,"float_from_pyobj failed in converting 2nd argument `flng' of nclip.rltlg to C float\n"))
    goto capi_fail;
  /* Processing variable dir */
  if (!float_from_pyobj(&dir,dir_capi,"float_from_pyobj failed in converting 5th argument `dir' of nclip.rltlg to C float\n"))
    goto capi_fail;
  /* Processing variable dst */
  if (!float_from_pyobj(&dst,dst_capi,"float_from_pyobj failed in converting 6th argument `dst' of nclip.rltlg to C float\n"))
    goto capi_fail;
  /* Processing variable tlng */
  if (!float_from_pyobj(&tlng,tlng_capi,"float_from_pyobj failed in converting 4th argument `tlng' of nclip.rltlg to C float\n"))
    goto capi_fail;
  /* Processing variable tlat */
  if (!float_from_pyobj(&tlat,tlat_capi,"float_from_pyobj failed in converting 3rd argument `tlat' of nclip.rltlg to C float\n"))
    goto capi_fail;
  /* Processing variable flat */
  if (!float_from_pyobj(&flat,flat_capi,"float_from_pyobj failed in converting 1st argument `flat' of nclip.rltlg to C float\n"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&flat,&flng,&tlat,&tlng,&dir,&dst);
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  return capi_buildvalue;
}
/******************************** end of rltlg ********************************/

/*********************************** atclip ***********************************/
static char doc_nclip_atclip[] = "\
Function signature:\n\
  atclip(iymdh,y,x,dnow,snow,dm12,sm12,wkts,strmid)\n\
Required arguments:\n\
  iymdh : input int\n\
  y : input float\n\
  x : input float\n\
  dnow : input float\n\
  snow : input float\n\
  dm12 : input float\n\
  sm12 : input float\n\
  wkts : input float\n\
  strmid : input string(len=8)";
/* extern void F_FUNC(atclip,ATCLIP)(); */ /* obsolute */
static PyObject *nclip_atclip(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  int iymdh;
  PyObject *iymdh_capi = Py_None;
  float y;
  PyObject *y_capi = Py_None;
  float x;
  PyObject *x_capi = Py_None;
  float dnow;
  PyObject *dnow_capi = Py_None;
  float snow;
  PyObject *snow_capi = Py_None;
  float dm12;
  PyObject *dm12_capi = Py_None;
  float sm12;
  PyObject *sm12_capi = Py_None;
  float wkts;
  PyObject *wkts_capi = Py_None;
  string strmid = NULL;
  int slen(strmid);
  PyObject *strmid_capi = Py_None;
  static char *capi_kwlist[] = {"iymdh","y","x","dnow","snow","dm12","sm12","wkts","strmid",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO|:nclip.atclip",\
    capi_kwlist,&iymdh_capi,&y_capi,&x_capi,&dnow_capi,&snow_capi,&dm12_capi,&sm12_capi,&wkts_capi,&strmid_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable strmid */
  slen(strmid) = 8;
  if (!string_from_pyobj(&strmid,&slen(strmid),"",strmid_capi,"string_from_pyobj failed in converting 9th argument `strmid' of nclip.atclip to C string"))
    goto capi_fail;
  /* Processing variable x */
  if (!float_from_pyobj(&x,x_capi,"float_from_pyobj failed in converting 3rd argument `x' of nclip.atclip to C float\n"))
    goto capi_fail;
  /* Processing variable y */
  if (!float_from_pyobj(&y,y_capi,"float_from_pyobj failed in converting 2nd argument `y' of nclip.atclip to C float\n"))
    goto capi_fail;
  /* Processing variable sm12 */
  if (!float_from_pyobj(&sm12,sm12_capi,"float_from_pyobj failed in converting 7th argument `sm12' of nclip.atclip to C float\n"))
    goto capi_fail;
  /* Processing variable snow */
  if (!float_from_pyobj(&snow,snow_capi,"float_from_pyobj failed in converting 5th argument `snow' of nclip.atclip to C float\n"))
    goto capi_fail;
  /* Processing variable dnow */
  if (!float_from_pyobj(&dnow,dnow_capi,"float_from_pyobj failed in converting 4th argument `dnow' of nclip.atclip to C float\n"))
    goto capi_fail;
  /* Processing variable wkts */
  if (!float_from_pyobj(&wkts,wkts_capi,"float_from_pyobj failed in converting 8th argument `wkts' of nclip.atclip to C float\n"))
    goto capi_fail;
  /* Processing variable iymdh */
  if (!int_from_pyobj(&iymdh,iymdh_capi,"int_from_pyobj failed in converting 1st argument `iymdh' of nclip.atclip to C int\n"))
    goto capi_fail;
  /* Processing variable dm12 */
  if (!float_from_pyobj(&dm12,dm12_capi,"float_from_pyobj failed in converting 6th argument `dm12' of nclip.atclip to C float\n"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&iymdh,&y,&x,&dnow,&snow,&dm12,&sm12,&wkts,strmid,slen(strmid));
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  STRINGFREE(strmid);
  return capi_buildvalue;
}
/******************************* end of atclip *******************************/

/*********************************** cgulf ***********************************/
static char doc_nclip_cgulf[] = "\
Function signature:\n\
  cgulf(y,x,u,v,u12,v12,dn,w,wgulf,gulf)\n\
Required arguments:\n\
  y : input float\n\
  x : input float\n\
  u : input float\n\
  v : input float\n\
  u12 : input float\n\
  v12 : input float\n\
  dn : input float\n\
  w : input float\n\
  wgulf : input float\n\
  gulf : input rank-1 array('f') with bounds (10)";
/* extern void F_FUNC(cgulf,CGULF)(); */ /* obsolute */
static PyObject *nclip_cgulf(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  float y;
  PyObject *y_capi = Py_None;
  float x;
  PyObject *x_capi = Py_None;
  float u;
  PyObject *u_capi = Py_None;
  float v;
  PyObject *v_capi = Py_None;
  float u12;
  PyObject *u12_capi = Py_None;
  float v12;
  PyObject *v12_capi = Py_None;
  float dn;
  PyObject *dn_capi = Py_None;
  float w;
  PyObject *w_capi = Py_None;
  float wgulf;
  PyObject *wgulf_capi = Py_None;
  float *gulf = NULL;
  int gulf_Dims[1] = {-1};
  PyArrayObject *capi_gulf_tmp = NULL;
  PyObject *gulf_capi = Py_None;
  static char *capi_kwlist[] = {"y","x","u","v","u12","v12","dn","w","wgulf","gulf",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOO|:nclip.cgulf",\
    capi_kwlist,&y_capi,&x_capi,&u_capi,&v_capi,&u12_capi,&v12_capi,&dn_capi,&w_capi,&wgulf_capi,&gulf_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable wgulf */
  if (!float_from_pyobj(&wgulf,wgulf_capi,"float_from_pyobj failed in converting 9th argument `wgulf' of nclip.cgulf to C float\n"))
    goto capi_fail;
  /* Processing variable u12 */
  if (!float_from_pyobj(&u12,u12_capi,"float_from_pyobj failed in converting 5th argument `u12' of nclip.cgulf to C float\n"))
    goto capi_fail;
  /* Processing variable x */
  if (!float_from_pyobj(&x,x_capi,"float_from_pyobj failed in converting 2nd argument `x' of nclip.cgulf to C float\n"))
    goto capi_fail;
  /* Processing variable v12 */
  if (!float_from_pyobj(&v12,v12_capi,"float_from_pyobj failed in converting 6th argument `v12' of nclip.cgulf to C float\n"))
    goto capi_fail;
  /* Processing variable v */
  if (!float_from_pyobj(&v,v_capi,"float_from_pyobj failed in converting 4th argument `v' of nclip.cgulf to C float\n"))
    goto capi_fail;
  /* Processing variable w */
  if (!float_from_pyobj(&w,w_capi,"float_from_pyobj failed in converting 8th argument `w' of nclip.cgulf to C float\n"))
    goto capi_fail;
  /* Processing variable u */
  if (!float_from_pyobj(&u,u_capi,"float_from_pyobj failed in converting 3rd argument `u' of nclip.cgulf to C float\n"))
    goto capi_fail;
  /* Processing variable gulf */
  gulf_Dims[0]=10;
  capi_gulf_tmp = arr_from_pyobj(PyArray_FLOAT,gulf_Dims,1,gulf_capi);
  if (capi_gulf_tmp == NULL) {
    PyErr_SetString(nclip_error,"failed in converting 10th argument `gulf' of nclip.cgulf to C array" );
      goto capi_fail;
  }
  gulf = (float *)(capi_gulf_tmp->data);
  /* Processing variable y */
  if (!float_from_pyobj(&y,y_capi,"float_from_pyobj failed in converting 1st argument `y' of nclip.cgulf to C float\n"))
    goto capi_fail;
  /* Processing variable dn */
  if (!float_from_pyobj(&dn,dn_capi,"float_from_pyobj failed in converting 7th argument `dn' of nclip.cgulf to C float\n"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&y,&x,&u,&v,&u12,&v12,&dn,&w,&wgulf,gulf);
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  /* TODO: Check if the following (0 && ..) produces memory leak */
  if (0 && capi_gulf_tmp != NULL) Py_XDECREF(capi_gulf_tmp->base);
  Py_XDECREF(capi_gulf_tmp);

  return capi_buildvalue;
}
/******************************** end of cgulf ********************************/

/*********************************** atshif ***********************************/
static char doc_nclip_atshif[] = "\
Function signature:\n\
  atshif(ymdh,alat,alon,alat12,alon12,vel,vel12,strmid)\n\
Required arguments:\n\
  ymdh : input int\n\
  alat : input float\n\
  alon : input float\n\
  alat12 : input float\n\
  alon12 : input float\n\
  vel : input float\n\
  vel12 : input float\n\
  strmid : input string(len=8)";
/* extern void F_FUNC(atshif,ATSHIF)(); */ /* obsolute */
static PyObject *nclip_atshif(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  int ymdh;
  PyObject *ymdh_capi = Py_None;
  float alat;
  PyObject *alat_capi = Py_None;
  float alon;
  PyObject *alon_capi = Py_None;
  float alat12;
  PyObject *alat12_capi = Py_None;
  float alon12;
  PyObject *alon12_capi = Py_None;
  float vel;
  PyObject *vel_capi = Py_None;
  float vel12;
  PyObject *vel12_capi = Py_None;
  string strmid = NULL;
  int slen(strmid);
  PyObject *strmid_capi = Py_None;
  static char *capi_kwlist[] = {"ymdh","alat","alon","alat12","alon12","vel","vel12","strmid",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO|:nclip.atshif",\
    capi_kwlist,&ymdh_capi,&alat_capi,&alon_capi,&alat12_capi,&alon12_capi,&vel_capi,&vel12_capi,&strmid_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable alon12 */
  if (!float_from_pyobj(&alon12,alon12_capi,"float_from_pyobj failed in converting 5th argument `alon12' of nclip.atshif to C float\n"))
    goto capi_fail;
  /* Processing variable ymdh */
  if (!int_from_pyobj(&ymdh,ymdh_capi,"int_from_pyobj failed in converting 1st argument `ymdh' of nclip.atshif to C int\n"))
    goto capi_fail;
  /* Processing variable alon */
  if (!float_from_pyobj(&alon,alon_capi,"float_from_pyobj failed in converting 3rd argument `alon' of nclip.atshif to C float\n"))
    goto capi_fail;
  /* Processing variable vel */
  if (!float_from_pyobj(&vel,vel_capi,"float_from_pyobj failed in converting 6th argument `vel' of nclip.atshif to C float\n"))
    goto capi_fail;
  /* Processing variable vel12 */
  if (!float_from_pyobj(&vel12,vel12_capi,"float_from_pyobj failed in converting 7th argument `vel12' of nclip.atshif to C float\n"))
    goto capi_fail;
  /* Processing variable alat12 */
  if (!float_from_pyobj(&alat12,alat12_capi,"float_from_pyobj failed in converting 4th argument `alat12' of nclip.atshif to C float\n"))
    goto capi_fail;
  /* Processing variable alat */
  if (!float_from_pyobj(&alat,alat_capi,"float_from_pyobj failed in converting 2nd argument `alat' of nclip.atshif to C float\n"))
    goto capi_fail;
  /* Processing variable strmid */
  slen(strmid) = 8;
  if (!string_from_pyobj(&strmid,&slen(strmid),"",strmid_capi,"string_from_pyobj failed in converting 8th argument `strmid' of nclip.atshif to C string"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&ymdh,&alat,&alon,&alat12,&alon12,&vel,&vel12,strmid,slen(strmid));
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  STRINGFREE(strmid);
  return capi_buildvalue;
}
/******************************* end of atshif *******************************/

/*********************************** ashif3 ***********************************/
static char doc_nclip_ashif3[] = "\
Function signature:\n\
  ashif3(p1,p2,p3,p4,p6,p7)\n\
Required arguments:\n\
  p1 : input float\n\
  p2 : input float\n\
  p3 : input float\n\
  p4 : input float\n\
  p6 : input float\n\
  p7 : input float";
/* extern void F_FUNC(ashif3,ASHIF3)(); */ /* obsolute */
static PyObject *nclip_ashif3(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  double p1;
  PyObject *p1_capi = Py_None;
  double p2;
  PyObject *p2_capi = Py_None;
  double p3;
  PyObject *p3_capi = Py_None;
  double p4;
  PyObject *p4_capi = Py_None;
  double p6;
  PyObject *p6_capi = Py_None;
  double p7;
  PyObject *p7_capi = Py_None;
  static char *capi_kwlist[] = {"p1","p2","p3","p4","p6","p7",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|:nclip.ashif3",\
    capi_kwlist,&p1_capi,&p2_capi,&p3_capi,&p4_capi,&p6_capi,&p7_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable p4 */
  if (!double_from_pyobj(&p4,p4_capi,"double_from_pyobj failed in converting 4th argument `p4' of nclip.ashif3 to C double\n"))
    goto capi_fail;
  /* Processing variable p7 */
  if (!double_from_pyobj(&p7,p7_capi,"double_from_pyobj failed in converting 6th argument `p7' of nclip.ashif3 to C double\n"))
    goto capi_fail;
  /* Processing variable p6 */
  if (!double_from_pyobj(&p6,p6_capi,"double_from_pyobj failed in converting 5th argument `p6' of nclip.ashif3 to C double\n"))
    goto capi_fail;
  /* Processing variable p1 */
  if (!double_from_pyobj(&p1,p1_capi,"double_from_pyobj failed in converting 1st argument `p1' of nclip.ashif3 to C double\n"))
    goto capi_fail;
  /* Processing variable p3 */
  if (!double_from_pyobj(&p3,p3_capi,"double_from_pyobj failed in converting 3rd argument `p3' of nclip.ashif3 to C double\n"))
    goto capi_fail;
  /* Processing variable p2 */
  if (!double_from_pyobj(&p2,p2_capi,"double_from_pyobj failed in converting 2nd argument `p2' of nclip.ashif3 to C double\n"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&p1,&p2,&p3,&p4,&p6,&p7);
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  return capi_buildvalue;
}
/******************************* end of ashif3 *******************************/

/********************************** atshif5d **********************************/
static char doc_nclip_atshif5d[] = "\
Function signature:\n\
  atshif5d(ymdh,alat,alon,alat12,alon12,vel,vel12,strmid)\n\
Required arguments:\n\
  ymdh : input int\n\
  alat : input float\n\
  alon : input float\n\
  alat12 : input float\n\
  alon12 : input float\n\
  vel : input float\n\
  vel12 : input float\n\
  strmid : input string(len=6)";
/* extern void F_FUNC(atshif5d,ATSHIF5D)(); */ /* obsolute */
static PyObject *nclip_atshif5d(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  int ymdh;
  PyObject *ymdh_capi = Py_None;
  float alat;
  PyObject *alat_capi = Py_None;
  float alon;
  PyObject *alon_capi = Py_None;
  float alat12;
  PyObject *alat12_capi = Py_None;
  float alon12;
  PyObject *alon12_capi = Py_None;
  float vel;
  PyObject *vel_capi = Py_None;
  float vel12;
  PyObject *vel12_capi = Py_None;
  string strmid = NULL;
  int slen(strmid);
  PyObject *strmid_capi = Py_None;
  static char *capi_kwlist[] = {"ymdh","alat","alon","alat12","alon12","vel","vel12","strmid",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO|:nclip.atshif5d",\
    capi_kwlist,&ymdh_capi,&alat_capi,&alon_capi,&alat12_capi,&alon12_capi,&vel_capi,&vel12_capi,&strmid_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable strmid */
  slen(strmid) = 6;
  if (!string_from_pyobj(&strmid,&slen(strmid),"",strmid_capi,"string_from_pyobj failed in converting 8th argument `strmid' of nclip.atshif5d to C string"))
    goto capi_fail;
  /* Processing variable vel */
  if (!float_from_pyobj(&vel,vel_capi,"float_from_pyobj failed in converting 6th argument `vel' of nclip.atshif5d to C float\n"))
    goto capi_fail;
  /* Processing variable vel12 */
  if (!float_from_pyobj(&vel12,vel12_capi,"float_from_pyobj failed in converting 7th argument `vel12' of nclip.atshif5d to C float\n"))
    goto capi_fail;
  /* Processing variable alat12 */
  if (!float_from_pyobj(&alat12,alat12_capi,"float_from_pyobj failed in converting 4th argument `alat12' of nclip.atshif5d to C float\n"))
    goto capi_fail;
  /* Processing variable alat */
  if (!float_from_pyobj(&alat,alat_capi,"float_from_pyobj failed in converting 2nd argument `alat' of nclip.atshif5d to C float\n"))
    goto capi_fail;
  /* Processing variable alon12 */
  if (!float_from_pyobj(&alon12,alon12_capi,"float_from_pyobj failed in converting 5th argument `alon12' of nclip.atshif5d to C float\n"))
    goto capi_fail;
  /* Processing variable ymdh */
  if (!int_from_pyobj(&ymdh,ymdh_capi,"int_from_pyobj failed in converting 1st argument `ymdh' of nclip.atshif5d to C int\n"))
    goto capi_fail;
  /* Processing variable alon */
  if (!float_from_pyobj(&alon,alon_capi,"float_from_pyobj failed in converting 3rd argument `alon' of nclip.atshif5d to C float\n"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&ymdh,&alat,&alon,&alat12,&alon12,&vel,&vel12,strmid,slen(strmid));
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  STRINGFREE(strmid);
  return capi_buildvalue;
}
/****************************** end of atshif5d ******************************/

/************************************ jday ************************************/
static char doc_nclip_jday[] = "\
Function signature:\n\
  jday(imon,iday,iyear,julday)\n\
Required arguments:\n\
  imon : input int\n\
  iday : input int\n\
  iyear : input int\n\
  julday : input int";
/* extern void F_FUNC(jday,JDAY)(); */ /* obsolute */
static PyObject *nclip_jday(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  int imon;
  PyObject *imon_capi = Py_None;
  int iday;
  PyObject *iday_capi = Py_None;
  int iyear;
  PyObject *iyear_capi = Py_None;
  int julday;
  PyObject *julday_capi = Py_None;
  static char *capi_kwlist[] = {"imon","iday","iyear","julday",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|:nclip.jday",\
    capi_kwlist,&imon_capi,&iday_capi,&iyear_capi,&julday_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable iyear */
  if (!int_from_pyobj(&iyear,iyear_capi,"int_from_pyobj failed in converting 3rd argument `iyear' of nclip.jday to C int\n"))
    goto capi_fail;
  /* Processing variable imon */
  if (!int_from_pyobj(&imon,imon_capi,"int_from_pyobj failed in converting 1st argument `imon' of nclip.jday to C int\n"))
    goto capi_fail;
  /* Processing variable iday */
  if (!int_from_pyobj(&iday,iday_capi,"int_from_pyobj failed in converting 2nd argument `iday' of nclip.jday to C int\n"))
    goto capi_fail;
  /* Processing variable julday */
  if (!int_from_pyobj(&julday,julday_capi,"int_from_pyobj failed in converting 4th argument `julday' of nclip.jday to C int\n"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&imon,&iday,&iyear,&julday);
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  return capi_buildvalue;
}
/******************************** end of jday ********************************/

/*********************************** epcl84 ***********************************/
static char doc_nclip_epcl84[] = "\
Function signature:\n\
  epcl84(ymdh,la0,lo0,lam12,lom12,lam24,lom24,dir0,spd0,wnd0,strmid)\n\
Required arguments:\n\
  ymdh : input int\n\
  la0 : input float\n\
  lo0 : input float\n\
  lam12 : input float\n\
  lom12 : input float\n\
  lam24 : input float\n\
  lom24 : input float\n\
  dir0 : input float\n\
  spd0 : input float\n\
  wnd0 : input float\n\
  strmid : input string(len=8)";
/* extern void F_FUNC(epcl84,EPCL84)(); */ /* obsolute */
static PyObject *nclip_epcl84(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  int ymdh;
  PyObject *ymdh_capi = Py_None;
  float la0;
  PyObject *la0_capi = Py_None;
  float lo0;
  PyObject *lo0_capi = Py_None;
  float lam12;
  PyObject *lam12_capi = Py_None;
  float lom12;
  PyObject *lom12_capi = Py_None;
  float lam24;
  PyObject *lam24_capi = Py_None;
  float lom24;
  PyObject *lom24_capi = Py_None;
  float dir0;
  PyObject *dir0_capi = Py_None;
  float spd0;
  PyObject *spd0_capi = Py_None;
  float wnd0;
  PyObject *wnd0_capi = Py_None;
  string strmid = NULL;
  int slen(strmid);
  PyObject *strmid_capi = Py_None;
  static char *capi_kwlist[] = {"ymdh","la0","lo0","lam12","lom12","lam24","lom24","dir0","spd0","wnd0","strmid",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOO|:nclip.epcl84",\
    capi_kwlist,&ymdh_capi,&la0_capi,&lo0_capi,&lam12_capi,&lom12_capi,&lam24_capi,&lom24_capi,&dir0_capi,&spd0_capi,&wnd0_capi,&strmid_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable strmid */
  slen(strmid) = 8;
  if (!string_from_pyobj(&strmid,&slen(strmid),"",strmid_capi,"string_from_pyobj failed in converting 11st argument `strmid' of nclip.epcl84 to C string"))
    goto capi_fail;
  /* Processing variable lam24 */
  if (!float_from_pyobj(&lam24,lam24_capi,"float_from_pyobj failed in converting 6th argument `lam24' of nclip.epcl84 to C float\n"))
    goto capi_fail;
  /* Processing variable la0 */
  if (!float_from_pyobj(&la0,la0_capi,"float_from_pyobj failed in converting 2nd argument `la0' of nclip.epcl84 to C float\n"))
    goto capi_fail;
  /* Processing variable wnd0 */
  if (!float_from_pyobj(&wnd0,wnd0_capi,"float_from_pyobj failed in converting 10th argument `wnd0' of nclip.epcl84 to C float\n"))
    goto capi_fail;
  /* Processing variable lo0 */
  if (!float_from_pyobj(&lo0,lo0_capi,"float_from_pyobj failed in converting 3rd argument `lo0' of nclip.epcl84 to C float\n"))
    goto capi_fail;
  /* Processing variable lom24 */
  if (!float_from_pyobj(&lom24,lom24_capi,"float_from_pyobj failed in converting 7th argument `lom24' of nclip.epcl84 to C float\n"))
    goto capi_fail;
  /* Processing variable lam12 */
  if (!float_from_pyobj(&lam12,lam12_capi,"float_from_pyobj failed in converting 4th argument `lam12' of nclip.epcl84 to C float\n"))
    goto capi_fail;
  /* Processing variable ymdh */
  if (!int_from_pyobj(&ymdh,ymdh_capi,"int_from_pyobj failed in converting 1st argument `ymdh' of nclip.epcl84 to C int\n"))
    goto capi_fail;
  /* Processing variable spd0 */
  if (!float_from_pyobj(&spd0,spd0_capi,"float_from_pyobj failed in converting 9th argument `spd0' of nclip.epcl84 to C float\n"))
    goto capi_fail;
  /* Processing variable lom12 */
  if (!float_from_pyobj(&lom12,lom12_capi,"float_from_pyobj failed in converting 5th argument `lom12' of nclip.epcl84 to C float\n"))
    goto capi_fail;
  /* Processing variable dir0 */
  if (!float_from_pyobj(&dir0,dir0_capi,"float_from_pyobj failed in converting 8th argument `dir0' of nclip.epcl84 to C float\n"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&ymdh,&la0,&lo0,&lam12,&lom12,&lam24,&lom24,&dir0,&spd0,&wnd0,strmid,slen(strmid));
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  STRINGFREE(strmid);
  return capi_buildvalue;
}
/******************************* end of epcl84 *******************************/

/*********************************** mult1 ***********************************/
static char doc_nclip_mult1[] = "\
Function signature:\n\
  mult1()\n\
";
/* extern void F_FUNC(mult1,MULT1)(); */ /* obsolute */
static PyObject *nclip_mult1(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  static char *capi_kwlist[] = {NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "|:nclip.mult1",\
    capi_kwlist))
    goto capi_fail;
/*frompyobj*/
/*callfortranroutine*/
  (*f2py_func)();
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  return capi_buildvalue;
}
/******************************** end of mult1 ********************************/

/*********************************** mult2 ***********************************/
static char doc_nclip_mult2[] = "\
Function signature:\n\
  mult2()\n\
";
/* extern void F_FUNC(mult2,MULT2)(); */ /* obsolute */
static PyObject *nclip_mult2(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  static char *capi_kwlist[] = {NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "|:nclip.mult2",\
    capi_kwlist))
    goto capi_fail;
/*frompyobj*/
/*callfortranroutine*/
  (*f2py_func)();
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  return capi_buildvalue;
}
/******************************** end of mult2 ********************************/

/*********************************** mult3 ***********************************/
static char doc_nclip_mult3[] = "\
Function signature:\n\
  mult3()\n\
";
/* extern void F_FUNC(mult3,MULT3)(); */ /* obsolute */
static PyObject *nclip_mult3(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  static char *capi_kwlist[] = {NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "|:nclip.mult3",\
    capi_kwlist))
    goto capi_fail;
/*frompyobj*/
/*callfortranroutine*/
  (*f2py_func)();
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  return capi_buildvalue;
}
/******************************** end of mult3 ********************************/

/*********************************** mult4 ***********************************/
static char doc_nclip_mult4[] = "\
Function signature:\n\
  mult4()\n\
";
/* extern void F_FUNC(mult4,MULT4)(); */ /* obsolute */
static PyObject *nclip_mult4(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  static char *capi_kwlist[] = {NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "|:nclip.mult4",\
    capi_kwlist))
    goto capi_fail;
/*frompyobj*/
/*callfortranroutine*/
  (*f2py_func)();
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  return capi_buildvalue;
}
/******************************** end of mult4 ********************************/

/*********************************** sthgpr ***********************************/
static char doc_nclip_sthgpr[] = "\
Function signature:\n\
  sthgpr(xlath,xlonh,bear,gridsz,xi0,yj0)\n\
Required arguments:\n\
  xlath : input float\n\
  xlonh : input float\n\
  bear : input float\n\
  gridsz : input float\n\
  xi0 : input float\n\
  yj0 : input float";
/* extern void F_FUNC(sthgpr,STHGPR)(); */ /* obsolute */
static PyObject *nclip_sthgpr(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  float xlath;
  PyObject *xlath_capi = Py_None;
  float xlonh;
  PyObject *xlonh_capi = Py_None;
  float bear;
  PyObject *bear_capi = Py_None;
  float gridsz;
  PyObject *gridsz_capi = Py_None;
  float xi0;
  PyObject *xi0_capi = Py_None;
  float yj0;
  PyObject *yj0_capi = Py_None;
  static char *capi_kwlist[] = {"xlath","xlonh","bear","gridsz","xi0","yj0",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|:nclip.sthgpr",\
    capi_kwlist,&xlath_capi,&xlonh_capi,&bear_capi,&gridsz_capi,&xi0_capi,&yj0_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable yj0 */
  if (!float_from_pyobj(&yj0,yj0_capi,"float_from_pyobj failed in converting 6th argument `yj0' of nclip.sthgpr to C float\n"))
    goto capi_fail;
  /* Processing variable xlonh */
  if (!float_from_pyobj(&xlonh,xlonh_capi,"float_from_pyobj failed in converting 2nd argument `xlonh' of nclip.sthgpr to C float\n"))
    goto capi_fail;
  /* Processing variable gridsz */
  if (!float_from_pyobj(&gridsz,gridsz_capi,"float_from_pyobj failed in converting 4th argument `gridsz' of nclip.sthgpr to C float\n"))
    goto capi_fail;
  /* Processing variable xlath */
  if (!float_from_pyobj(&xlath,xlath_capi,"float_from_pyobj failed in converting 1st argument `xlath' of nclip.sthgpr to C float\n"))
    goto capi_fail;
  /* Processing variable xi0 */
  if (!float_from_pyobj(&xi0,xi0_capi,"float_from_pyobj failed in converting 5th argument `xi0' of nclip.sthgpr to C float\n"))
    goto capi_fail;
  /* Processing variable bear */
  if (!float_from_pyobj(&bear,bear_capi,"float_from_pyobj failed in converting 3rd argument `bear' of nclip.sthgpr to C float\n"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&xlath,&xlonh,&bear,&gridsz,&xi0,&yj0);
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  return capi_buildvalue;
}
/******************************* end of sthgpr *******************************/

/*********************************** ll2xyh ***********************************/
static char doc_nclip_ll2xyh[] = "\
Function signature:\n\
  ll2xyh(xlat,xlong,xi,yj)\n\
Required arguments:\n\
  xlat : input float\n\
  xlong : input float\n\
  xi : input float\n\
  yj : input float";
/* extern void F_FUNC(ll2xyh,LL2XYH)(); */ /* obsolute */
static PyObject *nclip_ll2xyh(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  float xlat;
  PyObject *xlat_capi = Py_None;
  float xlong;
  PyObject *xlong_capi = Py_None;
  float xi;
  PyObject *xi_capi = Py_None;
  float yj;
  PyObject *yj_capi = Py_None;
  static char *capi_kwlist[] = {"xlat","xlong","xi","yj",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|:nclip.ll2xyh",\
    capi_kwlist,&xlat_capi,&xlong_capi,&xi_capi,&yj_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable xlat */
  if (!float_from_pyobj(&xlat,xlat_capi,"float_from_pyobj failed in converting 1st argument `xlat' of nclip.ll2xyh to C float\n"))
    goto capi_fail;
  /* Processing variable xlong */
  if (!float_from_pyobj(&xlong,xlong_capi,"float_from_pyobj failed in converting 2nd argument `xlong' of nclip.ll2xyh to C float\n"))
    goto capi_fail;
  /* Processing variable yj */
  if (!float_from_pyobj(&yj,yj_capi,"float_from_pyobj failed in converting 4th argument `yj' of nclip.ll2xyh to C float\n"))
    goto capi_fail;
  /* Processing variable xi */
  if (!float_from_pyobj(&xi,xi_capi,"float_from_pyobj failed in converting 3rd argument `xi' of nclip.ll2xyh to C float\n"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&xlat,&xlong,&xi,&yj);
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  return capi_buildvalue;
}
/******************************* end of ll2xyh *******************************/

/*********************************** xy2llh ***********************************/
static char doc_nclip_xy2llh[] = "\
Function signature:\n\
  xy2llh(xi,yj,xlat,xlong)\n\
Required arguments:\n\
  xi : input float\n\
  yj : input float\n\
  xlat : input float\n\
  xlong : input float";
/* extern void F_FUNC(xy2llh,XY2LLH)(); */ /* obsolute */
static PyObject *nclip_xy2llh(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  float xi;
  PyObject *xi_capi = Py_None;
  float yj;
  PyObject *yj_capi = Py_None;
  float xlat;
  PyObject *xlat_capi = Py_None;
  float xlong;
  PyObject *xlong_capi = Py_None;
  static char *capi_kwlist[] = {"xi","yj","xlat","xlong",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|:nclip.xy2llh",\
    capi_kwlist,&xi_capi,&yj_capi,&xlat_capi,&xlong_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable xlat */
  if (!float_from_pyobj(&xlat,xlat_capi,"float_from_pyobj failed in converting 3rd argument `xlat' of nclip.xy2llh to C float\n"))
    goto capi_fail;
  /* Processing variable xlong */
  if (!float_from_pyobj(&xlong,xlong_capi,"float_from_pyobj failed in converting 4th argument `xlong' of nclip.xy2llh to C float\n"))
    goto capi_fail;
  /* Processing variable yj */
  if (!float_from_pyobj(&yj,yj_capi,"float_from_pyobj failed in converting 2nd argument `yj' of nclip.xy2llh to C float\n"))
    goto capi_fail;
  /* Processing variable xi */
  if (!float_from_pyobj(&xi,xi_capi,"float_from_pyobj failed in converting 1st argument `xi' of nclip.xy2llh to C float\n"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&xi,&yj,&xlat,&xlong);
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  return capi_buildvalue;
}
/******************************* end of xy2llh *******************************/

/*********************************** epshif ***********************************/
static char doc_nclip_epshif[] = "\
Function signature:\n\
  epshif(idtg,alat,alon,alat12,alon12,vel,vel12,strmid)\n\
Required arguments:\n\
  idtg : input int\n\
  alat : input float\n\
  alon : input float\n\
  alat12 : input float\n\
  alon12 : input float\n\
  vel : input float\n\
  vel12 : input float\n\
  strmid : input string(len=8)";
/* extern void F_FUNC(epshif,EPSHIF)(); */ /* obsolute */
static PyObject *nclip_epshif(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  int idtg;
  PyObject *idtg_capi = Py_None;
  float alat;
  PyObject *alat_capi = Py_None;
  float alon;
  PyObject *alon_capi = Py_None;
  float alat12;
  PyObject *alat12_capi = Py_None;
  float alon12;
  PyObject *alon12_capi = Py_None;
  float vel;
  PyObject *vel_capi = Py_None;
  float vel12;
  PyObject *vel12_capi = Py_None;
  string strmid = NULL;
  int slen(strmid);
  PyObject *strmid_capi = Py_None;
  static char *capi_kwlist[] = {"idtg","alat","alon","alat12","alon12","vel","vel12","strmid",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO|:nclip.epshif",\
    capi_kwlist,&idtg_capi,&alat_capi,&alon_capi,&alat12_capi,&alon12_capi,&vel_capi,&vel12_capi,&strmid_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable alon12 */
  if (!float_from_pyobj(&alon12,alon12_capi,"float_from_pyobj failed in converting 5th argument `alon12' of nclip.epshif to C float\n"))
    goto capi_fail;
  /* Processing variable alon */
  if (!float_from_pyobj(&alon,alon_capi,"float_from_pyobj failed in converting 3rd argument `alon' of nclip.epshif to C float\n"))
    goto capi_fail;
  /* Processing variable vel */
  if (!float_from_pyobj(&vel,vel_capi,"float_from_pyobj failed in converting 6th argument `vel' of nclip.epshif to C float\n"))
    goto capi_fail;
  /* Processing variable vel12 */
  if (!float_from_pyobj(&vel12,vel12_capi,"float_from_pyobj failed in converting 7th argument `vel12' of nclip.epshif to C float\n"))
    goto capi_fail;
  /* Processing variable idtg */
  if (!int_from_pyobj(&idtg,idtg_capi,"int_from_pyobj failed in converting 1st argument `idtg' of nclip.epshif to C int\n"))
    goto capi_fail;
  /* Processing variable alat12 */
  if (!float_from_pyobj(&alat12,alat12_capi,"float_from_pyobj failed in converting 4th argument `alat12' of nclip.epshif to C float\n"))
    goto capi_fail;
  /* Processing variable alat */
  if (!float_from_pyobj(&alat,alat_capi,"float_from_pyobj failed in converting 2nd argument `alat' of nclip.epshif to C float\n"))
    goto capi_fail;
  /* Processing variable strmid */
  slen(strmid) = 8;
  if (!string_from_pyobj(&strmid,&slen(strmid),"",strmid_capi,"string_from_pyobj failed in converting 8th argument `strmid' of nclip.epshif to C string"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&idtg,&alat,&alon,&alat12,&alon12,&vel,&vel12,strmid,slen(strmid));
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  STRINGFREE(strmid);
  return capi_buildvalue;
}
/******************************* end of epshif *******************************/

/********************************** epshif5d **********************************/
static char doc_nclip_epshif5d[] = "\
Function signature:\n\
  epshif5d(ymdh,elat,elon,elat12,elon12,vel,vel12,strmid)\n\
Required arguments:\n\
  ymdh : input int\n\
  elat : input float\n\
  elon : input float\n\
  elat12 : input float\n\
  elon12 : input float\n\
  vel : input float\n\
  vel12 : input float\n\
  strmid : input string(len=6)";
/* extern void F_FUNC(epshif5d,EPSHIF5D)(); */ /* obsolute */
static PyObject *nclip_epshif5d(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  int ymdh;
  PyObject *ymdh_capi = Py_None;
  float elat;
  PyObject *elat_capi = Py_None;
  float elon;
  PyObject *elon_capi = Py_None;
  float elat12;
  PyObject *elat12_capi = Py_None;
  float elon12;
  PyObject *elon12_capi = Py_None;
  float vel;
  PyObject *vel_capi = Py_None;
  float vel12;
  PyObject *vel12_capi = Py_None;
  string strmid = NULL;
  int slen(strmid);
  PyObject *strmid_capi = Py_None;
  static char *capi_kwlist[] = {"ymdh","elat","elon","elat12","elon12","vel","vel12","strmid",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO|:nclip.epshif5d",\
    capi_kwlist,&ymdh_capi,&elat_capi,&elon_capi,&elat12_capi,&elon12_capi,&vel_capi,&vel12_capi,&strmid_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable strmid */
  slen(strmid) = 6;
  if (!string_from_pyobj(&strmid,&slen(strmid),"",strmid_capi,"string_from_pyobj failed in converting 8th argument `strmid' of nclip.epshif5d to C string"))
    goto capi_fail;
  /* Processing variable elon12 */
  if (!float_from_pyobj(&elon12,elon12_capi,"float_from_pyobj failed in converting 5th argument `elon12' of nclip.epshif5d to C float\n"))
    goto capi_fail;
  /* Processing variable vel */
  if (!float_from_pyobj(&vel,vel_capi,"float_from_pyobj failed in converting 6th argument `vel' of nclip.epshif5d to C float\n"))
    goto capi_fail;
  /* Processing variable vel12 */
  if (!float_from_pyobj(&vel12,vel12_capi,"float_from_pyobj failed in converting 7th argument `vel12' of nclip.epshif5d to C float\n"))
    goto capi_fail;
  /* Processing variable elon */
  if (!float_from_pyobj(&elon,elon_capi,"float_from_pyobj failed in converting 3rd argument `elon' of nclip.epshif5d to C float\n"))
    goto capi_fail;
  /* Processing variable ymdh */
  if (!int_from_pyobj(&ymdh,ymdh_capi,"int_from_pyobj failed in converting 1st argument `ymdh' of nclip.epshif5d to C int\n"))
    goto capi_fail;
  /* Processing variable elat12 */
  if (!float_from_pyobj(&elat12,elat12_capi,"float_from_pyobj failed in converting 4th argument `elat12' of nclip.epshif5d to C float\n"))
    goto capi_fail;
  /* Processing variable elat */
  if (!float_from_pyobj(&elat,elat_capi,"float_from_pyobj failed in converting 2nd argument `elat' of nclip.epshif5d to C float\n"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&ymdh,&elat,&elon,&elat12,&elon12,&vel,&vel12,strmid,slen(strmid));
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  STRINGFREE(strmid);
  return capi_buildvalue;
}
/****************************** end of epshif5d ******************************/

/*********************************** readbt ***********************************/
static char doc_nclip_readbt[] = "\
Function signature:\n\
  readbt(datfile,cent,dtg,flat,ns,flon,ew,iwind,ios)\n\
Required arguments:\n\
  datfile : input int\n\
  cent : input string(len=2)\n\
  dtg : input string(len=8)\n\
  flat : input float\n\
  ns : input string(len=1)\n\
  flon : input float\n\
  ew : input string(len=1)\n\
  iwind : input int\n\
  ios : input int";
/* extern void F_FUNC(readbt,READBT)(); */ /* obsolute */
static PyObject *nclip_readbt(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  int datfile;
  PyObject *datfile_capi = Py_None;
  string cent = NULL;
  int slen(cent);
  PyObject *cent_capi = Py_None;
  string dtg = NULL;
  int slen(dtg);
  PyObject *dtg_capi = Py_None;
  float flat;
  PyObject *flat_capi = Py_None;
  string ns = NULL;
  int slen(ns);
  PyObject *ns_capi = Py_None;
  float flon;
  PyObject *flon_capi = Py_None;
  string ew = NULL;
  int slen(ew);
  PyObject *ew_capi = Py_None;
  int iwind;
  PyObject *iwind_capi = Py_None;
  int ios;
  PyObject *ios_capi = Py_None;
  static char *capi_kwlist[] = {"datfile","cent","dtg","flat","ns","flon","ew","iwind","ios",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO|:nclip.readbt",\
    capi_kwlist,&datfile_capi,&cent_capi,&dtg_capi,&flat_capi,&ns_capi,&flon_capi,&ew_capi,&iwind_capi,&ios_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable cent */
  slen(cent) = 2;
  if (!string_from_pyobj(&cent,&slen(cent),"",cent_capi,"string_from_pyobj failed in converting 2nd argument `cent' of nclip.readbt to C string"))
    goto capi_fail;
  /* Processing variable dtg */
  slen(dtg) = 8;
  if (!string_from_pyobj(&dtg,&slen(dtg),"",dtg_capi,"string_from_pyobj failed in converting 3rd argument `dtg' of nclip.readbt to C string"))
    goto capi_fail;
  /* Processing variable ns */
  slen(ns) = 1;
  if (!string_from_pyobj(&ns,&slen(ns),"",ns_capi,"string_from_pyobj failed in converting 5th argument `ns' of nclip.readbt to C string"))
    goto capi_fail;
  /* Processing variable ew */
  slen(ew) = 1;
  if (!string_from_pyobj(&ew,&slen(ew),"",ew_capi,"string_from_pyobj failed in converting 7th argument `ew' of nclip.readbt to C string"))
    goto capi_fail;
  /* Processing variable ios */
  if (!int_from_pyobj(&ios,ios_capi,"int_from_pyobj failed in converting 9th argument `ios' of nclip.readbt to C int\n"))
    goto capi_fail;
  /* Processing variable flon */
  if (!float_from_pyobj(&flon,flon_capi,"float_from_pyobj failed in converting 6th argument `flon' of nclip.readbt to C float\n"))
    goto capi_fail;
  /* Processing variable datfile */
  if (!int_from_pyobj(&datfile,datfile_capi,"int_from_pyobj failed in converting 1st argument `datfile' of nclip.readbt to C int\n"))
    goto capi_fail;
  /* Processing variable flat */
  if (!float_from_pyobj(&flat,flat_capi,"float_from_pyobj failed in converting 4th argument `flat' of nclip.readbt to C float\n"))
    goto capi_fail;
  /* Processing variable iwind */
  if (!int_from_pyobj(&iwind,iwind_capi,"int_from_pyobj failed in converting 8th argument `iwind' of nclip.readbt to C int\n"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&datfile,cent,dtg,&flat,ns,&flon,ew,&iwind,&ios,slen(cent),slen(dtg),slen(ns),slen(ew));
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  STRINGFREE(cent);
  STRINGFREE(dtg);
  STRINGFREE(ns);
  STRINGFREE(ew);
  return capi_buildvalue;
}
/******************************* end of readbt *******************************/

/********************************** readbest **********************************/
static char doc_nclip_readbest[] = "\
Function signature:\n\
  readbest(datfile,basin,cycnum,cent,dtg,flat,ns,flon,ew,iwind,ios)\n\
Required arguments:\n\
  datfile : input int\n\
  basin : input string(len=2)\n\
  cycnum : input string(len=2)\n\
  cent : input string(len=2)\n\
  dtg : input string(len=8)\n\
  flat : input float\n\
  ns : input string(len=1)\n\
  flon : input float\n\
  ew : input string(len=1)\n\
  iwind : input int\n\
  ios : input int";
/* extern void F_FUNC(readbest,READBEST)(); */ /* obsolute */
static PyObject *nclip_readbest(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  int datfile;
  PyObject *datfile_capi = Py_None;
  string basin = NULL;
  int slen(basin);
  PyObject *basin_capi = Py_None;
  string cycnum = NULL;
  int slen(cycnum);
  PyObject *cycnum_capi = Py_None;
  string cent = NULL;
  int slen(cent);
  PyObject *cent_capi = Py_None;
  string dtg = NULL;
  int slen(dtg);
  PyObject *dtg_capi = Py_None;
  float flat;
  PyObject *flat_capi = Py_None;
  string ns = NULL;
  int slen(ns);
  PyObject *ns_capi = Py_None;
  float flon;
  PyObject *flon_capi = Py_None;
  string ew = NULL;
  int slen(ew);
  PyObject *ew_capi = Py_None;
  int iwind;
  PyObject *iwind_capi = Py_None;
  int ios;
  PyObject *ios_capi = Py_None;
  static char *capi_kwlist[] = {"datfile","basin","cycnum","cent","dtg","flat","ns","flon","ew","iwind","ios",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOO|:nclip.readbest",\
    capi_kwlist,&datfile_capi,&basin_capi,&cycnum_capi,&cent_capi,&dtg_capi,&flat_capi,&ns_capi,&flon_capi,&ew_capi,&iwind_capi,&ios_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable ns */
  slen(ns) = 1;
  if (!string_from_pyobj(&ns,&slen(ns),"",ns_capi,"string_from_pyobj failed in converting 7th argument `ns' of nclip.readbest to C string"))
    goto capi_fail;
  /* Processing variable basin */
  slen(basin) = 2;
  if (!string_from_pyobj(&basin,&slen(basin),"",basin_capi,"string_from_pyobj failed in converting 2nd argument `basin' of nclip.readbest to C string"))
    goto capi_fail;
  /* Processing variable cycnum */
  slen(cycnum) = 2;
  if (!string_from_pyobj(&cycnum,&slen(cycnum),"",cycnum_capi,"string_from_pyobj failed in converting 3rd argument `cycnum' of nclip.readbest to C string"))
    goto capi_fail;
  /* Processing variable flon */
  if (!float_from_pyobj(&flon,flon_capi,"float_from_pyobj failed in converting 8th argument `flon' of nclip.readbest to C float\n"))
    goto capi_fail;
  /* Processing variable datfile */
  if (!int_from_pyobj(&datfile,datfile_capi,"int_from_pyobj failed in converting 1st argument `datfile' of nclip.readbest to C int\n"))
    goto capi_fail;
  /* Processing variable ew */
  slen(ew) = 1;
  if (!string_from_pyobj(&ew,&slen(ew),"",ew_capi,"string_from_pyobj failed in converting 9th argument `ew' of nclip.readbest to C string"))
    goto capi_fail;
  /* Processing variable iwind */
  if (!int_from_pyobj(&iwind,iwind_capi,"int_from_pyobj failed in converting 10th argument `iwind' of nclip.readbest to C int\n"))
    goto capi_fail;
  /* Processing variable cent */
  slen(cent) = 2;
  if (!string_from_pyobj(&cent,&slen(cent),"",cent_capi,"string_from_pyobj failed in converting 4th argument `cent' of nclip.readbest to C string"))
    goto capi_fail;
  /* Processing variable ios */
  if (!int_from_pyobj(&ios,ios_capi,"int_from_pyobj failed in converting 11st argument `ios' of nclip.readbest to C int\n"))
    goto capi_fail;
  /* Processing variable dtg */
  slen(dtg) = 8;
  if (!string_from_pyobj(&dtg,&slen(dtg),"",dtg_capi,"string_from_pyobj failed in converting 5th argument `dtg' of nclip.readbest to C string"))
    goto capi_fail;
  /* Processing variable flat */
  if (!float_from_pyobj(&flat,flat_capi,"float_from_pyobj failed in converting 6th argument `flat' of nclip.readbest to C float\n"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&datfile,basin,cycnum,cent,dtg,&flat,ns,&flon,ew,&iwind,&ios,slen(basin),slen(cycnum),slen(cent),slen(dtg),slen(ns),slen(ew));
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  STRINGFREE(basin);
  STRINGFREE(cycnum);
  STRINGFREE(cent);
  STRINGFREE(dtg);
  STRINGFREE(ns);
  STRINGFREE(ew);
  return capi_buildvalue;
}
/****************************** end of readbest ******************************/

/******************************* dowriteaidrcd *******************************/
static char doc_nclip_dowriteaidrcd[] = "\
Function signature:\n\
  dowriteaidrcd(datfile,stormid,cdtg,techname,itau,llwnd)\n\
Required arguments:\n\
  datfile : input int\n\
  stormid : input string(len=8)\n\
  cdtg : input string(len=10)\n\
  techname : input string(len=4)\n\
  itau : input int\n\
  llwnd : input rank-1 array('i') with bounds (3)";
/* extern void F_FUNC(dowriteaidrcd,DOWRITEAIDRCD)(); */ /* obsolute */
static PyObject *nclip_dowriteaidrcd(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  int datfile;
  PyObject *datfile_capi = Py_None;
  string stormid = NULL;
  int slen(stormid);
  PyObject *stormid_capi = Py_None;
  string cdtg = NULL;
  int slen(cdtg);
  PyObject *cdtg_capi = Py_None;
  string techname = NULL;
  int slen(techname);
  PyObject *techname_capi = Py_None;
  int itau;
  PyObject *itau_capi = Py_None;
  int *llwnd = NULL;
  int llwnd_Dims[1] = {-1};
  PyArrayObject *capi_llwnd_tmp = NULL;
  PyObject *llwnd_capi = Py_None;
  static char *capi_kwlist[] = {"datfile","stormid","cdtg","techname","itau","llwnd",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|:nclip.dowriteaidrcd",\
    capi_kwlist,&datfile_capi,&stormid_capi,&cdtg_capi,&techname_capi,&itau_capi,&llwnd_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable cdtg */
  slen(cdtg) = 10;
  if (!string_from_pyobj(&cdtg,&slen(cdtg),"",cdtg_capi,"string_from_pyobj failed in converting 3rd argument `cdtg' of nclip.dowriteaidrcd to C string"))
    goto capi_fail;
  /* Processing variable techname */
  slen(techname) = 4;
  if (!string_from_pyobj(&techname,&slen(techname),"",techname_capi,"string_from_pyobj failed in converting 4th argument `techname' of nclip.dowriteaidrcd to C string"))
    goto capi_fail;
  /* Processing variable llwnd */
  llwnd_Dims[0]=3;
  capi_llwnd_tmp = arr_from_pyobj(PyArray_INT,llwnd_Dims,1,llwnd_capi);
  if (capi_llwnd_tmp == NULL) {
    PyErr_SetString(nclip_error,"failed in converting 6th argument `llwnd' of nclip.dowriteaidrcd to C array" );
      goto capi_fail;
  }
  llwnd = (int *)(capi_llwnd_tmp->data);
  /* Processing variable itau */
  if (!int_from_pyobj(&itau,itau_capi,"int_from_pyobj failed in converting 5th argument `itau' of nclip.dowriteaidrcd to C int\n"))
    goto capi_fail;
  /* Processing variable stormid */
  slen(stormid) = 8;
  if (!string_from_pyobj(&stormid,&slen(stormid),"",stormid_capi,"string_from_pyobj failed in converting 2nd argument `stormid' of nclip.dowriteaidrcd to C string"))
    goto capi_fail;
  /* Processing variable datfile */
  if (!int_from_pyobj(&datfile,datfile_capi,"int_from_pyobj failed in converting 1st argument `datfile' of nclip.dowriteaidrcd to C int\n"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&datfile,stormid,cdtg,techname,&itau,llwnd,slen(stormid),slen(cdtg),slen(techname));
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  STRINGFREE(stormid);
  STRINGFREE(cdtg);
  STRINGFREE(techname);
  /* TODO: Check if the following (0 && ..) produces memory leak */
  if (0 && capi_llwnd_tmp != NULL) Py_XDECREF(capi_llwnd_tmp->base);
  Py_XDECREF(capi_llwnd_tmp);

  return capi_buildvalue;
}
/**************************** end of dowriteaidrcd ****************************/

/******************************** writeaidrcd ********************************/
static char doc_nclip_writeaidrcd[] = "\
Function signature:\n\
  writeaidrcd(datfile,stormid,cdtg,techname,ltlnwnd)\n\
Required arguments:\n\
  datfile : input int\n\
  stormid : input string(len=8)\n\
  cdtg : input string(len=10)\n\
  techname : input string(len=4)\n\
  ltlnwnd : input rank-2 array('i') with bounds (3,10)";
/* extern void F_FUNC(writeaidrcd,WRITEAIDRCD)(); */ /* obsolute */
static PyObject *nclip_writeaidrcd(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  int datfile;
  PyObject *datfile_capi = Py_None;
  string stormid = NULL;
  int slen(stormid);
  PyObject *stormid_capi = Py_None;
  string cdtg = NULL;
  int slen(cdtg);
  PyObject *cdtg_capi = Py_None;
  string techname = NULL;
  int slen(techname);
  PyObject *techname_capi = Py_None;
  int *ltlnwnd = NULL;
  int ltlnwnd_Dims[2] = {-1, -1};
  PyArrayObject *capi_ltlnwnd_tmp = NULL;
  PyObject *ltlnwnd_capi = Py_None;
  static char *capi_kwlist[] = {"datfile","stormid","cdtg","techname","ltlnwnd",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|:nclip.writeaidrcd",\
    capi_kwlist,&datfile_capi,&stormid_capi,&cdtg_capi,&techname_capi,&ltlnwnd_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable ltlnwnd */
  ltlnwnd_Dims[0]=3,ltlnwnd_Dims[1]=10;
  capi_ltlnwnd_tmp = arr_from_pyobj(PyArray_INT,ltlnwnd_Dims,2,ltlnwnd_capi);
  if (capi_ltlnwnd_tmp == NULL) {
    PyErr_SetString(nclip_error,"failed in converting 5th argument `ltlnwnd' of nclip.writeaidrcd to C array" );
      goto capi_fail;
  }
  ltlnwnd = (int *)(capi_ltlnwnd_tmp->data);
  /* Processing variable stormid */
  slen(stormid) = 8;
  if (!string_from_pyobj(&stormid,&slen(stormid),"",stormid_capi,"string_from_pyobj failed in converting 2nd argument `stormid' of nclip.writeaidrcd to C string"))
    goto capi_fail;
  /* Processing variable datfile */
  if (!int_from_pyobj(&datfile,datfile_capi,"int_from_pyobj failed in converting 1st argument `datfile' of nclip.writeaidrcd to C int\n"))
    goto capi_fail;
  /* Processing variable techname */
  slen(techname) = 4;
  if (!string_from_pyobj(&techname,&slen(techname),"",techname_capi,"string_from_pyobj failed in converting 4th argument `techname' of nclip.writeaidrcd to C string"))
    goto capi_fail;
  /* Processing variable cdtg */
  slen(cdtg) = 10;
  if (!string_from_pyobj(&cdtg,&slen(cdtg),"",cdtg_capi,"string_from_pyobj failed in converting 3rd argument `cdtg' of nclip.writeaidrcd to C string"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&datfile,stormid,cdtg,techname,ltlnwnd,slen(stormid),slen(cdtg),slen(techname));
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  STRINGFREE(stormid);
  STRINGFREE(cdtg);
  STRINGFREE(techname);
  /* TODO: Check if the following (0 && ..) produces memory leak */
  if (0 && capi_ltlnwnd_tmp != NULL) Py_XDECREF(capi_ltlnwnd_tmp->base);
  Py_XDECREF(capi_ltlnwnd_tmp);

  return capi_buildvalue;
}
/***************************** end of writeaidrcd *****************************/

/******************************* newwriteaidrcd *******************************/
static char doc_nclip_newwriteaidrcd[] = "\
Function signature:\n\
  newwriteaidrcd(datfile,stormid,cdtg,techname,ltlnwnd)\n\
Required arguments:\n\
  datfile : input int\n\
  stormid : input string(len=8)\n\
  cdtg : input string(len=10)\n\
  techname : input string(len=4)\n\
  ltlnwnd : input rank-2 array('i') with bounds (3,11)";
/* extern void F_FUNC(newwriteaidrcd,NEWWRITEAIDRCD)(); */ /* obsolute */
static PyObject *nclip_newwriteaidrcd(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  int datfile;
  PyObject *datfile_capi = Py_None;
  string stormid = NULL;
  int slen(stormid);
  PyObject *stormid_capi = Py_None;
  string cdtg = NULL;
  int slen(cdtg);
  PyObject *cdtg_capi = Py_None;
  string techname = NULL;
  int slen(techname);
  PyObject *techname_capi = Py_None;
  int *ltlnwnd = NULL;
  int ltlnwnd_Dims[2] = {-1, -1};
  PyArrayObject *capi_ltlnwnd_tmp = NULL;
  PyObject *ltlnwnd_capi = Py_None;
  static char *capi_kwlist[] = {"datfile","stormid","cdtg","techname","ltlnwnd",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|:nclip.newwriteaidrcd",\
    capi_kwlist,&datfile_capi,&stormid_capi,&cdtg_capi,&techname_capi,&ltlnwnd_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable ltlnwnd */
  ltlnwnd_Dims[0]=3,ltlnwnd_Dims[1]=11;
  capi_ltlnwnd_tmp = arr_from_pyobj(PyArray_INT,ltlnwnd_Dims,2,ltlnwnd_capi);
  if (capi_ltlnwnd_tmp == NULL) {
    PyErr_SetString(nclip_error,"failed in converting 5th argument `ltlnwnd' of nclip.newwriteaidrcd to C array" );
      goto capi_fail;
  }
  ltlnwnd = (int *)(capi_ltlnwnd_tmp->data);
  /* Processing variable stormid */
  slen(stormid) = 8;
  if (!string_from_pyobj(&stormid,&slen(stormid),"",stormid_capi,"string_from_pyobj failed in converting 2nd argument `stormid' of nclip.newwriteaidrcd to C string"))
    goto capi_fail;
  /* Processing variable datfile */
  if (!int_from_pyobj(&datfile,datfile_capi,"int_from_pyobj failed in converting 1st argument `datfile' of nclip.newwriteaidrcd to C int\n"))
    goto capi_fail;
  /* Processing variable techname */
  slen(techname) = 4;
  if (!string_from_pyobj(&techname,&slen(techname),"",techname_capi,"string_from_pyobj failed in converting 4th argument `techname' of nclip.newwriteaidrcd to C string"))
    goto capi_fail;
  /* Processing variable cdtg */
  slen(cdtg) = 10;
  if (!string_from_pyobj(&cdtg,&slen(cdtg),"",cdtg_capi,"string_from_pyobj failed in converting 3rd argument `cdtg' of nclip.newwriteaidrcd to C string"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&datfile,stormid,cdtg,techname,ltlnwnd,slen(stormid),slen(cdtg),slen(techname));
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  STRINGFREE(stormid);
  STRINGFREE(cdtg);
  STRINGFREE(techname);
  /* TODO: Check if the following (0 && ..) produces memory leak */
  if (0 && capi_ltlnwnd_tmp != NULL) Py_XDECREF(capi_ltlnwnd_tmp->base);
  Py_XDECREF(capi_ltlnwnd_tmp);

  return capi_buildvalue;
}
/*************************** end of newwriteaidrcd ***************************/

/********************************** writeaid **********************************/
static char doc_nclip_writeaid[] = "\
Function signature:\n\
  writeaid(datfile,stormid,century,cdtg,techname,ltlnwnd)\n\
Required arguments:\n\
  datfile : input int\n\
  stormid : input string(len=6)\n\
  century : input string(len=2)\n\
  cdtg : input string(len=8)\n\
  techname : input string(len=4)\n\
  ltlnwnd : input rank-2 array('i') with bounds (3,10)";
/* extern void F_FUNC(writeaid,WRITEAID)(); */ /* obsolute */
static PyObject *nclip_writeaid(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  int datfile;
  PyObject *datfile_capi = Py_None;
  string stormid = NULL;
  int slen(stormid);
  PyObject *stormid_capi = Py_None;
  string century = NULL;
  int slen(century);
  PyObject *century_capi = Py_None;
  string cdtg = NULL;
  int slen(cdtg);
  PyObject *cdtg_capi = Py_None;
  string techname = NULL;
  int slen(techname);
  PyObject *techname_capi = Py_None;
  int *ltlnwnd = NULL;
  int ltlnwnd_Dims[2] = {-1, -1};
  PyArrayObject *capi_ltlnwnd_tmp = NULL;
  PyObject *ltlnwnd_capi = Py_None;
  static char *capi_kwlist[] = {"datfile","stormid","century","cdtg","techname","ltlnwnd",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|:nclip.writeaid",\
    capi_kwlist,&datfile_capi,&stormid_capi,&century_capi,&cdtg_capi,&techname_capi,&ltlnwnd_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable ltlnwnd */
  ltlnwnd_Dims[0]=3,ltlnwnd_Dims[1]=10;
  capi_ltlnwnd_tmp = arr_from_pyobj(PyArray_INT,ltlnwnd_Dims,2,ltlnwnd_capi);
  if (capi_ltlnwnd_tmp == NULL) {
    PyErr_SetString(nclip_error,"failed in converting 6th argument `ltlnwnd' of nclip.writeaid to C array" );
      goto capi_fail;
  }
  ltlnwnd = (int *)(capi_ltlnwnd_tmp->data);
  /* Processing variable cdtg */
  slen(cdtg) = 8;
  if (!string_from_pyobj(&cdtg,&slen(cdtg),"",cdtg_capi,"string_from_pyobj failed in converting 4th argument `cdtg' of nclip.writeaid to C string"))
    goto capi_fail;
  /* Processing variable techname */
  slen(techname) = 4;
  if (!string_from_pyobj(&techname,&slen(techname),"",techname_capi,"string_from_pyobj failed in converting 5th argument `techname' of nclip.writeaid to C string"))
    goto capi_fail;
  /* Processing variable century */
  slen(century) = 2;
  if (!string_from_pyobj(&century,&slen(century),"",century_capi,"string_from_pyobj failed in converting 3rd argument `century' of nclip.writeaid to C string"))
    goto capi_fail;
  /* Processing variable stormid */
  slen(stormid) = 6;
  if (!string_from_pyobj(&stormid,&slen(stormid),"",stormid_capi,"string_from_pyobj failed in converting 2nd argument `stormid' of nclip.writeaid to C string"))
    goto capi_fail;
  /* Processing variable datfile */
  if (!int_from_pyobj(&datfile,datfile_capi,"int_from_pyobj failed in converting 1st argument `datfile' of nclip.writeaid to C int\n"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&datfile,stormid,century,cdtg,techname,ltlnwnd,slen(stormid),slen(century),slen(cdtg),slen(techname));
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  STRINGFREE(stormid);
  STRINGFREE(century);
  STRINGFREE(cdtg);
  STRINGFREE(techname);
  /* TODO: Check if the following (0 && ..) produces memory leak */
  if (0 && capi_ltlnwnd_tmp != NULL) Py_XDECREF(capi_ltlnwnd_tmp->base);
  Py_XDECREF(capi_ltlnwnd_tmp);

  return capi_buildvalue;
}
/****************************** end of writeaid ******************************/

/********************************** readnext **********************************/
static char doc_nclip_readnext[] = "\
Function signature:\n\
  readnext(datfile,rcd,ios)\n\
Required arguments:\n\
  datfile : input float\n\
  rcd : input float\n\
  ios : input int";
/* extern void F_FUNC(readnext,READNEXT)(); */ /* obsolute */
static PyObject *nclip_readnext(PyObject *capi_self, PyObject *capi_args, PyObject *capi_keywds, void (*f2py_func)()) {
  PyObject *capi_buildvalue = NULL;
/*decl*/

  float datfile;
  PyObject *datfile_capi = Py_None;
  float rcd;
  PyObject *rcd_capi = Py_None;
  int ios;
  PyObject *ios_capi = Py_None;
  static char *capi_kwlist[] = {"datfile","rcd","ios",NULL};
/*routdebugenter*/
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|:nclip.readnext",\
    capi_kwlist,&datfile_capi,&rcd_capi,&ios_capi))
    goto capi_fail;
/*frompyobj*/
  /* Processing variable ios */
  if (!int_from_pyobj(&ios,ios_capi,"int_from_pyobj failed in converting 3rd argument `ios' of nclip.readnext to C int\n"))
    goto capi_fail;
  /* Processing variable datfile */
  if (!float_from_pyobj(&datfile,datfile_capi,"float_from_pyobj failed in converting 1st argument `datfile' of nclip.readnext to C float\n"))
    goto capi_fail;
  /* Processing variable rcd */
  if (!float_from_pyobj(&rcd,rcd_capi,"float_from_pyobj failed in converting 2nd argument `rcd' of nclip.readnext to C float\n"))
    goto capi_fail;
/*callfortranroutine*/
  (*f2py_func)(&datfile,&rcd,&ios);
/*pyobjfrom*/
  CFUNCSMESS("Building return value.\n");
  capi_buildvalue = Py_BuildValue("");
capi_fail:
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
  return capi_buildvalue;
}
/****************************** end of readnext ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

static FortranDataDef f2py_extrap_def[] = {
  {"ifpxtrp",2,{3,11},PyArray_INT},
  {NULL}
};
static void f2py_setup_extrap(char *ifpxtrp) {
  int i_f2py=0;
  f2py_extrap_def[i_f2py++].data = ifpxtrp;
}
extern void F_FUNC(f2pyinitextrap,F2PYINITEXTRAP)();
static void f2py_init_extrap() {
  F_FUNC(f2pyinitextrap,F2PYINITEXTRAP)(f2py_setup_extrap);
}

static FortranDataDef f2py_cliper_def[] = {
  {"ifpclip",2,{3,11},PyArray_INT},
  {"flat",1,{7},PyArray_FLOAT},
  {"flon",1,{7},PyArray_FLOAT},
  {NULL}
};
static void f2py_setup_cliper(char *ifpclip,char *flat,char *flon) {
  int i_f2py=0;
  f2py_cliper_def[i_f2py++].data = ifpclip;
  f2py_cliper_def[i_f2py++].data = flat;
  f2py_cliper_def[i_f2py++].data = flon;
}
extern void F_FUNC(f2pyinitcliper,F2PYINITCLIPER)();
static void f2py_init_cliper() {
  F_FUNC(f2pyinitcliper,F2PYINITCLIPER)(f2py_setup_cliper);
}

static FortranDataDef f2py_shifor_def[] = {
  {"ishifor",2,{3,11},PyArray_INT},
  {NULL}
};
static void f2py_setup_shifor(char *ishifor) {
  int i_f2py=0;
  f2py_shifor_def[i_f2py++].data = ishifor;
}
extern void F_FUNC(f2pyinitshifor,F2PYINITSHIFOR)();
static void f2py_init_shifor() {
  F_FUNC(f2pyinitshifor,F2PYINITSHIFOR)(f2py_setup_shifor);
}

static FortranDataDef f2py_shifor5_def[] = {
  {"ishifor5",2,{3,11},PyArray_INT},
  {NULL}
};
static void f2py_setup_shifor5(char *ishifor5) {
  int i_f2py=0;
  f2py_shifor5_def[i_f2py++].data = ishifor5;
}
extern void F_FUNC(f2pyinitshifor5,F2PYINITSHIFOR5)();
static void f2py_init_shifor5() {
  F_FUNC(f2pyinitshifor5,F2PYINITSHIFOR5)(f2py_setup_shifor5);
}

static FortranDataDef f2py_al5coef_def[] = {
  {"scoef",2,{36,10},PyArray_FLOAT},
  {"avg",2,{36,10},PyArray_FLOAT},
  {"sdev",2,{36,10},PyArray_FLOAT},
  {NULL}
};
static void f2py_setup_al5coef(char *scoef,char *avg,char *sdev) {
  int i_f2py=0;
  f2py_al5coef_def[i_f2py++].data = scoef;
  f2py_al5coef_def[i_f2py++].data = avg;
  f2py_al5coef_def[i_f2py++].data = sdev;
}
extern void F_FUNC(f2pyinital5coef,F2PYINITAL5COEF)();
static void f2py_init_al5coef() {
  F_FUNC(f2pyinital5coef,F2PYINITAL5COEF)(f2py_setup_al5coef);
}

static FortranDataDef f2py_cl84_def[] = {
  {"cdi",1,{12},PyArray_FLOAT},
  {NULL}
};
static void f2py_setup_cl84(char *cdi) {
  int i_f2py=0;
  f2py_cl84_def[i_f2py++].data = cdi;
}
extern void F_FUNC(f2pyinitcl84,F2PYINITCL84)();
static void f2py_init_cl84() {
  F_FUNC(f2pyinitcl84,F2PYINITCL84)(f2py_setup_cl84);
}

static FortranDataDef f2py_pp_def[] = {
  {"p",1,{164},PyArray_FLOAT},
  {NULL}
};
static void f2py_setup_pp(char *p) {
  int i_f2py=0;
  f2py_pp_def[i_f2py++].data = p;
}
extern void F_FUNC(f2pyinitpp,F2PYINITPP)();
static void f2py_init_pp() {
  F_FUNC(f2pyinitpp,F2PYINITPP)(f2py_setup_pp);
}

static FortranDataDef f2py_hgrprm_def[] = {
  {"a",2,{3,3},PyArray_FLOAT},
  {"radpdg",0,{-1},PyArray_FLOAT},
  {"rrthnm",0,{-1},PyArray_FLOAT},
  {"dgridh",0,{-1},PyArray_FLOAT},
  {"hgridx",0,{-1},PyArray_FLOAT},
  {"hgridy",0,{-1},PyArray_FLOAT},
  {NULL}
};
static void f2py_setup_hgrprm(char *a,char *radpdg,char *rrthnm,char *dgridh,char *hgridx,char *hgridy) {
  int i_f2py=0;
  f2py_hgrprm_def[i_f2py++].data = a;
  f2py_hgrprm_def[i_f2py++].data = radpdg;
  f2py_hgrprm_def[i_f2py++].data = rrthnm;
  f2py_hgrprm_def[i_f2py++].data = dgridh;
  f2py_hgrprm_def[i_f2py++].data = hgridx;
  f2py_hgrprm_def[i_f2py++].data = hgridy;
}
extern void F_FUNC(f2pyinithgrprm,F2PYINITHGRPRM)();
static void f2py_init_hgrprm() {
  F_FUNC(f2pyinithgrprm,F2PYINITHGRPRM)(f2py_setup_hgrprm);
}

static FortranDataDef f2py_ep5coef_def[] = {
  {"scoef",2,{36,10},PyArray_FLOAT},
  {"avg",2,{36,10},PyArray_FLOAT},
  {"sdev",2,{36,10},PyArray_FLOAT},
  {NULL}
};
static void f2py_setup_ep5coef(char *scoef,char *avg,char *sdev) {
  int i_f2py=0;
  f2py_ep5coef_def[i_f2py++].data = scoef;
  f2py_ep5coef_def[i_f2py++].data = avg;
  f2py_ep5coef_def[i_f2py++].data = sdev;
}
extern void F_FUNC(f2pyinitep5coef,F2PYINITEP5COEF)();
static void f2py_init_ep5coef() {
  F_FUNC(f2pyinitep5coef,F2PYINITEP5COEF)(f2py_setup_ep5coef);
}

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/
extern void F_WRAPPEDFUNC(lastch,LASTCH)();
extern void F_FUNC(xtrap,XTRAP)();
extern void F_FUNC(rhdst,RHDST)();
extern void F_FUNC(rltlg,RLTLG)();
extern void F_FUNC(atclip,ATCLIP)();
extern void F_FUNC(cgulf,CGULF)();
extern void F_FUNC(atshif,ATSHIF)();
extern void F_FUNC(ashif3,ASHIF3)();
extern void F_FUNC(atshif5d,ATSHIF5D)();
extern void F_FUNC(jday,JDAY)();
extern void F_FUNC(epcl84,EPCL84)();
extern void F_FUNC(mult1,MULT1)();
extern void F_FUNC(mult2,MULT2)();
extern void F_FUNC(mult3,MULT3)();
extern void F_FUNC(mult4,MULT4)();
extern void F_FUNC(sthgpr,STHGPR)();
extern void F_FUNC(ll2xyh,LL2XYH)();
extern void F_FUNC(xy2llh,XY2LLH)();
extern void F_FUNC(epshif,EPSHIF)();
extern void F_FUNC(epshif5d,EPSHIF5D)();
extern void F_FUNC(readbt,READBT)();
extern void F_FUNC(readbest,READBEST)();
extern void F_FUNC(dowriteaidrcd,DOWRITEAIDRCD)();
extern void F_FUNC(writeaidrcd,WRITEAIDRCD)();
extern void F_FUNC(newwriteaidrcd,NEWWRITEAIDRCD)();
extern void F_FUNC(writeaid,WRITEAID)();
extern void F_FUNC(readnext,READNEXT)();
/*eof externroutines*/
static FortranDataDef f2py_routine_defs[] = {
  {"lastch",-1,{-1},0,(char *)F_WRAPPEDFUNC(lastch,LASTCH),(void *)nclip_lastch,doc_nclip_lastch},
  {"xtrap",-1,{-1},0,(char *)F_FUNC(xtrap,XTRAP),(void *)nclip_xtrap,doc_nclip_xtrap},
  {"rhdst",-1,{-1},0,(char *)F_FUNC(rhdst,RHDST),(void *)nclip_rhdst,doc_nclip_rhdst},
  {"rltlg",-1,{-1},0,(char *)F_FUNC(rltlg,RLTLG),(void *)nclip_rltlg,doc_nclip_rltlg},
  {"atclip",-1,{-1},0,(char *)F_FUNC(atclip,ATCLIP),(void *)nclip_atclip,doc_nclip_atclip},
  {"cgulf",-1,{-1},0,(char *)F_FUNC(cgulf,CGULF),(void *)nclip_cgulf,doc_nclip_cgulf},
  {"atshif",-1,{-1},0,(char *)F_FUNC(atshif,ATSHIF),(void *)nclip_atshif,doc_nclip_atshif},
  {"ashif3",-1,{-1},0,(char *)F_FUNC(ashif3,ASHIF3),(void *)nclip_ashif3,doc_nclip_ashif3},
  {"atshif5d",-1,{-1},0,(char *)F_FUNC(atshif5d,ATSHIF5D),(void *)nclip_atshif5d,doc_nclip_atshif5d},
  {"jday",-1,{-1},0,(char *)F_FUNC(jday,JDAY),(void *)nclip_jday,doc_nclip_jday},
  {"epcl84",-1,{-1},0,(char *)F_FUNC(epcl84,EPCL84),(void *)nclip_epcl84,doc_nclip_epcl84},
  {"mult1",-1,{-1},0,(char *)F_FUNC(mult1,MULT1),(void *)nclip_mult1,doc_nclip_mult1},
  {"mult2",-1,{-1},0,(char *)F_FUNC(mult2,MULT2),(void *)nclip_mult2,doc_nclip_mult2},
  {"mult3",-1,{-1},0,(char *)F_FUNC(mult3,MULT3),(void *)nclip_mult3,doc_nclip_mult3},
  {"mult4",-1,{-1},0,(char *)F_FUNC(mult4,MULT4),(void *)nclip_mult4,doc_nclip_mult4},
  {"sthgpr",-1,{-1},0,(char *)F_FUNC(sthgpr,STHGPR),(void *)nclip_sthgpr,doc_nclip_sthgpr},
  {"ll2xyh",-1,{-1},0,(char *)F_FUNC(ll2xyh,LL2XYH),(void *)nclip_ll2xyh,doc_nclip_ll2xyh},
  {"xy2llh",-1,{-1},0,(char *)F_FUNC(xy2llh,XY2LLH),(void *)nclip_xy2llh,doc_nclip_xy2llh},
  {"epshif",-1,{-1},0,(char *)F_FUNC(epshif,EPSHIF),(void *)nclip_epshif,doc_nclip_epshif},
  {"epshif5d",-1,{-1},0,(char *)F_FUNC(epshif5d,EPSHIF5D),(void *)nclip_epshif5d,doc_nclip_epshif5d},
  {"readbt",-1,{-1},0,(char *)F_FUNC(readbt,READBT),(void *)nclip_readbt,doc_nclip_readbt},
  {"readbest",-1,{-1},0,(char *)F_FUNC(readbest,READBEST),(void *)nclip_readbest,doc_nclip_readbest},
  {"dowriteaidrcd",-1,{-1},0,(char *)F_FUNC(dowriteaidrcd,DOWRITEAIDRCD),(void *)nclip_dowriteaidrcd,doc_nclip_dowriteaidrcd},
  {"writeaidrcd",-1,{-1},0,(char *)F_FUNC(writeaidrcd,WRITEAIDRCD),(void *)nclip_writeaidrcd,doc_nclip_writeaidrcd},
  {"newwriteaidrcd",-1,{-1},0,(char *)F_FUNC(newwriteaidrcd,NEWWRITEAIDRCD),(void *)nclip_newwriteaidrcd,doc_nclip_newwriteaidrcd},
  {"writeaid",-1,{-1},0,(char *)F_FUNC(writeaid,WRITEAID),(void *)nclip_writeaid,doc_nclip_writeaid},
  {"readnext",-1,{-1},0,(char *)F_FUNC(readnext,READNEXT),(void *)nclip_readnext,doc_nclip_readnext},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {
  {NULL,NULL}
};

void initnclip() {
  int i;
  PyObject *m, *d, *s;
  m = Py_InitModule("nclip", f2py_module_methods);
  import_array();
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  s = PyString_FromString("This module 'nclip' is auto-generated with f2py (version:2.317).\nFunctions:\n  lastch = lastch(string_v)\n  xtrap(iymdh,latcur,loncur,latm12,lonm12,strmid)\n  rhdst(flat,flng,tlat,tlng,dir,dst)\n  rltlg(flat,flng,tlat,tlng,dir,dst)\n  atclip(iymdh,y,x,dnow,snow,dm12,sm12,wkts,strmid)\n  cgulf(y,x,u,v,u12,v12,dn,w,wgulf,gulf)\n  atshif(ymdh,alat,alon,alat12,alon12,vel,vel12,strmid)\n  ashif3(p1,p2,p3,p4,p6,p7)\n  atshif5d(ymdh,alat,alon,alat12,alon12,vel,vel12,strmid)\n  jday(imon,iday,iyear,julday)\n  epcl84(ymdh,la0,lo0,lam12,lom12,lam24,lom24,dir0,spd0,wnd0,strmid)\n  mult1()\n  mult2()\n  mult3()\n  mult4()\n  sthgpr(xlath,xlonh,bear,gridsz,xi0,yj0)\n  ll2xyh(xlat,xlong,xi,yj)\n  xy2llh(xi,yj,xlat,xlong)\n  epshif(idtg,alat,alon,alat12,alon12,vel,vel12,strmid)\n  epshif5d(ymdh,elat,elon,elat12,elon12,vel,vel12,strmid)\n  readbt(datfile,cent,dtg,flat,ns,flon,ew,iwind,ios)\n  readbest(datfile,basin,cycnum,cent,dtg,flat,ns,flon,ew,iwind,ios)\n  dowriteaidrcd(datfile,stormid,cdtg,techname,itau,llwnd)\n  writeaidrcd(datfile,stormid,cdtg,techname,ltlnwnd)\n  newwriteaidrcd(datfile,stormid,cdtg,techname,ltlnwnd)\n  writeaid(datfile,stormid,century,cdtg,techname,ltlnwnd)\n  readnext(datfile,rcd,ios)\nCOMMON blocks:\n  /extrap/ ifpxtrp(3,11)\n  /cliper/ ifpclip(3,11),flat(7),flon(7)\n  /shifor/ ishifor(3,11)\n  /shifor5/ ishifor5(3,11)\n  /al5coef/ scoef(36,10),avg(36,10),sdev(36,10)\n  /cl84/ cdi(12)\n  /pp/ p(164)\n  /hgrprm/ a(3,3),radpdg,rrthnm,dgridh,hgridx,hgridy\n  /ep5coef/ scoef(36,10),avg(36,10),sdev(36,10)\n.");
  PyDict_SetItemString(d, "__doc__", s);
  nclip_error = PyErr_NewException ("nclip.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));
/*eof initf90modhooks*/

  PyDict_SetItemString(d, "extrap", PyFortranObject_New(f2py_extrap_def,f2py_init_extrap));
  PyDict_SetItemString(d, "cliper", PyFortranObject_New(f2py_cliper_def,f2py_init_cliper));
  PyDict_SetItemString(d, "shifor", PyFortranObject_New(f2py_shifor_def,f2py_init_shifor));
  PyDict_SetItemString(d, "shifor5", PyFortranObject_New(f2py_shifor5_def,f2py_init_shifor5));
  PyDict_SetItemString(d, "al5coef", PyFortranObject_New(f2py_al5coef_def,f2py_init_al5coef));
  PyDict_SetItemString(d, "cl84", PyFortranObject_New(f2py_cl84_def,f2py_init_cl84));
  PyDict_SetItemString(d, "pp", PyFortranObject_New(f2py_pp_def,f2py_init_pp));
  PyDict_SetItemString(d, "hgrprm", PyFortranObject_New(f2py_hgrprm_def,f2py_init_hgrprm));
  PyDict_SetItemString(d, "ep5coef", PyFortranObject_New(f2py_ep5coef_def,f2py_init_ep5coef));
/*eof initcommonhooks*/
  if (PyErr_Occurred())
    Py_FatalError("can't initialize module nclip");
}
#ifdef __CPLUSCPLUS__
}
#endif
