c
c  SCCS IDENTIFICATION:
c
c     name          description
c   ----------    ----------------------------------------------
c    pi           number of radians in 180 degrees
c    rad2deg      conversion factor, radians to degrees
c    deg2rad      conversion factor, degrees to radians
c    twomega      2 times the angular velocity of Earth
c . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
c
      double precision pi, rad2deg, deg2rad, twomega
c
      common/static1/ pi,rad2deg,deg2rad,twomega
