
      real              tech( kmax , naids )

      real              gech( kmax , naids )

      real              vmax( kmax , naids )

      integer           ic( naids )

      integer           nt

      integer           iclip

      integer           nclip

      common /techc/    tech ,
     &                  gech ,
     &                  vmax ,
     &                  ic ,
     &                  nt ,
     &                  iclip ,
     &                  nclip

