!  SCCS IDENTIFICATION:  @(#)view.inc	1.1 6/14/96
!
!  RECORD OF CHANGES:
!
!  <<CHANGE NOTICE>>  Version 1.1  (19 JUN 1996) -- Hamilton, H.
!    Initial installation on OASIS
!
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
!
      integer mini, maxi, minj, maxj
!
!                   common view variable definitions
!
!         mini - integer starting first  dimension of isogon box
!         maxi - integer ending first dimension of isogon box
!         minj - integer starting second dimension of isogon box
!         maxj - integer ending second dimension of isogon box
!
      common/view/ mini,maxi,minj,maxj
