
CCS Keywords: @(#)mndir.inc	1.1 12/15/94
C	      22:40:18 /cm/library/tctrack/src/inc/SCCS/s.mndir.inc

      integer ii, jj, iv, jv, kkk
c
c                   common mndir variable definitions
c
c           ii - starting minimum first  dimension of contouring block
c           jj - starting minimum second dimension of contouring block
c           iv - starting first  dimension contour direction vector
c           jv - starting second dimension contour direction vector
c          kkk - contour generation indicator
c
      common/mndir/ ii,jj,iv,jv,kkk
