
CCS Keywords: @(#)view.inc	1.1 12/15/94
C	      22:40:23 /cm/library/tctrack/src/inc/SCCS/s.view.inc

      integer mini, maxi, minj, maxj
c
c                   common view variable definitions
c
c         mini - integer starting first  dimension of isogon box
c         maxi - integer ending first dimension of isogon box
c         minj - integer starting second dimension of isogon box
c         maxj - integer ending second dimension of isogon box
c
      common/view/ mini,maxi,minj,maxj
